### ISSUE TITLE
Bank Robbery trigger chance

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Feedback#10]
<h2>What is your feature request?</h2>

There should be an extremely rare chance bank robberies don't trigger the alarm for example

1/100 chance.

IRL there would always be that possibility you execute the perfect robbery but it should also be a slim chance, shouldn't be possible for people to often rob a bank with no robbers.

<h2>What are the benefits of your idea?</h2>

Allows for a "OMG" moment where you can get away with a robbery and nobody even knows. Puts a small chance for robbers to get away with something and have some excitement.

<h2>Anything to support your idea?</h2>

N/A

**Comment by bloombydee** [comment]
Should be merged with gold bars suggestion under 'Bank Robbery' megatopic

**Comment by bloombydee** [comment]
Here we go #5
