### ISSUE TITLE
A few trash job related issues.

### ISSUE THREAD

**Issue by iamrayuu** [New-Chance-RP/Feedback#101]
<h2>What bug have you found?</h2>

The following issues were discovered by me on 4/28. May had been resolved by now but I will make a note of them here just in case they weren't.

- If in the case your trash truck is no longer on-site, you are still able to complete putting the trash bag in your hands on to the green marker. Upon putting it up, it calls that the end of your job since thats now when it considers it the end of your job and gives you the money. 

- When you're not in the trash truck, it's invisible to any gunshots and explosives. (I believe I encountered this with Loopolo)

- If in the case you don't put up your trash bag, it stays in your hand until you relog. You're able to shoot with it in hand, do emotes, get in your car... all while it's in your hand.

<h2>What do you expect should happen?</h2>

- I expect that since your truck is no longer nearby, that it is unable to be put up.

- I expect that the truck have its normal weaknesses much like any other truck or car.

- I expect that you can be able to drop your trash bag (or to even put it back in the trash barrel if you can't put it in a trash truck.)

<h2>Anything to support your bug report?</h2>

I have a clip of the first issue here:
https://medal.tv/clips/23965571/d1337YFJbEx5

**Comment by Senlarus** [comment]
This has been fixed, ready for testing!!
