### ISSUE TITLE
Motorcycle HUD

### ISSUE THREAD

**Issue by bloombydee** [New-Chance-RP/Feedback#102]
The vehicle HUD when driving a motorcycle shows the seatbelt option

Solution
Clone the HUD and make custom one without seatbelt option

**Comment by BadBritishGamer** [comment]
Testing Comment please ignore.

**Comment by BadBritishGamer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Added to Trello #102 - Motorcyle Hub](https://trello.com/c/Z9JBdPnk/3-added-to-trello-102-motorcyle-hub)
