### ISSUE TITLE
Snake Game High Score

### ISSUE THREAD

**Issue by Monster-Duck** [New-Chance-RP/Feedback#104]
<h2>What bug have you found?</h2>

After getting a highscore on the Snake phone app, if you close out the app it will reset your highscore.

<h2>What do you expect should happen?</h2>

The highscores should stay after closing the app.

<h2>Anything to support your bug report?</h2>

Easily recreatable if you run the Snake app.

**Comment by Senlarus** [comment]
This would require storing of high scores in the database and that isn't something we will do at this time. Take a screenshot and share it on discord to preserve the memory of your epic game of snake for now :)
