### ISSUE TITLE
Can't undo Wrist attachment.

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#106]
<h2>What bug have you found?</h2>

When you're choosing outfits at a store, there is no empty slot for your right wrist, you are stuck with one of the 8 options with no way to remove it if you accidentally click one.

<h2>What do you expect should happen?</h2>

Like the left wrist, there should be an empty wrist so you can revert back to not having anything there.

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/6095886/81874231-74082c80-954b-11ea-8eeb-f6c5a657b115.png)

**Comment by Senlarus** [comment]
The bracelets have been removed. They might be able to come back after we get the addon clothing, but for now they're broken.
