### ISSUE TITLE
NPC's pulling you out of your car when picking them up for a taxi ride.

### ISSUE THREAD

**Issue by Fat-Nick** [New-Chance-RP/Feedback#109]
<h2>What bug have you found?</h2>

While filling up my fuel for my taxi, i got a pickup propmt very close to me. when i went to pick him up, he pulled me out from the car.

<h2>What do you expect should happen?</h2>

Pick up the client with ease

<h2>Anything to support your bug report?</h2>

https://media.discordapp.net/attachments/257172492882411521/710679599100723260/unknown.png?width=720&height=405

**Comment by Senlarus** [comment]
We will look into how we can do this. Perhaps we can make the civ wait until the vehicle comes to a stop before they attempt to get in.

**Comment by Senlarus** [comment]
Is this still happening?

**Comment by Senlarus** [comment]
Taxi job has been improved.
