### ISSUE TITLE
4x4 trucks nose dive into the ground

### ISSUE THREAD

**Issue by Fat-Nick** [New-Chance-RP/Feedback#110]
<h2>What bug have you found?</h2>

When driving around, only 1 type of car would flip into the air. This would occur randomly when driving around the city. Sometimes they were fine, at other times all of that same car would do this.

<h2>What do you expect should happen?</h2>

the cars should be driving normaly, like all the others on the road.

<h2>Anything to support your bug report?</h2>

https://media.discordapp.net/attachments/257172492882411521/710838450466586804/unknown.png?width=720&height=405

https://media.discordapp.net/attachments/257172492882411521/710838175735611412/unknown.png?width=720&height=405

**Comment by OfficialMasuUK** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Passed to Design Team - #110 4x4 trucks nose dive into the ground](https://trello.com/c/VdqNrV3d/5-passed-to-design-team-110-4x4-trucks-nose-dive-into-the-ground)

**Comment by OfficialMasuUK** [comment]
Been looked into. After updating the handling.meta, issue seems to have been resolved. Thank you for your feedback.
