### ISSUE TITLE
Dispatch notifications text issue

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Feedback#111]
<h2>What bug have you found?</h2>

When we get a notification from car jacking within the text line it ends with "NULL" 

<h2>What do you expect should happen?</h2>

Get the prompt just without NULL in the sentence.

<h2>Anything to support your bug report?</h2>

https://gyazo.com/8adb917d76ee1d513c5fd234aa7054e1

**Comment by ixhal** [comment]
Removed NULL, Will add vehicle name at some point (maybe)
