### ISSUE TITLE
Seat belt buckle noise delay

### ISSUE THREAD

**Issue by OfficialMasuUK** [New-Chance-RP/Feedback#112]
<h2>What bug have you found?</h2>

When you get leave a vehicle whilst your seat belt is buckled, you'll still leave the vehicle (Icon turns from green to red). Upon returning or entering any vehicle you'll hear the seat belt unbuckle.

<h2>What do you expect should happen?</h2>

Upon leaving vehicle the seat belt unbuckle noise should play before exiting the vehicle

<h2>Anything to support your bug report?</h2>

Senlar and I discovered. Here to log.

**Comment by DerkDuece** [comment]
There is no longer a seatbelt sound when using the seatbelt now.
