### ISSUE TITLE
SO 11 & SO 12 speed

### ISSUE THREAD

**Issue by HenryBushen** [New-Chance-RP/Feedback#113]
<h2>What are you requesting?</h2

**2) Dodge ram and Silverado (Spawn codes SO 11 SO12 -**
**3) ** Speed needs to increased full tune only goes around 100 ish needs to be more maybe around 130 140  *What changes you want think should be made.*

<h2>Why are you making this request?</h2>
Because they are slower than most cars and still should be faster

**Comment by OfficialMasuUK** [comment]
Updated number of gears in both so11 and so12. Updated top speed. Speed should now sit at 124/125 top speed, unmodded. Thank you for your feedback.
