### ISSUE TITLE
Policebike

### ISSUE THREAD

**Issue by HenryBushen** [New-Chance-RP/Feedback#114]
<h2>What are you requesting?</h2>

*DELETE AS APPROPRIATE*

**2) Policebike ** *Name of vehicle*
**3) Turning and breaking needs to be buffed doesn't turn or break at all-** *

<h2>Why are you making this request?</h2>
Because cars turn better than the bike atm and break might as well not be on the bike :)

**Comment by OfficialMasuUK** [comment]
Modifications made to the bike. Tested by two people so far and seems to handle as should. Please test and resubmit any feedback if issue found. Thank you
