### ISSUE TITLE
Ability to put use /glasses and /hat

### ISSUE THREAD

**Issue by iamrayuu** [New-Chance-RP/Feedback#115]
<h2>Feature you are requesting.</h2>

To use /glasses and /hat to put back on said items.

<h2>What are the benefits to your feature?</h2>

Many servers have this concept so I think it would be a good idea to have something people can thoughtlessly do to bring back their accessories.

<h2>Anything to support your feature request?</h2>

"How do I put my glasses back on after they're punched off?" Rayuu asked innocently as she sat in the Public Dev. Lounge.
"You put in a feature request," replied the sassy dev Senlar, not missing a single beat.

**Comment by Senlarus** [comment]
We have added an accessory radial menu which allows for many more options than this. Enjoy!!
