### ISSUE TITLE
Emotes break meth/coke processing (Rayuu breaks things pt. 1)

### ISSUE THREAD

**Issue by iamrayuu** [New-Chance-RP/Feedback#116]
<h2>What bug have you found?</h2>
I initiated a shared emote while processing coke and it resulted in the halt of my coke production and made me unable to hit the 'e to stop processing' action and unable to walk out of the means in which you make coke.

<h2>What do you expect should happen?</h2>

I don't know what exactly to expect, but I feel there should be a block on doing shared emotes while doing such actions.

<h2>Anything to support your bug report?</h2>

Hal watched me do it and I'm a dirty bug maker.

**Comment by ixhal** [comment]
Should now be fixed thanks for the report :)
