### ISSUE TITLE
[EMS] Unable to escort patient from vehicle & Unable to un-ICU patient.

### ISSUE THREAD

**Issue by iamrayuu** [New-Chance-RP/Feedback#117]
<h2>What bug have you found?</h2>

As witnessed, EMS are unable to escort patients out of the ambulance or other vehicles. Also the option to take a patient out of ICU is non-existant, potentially causing issues if the wrong person is ICU'd.

<h2>What do you expect should happen?</h2>

EMTs should be able to drag out patients out of a vehicle or ambulance to add to the experience of roleplay and to essentially "roll the stretcher out" for the patient to roll them into the hospital. Also for the sake of being able to right the very likely mistake of ICUing the wrong person you should have the option of taking out a patient from ICU.

<h2>Anything to support your bug report?</h2>

Bloomb came across both these issues so if theres any questions you can ask him or if you need someone to replicate it or test it you can always ask me. :D

**Comment by ixhal** [comment]
Should now be fixed + added /unicu (serverID) to take someone out of the ICU
Thanks for the report!
