### ISSUE TITLE
Shooting/Aiming mechanics 

### ISSUE THREAD

**Issue by Birlzey** [New-Chance-RP/Feedback#119]
<h2>Feature you are requesting.</h2>

When holding right click with any firearm your instantly took into 1st person POV.

<h2>What are the benefits to your feature?</h2>

Crosshairs become more or less irrelevant and no more 3rd person cameraing around corners.

<h2>Anything to support your feature request?</h2>

Nope, just good idea imo.

**Comment by Senlarus** [comment]
Already been requested, please search before submitting new requests. Duplicate #49
