### ISSUE TITLE
Keybinds List

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Feedback#12]
<h2>What is your feature request?</h2>

A List of keybinds to go into #basic information channel allowing people to know what they need to press to do things.

<h2>What are the benefits of your idea?</h2>

Less questions from mostly everybody.

<h2>Anything to support your idea?</h2>

N/A

**Comment by Senlarus** [comment]
Working on it, check discord dev section and anytime anyone adds/changes a keybind please post there. I'll keep the main post updated as things change.

**Comment by bloombydee** [comment]
this is now COMPLETE *handclaps*
