### ISSUE TITLE
Garage camera bug

### ISSUE THREAD

**Issue by ixhal** [New-Chance-RP/Feedback#120]
<h2>What bug have you found?</h2>
When you try to take out a vehicle the camera angle sticks when certain conditions are met
1.Get a friend to take out a car at the garage
2.Try and pull out your vehicle while his car is there (blocking the spawn)
3.Get a notification saying the spawn point is blocked and camera angel gets stuck in the cinematic view

<h2>What do you expect should happen?</h2>
When spawn point is blocked say its blocked and give back the camera control to the player

<h2>Anything to support your bug report?</h2>
As seen on bloombs live stream view

**Comment by Senlarus** [comment]
I think this is fixed but @bloombydee needs to test.

**Comment by Senlarus** [comment]
Confirmed to be fixed.
