### ISSUE TITLE
License Issue - Weapons and other

### ISSUE THREAD

**Issue by Senlarus** [New-Chance-RP/Feedback#121]
<h2>License error in console and weapons license not working at Ammunation</h2>

**Comment by bloombydee** [comment]
This may be fixed, need to wipe licenses, restart and get people to test

**Comment by Senlarus** [comment]
Licenses wiped, ready for testing.

**Comment by Senlarus** [comment]
Has this been confirmed? Can someone test it?

**Comment by c-reckless** [comment]
@Senlarus will try on 2x characters now, could you wipe both for me?

**Comment by Senlarus** [comment]
Start with your new character. I’ll DM you when I’ve cleared them not at PC right now.

**Comment by c-reckless** [comment]
Driving, firearms and commercial tested on brand new character.

**Driving**, does not need a license, I could purchase a car if I had the funds.
**Firearms**, working as expected. Couldn't access shop.
**Commercial**, I could start trash master job and spawn the truck without license.

**Comment by Senlarus** [comment]
Driving, Firearms, and Commercial license requirements added and tested! Thanks @c-reckless !
