### ISSUE TITLE
Storing a vehicle while being used.

### ISSUE THREAD

**Issue by c-reckless** [New-Chance-RP/Feedback#123]
<h2>What bug have you found?</h2>

Another player can store my personal vehicle even when in "use". If stored, my player stays "using" the process animation and can freely walk around.

<h2>What do you expect should happen?</h2>

1. Vehicle stored into garage and disappears
2. Both players free to walk around
3. Any "use" processes before cancelled

To fix, vehicles being "used" cannot be stored.

<h2>Anything to support your bug report?</h2>

n/a

**Comment by ixhal** [comment]
Should be fixed now feel free to break it, Thanks for the report ;)
