### ISSUE TITLE
Hiding weapon in box

### ISSUE THREAD

**Issue by Monster-Duck** [New-Chance-RP/Feedback#124]
<h2>What bug have you found?</h2>

This isn't exactly a bug, but it could cause some RP issues. When you are carrying a box that you receive at a drug spot, you can pull out a weapon and it is inside the box, so no one can see it. 

<h2>What do you expect should happen?</h2>

Either the box should drop like the garbage bags do, or you should not be able to draw a weapon when carrying an item prop.

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/59716781/82607042-15176880-9b86-11ea-8462-ef18724d5bbd.png)
There is a knife in my hand in this image, but it is nearly invisible.

**Comment by ixhal** [comment]
Thanks for the report this should now have been fixed.
