### ISSUE TITLE
Graphic problem when purchasing a license

### ISSUE THREAD

**Issue by c-reckless** [New-Chance-RP/Feedback#125]
<h2>What bug have you found?</h2>

When purchasing a license using a higher resolution than 1920x1080 the graphic will not display properly and cannot finish the process.

<h2>What do you expect should happen?</h2>

Enter license screen, continue through prompts, purchase license.

<h2>Anything to support your bug report?</h2>

n/a

**Comment by Senlarus** [comment]
Thanks for finding this... I'll have to change the UI to a responsive layout instead of using fixed.

**Comment by Senlarus** [comment]
@c-reckless Can you test it again when you have a moment? I think I have it fixed for non-standard resolutions.

**Comment by c-reckless** [comment]
@Senlarus All working as expected now on 2560x1440 resolution

**Comment by Senlarus** [comment]
Fixed and confirmed!
