### ISSUE TITLE
Crouching changes walk style.

### ISSUE THREAD

**Issue by iamrayuu** [New-Chance-RP/Feedback#126]
<h2>What bug have you found?</h2>

After the first time you use the crouch key, your walkstyle changes to the same exact walk style for both sexes.

<h2>What do you expect should happen?</h2>

You should be able to keep the same walk despite crouching or doing anything else.

<h2>Anything to support your bug report?</h2>

Unsure on if this occurs on any other action done, but perhaps should be looked into on stuff like crawling as well! Problem was reported by Bloomb and I was able to replicate it on a female model.

**Comment by Senlarus** [comment]
Nice catch, I'll find a solution to this after alpha release. Thanks!

**Comment by bloombydee** [comment]
Fixed
