### ISSUE TITLE
Being able to drive anyone around in any type of vehicle during taxi missions.

### ISSUE THREAD

**Issue by iamrayuu** [New-Chance-RP/Feedback#127]
<h2>What bug have you found?</h2>

I was able to pick up locals during the taxi mission using both a firetruck and also a 2 door panto.

<h2>What do you expect should happen?</h2>

While I do know it says taxi/uber, I do think there definitely should be a car requirement for what kind of vehicles locals can and cannot ride in. Maybe preferrably just to taxis at the moment until theres possibly 'approved' uber cars.

<h2>Anything to support your bug report?</h2>

N/A

**Comment by Senlarus** [comment]
Forwarded this issue to the dev working on Taxi job. Thanks for the info!

**Comment by ixhal** [comment]
Issue has now been fixed, Thanks :)
