### ISSUE TITLE
Passengers don't see the same fuel level as drivers.

### ISSUE THREAD

**Issue by Dougjlb** [New-Chance-RP/Feedback#128]
<h2>What bug have you found?</h2>

Passengers don't see the same fuel level as drivers.

<h2>What do you expect should happen?</h2>

Passengers all see the same fuel level.

<h2>Anything to support your bug report?</h2>

Drive in a car as a driver or passenger and test fuel levels

**Comment by bloombydee** [comment]
@Dougjlb In your opinion do passengers need to see the vehicle HUD? I wouldn't mind everyone seeing the speedometer but the the different parts of the HUD can't be turned off individually so I'd think it should just appear to the driver

**Comment by c-reckless** [comment]
I think it would be more realistic to turn **off** the HUD as a passenger..
