### ISSUE TITLE
Hotel Keys

### ISSUE THREAD

**Issue by Dougjlb** [New-Chance-RP/Feedback#129]
<h2>What bug have you found?</h2>

When selling a hotel room you keep all the keys to the sold rooms (main and spare keys)

<h2>What do you expect should happen?</h2>

After selling a room, keys should be cleared for that room.

<h2>Anything to support your bug report?</h2>

Sell a hotel room and use F9 key to see all keys still there. they are removed after you leave and rejoin.

**Comment by bloombydee** [comment]
This will need to be fixed before alpha

**Comment by bloombydee** [comment]
Closing as we are replacing this resource
