### ISSUE TITLE
ALL furniture being removed when selling rooms

### ISSUE THREAD

**Issue by Dougjlb** [New-Chance-RP/Feedback#130]
<h2>What bug have you found?</h2>

When selling a hotel room, you lose all placed furniture and furniture in your "storage" (not placed furniture)

<h2>What do you expect should happen?</h2>

After selling a room, all your furniture should be: 
1. Returned to a "storage" 
2.Only lose furniture that you had placed
3. You should be able to pick all placed furniture up and it be places back in "storage"

In both cases, it should not be deleted with selling your room. 

<h2>Anything to support your bug report?</h2>

Buy furniture place some in a room and keep some in your "storage" then sell room. you will have nothing left.

**Comment by bloombydee** [comment]
Will be looking into this before release so assigning to alpha release milestone. Hopefully it will be fixed, if more complicated then we will use pre furnished rooms for the time being

**Comment by bloombydee** [comment]
Closing as we are replacing this resource
