### ISSUE TITLE
DOL Licensing overlap

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Feedback#132]
<h2>What bug have you found?</h2>
Just a graphical bug, when getting a gun license the long sentence just overlaps with the logo.

<h2>What do you expect should happen?</h2>

It to not overlap.

<h2>Anything to support your bug report?</h2>

https://gyazo.com/e54e123cbc76accbf3947a79de5e45b5

**Comment by Senlarus** [comment]
Fixed
