### ISSUE TITLE
Oxygen meter while under water

### ISSUE THREAD

**Issue by iamrayuu** [New-Chance-RP/Feedback#133]
<h2>Feature you are requesting.</h2>

Ability to view the amount of oxygen you have while you're underwater, because currently it's invisible and it's unknown to when your oxygen has ran out and you begin to take damage.

<h2>What are the benefits to your feature?</h2>

For anyone swimming around it's good to know when you may possibly be unable to no longer breathe and are starting to die underwater. It'll prevent a lot less drownings to be more aware of your lung capacity and is overall just more realistic!

<h2>Anything to support your feature request?</h2>

N/A

**Comment by Senlarus** [comment]
Added
