### ISSUE TITLE
Emergency vehicle sirens

### ISSUE THREAD

**Issue by c-reckless** [New-Chance-RP/Feedback#134]
<h2>What bug have you found?</h2>

Only the person who spawned the vehicle can hear the sirens

<h2>What do you expect should happen?</h2>

Everyone should be able to hear the police vehicle sirens

<h2>Anything to support your bug report?</h2>

**EMS:**
AMBO - working
FIRE1 - not working _(and currently using POLICE not FIRE siren)_
FIRE3 - working
FIRE4 - working _(and currently using POLICE not FIRE siren)_

**Police:**
SO3 - working
SO5 - not working
SO7 - working
SO8 - not working
SO11 - not working
SO12 - not working
POLICEBIKE - working
RIOT - working
"PDSpecial" - not workling

**Comment by BadBritishGamer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Replace Sirens on Police Cars that aren't working](https://trello.com/c/V86WyX3H/9-replace-sirens-on-police-cars-that-arent-working)

**Comment by OfficialMasuUK** [comment]
Vehicles.meta for NCRP-EMS Updated. Potential server restart needed before it takes effect. Will check theses before moving onto the Police Vehicles.

**Comment by HenryBushen** [comment]
Working on a potential fix for all emergency vehicle. Potential server restart needed before it takes effect. Got it working localhost just waiting to test it in the server with others.

**Comment by OfficialMasuUK** [comment]
Fix implemented thanks to Senlar. Should all now be working.
