### ISSUE TITLE
Handcuffs stay on when jailed.

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Feedback#135]
<h2>What bug have you found?</h2>

If you jail someone the handcuffs stay on.

<h2>What do you expect should happen?</h2>

When jailed your handcuffs should come off, sometimes we get pain in the ass people who need to be kept in cuffs, these should disappear once they are jailed so it doesn't cause limitations.

<h2>Anything to support your bug report?</h2>

https://media.discordapp.net/attachments/600388327400669269/713849493807825046/unknown.png

**Comment by ixhal** [comment]
Should now be fixed give it a try
