### ISSUE TITLE
When cuffed can use a bicycle

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Feedback#137]
<h2>What bug have you found?</h2>
When you are handcuffed you can use the rent-abike system and get a bike and get on the bike.

<h2>What do you expect should happen?</h2>

If cuffed be a walking potato.

<h2>Anything to support your bug report?</h2>

https://media.discordapp.net/attachments/600388327400669269/713849819713765470/unknown.png

**Comment by ixhal** [comment]
Intended feature, No hands very hard to master but not impossible.
In all seriousness this has been fixed.
