### ISSUE TITLE
Being in the same area as someone during character creation

### ISSUE THREAD

**Issue by iamrayuu** [New-Chance-RP/Feedback#139]
<h2>What bug have you found?</h2>

When making your character while someone else is, you end up either being really close to them or meshed into them

<h2>What do you expect should happen?</h2>

To be in a different instanced location for the time you're walking through the bathroom/closet scene so that you're not interfering with someone elses character creation.

<h2>Anything to support your bug report?</h2>

I had not personally come across this bug, but Nerdymomma did according to Senlar. If there needs to be any clarification made, it'd be best to contact her! :)

**Comment by Senlarus** [comment]
Fixed and confirmed
