### ISSUE TITLE
All Vehicles currently unlocked

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Feedback#14]
<h2>What bug have you found?</h2>

Every vehicle is currently accessible via walking up and opening door.

<h2>What do you expect should happen?</h2>

75% of vehicles should be locked, it shouldn't be easy for a player to steal a vehicle.

<h2>Anything to support your bug report?</h2>

Easily repeated in game

**Comment by adsam56** [comment]
All vehicles will now be locking by default with a lockpick minigame to unlock them

**Comment by ixhal** [comment]
All vehicles are now locked.
