### ISSUE TITLE
Mike Gallope

### ISSUE THREAD

**Issue by Jukoro420** [New-Chance-RP/Feedback#140]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:
11000010479d82e

**Do you have troubleshooting experience?** *(If yes please explain)* :
Yes i have troubleshooting experience when i find a bug i typically test it a few times before sending in a report if it just happens once and i can't get it to happen again then i would assume it is a one time scenario.
**How do you personally take screenshots?** : 
i personally take screenshots by just doing print screen and having it saved to one drive

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : 
first of all i would try it more then once if nothing happens a couple times i would file a bug report via github with a screenshot of what is happening and i would also explain what is happening when i try to use the garage and give them the exact time of when this occurred. 

**Discord ID** *Please include numbers* :
Jukoro420#6808

**Comment by Senlarus** [comment]
What is your timezone?

**Comment by bloombydee** [comment]
Congratulations, application approved
