### ISSUE TITLE
50bmg

### ISSUE THREAD

**Issue by Real50BMG** [New-Chance-RP/Feedback#141]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) 
------------------------------------------------------------------------------------------------------------

**Steam ID**: 1100001183c1378

**Do you have troubleshooting experience?** *(If yes please explain)* : As part of my job (and hobby) irl i troubleshoot pc hardware all the time. Just change 1 variable and see if it fixes the issue. If it didnt fix it, change something else and check again. etc etc

**How do you personally take screenshots?** : Snippingtool mainly

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** :  
Possibly a clip of it happening but mainly short straight to the point type info posted on the feedback section of the github

**Discord ID** *Please include numbers* : 50BMG#8672

**Comment by Senlarus** [comment]
What is your timezone?

**Comment by Real50BMG** [comment]
I am West-EU (Amsterdam timezone)

**Comment by bloombydee** [comment]
Congratulations, application approved
