### ISSUE TITLE
Lena Perry "Closed Alpha Application"

### ISSUE THREAD

**Issue by lAmantel** [New-Chance-RP/Feedback#142]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 110000105a23149

**Do you have troubleshooting experience?** *(If yes please explain)* : No, Not entirely, I've done some here and there, but I wouldn't say I'm perfectly experienced.

**How do you personally take screenshots?** : If I'm taking personal screenshots, I have Reshader installed so I would get the black boarders that would block out the map and all the logos, and Then take the photo using Print Screen, usually saving them onto discord or Imgur.

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : First I would make sure that I'm over the correct marker and at the correct garage. If It's still in neither I would check the impound lot to see if it was Impounded some how before I decide to put in a report, If all of the above has been done, then I'll come to git hub to check if anyone else has posted something of the similar If someone has I would comment on theirs describing that I had a similar situation and what happened,(If that hasn't been found then I'd make my own). 

**Discord ID** *Please include numbers* : Amante#2295

**Comment by Senlarus** [comment]
What is your timezone?

**Comment by lAmantel** [comment]
Eastern Standard Time

**Comment by bloombydee** [comment]
Congratulations, application approved
