### ISSUE TITLE
George Prezo

### ISSUE THREAD

**Issue by Prezoo** [New-Chance-RP/Feedback#143]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 11000010bad714d

**Do you have troubleshooting experience?** *(If yes please explain)* : Used work on IT help desk trouble shooting problems for people and writing reports for each problem.

**How do you personally take screenshots?** :  Gyazo

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : Clip the last few minutes of the game. See if bug or issue reoccurs , check if issue has happened before if not post on relevant page.

**Discord ID** *Please include numbers* : Prezo#4993

**Comment by Senlarus** [comment]
What is your timezone?

**Comment by Prezoo** [comment]
BST but i work nights so i'm usually on in afternoon and through the night on weekends

**Comment by bloombydee** [comment]
Congratulations, application approved
