### ISSUE TITLE
Monster_Duck’s whitelist application.

### ISSUE THREAD

**Issue by Monster-Duck** [New-Chance-RP/Feedback#144]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:110000111cfc8ff

**Do you have troubleshooting experience?** *(If yes please explain)* :

No, I am not good enough at any sort of programming to fix issues. If I’m misunderstanding the question and you are wondering if I’ve worked to find bugs before yes. Just last month I became a staff member of a Minecraft PVP server and I’ve spent about 60 hours running games in spectator mode looking for issues. On FiveM I have done a small bit of bug fixing on LiveRP (which is the small server I came from before joining here full time). I spent most of my time helping the owner find issues with gang related activity. I’ve also spent a morsel of time finding bugs on here.

**How do you personally take screenshots?** : 

I print screen and paste them into Paint 3D or just take a Rockstar screenshot depending  on the situation.

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : 

Before I report a bug I would probably try a couple sifferent things like relogging, restarting FiveM or just testing a different garage. I don’t know if becoming instanced is a big problem here, but most issues I’ve encountered on others servers are fixed by that sort of thing. If I’m sure it is a bug after these things, I’d probably ask someone else to test it, and if they cannot recreate it I would take a clip with Medal trim it down to size and then send a link to the clip to my bug report on GitHub.

**Discord ID** *Please include numbers* :

Monster_Duck #7435

**Comment by Senlarus** [comment]
What is your timezone?

**Comment by bloombydee** [comment]
Congratulations, application approved
