### ISSUE TITLE
Closed alpha application

### ISSUE THREAD

**Issue by Whacklycloud** [New-Chance-RP/Feedback#146]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:110000106a77df2

**Do you have troubleshooting experience?** *(If yes please explain)* : no

**How do you personally take screenshots?** : Lightshot stream 

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : take a video of it and if someone is having the same bug if not report it.

**Discord ID** *Please include numbers* :Cloudy9597

**Comment by Senlarus** [comment]
What is your timezone?

**Comment by Whacklycloud** [comment]
PDT

**Comment by bloombydee** [comment]
Congratulations, application approved
