### ISSUE TITLE
Closed alpha app by scruxy

### ISSUE THREAD

**Issue by Scruxyy** [New-Chance-RP/Feedback#147]
Steam ID   (HEX) :11000013d2a31c8
https://steamcommunity.com/profiles/76561198986441160/
Profile link just in case 

Do you have troubleshooting experience? (If yes please explain) : Yes , i have tested cars and things on another server and have tested maps in other games so i have some pretty good experience 

How do you personally take screenshots? : i press windows key alt and print screen and it screen shots into a folder in my files 

If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide? :well i would first screen shot it then i would relog if it fixed it i would still report it just incase its a server side issue and if it didnt i would put the screen shot in a git hub post and explain everything from when i walked up to when i wrote he report because it can be little things that cause huge trouble 

Discord ID Please include numbers : Scruxy#7617To retrieve your steam ID please do the following steps

**Comment by Senlarus** [comment]
What is your timezone?

**Comment by bloombydee** [comment]
Congratulations, application approved

**Comment by Scruxyy** [comment]
est
sorry didnt see the email
