### ISSUE TITLE
N3rdy's closed alpha app

### ISSUE THREAD

**Issue by N3rdymomma** [New-Chance-RP/Feedback#148]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:
110000115b7bb96 (Hex)

**Do you have troubleshooting experience?** *(If yes please explain)* : Not really, I have helped in small parts testing stuff. However I dont have any large scale experience. 

**How do you personally take screenshots?** :  I the f12 key within steam. 

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?**: If after making sure I was at the correct garage and relogging didnt work. I would recreate it while recording what is going on. I would then check on github to see if there is already a thread for this issue, if there is I would comment on it with my evidence. If there is not a thread I would create my own with said evidence. 

**Discord ID** *Please include numbers* : N3rdymomma#1788

**Comment by Senlarus** [comment]
What is your timezone?

**Comment by N3rdymomma** [comment]
CST

**Comment by bloombydee** [comment]
Congratulations, application approved
