### ISSUE TITLE
Bapes Closed Alpha Application

### ISSUE THREAD

**Issue by BillChirico** [New-Chance-RP/Feedback#149]
**Steam ID**: 11000010d87c75e 

**Do you have troubleshooting experience?** *(If yes please explain)* : Yes, I work at a software engineering company where I solve problems all day long.

**How do you personally take screenshots?** :  GeForce Screen Capture or Windows ScreenShot

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : I would send a clip of the incident, provide the location, and what I was doing immediately before that, I would then compile all of this information and create a GitHub issue.

**Discord ID** *Please include numbers* : Bapes#1812

**Comment by Senlarus** [comment]
What is your timezone?

**Comment by BillChirico** [comment]
> What is your timezone?

EST

**Comment by bloombydee** [comment]
Congratulations, application approved
