### ISSUE TITLE
NoCreamCheese Closed Alpha Application

### ISSUE THREAD

**Issue by nicoflora** [New-Chance-RP/Feedback#150]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 11000010aff2ddc

**Do you have troubleshooting experience?** *(If yes please explain)* : Yes, I work as a software engineer solving software problems most of the day. 

**How do you personally take screenshots?** : I use WIN+SHFT+S or F12 

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : I would create a GitHub issue including a timestamp, recording of the incident, as well as what I was doing in the city before it occurred. 

**Discord ID** *Please include numbers* : NoCreamCheese#1925

**Comment by Senlarus** [comment]
What is your timezone?

**Comment by nicoflora** [comment]
> What is your timezone?

EST

**Comment by bloombydee** [comment]
Congratulations, application approved
