### ISSUE TITLE
Itomicz.

### ISSUE THREAD

**Issue by itomicz** [New-Chance-RP/Feedback#151]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 110000110a991f2

**Do you have troubleshooting experience?** : No

**How do you personally take screenshots?** : F12 

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : I would go back onto the discord and go onto the github. I would then click onto the Bug reports tab and eplain what the issue is and how it should be working so the devs can easily fix it.

**Discord ID** *Please include numbers* : itomicz#9495

**Comment by Senlarus** [comment]
What is your timezone?

**Comment by Senlarus** [comment]
Marge #152
