### ISSUE TITLE
Bushen

### ISSUE THREAD

**Issue by HenryBushen** [New-Chance-RP/Feedback#152]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into the search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 11000013afd2743 

**Do you have troubleshooting experience?** *(If yes please explain)* :

**How do you personally take screenshots?** : Light shot

**If you were trying to get your car out of a garage when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : I would make a git hub under the bug section and fill in all info and even a little gif/ video if need

**Discord ID** *Please include numbers* :Bushen#2233

**Comment by Senlarus** [comment]
What is your timezone?

**Comment by HenryBushen** [comment]
BST EU

**Comment by Senlarus** [comment]
Approved, thanks for offering to help!
