### ISSUE TITLE
Him Who Robs

### ISSUE THREAD

**Issue by HimWhoRobs** [New-Chance-RP/Feedback#153]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82
11000010545dcea
------------------------------------------------------------------------------------------------------------

**Steam ID**:11000010545dcea

**Do you have troubleshooting experience?** *(If yes please explain)* : Yes, i have reported things in the past however i still wouldn't say I'm 100% comfortable with it.

**How do you personally take screenshots?** : Screenshot button paste to discord so I have it saved in my own personal server. Crop my other screens out of it then send it to where ever it needs sending.

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : Firstly I wold write down the steps I had done to make the bug happen. Then I would try to reproduce it. once having done that and found out how to do this. I would write it up on git hub in the bugs section putting in detailed information such as make of car and what garage and any steps I had take previously to reproduce this. 

**Discord ID** *Please include numbers* : HimWhoRobs#0402

**Comment by Senlarus** [comment]
What is your timezone?

**Comment by HimWhoRobs** [comment]
UK

**Comment by Senlarus** [comment]
Approved, thanks for helping!
