### ISSUE TITLE
PD/EMS Vehicle Deformation

### ISSUE THREAD

**Issue by Senlarus** [New-Chance-RP/Feedback#154]
<h2>What are you requesting?</h2>

For the EMS/PD vehicles, when they have massive body damage the lights drifts off the car and flash floating in mid air. I'm requesting that we limit the amount of body damage on the vehicles as a way to attempt to prevent this visual bug. I think there should still be some body damage available, but only as much as doesn't change the light positions.

<h2>Why are you making this request?</h2>

The lights issue is immersion breaking

<h2>Anything to support the above?</h2>

![image](https://user-images.githubusercontent.com/1503963/82825462-49866f80-9e79-11ea-8ea6-f7725f5d1310.png)

**Comment by OfficialMasuUK** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PD/EMS Vehicle Deformation #154](https://trello.com/c/lggI0WFa/14-pd-ems-vehicle-deformation-154)

**Comment by OfficialMasuUK** [comment]
Files changed. Just need to push them to the server and test.

**Comment by OfficialMasuUK** [comment]
Handling.Metas updated for all EMS and PD Ground vehicles. Pushed to server. Resource restart or server restart needed to see effects.

**Comment by Senlarus** [comment]
New update fixed deformation a bit but this still happens.
![image](https://user-images.githubusercontent.com/1503963/83284491-b025c900-a1aa-11ea-9e6a-409305dd67cf.png)

**Comment by OfficialMasuUK** [comment]
If we lower body deformation any lower there won't be any deformation at all. I'll see if any of the other emergency vehicle models have the same issue.

**Comment by OfficialMasuUK** [comment]
Solution implemented.
