### ISSUE TITLE
The Dougler Application

### ISSUE THREAD

**Issue by Dougjlb** [New-Chance-RP/Feedback#156]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 110000104956242

**Do you have troubleshooting experience?** *(If yes please explain)* : 
Yes, helped before the closed alpha was a thing.

**How do you personally take screenshots?** : 
Sniping tool (dew to my 4k screen it helps down size my image)

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : 
Note what happened and then try to replicate the issue. If i can, note down how i did and then report the issue on Github.

**Discord ID** *Please include numbers* : The__Dougler#7731

**Comment by bloombydee** [comment]
Congratulations, application approved
