### ISSUE TITLE
Police AS350 incorrect title

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Feedback#157]
<h2>What bug have you found?</h2>

When going to the menu to assign yourself the AS350 it shows as "NIL"

<h2>What do you expect should happen?</h2>

To show the vehicle name instead of NIL.

<h2>Anything to support your bug report?</h2>

https://gyazo.com/a42f8f0edeef01552be6cef07fc30010

**Comment by Senlarus** [comment]
Alan fixed it
