### ISSUE TITLE
ID Check bugging out

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Feedback#158]
<h2>What bug have you found?</h2>

This first ID you check when clocking in as a cop will be the only ID you ever get. If I check the nearest player to me it will give me their ID,  if I then check a different player it will still give me the original persons ID.

<h2>What do you expect should happen?</h2>

If there is nobody nearby it returns no ID with "no players nearby"

If there is a player nearby to give the correct player ID to you.

<h2>Anything to support your bug report?</h2>

https://gyazo.com/f62e8d63bd8f1dc260697f96f74bf78a

**Comment by ixhal** [comment]
Fixed me made a oopsie
