### ISSUE TITLE
Unable to pay invoices

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Feedback#159]
<h2>What bug have you found?</h2>

When you are fined by LSPD and invoiced, the fine appears in billing via your phone but it doesn't allow you to pay the fine.

<h2>What do you expect should happen?</h2>

A way to pay the fine via the billing method in your phone.

<h2>Anything to support your bug report?</h2>

N/A

**Comment by Senlarus** [comment]
This has been fixed.
