### ISSUE TITLE
Scarfninja/Teagan CA application

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#161]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 1100001059b2ae0

**Do you have troubleshooting experience?** *(If yes please explain)* : Yes, I've been a part of several beta tests and have usually gone out of my way to try and break as many things as I can.

**How do you personally take screenshots?** : I usually can just alt+prntscrn and paste it into photoshop or depending on where I'm at I use gyazo to take a segmented picture of an area on my screen.

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : I'd make a bug report through our github. "When I try to access the garage to get my car, there is no hud menu showing up for me to access, I checked f8 and didn't see any errors come up."  I would leave the area, maybe even go into an instanced room and come back to try again and see if the hud is still not showing up.  As well as steal a car and see if I can force the menu to show up when driving over it with a different vehicle.  

**Discord ID** *Please include numbers* : Scarfninja#8334

**Comment by Scarfninja** [comment]
Also going to add i'm EST

**Comment by Senlarus** [comment]
Approved, thanks for continuing to help!
