### ISSUE TITLE
Dontbesalty’s app

### ISSUE THREAD

**Issue by dontbesalty1** [New-Chance-RP/Feedback#162]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) 

------------------------------------------------------------------------------------------------------------

**Steam ID**: 
11000010027a0a5

**Do you have troubleshooting experience?** *(If yes please explain)* : no

**How do you personally take screenshots?** : snipping tool

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : would go to feedback and create one showing the clip what’s wrong and a screenshot of the f8 log

**Discord ID** *Please include numbers* :
Don’t Be Salty#6457

**Comment by bloombydee** [comment]
Congratulations, application approved

**Comment by Senlarus** [comment]
@BadBritishGamer Here's the steam ID
11000010d6f24d7
