### ISSUE TITLE
Hustleren's Closed Alpha Application

### ISSUE THREAD

**Issue by stiansen123** [New-Chance-RP/Feedback#163]
**Steam ID**: 1100001023f0dac

**Do you have troubleshooting experience?** *(If yes please explain)* : I work in an environment where I troubleshoot computers on a daily basis for my job. 

**How do you personally take screenshots?** : F12 / Screenshot / Shadowplay 

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : Screenshot, video evidence, submit a GitHub issue, give full detail of what happened before the problem occurred. 

**Discord ID** *Please include numbers* : Hustleren#9936

**Comment by bloombydee** [comment]
110000104956242

**Comment by donbmc** [comment]
@bloombydee Hey, I got responded to with 110000104956242, and closed does that mean not approved at this time?
