### ISSUE TITLE
Bradley Hooper Closed Alpha Application

### ISSUE THREAD

**Issue by donbmc** [New-Chance-RP/Feedback#164]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/ 
- Paste your steam profile link into search 
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82 

Steam3 ID (64bit) | 11000010e951f3d (Hex)

------------------------------------------------------------------------------------------------------------

**Steam ID**:
https://steamcommunity.com/id/bmcfreshcash/

**Do you have troubleshooting experience?** *(If yes please explain)* :
Yes, I used to be a head admin on a server called MagicallityRP from 2017 - 2019. I helped test and create feedback / suggestions for future updates on the server for our developers. I also work for a bank in real life so, our systems go down constantly and I have to create work arounds and get creative with different systems.  

**How do you personally take screenshots?** : 
I use Gyazo, and I have shadowplay to record video and capture anything within the last 15 minutes even if I'm not prepared or recording. 

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : 

Self Diagnosis : (Make sure its not just on my end) First I would wait to make sure there wasnt any type of connection delay, run away from the circle and run back in. If this was not the fix, I would restart my game and try to store the vehicle. 

Escalate : (After trying all realistic self assist options) If this continues to not work I will then escalate all of the information and video of this information to the forum or discord (appropriate place) of the issue to let it be known there is something going on. 

**Discord ID** *Please include numbers* : 
BMC#9270
I am 21 years old from Michigan, EST Time zone.

**Comment by bloombydee** [comment]
110000104956242
