### ISSUE TITLE
Closed Alpha application

### ISSUE THREAD

**Issue by RaZerHaugen** [New-Chance-RP/Feedback#165]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 11000010f81fd1f 

**Do you have troubleshooting experience?** *(Well I wouldn't say I have so much no)* :

**How do you personally take screenshots?** : It has a lot on what it is, is usually at the best of times, when it looks best, etc.

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : So if it takes a long time before the garage menu opens, I will end up waiting to see if it comes up that it might be a delay. But if it does not open at all, I will report it to the staff and tell what happens and does not happen.

**Discord ID** *Please include numbers* : RaZerHaugen#1437 or King#5659

**Comment by Senlarus** [comment]
Approved
