### ISSUE TITLE
HoldTheDoor’s Closed Alpha Application 

### ISSUE THREAD

**Issue by frinzia12** [New-Chance-RP/Feedback#166]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into the search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 1100001042aa87b

**Do you have troubleshooting experience?** *(If yes please explain)*: I currently manage a team of hardware technicians for an IT Department, troubleshooting IT-related issued is a daily task for myself and my team. In my personal experience, I have been involved with hardware and software tinkering my entire adult life. My education experience is a Computer Science Bachelors's degree.  

**How do you personally take screenshots?** : Radeon ReLive 

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : 

Record a screen capture of my attempt to get the car out. Include any useful variables in my incident report (time of day, items in my inventory, any errors that were generated, etc.) 

**Discord ID** *Please include numbers* : HoldTheDoor#9283

**Comment by Senlarus** [comment]
Approved, thanks for offering to help!
