### ISSUE TITLE
Kuruma Handling

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#167]
<h2>What are you requesting?</h2>

*DELETE AS APPROPRIATE*

**1) - Vehicle addition -** *(Provide Link)*
**2) - Vehicle removal -** *Name of vehicle*
**3) - Vehicle changes -** *What changes you want think should be made.* Currently the Kuruma's handling is too squirrelly.  Being a sports car designed around drifting its expected to slide but there's no way to stop yourself once in the slide and you will go sideways until you collide with something. (Also don't know if this is all vehicles but car damage seems really high from bumping into anything)

<h2>Why are you making this request?</h2>
It's a car that I enjoy aesthetically but struggle to drive it because the controls feel too loose and have no grip when you want to have it.

I believe the improvements/benefits this would make the car more applicable to normal street running and more desirable for purchase.

<h2>Anything to support the above?</h2>

**Comment by OfficialMasuUK** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Kuruma Handling #167](https://trello.com/c/12yPrUbD/15-kuruma-handling-167)

**Comment by driftoooo** [comment]
Custom handling for the Kuruma will be implemented once I've finished my current assignment. I know this comment was made lonnngggg ago, but finally... it'll be done haha. 

Thanks for the request, if you're still around...
