### ISSUE TITLE
Diskoalified's Application

### ISSUE THREAD

**Issue by nells322** [New-Chance-RP/Feedback#168]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 110000105cb3893

**Do you have troubleshooting experience?** *(If yes please explain)* : Yes. I work in finance and have to troubleshoot PC and software daily. I also have experience in streaming bots. 

**How do you personally take screenshots?** : GeForce Screen Capture or Windows ScreenShot

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : I would clip it and show the location of the issue. I would also write in detail and explain along side the video what I did that caused the issue or bug. 

**Discord ID** *Please include numbers* : Diskoalified#1586

**Comment by Senlarus** [comment]
Approved

**Comment by Senlarus** [comment]
Approved!
