### ISSUE TITLE
Closed Alpha App - Alex

### ISSUE THREAD

**Issue by alexkaz0** [New-Chance-RP/Feedback#169]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 11000011780f7de

**Do you have troubleshooting experience?** *(If yes please explain)* : Yes, I am a software engineer with a Masters degree. I do troubleshooting with QA on a daily basis as a professional.

**How do you personally take screenshots?** : Geforce Shadow play, Windows Shift S, F12

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : I would clip the issue with video, and or screenshot. Report it to the dev's github repo. Retrace and Document.

**Discord ID** *Please include numbers* : mr.jawns#1625

**Comment by Senlarus** [comment]
Added! Thanks for offering to help out!
