### ISSUE TITLE
Legs missing on other peoples screens when using a particular leg setting

### ISSUE THREAD

**Issue by OfficialMasuUK** [New-Chance-RP/Feedback#173]
<h2>What bug have you found?</h2>

Legs are missing on other peoples screens.

<h2>What do you expect should happen?</h2>

Legs should be there.

<h2>Anything to support your bug report?</h2>

![20200525222318_1](https://user-images.githubusercontent.com/10865605/82857416-d3c9e480-9f08-11ea-99b5-df11fbe3e926.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/10865605/82857421-d4627b00-9f08-11ea-8e4c-6dff530717b1.png)

**Comment by bloombydee** [comment]
Merging with #145
