### ISSUE TITLE
Reggie's Closed Alpha Application

### ISSUE THREAD

**Issue by reggie-p** [New-Chance-RP/Feedback#176]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 11000014028585a

**Do you have troubleshooting experience?** *(If yes please explain)* :
No, but I would be interested in making a start. I am at all no expert but at least I can make the troubleshooters time in the city a bit more enjoyable. With that said I am a faster learner and have had to adapt all my life. Dont mind helping out.

**How do you personally take screenshots?** : 

GeForce Experience, but lately its been fucky so I use the steam F12 function.

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : 

A brief description of the problem, location of the garage, and a screenshot of my F8 console.

**Discord ID** *Please include numbers* : ceven#7325

**Comment by Senlarus** [comment]
Added! Thanks for offering to help!
