### ISSUE TITLE
Can't See Argent in Shop

### ISSUE THREAD

**Issue by BillChirico** [New-Chance-RP/Feedback#178]
<h2>What bug have you found?</h2>

You cannot view the Argent in the vehicle shop

<h2>What do you expect should happen?</h2>

Show the vehicle

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/13951316/82858198-242d4c00-9ee1-11ea-83ee-5045c37361e9.png)

**Comment by ixhal** [comment]
This has been removed thanks for the feedback, reason it was removed:
It has guns on the car.
