### ISSUE TITLE
Large Trash Container's, Small Circles.

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#180]
<h2>What bug have you found?</h2>

The Large Trash Container's for the trash job have a very small interaction circle, sometimes having to struggle to get into the circle to pick up trash out of it.

<h2>What do you expect should happen?</h2>

The circle to be just a little big larger so that you're still against the container but don't have to wiggle to find the interaction menu.

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/6095886/82859553-1679c580-9ee5-11ea-9e94-1d94b8a28e6a.png)

**Comment by Senlarus** [comment]
Increased size of zone
