### ISSUE TITLE
Gas Station using Debit instead of cash at pump.

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#182]
<h2>Feature you are requesting.</h2>

Currently there's a conflict in currency choices as the shops ask for Debit money but the pump asks for physical cash. It would be better if it were streamlined together in either direction.  Debit seems easiest since you may forget to withdraw money.

<h2>What are the benefits to your feature?</h2>

being able to fill a vehicle without having to make sure you have cash on hand.

<h2>Anything to support your feature request?</h2>

Senlar.

**Comment by BillChirico** [comment]
@Senlarus You still can't do it with no cash on you. You need to have at least $1,

**Comment by Senlarus** [comment]
Oops! Missed the money check. It’s checking to see if you have the cash then charging your bank account! I’ll fix it after dinner. Thanks!

**Comment by ixhal** [comment]
Issue should now be fixed! thanks for the feedback
