### ISSUE TITLE
PD Garage Crash

### ISSUE THREAD

**Issue by ZeroInsomniac** [New-Chance-RP/Feedback#183]
<h2>Crashed when spawning 2016 Charger from MRPD after putting away camaro</h2>

[CfxCrashDump_2020_05_26_04_13_06.zip](https://github.com/New-Chance-RP/Feedback/files/4679870/CfxCrashDump_2020_05_26_04_13_06.zip)

<h2>Car to be pulled and to not crash</h2>

**Comment by ixhal** [comment]
This was caused my a interior load issue not the vehicle, will look into it more if multiple people get the same issue with the interior.
Thanks for the report
