### ISSUE TITLE
Mega Mall Wrench Issue

### ISSUE THREAD

**Issue by BillChirico** [New-Chance-RP/Feedback#184]
<h2>What bug have you found?</h2>

Image and spelling on the wrench is wrong at the Mega Mall

<h2>What do you expect should happen?</h2>

Show image and the correct spelling

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/13951316/82860809-cef53880-9ee8-11ea-99f6-47046c828db7.png)

Edit: Can't buy anything from here

**Comment by ixhal** [comment]
correct image should now be showed, thanks for the report 👍
