### ISSUE TITLE
Trash collection outside of Circle

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#186]
<h2>What bug have you found?</h2>

There is a location during the trash job that you can't grab a trash bag while in the circle but in another location just outside of the circle.

<h2>What do you expect should happen?</h2>

CIRCLES ARE MEANT FOR PROMPS :3 

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/6095886/82861644-5cd22300-9eeb-11ea-8edf-3b0d14e726ff.png)

**Comment by Senlarus** [comment]
@Scarfninja has this happened again? I haven't gotten that location since this post.

**Comment by Senlarus** [comment]
Haven't seen this reproduced. If it happens again let us know whats up.
