### ISSUE TITLE
Phone notification language for new message

### ISSUE THREAD

**Issue by OfficialMasuUK** [New-Chance-RP/Feedback#187]
<h2>What bug have you found?</h2>

Phone notification for new message is in french

<h2>What do you expect should happen?</h2>

Should be in english.

<h2>Anything to support your bug report?</h2>

![Screenshot_6](https://user-images.githubusercontent.com/10865605/82861739-8c962080-9f15-11ea-8e2e-3db9be73b59a.png)

**Comment by BillChirico** [comment]
@OfficialMasuUK Go to phone settings and set the language to English

**Comment by OfficialMasuUK** [comment]
It's not the phone language. It's the notification in the script. Phone language was set to english before I received the message.

**Comment by ixhal** [comment]
Should now be fixed (after the next server restart)
