### ISSUE TITLE
First person

### ISSUE THREAD

**Issue by OfficialMasuUK** [New-Chance-RP/Feedback#188]
<h2>What bug have you found?</h2>

First person causes player to look like they are T-Posing. Also, first person crouch looks like you're trying to hold a weapon.

<h2>What do you expect should happen?</h2>

Not look like you're T-Posing or holding a weapon when you aren't when in first person.

<h2>Anything to support your bug report?</h2>

No evidence of the T-Posing but a screenshot of the weapon issue.

![Screenshot_4](https://user-images.githubusercontent.com/10865605/82861813-cc5d0800-9f15-11ea-8bbe-2295bde1fbb2.png)

**Comment by ixhal** [comment]
Issue should now be fixed
