### ISSUE TITLE
Draw Time on Guns

### ISSUE THREAD

**Issue by HimWhoRobs** [New-Chance-RP/Feedback#19]
<h2>What is your feature request?</h2>

Currently you can whip out a pistol almost instantly same with assault rifles and shotguns. I think there should be a draw time for all weapons but maybe increase it for bigger rifles also. This is so when being held up the person cannot just simple take a pistol out instantly and kill the people.

<h2>What are the benefits of your idea?</h2>

Leads to a fairer game play chain. People who already have weapons draw have a clear advantage and cant be screwed over by GTA mechanics, irl it would take time to upholster weapons.

**Comment by Senlarus** [comment]
This has been added, enjoy!
