### ISSUE TITLE
Police Gate

### ISSUE THREAD

**Issue by DerkDuece** [New-Chance-RP/Feedback#190]
<h2>Feature you are requesting.</h2>

Upgrade the distance at which you can lock and unlock the police gate.

<h2>What are the benefits to your feature?</h2>

Being able to lock the gate while still being in your car.
<h2>Anything to support your feature request?</h2>

**Comment by ixhal** [comment]
Which gate the one at the front of MRPD?

**Comment by Senlarus** [comment]
It’s the one I did and I know how to fix it.

**Comment by ixhal** [comment]
Distance changed thanks for the report
