### ISSUE TITLE
Police Bike not in Vehicle Assignment

### ISSUE THREAD

**Issue by ZeroInsomniac** [New-Chance-RP/Feedback#192]
<h2>Police BMW 1200R not in vehicle assignment</h2>

<h2>Bike to be in assignment menu</h2>

<h2>Anything to support your bug report?</h2>
![image](https://user-images.githubusercontent.com/49663655/82863369-3312ff00-9edf-11ea-96e6-6b6dce2e4695.png)

**Comment by Senlarus** [comment]
I can add this to the menu, but I need to know what ranks are authorized to use it.
