### ISSUE TITLE
Taco Trucks and Buses

### ISSUE THREAD

**Issue by OfficialMasuUK** [New-Chance-RP/Feedback#193]
<h2>What bug have you found?</h2>

Taco Trucks and buses seem to spawn on top of other vehicles randomly

<h2>What do you expect should happen?</h2>

Shouldn't spawn on top of other vehicles.

<h2>Anything to support your bug report?</h2>

None, but I saw it several times in the space of about 5 minutes around a 2 block radius of MRPD

**Comment by bloombydee** [comment]
Not an issue that can be fixed by itself, it is symptom of other issues
