### ISSUE TITLE
Application

### ISSUE THREAD

**Issue by BigPungus** [New-Chance-RP/Feedback#194]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:
76561198836490351 (Dec)
1100001343a206f (Hex)

**Do you have troubleshooting experience?** *(If yes please explain)* :
A little but not much, just bascis
**How do you personally take screenshots?** : 
Through Nivida shadowplay
**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : 
Take a video of it happening and report the video to the Bug report tab in github. Describe what happened and how it happened if able, How you think it should work and intened outcome.

**Discord ID** *Please include numbers* :
Pvt. Pungus#4503

**Comment by Senlarus** [comment]
Approved! Thanks for offering to help. Check discord for more info.
