### ISSUE TITLE
Using elevator while dragging someone

### ISSUE THREAD

**Issue by DerkDuece** [New-Chance-RP/Feedback#195]
<h2>What bug have you found?</h2>

*DELETE THIS LINE - Describe in good detail what bug you have found as well as list the steps to reproduce if known*

<h2>What do you expect should happen?</h2>

The person should see the world and still be being dragged by the med or police officer.

<h2>Anything to support your bug report?</h2>

https://imgur.com/a/I1bUw8k

**Comment by ixhal** [comment]
This is just a drag issue, I'll look into this more when I learn about interiors.

**Comment by bloombydee** [comment]
Interior proxies fixed, remaining issues are just GTA being GTA
