### ISSUE TITLE
Car Lost at Sea

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#197]
<h2>What bug have you found?</h2>

I accidentally drove my car into the ocean, I figured when I went back to the original garage I stored it in I would be able to retrieve it.  However the game still thinks my car is on the streets and won't return the vehicle to me.

<h2>What do you expect should happen?</h2>

Either allow persons to recall vehicles from the last garage they put a vehicle in or have an impound lot you can pay to have your vehicle restored from anywhere.

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/6095886/82868502-bee65480-9efa-11ea-89d4-972c50b0aeb9.png)

**Comment by Senlarus** [comment]
Insurance system has been implimented.
