### ISSUE TITLE
Option to write notes and put on the ground.

### ISSUE THREAD

**Issue by iamrayuu** [New-Chance-RP/Feedback#198]
<h2>Feature you are requesting.</h2>

The option to write notes and put them on the ground for players to pick up and read and destroy after reading.

<h2>What are the benefits to your feature?</h2>

May add to some fun roleplay such as a fake cop writing fake fines, a mysterious note left by a secret admirer 

<h2>Anything to support your feature request?</h2>

I've seen a script before on several servers for this so hopefully it's not too hard to possibly plug in such a feature!

**Comment by Senlarus** [comment]
Added... took a while but we got there!
