### ISSUE TITLE
Trash truck stops taking trash and then refuses to despawn.

### ISSUE THREAD

**Issue by iamrayuu** [New-Chance-RP/Feedback#199]
<h2>What bug have you found?</h2>

At one point during my trash truck run, I attempted to put up a bag in my truck and it said something along the lines of "Must put inside of trash truck", and then when I went to go put it up since it was giving me issues I was unable to make it despawn in there after it gave me the 'end mission' option.

<h2>What do you expect should happen?</h2>

Trash should be able to be stowed in the truck and it should despawn upon entering it in the yellow circle upon inserting it into the yellow circle.

<h2>Anything to support your bug report?</h2>

No evidence but if I replicate it I will share it in an edit or an additional post.

**Comment by Senlarus** [comment]
{x = 484.2, y = -1276.24, z = 29.6}
1605769687 218085040 666561306
"Trying to set workers 2"
![image](https://user-images.githubusercontent.com/1503963/82948561-fe9b5380-9f6f-11ea-818f-193efed09699.png)

**Comment by Senlarus** [comment]
This hasn't been able to reproduced. I took out and stored over 12 truck a couple days ago while testing the red circle issue and all of them de-spawned. This might be related to the current issue #207
