### ISSUE TITLE
/toggleUI gives you a free GPS

### ISSUE THREAD

**Issue by iamrayuu** [New-Chance-RP/Feedback#200]
<h2>What bug have you found?</h2>

If you're not in a car and you use /toggleui and turn it back on, the UI now includes a GPS if you don't have a gps on your person.

<h2>What do you expect should happen?</h2>

Should not have the GPS on it if you don't have a GPS or if you're not in a car.

<h2>Anything to support your bug report?</h2>

Replicated by both me and Redmond!

**Comment by ixhal** [comment]
This should now be fixed. Thanks for the feedback
