### ISSUE TITLE
Serilo - Closed Alpha Access Request

### ISSUE THREAD

**Issue by SeriloUK** [New-Chance-RP/Feedback#201]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 11000010a7935d3

**Do you have troubleshooting experience?** *(If yes please explain)* :

Yes, I am an IT Engineer in real life so troubleshooting is part of my daily routine. I also help to run an Arma III community with Commander Mason and Silver in my spare time which often requires some software and hardware troubleshooting.

**How do you personally take screenshots?** : 

I use Lightshot to take screen caps of the entire screen and snipping tool for sections of the screen.

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : 

I would fill in a Bug Report form on the GitHub and provide as much information as possible (including screenshots where applicable).

**Discord ID** *Please include numbers* : Serilo#3575

**Comment by Senlarus** [comment]
Approved, thanks for offering to help! Check discord for more info!
