### ISSUE TITLE
Closed Alpha Application 

### ISSUE THREAD

**Issue by Fockerlized** [New-Chance-RP/Feedback#202]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 1100001104bd2dc

**Do you have troubleshooting experience?** *(If yes please explain)* :

**How do you personally take screenshots?** : I take screenshots by using the short key on my keyboard (PRTSC), I also sometimes use shadow play to take screenshots as it doesn't disrupt my game as it saves the screenshot into a folder which is easily accessible.

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : I would record everything that is happening so that it is easy to visualise the bug in order to see what went wrong, I would then message a member of staff via in-game or discord informing them about the bug as well as sending them the video footage so that they are able to deal with the matter and resolve this bug.

**Discord ID** *Please include numbers* : Fockerlized#0400

**Comment by Senlarus** [comment]
Approved!
