### ISSUE TITLE
Police Menu/MDT not available inside a vehicle

### ISSUE THREAD

**Issue by OfficialMasuUK** [New-Chance-RP/Feedback#204]
<h2>What bug have you found?</h2>

Police Menu (F5) and the MDT (F6) are not available inside a vehicle

<h2>What do you expect should happen?</h2>

Both should be accessible within a vehicle.

<h2>Anything to support your bug report?</h2>

None

**Comment by Senlarus** [comment]
This is working for me, can you check again? What vehicle?
