### ISSUE TITLE
Police Radar picks up other Police Vehicles like crazy

### ISSUE THREAD

**Issue by OfficialMasuUK** [New-Chance-RP/Feedback#205]
<h2>What bug have you found?</h2>

Police radar picks up police vehicles like 300 times within 1 minute

<h2>What do you expect should happen?</h2>

Should pick up like normal vehicles.

<h2>Anything to support your bug report?</h2>

No image. However, Novoa and also attest to this and maybe other officers can too

**Comment by Senlarus** [comment]
Fixed
