### ISSUE TITLE
Colin Perry App

### ISSUE THREAD

**Issue by cNRR92** [New-Chance-RP/Feedback#206]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: steam id 2 STEAM_0:0:82523697     Steam id 3 64 bit 76561198125313122 (Dec) or 110000109d66c62 (Hex)

**Do you have troubleshooting experience?** *(If yes please explain)* : no

**How do you personally take screenshots?** : ShareX

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : currently dont have a recording programme since plays went down but i could use shadow play

**Discord ID** *Please include numbers* : cNRR#5713

**Comment by bloombydee** [comment]
Congratulations, application approved
