### ISSUE TITLE
Trashmaster bug

### ISSUE THREAD

**Issue by c-reckless** [New-Chance-RP/Feedback#207]
<h2>What bug have you found?</h2>

Pulled up to first location, pressed E to start pickup, red blip did not appear and cannot collect bags.

<h2>What do you expect should happen?</h2>

Press E at location, red blip appears, collect trash bagss.

<h2>Anything to support your bug report?</h2>

https://ibb.co/KGCWj5b

**Comment by Senlarus** [comment]
This needs testing, a fix has been attempted. :)

**Comment by DropKickVibe** [comment]
I had a recording of the whole thing but unfortunately, it corrupted. That's all I could get.
https://user-images.githubusercontent.com/66173725/83357512-b790d200-a364-11ea-83e4-110e08942467.png

**Comment by Senlarus** [comment]
Sadly that's not the debug info I need. It would have info about the trash job in it.

**Comment by Senlarus** [comment]
Ok I think I have it fixed, or at least have made some progress. Give it another shot.

**Comment by DropKickVibe** [comment]
Broke it again, I was testing to see if taking more trash bags than you are supposed to breaks it and it looks like it does 
![image](https://user-images.githubusercontent.com/66173725/83518255-1fb0f680-a4d2-11ea-9f4e-4472b7dd7e9f.png)

**Comment by Senlarus** [comment]
How were you able to take more bags?

**Comment by Senlarus** [comment]
Did someone on your crew die? Because that's what it looks like.

**Comment by DropKickVibe** [comment]
I think so, right as we activated the yellow circle.

**Comment by GiVeDB** [comment]
No, that was +10 minutes before they broke the red circle

**Comment by DropKickVibe** [comment]
Yeah, he died as we arrived at a pickup, but we were able to continue. It actually broke after we picked him up again

**Comment by Senlarus** [comment]
This has been fixed... thanks for all of your help in testing!
