### ISSUE TITLE
Character creation bug

### ISSUE THREAD

**Issue by ixhal** [New-Chance-RP/Feedback#208]
<h2>What bug have you found?</h2>

Character creation issue.
When I went to create a new character no NUI popped up to select my face/hair

<h2>What do you expect should happen?</h2>

I should be able to select what I want to look like

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/32721344/82924189-e6c5ce80-9f73-11ea-9b43-ea5d01d4f04c.png)

EDIT:
(It happened again all i did was try to create a new character I am using character slot 2)
![image](https://user-images.githubusercontent.com/32721344/82925119-38bb2400-9f75-11ea-80cb-9f84c5d26d72.png)

**Comment by Senlarus** [comment]
Anything in F8?

**Comment by Senlarus** [comment]
Reboot fix?

**Comment by ixhal** [comment]
Nope
![image](https://user-images.githubusercontent.com/32721344/82957003-f6f8a080-9fa9-11ea-9957-31c97fe3e744.png)

**Comment by ixhal** [comment]
Seems to be resolved
