### ISSUE TITLE
Closed alpha application

### ISSUE THREAD

**Issue by eguest01** [New-Chance-RP/Feedback#210]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**11000010d89807d (Hex)**:

**YES** *I've been a beta tester for a software service called Apollo for about 6 months. Apollo is a bot that filters messages on platforms like Twitch and Discord.* :

**ShareX, Snipping tool, or NVIDIA overlay.** : 

**I would first create a new issue with the proper label, assign it to the proper roles, then write a detailed description about when, where, and what I was doing. I will also provide screenshots and HD game captures if necessary. ** : 

**Dopey#9027**

**Comment by bloombydee** [comment]
Congratulations, application accepted
