### ISSUE TITLE
Unable to view some peoples legs 

### ISSUE THREAD

**Issue by iamrayuu** [New-Chance-RP/Feedback#211]
<h2>What bug have you found?</h2>

Some people are able to view certain people's characters without their legs, only showing their body head and feet.

<h2>What do you expect should happen?</h2>

Everyone should be able to view everyone the same way.

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/35026673/82940056-e3bde480-9f59-11ea-8ceb-c68c3340350c.png)

**Comment by bloombydee** [comment]
Merging with #145
