### ISSUE TITLE
Closed alpha application | Limerick

### ISSUE THREAD

**Issue by LimerickTV** [New-Chance-RP/Feedback#212]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 11000013d8beaff

**Do you have troubleshooting experience?** *(If yes please explain)* : I wouldnt say i am above average here with experience, however i know how fivem works and its inners. I could be of some help if i found something that needed its attention.

**How do you personally take screenshots?** :  Steam f12

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** :  Before reporting i would see if it is a problem i could fix myself within my rights (rp wise, restarting fivem, rejoining server or something as simple as insurance ect ect within rp of course). If the problem persists i would use one of the reporting bug systems in place with the following. "Hi, as i try to take a car out of my garage i notice nothing is showing on my screen. No prompts or messages, I have tried relogging ect ect but nothing happens. Any ideas?"

**Discord ID** *Please include numbers* : Limerick_TV
#5426

**Comment by Senlarus** [comment]
Approved
