### ISSUE TITLE
Server Status Discord Bot

### ISSUE THREAD

**Issue by BillChirico** [New-Chance-RP/Feedback#213]
<h2>Feature you are requesting.</h2>

Show the server status, amount of players, and whitelisted jobs clocked in.

<h2>What are the benefits to your feature?</h2>

Able to see when the server is back online.

<h2>Anything to support your feature request?</h2>

I can help develop the bot.

**Comment by Senlarus** [comment]
Will get to it eventually but we’re going to focus on more gameplay issues and feature for the immediate release. Thanks!

**Comment by BillChirico** [comment]
@Senlarus Sounds good! I can help develop the bot if you guys would like. I've developed a lot of Discord bots.

**Comment by Senlarus** [comment]
Added
