### ISSUE TITLE
Closed Alpha Apllication - Yung Felix

### ISSUE THREAD

**Issue by yungfelixgg** [New-Chance-RP/Feedback#214]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82
hexcode: 11000011bdaec38

------------------------------------------------------------------------------------------------------------

**Steam ID**:
https://steamcommunity.com/id/skitzofren1x/

**Do you have troubleshooting experience?** *(If yes please explain)* : no

**How do you personally take screenshots?** : lightshot

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : 
I would report the bug to a mod/dev and explain that nothing happens when i'm walking over the marker. Also I will provide information such as: relog.

**Discord ID** *Please include numbers* : Yung Felix#3370

**Comment by ixhal** [comment]
You have been accepted but if you run into any issues please report them on github so we can keep track of the ongoing bugs/issues
Thank you and good luck!

**Comment by yungfelixgg** [comment]
Sure thing will do!
