### ISSUE TITLE
Can't buy a car

### ISSUE THREAD

**Issue by stiansen123** [New-Chance-RP/Feedback#215]
<h2>What bug have you found?</h2> Can't purchase a car

*DELETE THIS LINE - Describe in good detail what bug you have found as well as list the steps to reproduce if known* I can select the car i'd like to buy, but i can't purchase it althought i have money in the bank and on me.

<h2>What do you expect should happen?</h2>  Be able to purchase the car

*DELETE THIS LINE - What do you think should happen, what is the intended outcome that you are currently not getting?* Be the owner of a new car

<h2>Anything to support your bug report?</h2>
Bloomb saw it also, along with other people dropping by the car dealer unable to buy a car

*DELETE THIS LINE - Have you got any evidence to help prove the bug, a video or picture etc?*
Nah

**Comment by Senlarus** [comment]
This has been fixed.
