### ISSUE TITLE
Trash Job No Garbage

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#216]
<h2>What bug have you found?</h2>

I've ended two runs on the very first trash location because when I honk my horn to open the trash chute the garbage bins don't have a red circle for me to collect anything from.

<h2>What do you expect should happen?</h2>

I should be able to pick up garbage when arriving at the location given to me.

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/6095886/82958026-6ce91180-9f82-11ea-9e34-1fd1b4b3b2ff.png)

**Comment by bloombydee** [comment]
Merging with #207
