### ISSUE TITLE
Empty wall on storefront

### ISSUE THREAD

**Issue by alexkaz0** [New-Chance-RP/Feedback#217]
<h2>What bug have you found?</h2>

Can walk through storefront. Friend fell through map if you walked far enough. Entire wall is not there not just doorway. location in video below

<h2>What do you expect should happen?</h2>

Solid Wall

<h2>Anything to support your bug report?</h2>

https://medal.tv/clips/25083715/d1337MTwnRda

Cheers
~Alex

**Comment by bloombydee** [comment]
Part of that storefronts collision had to be removed manually for the burger store next door, will have to go back and revert. thanks for the feedback!

**Comment by Senlarus** [comment]
This has been fixed.
