### ISSUE TITLE
closed alpha application

### ISSUE THREAD

**Issue by luluzedyke** [New-Chance-RP/Feedback#218]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:11000013ffe5e5c (Hex)

**Do you have troubleshooting experience?** *(If yes please explain)* :

**How do you personally take screenshots?** : I use a print screen on my keyboard to capture images

**If you were trying to get your car out of a garage, when you walk over the marker nothing .happens. How would you report that bug? What information would you provide?** : I will record it and send it to a member of staff.

**Discord ID** *Please include numbers* : L_#8585

**Comment by ixhal** [comment]
Accepted but if you run into any issues please post them on github with the correct label just so things don't get lost in translation and we can keep track and squash the bugs!
Thank you and good luck!
