### ISSUE TITLE
Casper/Closed Alpha App

### ISSUE THREAD

**Issue by rubberdingy** [New-Chance-RP/Feedback#219]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:1100001196b638e

**Do you have troubleshooting experience?** *(If yes please explain)* :

**How do you personally take screenshots?** : Print screen or through geforce exp.

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : I would record and give feedback through github or discord. 

**Discord ID** *Please include numbers* :Casper#2385

**Comment by ixhal** [comment]
Accepted good luck in the city!
