### ISSUE TITLE
Lock Pick Not Drivable

### ISSUE THREAD

**Issue by BillChirico** [New-Chance-RP/Feedback#221]
<h2>What bug have you found?</h2>

Lockpicking into a car doesn't allow you to drive it. I've tried toggling the engine, I also stole another car from a local after and was unable to drive it.

<h2>What do you expect should happen?</h2>

Car should be able to be driven.

<h2>Anything to support your bug report?</h2>

Lockpick a car and attempt to drive it. Steal another and still cannot drive the car.

**Comment by ixhal** [comment]
/hotwire, subject to change will need more feedback, maybe make it so you use the lockpick inside of the car to hotwire it.

**Comment by BillChirico** [comment]
@ixhal Ah okay, didn’t know that was a function

**Comment by BillChirico** [comment]
@ixhal Another alternative that may be better is after you local pick the car there is an M menu option to Hotwire it.

**Comment by ixhal** [comment]
Yep its not very well documented on my part, sorry will be changed in the future

**Comment by ixhal** [comment]
System has been changed for this now to be more user friendly, Thanks for the feedback 👍
