### ISSUE TITLE
Motel room glitch

### ISSUE THREAD

**Issue by nells322** [New-Chance-RP/Feedback#222]
<h2>What bug have you found?</h2>
Inside the Pink hotel, after purchasing a room, there's no furniture inside. 
Also, the "invite" function isn't working to invite a friend in. One of my friends tried to invite me and he fell through the floor and spawned in the middle of Legion.

PD: Just found out about the furniture shop. The invite situation still doesn't work though

<h2>What do you expect should happen?</h2>

There should be furniture inside the room. Especially the drawer since those motel rooms are purchased to store stuff in them. Without the furniture, it won't allow us to store things.

<h2>Anything to support your bug report?</h2>

NA

**Comment by bloombydee** [comment]
Go to the furniture store to buy furniture, you're just buying an empty shell. Invite function needs work but for the mean time you can give your friend a spare copy of the key from the managers office with the f9 menu

**Comment by bloombydee** [comment]
Closing as system is changing
