### ISSUE TITLE
pandas alpha app.

### ISSUE THREAD

**Issue by Sexypanda97** [New-Chance-RP/Feedback#223]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 110000111eb4b6a

**Do you have troubleshooting experience?** *(If yes please explain)* : i like .....breaking things and telling people that i broke it, i spent a lot of time in a lot of different games such as borderlands and a few other titles and trying to find ways to brake the game in my advantage.

**How do you personally take screenshots?** : either screenshot or for more precise pics gyazo

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : i would try to replicate what happend and see how i can brake it more, then i would take it to discord to show my results.

**Discord ID** *Please include numbers* : sexypanda#4819

**Comment by Senlarus** [comment]
Approved!
