### ISSUE TITLE
Rena's closed alpha application

### ISSUE THREAD

**Issue by Azeii** [New-Chance-RP/Feedback#225]
**Steam ID**: 110000132029250 

**Do you have troubleshooting experience?** *(If yes please explain)* : In high school, I am able to troubleshoot math problems very easily by using the internet to find solutions to problems.

**How do you personally take screenshots?** : Snipping tool, Shadow play

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : I would re log and check if its an issue on my side, if it inst an issue on my side I'd do everything I just did and I'd make a GitHub ticket about it with screenshots/videos

**Discord ID** *Please include numbers* :rena#6605

**Comment by Senlarus** [comment]
Approved!
