### ISSUE TITLE
Can't drink whisky/vodka/etc

### ISSUE THREAD

**Issue by iamrayuu** [New-Chance-RP/Feedback#226]
<h2>What bug have you found?</h2>

Unable to drink Whisky and Vodka, and the use button is basically like 'greyed out' in a way when you go to drag it over the use.

<h2>What do you expect should happen?</h2>

Should be able to drink all the drinks if they're a type of drink! No matter how bad said drink may be for you.

<h2>Anything to support your bug report?</h2>

https://medal.tv/clips/25094706/d1337B4zx54A
Note: nothing in the F8 menu, no errors.

**Comment by ixhal** [comment]
Will be able to drink them on the next server restart, will be basic and will be improved later on tomorrow thanks for the report 👍
