### ISSUE TITLE
Ambulance garage

### ISSUE THREAD

**Issue by N3rdymomma** [New-Chance-RP/Feedback#227]
<h2>What bug have you found?</h2>

I put away an ambulance and Lena pulled out hers about a min later and it seemed to pull two out. I only saw one but she saw two and was able to put one away while one stayed. 

<h2>What do you expect should happen?</h2>

Only one ambulance should spawn. 

<h2>Anything to support your bug report?</h2>

I cant attach file but DM'd it to Alan(fingers crossed)

**Comment by Senlarus** [comment]
This could have been when we were working on the scripts. I have been unable to reproduce this. If you can try it again and let me know if you can get it to happen that'd be great.

**Comment by Senlarus** [comment]
Will add a sleep to this after requesting the vehicle.
