### ISSUE TITLE
Kazz's Closed Alpha application

### ISSUE THREAD

**Issue by Kazz1** [New-Chance-RP/Feedback#228]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:110000134574953

**Do you have troubleshooting experience?** *(If yes please explain)* :No

**How do you personally take screenshots?** : GeForce Experience

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : First, I would relog to see if it is still a problem then I would report it to a staff with a clip of what's happening and try to describe it if it is something that is descriable.

**Discord ID** *Please include numbers* :Kazz#8602

**Comment by BadBritishGamer** [comment]
If my powers haven't failed me you should be added to the whitelist. Apologies for the time taken getting to this, we hope you enjoy the early access!
