### ISSUE TITLE
Uzi's alpha application

### ISSUE THREAD

**Issue by ItsUzi** [New-Chance-RP/Feedback#229]
**Steam ID**:11000013d35e235

**Do you have troubleshooting experience?** *(If yes please explain)* : somewhat whenever I first got my PC I had to do a lot of troubleshooting and figure things out on my own to get everything on working order

**How do you personally take screenshots?** : Xbox Game bar and snipping tool 

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : I would personally check if its a problem on my side by re logging if that doesn't work i would take a good clip showing the bug then take it to a staff member and make a GitHub ticket   

**Discord ID** *Please include numbers* : ItsUzi#6180

**Comment by BadBritishGamer** [comment]
Thanks for taking the time to complete your application, you should now have access and will be tagged in discord!
