### ISSUE TITLE
Blowtorch when lockpicking

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Feedback#23]
<h2>What bug have you found?</h2>
When using the PD menu's and using "lockpick vehicle" character gets out a blowtorch

<h2>What do you expect should happen?</h2>
A lockpicking animation to be played.

<h2>Anything to support your bug report?</h2>

Clock in as PD, use lockpick on a vehicle.

**Comment by ixhal** [comment]
Fixed let me know if its broken
