### ISSUE TITLE
Closed alpha application

### ISSUE THREAD

**Issue by Nerve012** [New-Chance-RP/Feedback#230]
----------------------------------------------------------------------------------------------------------

**Steam ID**: 11000010d9b1b33

**Do you have troubleshooting experience?** *(If yes please explain)* : No i dont.

**How do you personally take screenshots?** : I use gyazo (https://gyazo.com/captures)

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : I would first contact any developer that i can currently see that is either online in game or in discord, i would explain to them that when i tried to rececive my car it didnt work, if they ask how i meant this i would tell them then when i hover over the prompt to get a car out the garage nothing pops up.

**Discord ID** *Please include numbers* : Baxter Black#5534

**Comment by BadBritishGamer** [comment]
I appreciate you taking the time to apply for the closed alpha, please don't reach out to developers about bugs.

If you come across things that don't work or want to get information across to the development team, open the appropriate issues here on github so it's tracked.

Enjoy the early acces :)
