### ISSUE TITLE
Clutch's App 

### ISSUE THREAD

**Issue by ItsClutcth** [New-Chance-RP/Feedback#231]
**Steam ID**: 110000121699beb 

**Do you have troubleshooting experience?** *(If yes please explain)* : A little bit I'm good at finding the source of problems, like when my PC isn't running right for example my headset wasn't working and broke it down and my drivers weren't updated. 

**How do you personally take screenshots?** : I personally use shadow play for screenshots and taking clips.

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : First i would find out  if the problem is client side by asking if anyone besides me has the problem if that is the case them i contact an admin and or staff if the problem still there then i would compose a clip of the problem make a github ticket and go in to full detail of the whole problem.

**Discord ID** *Please include numbers* : Clutch#2332

**Comment by BadBritishGamer** [comment]
I appreciate you taking the time to complete an application for the closed alpha.

Please skip the step about contacting an admin or staff member unless it's a game breaking bug that is causing huge issues.

All bugs need to be added straight here on the github for tracking purposes.

Enjoy your early access.
