### ISSUE TITLE
Handling change to Comet SR

### ISSUE THREAD

**Issue by BIRLZ95** [New-Chance-RP/Feedback#232]
<h2>What are you requesting?</h2>

Vehicle changes - Comet SR handling to be turned down, less responsive, as its way too good atm, like a pocket rocket on them corners.

<h2>Why are you making this request?</h2>

The car is just too good as it stands, tuning it down would make chases and stuff more fare.

<h2>Anything to support the above?</h2>

Nope, take my word XD

**Comment by Real50BMG** [comment]
Thanks for the feedback. We will tweak most vehicles a bit temporarily and will have much different handlings planned later on

**Comment by OfficialMasuUK** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Handling change to Comet SR #232](https://trello.com/c/QRyaFay3/17-handling-change-to-comet-sr-232)

**Comment by ixhal** [comment]
Closing this since we have new handling since the time it was posted
