### ISSUE TITLE
Trash Job 

### ISSUE THREAD

**Issue by Birlzey** [New-Chance-RP/Feedback#233]
<h2>What bug have you found?</h2>

When doing the trash job with multiple people if someone exits the vehicle or jumps of the back before being in the parkup spot, the circle to pickup trash never shows up, tried clocking on and off multiple times still never worked.

<h2>What do you expect should happen?</h2>

Once you pull up inside the circle and press E another circle should appear next to the garabage so you can collect it.

<h2>Anything to support your bug report?</h2>

Video footage on request

**Comment by Senlarus** [comment]
This is related to the red circle glitch and should be fixed now. Please track all trash related issues on #207 now.
