### ISSUE TITLE
Weed Collection Issue

### ISSUE THREAD

**Issue by BillChirico** [New-Chance-RP/Feedback#234]
<h2>What bug have you found?</h2>

I had 5 weed buds on me, went to collect more, and now I have over the cap of 100.

<h2>What do you expect should happen?</h2>

Allow you to only keep the cap in your inventory.

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/13951316/83047547-863b9d80-a016-11ea-986d-7506f150b788.png)

**Comment by Senlarus** [comment]
@bloombydee Do we care? Most that'll happen is they'll get to 109 / 100

**Comment by BillChirico** [comment]
> @bloombydee Do we care? Most that'll happen is they'll get to 109 / 100

What’s the value of 9 from? Trying to understand it fully

**Comment by BadBritishGamer** [comment]
> 
> 
> @bloombydee Do we care? Most that'll happen is they'll get to 109 / 100

My OCD cares.

**Comment by Senlarus** [comment]
Because the limit of 100 is enforced in your inventory but you pick 10 at a time. So if you have 99, you can still pick a plant and end up with 109. Then you won't be able to pick again. We will just make the check on picking stop you if you have over 90.

**Comment by BillChirico** [comment]
> Because the limit of 100 is enforced in your inventory but you pick 10 at a time. So if you have 99, you can still pick a plant and end up with 109. Then you won't be able to pick again. We will just make the check on picking stop you if you have over 90.

Can I just give you 10 instead? Also, you get 20 buds per

**Comment by Senlarus** [comment]
Np, we'll figure it out.

**Comment by ixhal** [comment]
Should now be fixed, let me know if it still happens 👍
