### ISSUE TITLE
Closed Alpha App.

### ISSUE THREAD

**Issue by ThaDerbMan** [New-Chance-RP/Feedback#235]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:
11000010b4b0890

**Do you have troubleshooting experience?** *(If yes please explain)* :
Yes i use to help run a DayZ server and we all know how buggy that game as been over the years haha.

**How do you personally take screenshots?** : 
I personally use F12 hotkey setup up through my steam overlay but i also run a constant body cam through streamlabs obs.

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : 
I would make sure to re-log and confirm its not client side. The once i find it may seem to be a server or game issue i will then test a few theories to try to get it to function properly. Then i would make sure to fill out a detailed report in feedback with my said findings. 

**Discord ID** *Please include numbers* :
ThaDerbMan#1995

**Comment by BadBritishGamer** [comment]
I appreciate you taking the time to fill out an application, enjoy the closed alpha access :)
