### ISSUE TITLE
NewChance Closed Alpha Access, DHilly#9742

### ISSUE THREAD

**Issue by DHilly69** [New-Chance-RP/Feedback#236]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 11000013f42e8fe

**Do you have troubleshooting experience?** *(If yes please explain)* :Some

**How do you personally take screenshots?** : Yes

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : I would try it again to see if it was an actual bug, if it is I would record it and then use github to report the bug if it continues.

**Discord ID** *Please include numbers* : DHilly#9742

**Comment by BadBritishGamer** [comment]
Appreciate you taking the time to make an application, enjoy closed alpha access :)
