### ISSUE TITLE
Fuel Change on Vehicles

### ISSUE THREAD

**Issue by HimWhoRobs** [New-Chance-RP/Feedback#237]
<h2>What are you requesting?</h2>
Currently the fuel consumption of vehicles seems extremely high. I have asked the discord for people feedback and a lot of people also agree, currently I can do 2 drop offs on the taxi job and I need to refuel the taxi. I think all vehicles need to have less fuel consumption / bigger fuel tanks. I also think that different types of cars should also have unique fuel consumption levels. IE Sports / super cars using more fuel than a normal sedan.
*DELETE AS APPROPRIATE*

3) - Vehicle changes -** *What changes you want think should be made.*
As stated above fuel consumption is very high on all vehicles
<h2>Why are you making this request?</h2>
 Alot of people on the test server feel this way
 What improvements / benefits do you think this will have and why?*
While I do agree there is 100% a need for fuel in the game and it is something I enjoy on the server currently having to fuel up every 25/30 mins is kinda annoying. Especially on the taxi job where this may be a job someone new to the city will take and be low on cash, having to fill up for $100 every $500/$600 you make just feels bad.

**Comment by Real50BMG** [comment]
I do agree that the fuel consumption is very fast. Maybe this could be changed by taking the class of the vehicle in the calculation? Or maybe even the Fmass value of the vehicle.meta files could be a part of how fast the vehicle goes through it's fuel.

**Comment by Senlarus** [comment]
Fuel is taking vehicle class and RPM into consideration. I will look at how we can lower the consumption.

**Comment by Senlarus** [comment]
I have decreased fuel consumption based on vehicle type model across the board. They were decreased by different amount by class so not every type of vehicle will notice a massive improvement while others will see as much as 50% reduction in fuel usage. I'll close this ticket for now and we can continue to discuss in the closed alpha channel in discord.
