### ISSUE TITLE
Locals (NPC's) disappearing (10 minute ghost town) 

### ISSUE THREAD

**Issue by stiansen123** [New-Chance-RP/Feedback#239]
<h2>What bug have you found?</h2>
Locals despawn for about 10 minutes sometimes, it happens quite frequently 
*Describe in good detail what bug you have found as well as list the steps to reproduce if known*
The locals despawn after you've been on the street for a while. In my case, selling drugs. For 10 minutes its a ghost town, then they start to reappear again until next time they despawn for 10 minutes.
<h2>What do you expect should happen?</h2>
Be a constant amount of locals at all times, except maybe less during night time? 
*What do you think should happen, what is the intended outcome that you are currently not getting?*
People to sell drugs to. 
<h2>Anything to support your bug report?</h2>
Nah
*Have you got any evidence to help prove the bug, a video or picture etc?*
Nope

**Comment by HimWhoRobs** [comment]
Ive noticed this also... however it normaly happens around night time and if the weather is kinda shitty. Unsure if its tied to anything or just general gta5 mechanics of less locals at these times

**Comment by Senlarus** [comment]
We have a dynamic population script running that changes Cars, Parked Cars, and Ped every hour. If you are around a crowded area when the pop changes you may notice this despawning occurring because it forces change on your client.

**Comment by OfficialMasuUK** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Journey's fuel drains way too fast even after the decreased fuel consumption #243](https://trello.com/c/88P4SP6q/19-journeys-fuel-drains-way-too-fast-even-after-the-decreased-fuel-consumption-243)

**Comment by stiansen123** [comment]
@Senlarus This happens way more of then than every hour in me and my friends case. I'd say 3-4 times trying to sell 50 bags each

**Comment by Senlarus** [comment]
That would make sense as the hours this script runs on is in-game hours, not IRL hours. It must be just deleting peds when the population is changed down... Will have to look into how to address this.

**Comment by Senlarus** [comment]
We've added one sync. The system that handles this is completely different now so I'm closing for now.
