### ISSUE TITLE
Cop/EMS blips when on duty

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Feedback#24]
<h2>What is your feature request?</h2>

A blip on the map showing where specific members are when clocked in.

<h2>What are the benefits of your idea?</h2>

Allows services to track one another when they are in need of help.

<h2>Anything to support your idea?</h2>

N/A

**Comment by bloombydee** [comment]
Blips added, only need to on player load check blip status

**Comment by Senlarus** [comment]
Fixed
