### ISSUE TITLE
Voice Range

### ISSUE THREAD

**Issue by HimWhoRobs** [New-Chance-RP/Feedback#240]
<h2>What bug have you found?</h2>
Voice range is abit lacking

While attending a store robbery I was unable to hear the people inside and vice versa this was having both of our volumes on the shout feature. I think this shout range should be increased by alot! 14 meters makes it very hard to do any sort of negotiation at a medium range. It only just covers the 24/7 stores and most police trying to talk would be a few meters away behind cars.

<h2>What do you expect should happen?</h2>
 I think that the voice meter should be 25 / 30 meters allowing police and criminals to talk back and forth in store / bank robberies. Allowing police and criminal to stay behind cover and keep the situation realistic
*DELETE THIS LINE - What do you think should happen, what is the intended outcome that you are currently not getting?*

**Comment by Senlarus** [comment]
This is something we will have to re-assess once we go to OneSync 3D audio. For now you will have to get close to the building. I did change a few settings and tested the voice changes, they seem consistent with the blue bubble that shows up when you press ~
