### ISSUE TITLE
Shift Drag to Give/Take Maximum

### ISSUE THREAD

**Issue by BillChirico** [New-Chance-RP/Feedback#242]
<h2>Feature you are requesting.</h2>

Instead of specifying a specific number, it would be nice if you shift dragged so it gives you the maximum amount you can hold.

<h2>What are the benefits to your feature?</h2>

Not having to enter a number so this will highly optimize buying and selling or placing in vehicles.

<h2>Anything to support your feature request?</h2>

N/A

**Comment by Senlarus** [comment]
We won't be able to do this, but we will look into adding double click to use.

**Comment by BillChirico** [comment]
@Senlarus Would setting the number to 0 be doable in order to pass/move the maximum?
