### ISSUE TITLE
Journey's fuel drains way too fast even after the decreased fuel consumption

### ISSUE THREAD

**Issue by BillChirico** [New-Chance-RP/Feedback#243]
<h2>What are you requesting?</h2>

**1) - Vehicle Name-** Journey
**2) - Vehicle changes -** Increase fuel

<h2>Why are you making this request?</h2>

Journey's fuel drains way too fast even after the decreased fuel consumption.

<h2>Anything to support the above?</h2>

N/A

**Comment by OfficialMasuUK** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Journey's fuel drains way too fast even after the decreased fuel consumption #243](https://trello.com/c/88P4SP6q/19-journeys-fuel-drains-way-too-fast-even-after-the-decreased-fuel-consumption-243)

**Comment by Senlarus** [comment]
Gas is done by class. All vehicles in the same class have the same fuel consumption and tank levels. The only difference is the RPMs, so the more you run a vehicle at top speed the faster it drains. This is the same for all other vehicles. We aren't going to change gas levels to be based on specific vehicles at this time.
