### ISSUE TITLE
Cocaine sale price is wrong IMO

### ISSUE THREAD

**Issue by stiansen123** [New-Chance-RP/Feedback#244]
<h2>What bug have you found?</h2>
Cocaine selling for the same as Meth, i believe it should be way higher. Top dollar is 200 dollars per bag for both Meth and Cocaine at the moment.
*Describe in good detail what bug you have found as well as list the steps to reproduce if known*
Cocaine selling for the same as Meth, i believe it should be way higher. Top dollar is 200 dollars per bag for both Meth and Cocaine at the moment.
<h2>What do you expect should happen?</h2>
I expected the Cocaine Sale Price to be way higher than Meth. 
*What do you think should happen, what is the intended outcome that you are currently not getting?*
Higher value than meth, at least maybe 6-800 dollars minimum per bag,
<h2>Anything to support your bug report?</h2>
Nah
*Have you got any evidence to help prove the bug, a video or picture etc?*
Nah

**Comment by ixhal** [comment]
Feedback noted thanks

**Comment by BillChirico** [comment]
@ixhal 

I’ve created a spreadsheet to log data for all types of drugs, their bag sell count, profit, attempts, and rejection percentage. Will have a chat with you about it
