### ISSUE TITLE
Jerry Can Requiring Cash

### ISSUE THREAD

**Issue by BillChirico** [New-Chance-RP/Feedback#245]
<h2>What bug have you found?</h2>

Unable to fuel my car with a jerry can as it requires cash, even though I have some on me.

<h2>What do you expect should happen?</h2>

Be able to fill for free since I already spent money on it.

<h2>Anything to support your bug report?</h2>

*DELETE THIS LINE - Have you got any evidence to help prove the bug, a video or picture etc?*
![image](https://user-images.githubusercontent.com/13951316/83084732-d7b84c80-a057-11ea-93e6-3aecd4721591.png)

![image](https://user-images.githubusercontent.com/13951316/83084741-dedf5a80-a057-11ea-9061-65570191efb4.png)

**Comment by Senlarus** [comment]
This has been fixed.
