### ISSUE TITLE
Gothicce (Celeste Swan)

### ISSUE THREAD

**Issue by GothiccBih** [New-Chance-RP/Feedback#248]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 11000010c8262b7 (Hex)

**Do you have troubleshooting experience?** *(If yes please explain)* : No.

**How do you personally take screenshots?** : Steam, or PRT SC

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : I would report the bug to any available helper/mod and explain that my car won't come out of the garage.

**Discord ID** *Please include numbers* : Gothicc Bih#0229

**Comment by Senlarus** [comment]
Approved, welcome to the closed Alpha!
