### ISSUE TITLE
Closed Alpha App

### ISSUE THREAD

**Issue by BottiBoii** [New-Chance-RP/Feedback#249]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:
-110000117fb2314
**Do you have troubleshooting experience?** *(If yes please explain)* :
- I am not a professional but I have been on another GTA RP server for around 6 months and I usually relog to make sure it's not client side then trouble shoot and report my findings in a detailed message in feedback with a crash dump if needed.
**How do you personally take screenshots?** : 
- Personally I use Nvidia GeForce, Just a simple ALT +F1!
**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : 
- I would have my body cam rolling, I would then save the recording and post it into feedback so that the staff can look into the issue and hopefully find a resolution
**Discord ID** *Please include numbers* :
-BottiFishh#9442

**Comment by Senlarus** [comment]
Approved, welcome to the closed Alpha!
