### ISSUE TITLE
Closed alpha application

### ISSUE THREAD

**Issue by LonelyOven** [New-Chance-RP/Feedback#250]
STEAM ID: 11000010ff0d7f0

Do you have troubleshooting experience? No I haven't had any previous troubleshooting experience

How do you personally take screenshots? I use printscreen or snipping tool

If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?  I would personally see if its not a user issue so i might try a re-log. If the error still persist I will take a screenshot note the time and day and write a description out of the error and send this through bug report feature on Github.com

Discord ID: Sanket#8485

**Comment by bloombydee** [comment]
Congratulations, application accepted
