### ISSUE TITLE
Application 

### ISSUE THREAD

**Issue by jkobro** [New-Chance-RP/Feedback#251]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:1100001184f1aef

**Do you have troubleshooting experience?** *(If yes please explain)* :No i do not.

**How do you personally take screenshots?** : Print Screen Button then copy and paste

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : i would clip the proof and send it into support so a higher up could realise this and help to fix the problem

**Discord ID** *Please include numbers* :jko#8799

**Comment by bloombydee** [comment]
Congratulations, application accepted
