### ISSUE TITLE
low cut top/corset isn't showing up for females

### ISSUE THREAD

**Issue by iamrayuu** [New-Chance-RP/Feedback#253]
<h2>What bug have you found?</h2>

The image in the overshirts of the corset is false, as clicking it actually gives you the checker spotted top from before it in the list.

<h2>What do you expect should happen?</h2>

Should be able to have that top and be able to wear it in game. It's kind of a popular thing a lot of female characters wear! lol

<h2>Anything to support your bug report?</h2>

This is me clicking through 4 of the clothes on the row the corset is on, if you follow my mouse and see what's being equipped on my person, you can see it simply doesnt change between the tank and the corset before it goes to the collared shirt!
https://medal.tv/clips/25094778/d13376UdDoOP

**Comment by iamrayuu** [comment]
addition: It also effects the undershirt version of this particular clothing as well!

**Comment by Senlarus** [comment]
This has been fixed! Let me know if you find any more like it.
