### ISSUE TITLE
Garbage Truck Stopping Working

### ISSUE THREAD

**Issue by Monster-Duck** [New-Chance-RP/Feedback#254]
<h2>What bug have you found?</h2>

I have discovered two bugs. The first was me not being able to start putting bags into the garbage truck, and the second bug prevented me from returning my vehicle. I am guessing this either resulted from renting a bike or repairing the garbage truck as I did both of these things mid run. 

<h2>What do you expect should happen?</h2>

After repairing the trashmaster/renting a bike, I should still be able to continue my task and return my vehicle at the end of it.

<h2>Anything to support your bug report?</h2>

I don't have a clip of me being unable to return the Trashmaster, but here is me unable to continue my task at the pickup point: https://medal.tv/clips/25194031/d1337vyfaVVP

**Comment by eguest01** [comment]
Had the same issue with picking up trash, although my situation was a bit different. On my second stop, I crashed into the dumpster and the red circle disappeared and I could not complete the tasks. Clocking in and out again did not fix it. In both our scenarios it appears our truck was damaged, that could have something to do with it.

**Comment by Senlarus** [comment]
These issues with the red circle were all related to one major issue. This should be fixed now, please track all trash related issues on #207 now. Leave feedback there too.
