### ISSUE TITLE
Burgershot Map Icon

### ISSUE THREAD

**Issue by YahhDopey** [New-Chance-RP/Feedback#255]
<h2>What bug have you found?</h2>

The burgershot icon on the west side of the city is the same as the Pacific Bank icon. This was confusing as I though the bank was a burgershot.

<h2>What do you expect should happen?</h2>

Either the burgershot should have a different icon, or the pacific bank icon should match the rest of the banks in the city.

<h2>Anything to support your bug report?</h2>

https://imgur.com/a/Cn93jKp

**Comment by bloombydee** [comment]
There's no food related blips in the game but this is a unique that I feel would be good

![chrome_nM661vyFhh](https://user-images.githubusercontent.com/52055878/83286327-52db4900-a1a5-11ea-92c2-fc9e47570c67.png)

**Comment by YahhDopey** [comment]
> There's no food related blips in the game but this is a unique that I feel would be good
> 
> ![chrome_nM661vyFhh](https://user-images.githubusercontent.com/52055878/83286327-52db4900-a1a5-11ea-92c2-fc9e47570c67.png)

I like that a lot, the easier solution would be to switch the Pacific Bank icon to match the rest of the banks. Although I'm not sure if you intended on making it stand out from the rest for RP purposes.
