### ISSUE TITLE
CLOSED ALPHA APPLICATION

### ISSUE THREAD

**Issue by Gingejah** [New-Chance-RP/Feedback#257]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:11000013c9c65a8

**Do you have troubleshooting experience?** *(If yes please explain)* :I KNOW HOW TO REPORT BUGS

**How do you personally take screenshots?** :CTRL Z 

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : ID COME ON GITHUB AND SEE IF ANYONE ELSE REPORTED IT IF THEY HAVENT ID REPORT IT 

**Discord ID** *Please include numbers* :Gingejah#3442

**Comment by ixhal** [comment]
Approved hope you enjoy!
