### ISSUE TITLE
Add garage location to car menu

### ISSUE THREAD

**Issue by iamrayuu** [New-Chance-RP/Feedback#260]
<h2>Feature you are requesting.</h2>

Add the garage location of the cars you own so you know where to retrieve them from.

<h2>What are the benefits to your feature?</h2>

With as many vehicles you own and the various garage location options, its hard to remember. If you have it labeled in the menu where the car is located, it will be a general quality of life improvement that makes things easier to keep tabs on!

<h2>Anything to support your feature request?</h2>

This is the car menu in question it should be attached to!
![image](https://user-images.githubusercontent.com/35026673/83190393-fa01a700-a0f7-11ea-9d6c-bab7abb2cd40.png)

**Comment by Senlarus** [comment]
This has been added, thanks for the suggestion!
