### ISSUE TITLE
whitelist app for Nucky Thompson

### ISSUE THREAD

**Issue by Aruss125** [New-Chance-RP/Feedback#262]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82
76561197960287930 (Dec)
1100001000056ba (Hex)
------------------------------------------------------------------------------------------------------------

**Steam ID**:

STEAM_0:0:11101, 76561197960287930 (Dec)
1100001000056ba (Hex)
--

**Do you have troubleshooting experience?** *(If yes please explain)* : yes

**How do you personally take screenshots?** : F12 through steam overlay and a bodycam footage

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : im gonna relog to make sure its not client side , test a few things to see if i can get it to work if not i will submit a report in feedback

**Discord ID** *Please include numbers* :Nucky (dagger) Thompson#0706

**Comment by bloombydee** [comment]
Congratulations, application accepted
