### ISSUE TITLE
Garbage Job no circle coming up in area

### ISSUE THREAD

**Issue by BottiBoii** [New-Chance-RP/Feedback#263]
<h2>What bug have you found?</h2>

While me and a buddy were running trash, we approached our location got the prompt to press E we did, The back opened up and we got out and no red circle was on the ground next to the dumpster

<h2>What do you expect should happen?</h2>

Red circle should appear so you can take trash out of the can

<h2>Anything to support your bug report?</h2>
I have a video clip of what happened. Please DM me on discord if you would like to see!

**Comment by bloombydee** [comment]
Merging with #207
