### ISSUE TITLE
closed alpha application

### ISSUE THREAD

**Issue by TrainWreckTrev** [New-Chance-RP/Feedback#264]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 11000013538beb2

**Do you have troubleshooting experience?** *(If yes please explain)* :somewhat. i try and do it on my own as much as i can. and if i cant get it then ill ask someone else for help.

**How do you personally take screenshots?** : Nvidia or print screen

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : i would screenshot what i was trying to do and where (specially on the map) and provide as much info as i could.

**Discord ID** *Please include numbers* :TrainWreckTrev#9942

**Comment by bloombydee** [comment]
Congratulations, application accepted
