### ISSUE TITLE
Closed alpha application - TheAmazingGryphon

### ISSUE THREAD

**Issue by TheAmazingGryphon** [New-Chance-RP/Feedback#265]
Steam ID:
11000010a72eef2
Do you have troubleshooting experience? (If yes please explain) :
unfortunately not.
How do you personally take screenshots? :
Disable HUD and F12.
If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide? :
I would use the GitHub link provided on discord and then would in individual segments explain 1) How the bug occurred (the sequence of events that happened that created the bug), 2) What the bug actually was and 3) If possible explain how it could possibly be prevented.
In this scenario it would be:
I was trying to get my car out of the garage but when I walked over to the marker. Then I would provide information on which car it was and which garage I was using. I would also report if anyone within the city (that I know of) has experienced a similar bug.
Explain then I would explain how the issue, which is nothing happens when I walk over to the marker and how I could not retrieve the vehicle from the garage.
In this scenario, I have no insight in how the bug could be fixed.
Discord ID Please include numbers
TheAmazingGryphon#7799

**Comment by bloombydee** [comment]
Congratulations, application accepted
