### ISSUE TITLE
rework controller keybinds

### ISSUE THREAD

**Issue by Aruss125** [New-Chance-RP/Feedback#266]
<h2>Feature you are requesting.</h2>
controller keybinds

<h2>What are the benefits to your feature?</h2>
like to get the a button for running only, and the right joystick to not have them ragdoll but more for looking around both ways, x for climbing, y for entering and exiting cars, as of now my right joystick makes my guy ragdoll when i look to the right and if i try and run with B button it pulls up my menu

this could improve the quality of play for those who dont use the keyboard to play

<h2>Anything to support your feature request?</h2>

*DELETE THIS LINE - If you have anything extra to provide, pictures or videos etc to help sell your idea put them here.*

**Comment by Senlarus** [comment]
There is a way to do this but it is going to take a lot of re-coding so we will put this up for post alpha.

**Comment by lAmantel** [comment]
I'm glad I looked, I was about to post a feature request similar. I think a more controller friendly rework of keybinds would be really good. I have also taken the time to go through what all the keybinds for controller do at this current state in closed alpha for on foot, in Vehicle, in a service vehicle (Cops, EMS) and in a helicopter which you can find by clicking [KeyBindings](https://docs.google.com/spreadsheets/d/1HksE5dCp_p3kDb_cgox1IxQO2wevuoVPHUfHDAknhz4/edit?usp=sharing)

**Comment by Senlarus** [comment]
This should be working now, can someone confirm?

**Comment by Senlarus** [comment]
Closing due to no feedback after applying fix.
