### ISSUE TITLE
VOIP breaks post ICU Visit

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#268]
<h2>What bug have you found?</h2>

Was talking with Mike before being put in ICU for 5 minutes, when I came back out of ICU I couldn't hear him and I don't know if he could hear me.

<h2>What do you expect should happen?</h2>

Be able to hear either while in ICU or at the very least after your ICU visit.

<h2>Anything to support your bug report?</h2>

Mike was the first to see me after ICU and I couldn't hear him.

**Comment by ixhal** [comment]
This is because of our current voice system, this will be resolved when we head to mumble, will discuss and see what to do for now.
