### ISSUE TITLE
Can't park car in Garage after an error

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#269]
<h2>What bug have you found?</h2>

Went to park my car in garage near Pillbox for the night and the circle disappeared and now every parking lot circle is missing.

<h2>What do you expect should happen?</h2>

Be able to park my car.

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/6095886/83222965-b3d43400-a147-11ea-8111-fcff701aef5a.png)

**Comment by BillChirico** [comment]
Relogging seems to fix this issue so it appears to be client side

**Comment by Senlarus** [comment]
I need your CitizenFX_log from this day please. You can find it in your fiveM install location in a logs folder. The name should be CitizenFX_log_THEDATEHERE.log

**Comment by Senlarus** [comment]
Any luck with the logs?
