### ISSUE TITLE
Inventory Issue

### ISSUE THREAD

**Issue by ThaDerbMan** [New-Chance-RP/Feedback#270]
<h2>What bug have you found?</h2>

When bagging weed once you reach 11/20 bags it stops you and tells you that you do not have anymore empty room to store weed nugs/bags. I tried dropping items and freeing up space. Nothing worked. 

<h2>What do you expect should happen?</h2>

I expect it to allow me to bag my full 20/20 bags. 

<h2>Anything to support your bug report?</h2>

![0_20200528223124_1](https://user-images.githubusercontent.com/65995423/83225827-a0789700-a14e-11ea-979b-46f34f359146.png)

**Comment by ixhal** [comment]
Should now be fixed thanks for the report!
