### ISSUE TITLE
Outfits also save hair styles.

### ISSUE THREAD

**Issue by ThaDerbMan** [New-Chance-RP/Feedback#271]
<h2>What bug have you found?</h2>

When saving a wardrobe it also saves your facial hair and hair style. I went to the clothes store and took my hat and mask off so i could see my hair and face. then i went and got a new hair style along with new facial hair. Then i went back to the clothes store. Instead of purchasing the hat and mask again i simply selected a saved outfit i had set before my new hair. Once i selected it i was given my saved wardrobe along with my old hair and facial hair. 

<h2>What do you expect should happen?</h2>

Should only save the outfit and not the characters entire physical look.

<h2>Anything to support your bug report?</h2>

None atm but will get small clip soon and DM it.

**Comment by Senlarus** [comment]
This should have been fixed, waiting for confirmation from testing.

**Comment by Senlarus** [comment]
Please verify this is corrected now. @anyone

**Comment by bloombydee** [comment]
Tested and works like it should, closing issue
