### ISSUE TITLE
Application to closed Alpha

### ISSUE THREAD

**Issue by gelatinouscub** [New-Chance-RP/Feedback#272]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:

**Do you have troubleshooting experience?** *(If yes please explain)* :

**How do you personally take screenshots?** : 

****If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide? : 

**Discord ID** *Please include numbers* :

Steam Id  110000137469c9e (Hex)  

  **Do you have troubleshooting experience?** *(If yes please explain)* :
I have no troubleshooting experience; just RP experience. 

  **How do you personally take screenshots?** : 
The only way i have taken screenshots is via steam.

  ****If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide? 👍 
  I would submit a Github ticket with needed information
**Discord ID** *Please include numbers* :
gelatinouscube#7025
 Thank you for your consideration.

**Comment by bloombydee** [comment]
Congratulations, application accepted
