### ISSUE TITLE
Application

### ISSUE THREAD

**Issue by Aggrorp** [New-Chance-RP/Feedback#273]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 11000013eaaaed9 (Hex)

**Do you have troubleshooting experience?** *(If yes please explain)* : No

**How do you personally take screenshots?** : I use an app called ShareX and is Screenshots my whoole page when i click (Print Screen)

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : I would say, "Hi im at a garage and when i try to get my car out nothing happens, i dont what the cause is and it could just be me but if you have time could you look at it? Thanks"

**Discord ID** *Please include numbers* : aggrorr#7632

**Comment by bloombydee** [comment]
Congratulations, application accepted

**Comment by Aggrorp** [comment]
Thankyou! So what’s the next step?
