### ISSUE TITLE
Closed alpha application

### ISSUE THREAD

**Issue by JaredCaz** [New-Chance-RP/Feedback#274]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:
11000010f23cd18

**Do you have troubleshooting experience?** *(If yes please explain)* :
No

**How do you personally take screenshots?** : 
Windows screenshot or steam screenshot

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : 
first re-log to see if that fixes it and if it still was broken after I re-log then I would try to do other things to attempt to get it to work and if it still wont work I would check to see if someone else reported it, if not then I would report it

**Discord ID** *Please include numbers* :
Jared#9966

**Comment by bloombydee** [comment]
Congratulations, application accepted
