### ISSUE TITLE
Application 

### ISSUE THREAD

**Issue by Geky000** [New-Chance-RP/Feedback#275]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**11000013b5eea96 (Hex)**:

**Do you have troubleshooting experience?**No *(If yes please explain)* :

**How do you personally take screenshots?*I F12 on steam and upload them to the steam cloud.* : 

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : First i would check if its been reported and if it hasnt i would say: When i tried to get my car out the garage i stood over the marker and the car didn't get pulled out.
1.Select to take car out
2.Stand over marker
3.Car does not come out.

**Discord ID** *Please include numbers* : 
Geky#0798

**Comment by bloombydee** [comment]
Congratulations, application accepted
