### ISSUE TITLE
Closed beta Application

### ISSUE THREAD

**Issue by gunnemike** [New-Chance-RP/Feedback#277]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:11000010f5ea0bb

**Do you have troubleshooting experience?** *(If yes please explain)* : no 

**How do you personally take screenshots?** : Gyazo

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : I would go into technical issues on the discord and report it on there with a video and explanation of what is wrong with it

**Discord ID** *Please include numbers* : Mik3sLIVE#8062

**Comment by BadBritishGamer** [comment]
#281 closed in reference to the second application.
