### ISSUE TITLE
Closed alpha application

### ISSUE THREAD

**Issue by That1Gamer** [New-Chance-RP/Feedback#278]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 110000106f908ad
**Do you have troubleshooting experience?** *(If yes please explain)* : Yes, troubleshooting code

**How do you personally take screenshots?** : snipping tool

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?**: Firstly I would screenshot me on the marker, then I would record the date and time. After that I would quickly write a description of what was the issue and then post a report on the github bug report page.

**Discord ID** *Please include numbers* : That1Gamer#8971

**Comment by BadBritishGamer** [comment]
Welcome to the closed alpha access, please check discord tags for more information.
