### ISSUE TITLE
PD Ranking breakdown

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Feedback#28]
<h2>What is your feature request?</h2>
Cadet & Officer - Flashlight, nightstick, taser, Combat pistol
	Car = 
		Cadet = Crown Vic
		Officer = Crown Vic
	Wage = 
		Cadet = $600
		Officer = $800

Senior Officer - Flashlight, nightstick, taser, Combat pistol, Pump Shotgun,
	Car = Ford Explorer
	Wage = $1000

Sergeant - Flashlight, nightstick, taser, combat pistol, pump shotgun, carbine rifle
	Car = No new vehicle
	Wage = $1300

Lieutenant - Flashlight, nightstick, taser, combat pistol, pump shotgun, carbine rifle
	car = Dodge Charger
	wage = $1500

Captain - Flashlight, nightstick, taser, combat pistol, pump shotgun, carbine rifle, Sniper Rifle
	Car = No new vehicle
	wage = $1700

Major - Flashlight, nightstick, taser, combat pistol, pump shotgun, carbine rifle, Sniper Rifle, Breach tools?
	Car = Chevy Tahoe
	Wage = $2000

Commander - Flashlight, nightstick, taser, combat pistol, pump shotgun, carbine rifle, Sniper Rifle, Breach tools?
	Car = No new vehicle
	Wage = $2200

<h2>What are the benefits of your idea?</h2>

PD structure to be implemented.

<h2>Anything to support your idea?</h2>

Nope

**Comment by Senlarus** [comment]
Send Hal or I the details on the new cars and ranks they go with and we will set it up.
