### ISSUE TITLE
Taser shots triggering 10-13 prompt.

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Feedback#280]
<h2>What bug have you found?</h2>
A taser is a very quiet weapon that wouldn't be heard, firing a taser currently will prompt the 10-13 code due to locals in the vicinity.

<h2>What do you expect should happen?</h2>
Tasers  shouldn't trigger the dispatch notification as it's not ideal. 

<h2>Anything to support your bug report?</h2>
Go in game, fire taser, PD gets prompt.

(Haven't checked but curious if this will then show the user positive for GSR)

**Comment by Senlarus** [comment]
I already have logic for silenced weapons, I'll just add this weapon to that logic... I guess GTA doesn't consider it silenced. lol
