### ISSUE TITLE
Application

### ISSUE THREAD

**Issue by gunnemike** [New-Chance-RP/Feedback#281]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:11000010f5ea0bb

**Do you have troubleshooting experience?** *(If yes please explain)* :  No

**How do you personally take screenshots?** : Gyazo 

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : Post it in the feedback information on discord with a video and explanation of what exactly is wrong

**Discord ID** *Please include numbers* :
Mik3sLIVE#8062

**Comment by BadBritishGamer** [comment]
Bug information should be posted here under "New issues > Bug report".

Before  we accept you I need to ask, why the 2nd application 2 hours after the first?

**Comment by gunnemike** [comment]
I didnt know if the application went thru because my pc reset as i was submitting the app!

**Comment by gunnemike** [comment]
How much longer until i get accepted or denied ? I really want to play on the server and help find problems and report them so its good for launch!

**Comment by bloombydee** [comment]
Congratulations, application accepted
