### ISSUE TITLE
Application 

### ISSUE THREAD

**Issue by Loudpack16** [New-Chance-RP/Feedback#282]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 11000013bc6e420

**Do you have troubleshooting experience?** *(If yes please explain)* : no

**How do you personally take screenshots?** :  Geforce experience 

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : i would take a 2 minute clip and send it to the bug reports.

**Discord ID** *Please include numbers* : Loudpack#6163

**Comment by BadBritishGamer** [comment]
Welcome to the closed alpha access, please check discord tags for more information.
