### ISSUE TITLE
Beta App

### ISSUE THREAD

**Issue by SwizzyWT** [New-Chance-RP/Feedback#283]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 110000140f0048b

**Do you have troubleshooting experience?** *(If yes please explain)* : No

**How do you personally take screenshots?** : Gyazo 

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : I would take a video clip of the issue that has taken place, look to see if it has been reported and if not I will report the issue to bug reports. 

**Discord ID** *Please include numbers* : Swizzy#0795

**Comment by BadBritishGamer** [comment]
Welcome to the closed alpha access, please check discord tags for more information.
