### ISSUE TITLE
Fife's Application 

### ISSUE THREAD

**Issue by FifeFX** [New-Chance-RP/Feedback#286]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 110000107e40506   (I'm currently using gta v through rockstar's application, if thats okay)

**Do you have troubleshooting experience?** *(If yes please explain)* : I have little experience, but I am more than willing to learn to help. In my experience i've only helped a few friends with old minecraft servers years ago. 

**How do you personally take screenshots?** :  Through nvidia's geforce experience application, and gyazoo at times.

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** :  I would state exactly what I'm attempting to do, and what the game is doing. I would also say when it occurred and what I did shortly beforehand. I would also say what I think might have happened if I believe it to be true. I could also provide a recording of what exactly i'm doing.

**Discord ID** *Please include numbers* : Fife#1886

**Comment by BadBritishGamer** [comment]
@Senlarus Will this be normal whitelist considering through rockstar client?

**Comment by BadBritishGamer** [comment]
Added to the closed alpha, please make sure you report bugs here on the github.
