### ISSUE TITLE
Ashton Closed alpha application

### ISSUE THREAD

**Issue by DankHub** [New-Chance-RP/Feedback#287]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:1100001162aa089

**Do you have troubleshooting experience?** *(If yes please explain)* : I once couldnt go in to a roleplay server and i went to their discord to check if the server is crashed or the server is shut down

**How do you personally take screenshots?** : I can take it with Geforce Experience and steam f12 and snipping tool

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : im gonna make sure its not a client issue and i will try to take as much screenshot to have more proof that my game is bugged and report all that on github

**Discord ID** *Please include numbers* :aashtoon#6201

**Comment by BadBritishGamer** [comment]
Wouldn't really consider checking if a server is online or not troubleshooting experience, that's basic common sense :) Regardless check discord tag for more information welcome to closed alpha.
