### ISSUE TITLE
DropKickVibe Application 

### ISSUE THREAD

**Issue by DropKickVibe** [New-Chance-RP/Feedback#289]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:
110000107d7d5c8

**Do you have troubleshooting experience?** *(If yes please explain)* :
Yes, I have some experience with Arma 3 Life RP servers. I helped test and administrate a popular sever on there. I was also part of The Division Closed Alpha by Ubisoft, so I helped troubleshoot issues before release.

**How do you personally take screenshots?** : I use GeForce experience to take screenshots or I am often running OBS so I will go back through a recording and take screenshots. I also use Steam sometimes. 

**If you were trying to get your car out of a garage when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** :
First I would try to confirm that the issue inst client side. After that, I would follow the Bug reporting procedure, so in this case by reporting it on GitHub. I would include as much detail as possible and Screenshots and video if possible.

**Discord ID** *Please include numbers* :
DropKickVibe#4056

**Comment by BadBritishGamer** [comment]
Check discord for a tag and more information, welcome to closed alpha.
