### ISSUE TITLE
New building for MRPD

### ISSUE THREAD

**Issue by itomicz** [New-Chance-RP/Feedback#29]
<h2>What is your feature request?</h2>

A new building for MRPD.

I think this would be a good feature towards the server as it is different to the normal and basic MRPD what GTA currently has. This one has multiple floors and will look good for people within the server to personally use and also for people who stream.

<h2>What are the benefits of your idea?</h2>

The benefits towards getting this building is that, there are more that 3 cells what the police, lawyers and criminals can use, there are multiple meeting rooms where you can have discussions, making the RP better. Also if someone is streaming, the viewers will be able to see that there is actually something different inside the police station and might like the idea, making them want to join the server

The server could benefit from this idea by getting more people to join, as it will show that the developers are taking their time to make something different, and wanting to improve the design within the server its self.

<h2>Anything to support your idea?</h2>

https://forum.cfx.re/t/community-mission-row-pd-mlo/803817

**Comment by HenryBushen** [comment]
Will add to my test server then see what pd thinks

**Comment by Senlarus** [comment]
This has been implemented, enjoy!
