### ISSUE TITLE
Jotham Closed alpha application

### ISSUE THREAD

**Issue by Sh4ddap** [New-Chance-RP/Feedback#291]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 110000118154435

**Do you have troubleshooting experience?** *(If yes please explain)* : yes, there was a hacker in a roleplay server. He was blowing up everyone and causing chaos in the city, i managed to get his id before i died and reported it to staff.

**How do you personally take screenshots?** : Steam screenshot, Nvdia Geforce,  snipping tool and considering to try medal.tv

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : Each server has a report button. First of all, i will clip it or screenshot make sure its a bug everyone's getting. Secondly, I will show the evidence of the bug and send to staff and tell what exactly happened and ask for assistance.

**Discord ID** *Please include numbers* : food#9470

**Comment by BadBritishGamer** [comment]
Finding a hacker isn't troubleshooting experience, please look into what troubleshooting means and reply to this application here in the comments with the definition.

Please do not send bugs to staff as they cannot fix bugs, the correct procedure is to post the bug report here on github. Please confirm you understand this procedure in place.

**Comment by Sh4ddap** [comment]
In general, troubleshooting is the identification of, or diagnosis of "trouble" in the management flow of a corporation or a system caused by a failure of some kind. The problem is initially described as symptoms of malfunction, and troubleshooting is the process of determining and remedying the causes of these symptoms.

Yes, i understand that any bug that took place, i will send to the github instead of the staff.

**Comment by BadBritishGamer** [comment]
Added to the closed alpha, please look for the tag in discord to get more info.
