### ISSUE TITLE
Lohkii's Application

### ISSUE THREAD

**Issue by Lohkii-s** [New-Chance-RP/Feedback#292]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:110000131e8aad4

**Do you have troubleshooting experience?** *(If yes please explain)* :Yes, My friend started a small Arma 3 Life server, and i helped him troubleshoot it, and get it started. And i always try to help improve the servers that i play on, by reporting bugs.

**How do you personally take screenshots?** : Sometimes i use GeForce experience or steam to capture screenshots. However i usually run StreamLabs OBS to capture, so if i need screenshots i usually go back through my recordings.

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : After i would ensure that it was not a client side issue, i would then report it in the relevant GitHub section, and include as much detail as possible, with screenshots and video if possible.

**Discord ID** *Please include numbers* : Lohkii#5918

**Comment by bloombydee** [comment]
Congratulations, application accepted
