### ISSUE TITLE
Orange high-vis vest overlaps with bulletproof vest, can't remove.

### ISSUE THREAD

**Issue by iamrayuu** [New-Chance-RP/Feedback#293]
<h2>What bug have you found?</h2>

I clocked on to PD (female) and realized the high-vis vest I had on is unable to be removed, even when I put on a bulletproof vest and also clicked the "orange high-vis vest" option (in hopes that it would remove it.)

<h2>What do you expect should happen?</h2>

Being able to remove the highvis vest and replace with bulletproof vest, or atleast being able to hit the orange vest in the clothing locker option and it removes it

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/35026673/83338495-9196ff00-a28a-11ea-9e87-5fffa66a5e2d.png)

**Comment by ixhal** [comment]
Just click civilian outfit for now and put on the options you want, this will be changed in the future when we get EUP and more clothing options + rework the menu 
thanks for the report

**Comment by Senlarus** [comment]
This item was removed.
