### ISSUE TITLE
Hair Dresser / Clothing Shop Bug

### ISSUE THREAD

**Issue by BillChirico** [New-Chance-RP/Feedback#294]
<h2>What bug have you found?</h2>

- Went to change my hair at the barbershop
- Went back to the clothing store and saved a new outfit
- No prompt now to buy more clothes but at barbershop it still allows me to have a prompt

<h2>What do you expect should happen?</h2>

Prompt should still work

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/13951316/83340469-9073cb00-a2a6-11ea-884c-8d5b6282f97b.png)

**Comment by Senlarus** [comment]
Related to a fix I was doing for #271
