### ISSUE TITLE
Lost character creation menu and couldn't bring it back.

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#295]
<h2>What bug have you found?</h2>

I was working on making a second character and while I was picking out clothes.  I think I hit the Num-0 key and then the menu disappeared and I couldn't get it to come back at all.

<h2>What do you expect should happen?</h2>

Hitting keys by mistake won't cause the menu to disappear.

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/6095886/83340622-789d4680-a2a8-11ea-88c5-f8567a9292c7.png)

**Comment by Senlarus** [comment]
Nope, that was me working on the clothing store script. I restarted it while you were in char creation.
