### ISSUE TITLE
Jimmy Kim's Application.

### ISSUE THREAD

**Issue by yungotti** [New-Chance-RP/Feedback#296]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:
11000010a0a5139

**Do you have troubleshooting experience?** *(If yes please explain)* :
Troubleshot years ago on a couple servers.

**How do you personally take screenshots?** : 
GeForce / F12 / MedalTV**

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : 
I would wait in Discord for a staff member, stay at the garage wait for a staff member to get on and try to figure out whats wrong together. Screen share if needed.

**Discord ID** *Please include numbers* :
Kim Jong Yun #2145

**Comment by bloombydee** [comment]
Congratulations, application accepted
