### ISSUE TITLE
Loading Video No Longer Showing

### ISSUE THREAD

**Issue by BillChirico** [New-Chance-RP/Feedback#297]
<h2>What bug have you found?</h2>

The loading video is no longer showing.

<h2>What do you expect should happen?</h2>

For it to show and play the music and allow you you mute the music,

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/13951316/83350625-5f79b180-a30b-11ea-9ab2-f86763b44826.png)

**Comment by Senlarus** [comment]
New video is up
