### ISSUE TITLE
Too Easy to Steal Vehicles

### ISSUE THREAD

**Issue by BillChirico** [New-Chance-RP/Feedback#298]
<h2>What bug have you found?</h2>

Pointing a gun at an individual car seems to have a 100% chance of them getting out. This seems too easy to steal a car and will be a nightmare for cops once that gets going fully.

<h2>What do you expect should happen?</h2>

Maybe add a chance that the individual will drive off, refuse to get out, or even possibly shoot back at you.

<h2>Anything to support your bug report?</h2>

Just point a gun at anyone driving a car.

**Comment by ixhal** [comment]
this is not a bug its a inteded feature.

**Comment by BillChirico** [comment]
@ixhal I know it's a feature and it's a great one, but there needs to be something to prevent it being 100% successful. Maybe they'll become aggressive and start attacking you?

**Comment by ixhal** [comment]
Either way no matter what happens as the outcome it will be reported to the police I believe there is no reason to change this, police see things as priority or not priority in the current situation + adds more for police to do on slow days, there is no reason to steal cars right now (no chop shop ect) so people being able to steal it 100% of the time does not matter imo.

**Comment by BillChirico** [comment]
> Either way no matter what happens as the outcome it will be reported to the police I believe there is no reason to change this, police see things as priority or not priority in the current situation + adds more for police to do on slow days, there is no reason to steal cars right now (no chop shop ect) so people being able to steal it 100% of the time does not matter imo.

Good call, I agree
