### ISSUE TITLE
Can't see other players at garbage job.

### ISSUE THREAD

**Issue by BillChirico** [New-Chance-RP/Feedback#299]
<h2>What bug have you found?</h2>

I went down to pick up two people from the garbage job and could not see them even though they are there. They are possibly instanced or I am.

<h2>What do you expect should happen?</h2>

Not be instanced and be able to see them.

<h2>Anything to support your bug report?</h2>

**My Angle:**
![image](https://user-images.githubusercontent.com/13951316/83351325-eed59380-a310-11ea-9eba-c112a8a2751d.png)

**Their Angle:** 
![image](https://user-images.githubusercontent.com/13951316/83351356-1dec0500-a311-11ea-8ba5-a733ccb0f8a3.png)

<h3>Edit: After some time I was able to eventually see one of them. The other one had to relog in order for me to see him<h3>

**Comment by Senlarus** [comment]
Sometimes people get instanced, the only fix is relogging. We have a instance kick but we turned it off for the time being.
