### ISSUE TITLE
PD Vehicles

### ISSUE THREAD

**Issue by itomicz** [New-Chance-RP/Feedback#30]
As of right now i have found a PD vehicle pack. Within the PD vehicle pack, you can either pick between a crown vic, explorer, interceptor ect. The second pack is the same however some of the models are different and might look a bit better. The third link is the link of a 2018 Chevrolet Camaro. Personally i like this car and should be added to supervisors+. It is fast and cool looking car and cool as fuck, and the last pack is a pack covering the 2016 Ford Police Interceptor Utility. 

PD CAR PACK 1: https://www.lcpdfr.com/downloads/gta5mods/vehiclemodels/25916-shp-vehicle-pack-non-els/

PD CAR PACK 2: https://www.lcpdfr.com/downloads/gta5mods/vehiclemodels/25910-rcmp-vehicle-pack-non-els/

2018 Chevrolet Camaro: https://www.lcpdfr.com/downloads/gta5mods/vehiclemodels/25708-non-els-2018-chevrolet-camaro-zl1-fivem-ready-awd-rb-all-blues/

2016 Ford Police Interceptor Utility pack: https://forum.cfx.re/t/release-2016-ford-police-interceptor-utility/162913

**Comment by Crab3512** [comment]
chose PD Car Pack 2 skinning in process
