### ISSUE TITLE
Trash Lorry Job

### ISSUE THREAD

**Issue by DropKickVibe** [New-Chance-RP/Feedback#303]
<h2>What bug have you found?</h2>

The red circle is missing at the pickup locations when working as a Trashman. There was four of us on one lorry and we did one stop just like last time and then the second stop broke, we went back to the depot and returned the lorry and clocked off and then tried again but it was still broke. I have two main theories, 1) When we arrived at the second pickup we crashed into the bin slightly, maybe this played a part in the pickup not working. 2) When you have multiple people pulling trash bags out of a bin, you can actually take more bags out of the bin that the game says are in the bin, I think this is the most likely issue as I think the game becomes confused as to where the extra bags come from.

**Comment by Senlarus** [comment]
Did you not grab the diagnostic info I had printing to the F8 window when you started the pickup and the red circle disappeared?

**Comment by Senlarus** [comment]
Please use main thread #207
