### ISSUE TITLE
Non-emergency number for PD.

### ISSUE THREAD

**Issue by iamrayuu** [New-Chance-RP/Feedback#305]
<h2>Feature you are requesting.</h2>

EMS has the option to make a non-emergency text to their area, but PD doesn't. I feel it'd be a good idea to have the same option for PD!

<h2>What are the benefits to your feature?</h2>

As I've been told, it's encouraged to call police in order to make them aware on if you're using an area for target practice (like the shooting range in ammunation), but there's no way to let them know without just hitting the 'request police' button. It's also good for perhaps be able to send to them to drop tips about a criminal on the run and just opens the door for more police/civilian interactions. 

And if anyone abuses it I guess they can be charged for abusing police resources?

<h2>Anything to support your feature request?</h2>

N/A

**Comment by Senlarus** [comment]
Done
