### ISSUE TITLE
application

### ISSUE THREAD

**Issue by BatsieSandra** [New-Chance-RP/Feedback#307]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 11000010ea783ac

**Do you have troubleshooting experience?** *(If yes please explain)* :
yes, windows
**How do you personally take screenshots?** : 
Prtsc
**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** :  Where the garage is location.If i did anything different,if the garage work befor i try it.

**Discord ID** *Please include numbers* :
Battsie Sandra #5142

**Comment by bloombydee** [comment]
Congratulations, application accepted
