### ISSUE TITLE
Police Car Performance Tweaks

### ISSUE THREAD

**Issue by HimWhoRobs** [New-Chance-RP/Feedback#308]
<h2>What are you requesting?</h2>

*DELETE AS APPROPRIATE*

**3) - Vehicle changes -** *What changes you want think should be made.*
A change to overall police cars in general (Most of them are far too OP or have massive issues) The Crown vic is imo a terrible car in its current state, it has very little back end traction once turning any corner cira 30mph and above. It has a feeling of having a huge water tank in the boot. and once this said water hits the side the back end shoots out. The car will need to have a center of mass change from the rear to the mid/ front. 2nd The charger needs to be heavier this car honestly feels like it has the inside filled with helium, any slight turn seems to shift the whole car causing it to spin out violently. and last on the list is the Tahoe, having the Tahoe and the Ram set off at the same time is a clear indication of the problem. The Tahoe is one of the quickest cars (in its current broken state) in the PD, both in accelaration and top speed. Not to mention it handles extremely well. I reckon this car should feel heavier and thus a slower acceleration. 
<h2>Why are you making this request?</h2>
In the current state the PD cars are far too broken. Yes we have to chase criminals but I want that chase to be fair for both parties.

What improvements / benefits do you think this will have and why?*
Stated above a genera slight nerf to most cars but major changes to the 3 mentioned
<h2>Anything to support the above?</h2>
Try the cars and apply basic logic

**Comment by OfficialMasuUK** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Crown Vic and Charger handling for PD](https://trello.com/c/z4FVeGqv/20-crown-vic-and-charger-handling-for-pd)

**Comment by OfficialMasuUK** [comment]
Made changes to several PD vehicles. Testing done by a few people and feedback seems to be good so far. Any issues, send back another vehicle report please. Thank you.
