### ISSUE TITLE
Garage script scuffed

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#309]
<h2>What bug have you found?</h2>

After the last reset, no cars can be unlocked/locked, and my camera is stuck in the overview position from checking what car to pull out.

<h2>What do you expect should happen?</h2>

My camera to not get trapped, being able to lock/unlock cars, and giving keys to friends.

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/6095886/83369690-34cf3d80-a38b-11ea-8802-f6496afe9f6d.png)

![image](https://user-images.githubusercontent.com/6095886/83369733-3f89d280-a38b-11ea-9d46-ea9b1452350d.png)

**Comment by Senlarus** [comment]
This was when a new car lock system was being installed. All issues should have been resolved.
