### ISSUE TITLE
Crim Insanity

### ISSUE THREAD

**Issue by Briefinsanitytv** [New-Chance-RP/Feedback#310]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 110000106fad7dd
------------------------------------------------------------------------------------------------------------

**Steam ID**: [PC-??] Crim I.

**Do you have troubleshooting experience?** *(If yes please explain)* : Yes, I have dealt with a lot of problems with computers and have quiet a bit of experience of successfully figuring out the problem.

**How do you personally take screenshots?** : no

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : Report the bug directly to the moderators so it can be dealt with, try to RP as tho the garage door is broken and need to call someone to come help open it.

**Discord ID** *Please include numbers* : BriefInsanityTV#0666

**Comment by Senlarus** [comment]
Approved, check discord.
