### ISSUE TITLE
Saved Outfits?

### ISSUE THREAD

**Issue by lAmantel** [New-Chance-RP/Feedback#311]
<h2>What bug have you found?</h2>

So I'm on my character Lena, and I wanted to used one of my saved outfits that I had. When I go to it they're gone, but what I do find is my outfits that I have saved for my OTHER character Grandma Memaw.

<h2>What do you expect should happen?</h2>

I think the outfits should be seperated, by character and if it was already then I think it's slightly bugged at this moment, Hence my post. I also think we should have maybe more then two saved outfits..

<h2>Anything to support your bug report?</h2>

Me on Lena, But with Grandma memaws outfits saved.
![image](https://user-images.githubusercontent.com/62526207/83411296-f5820a80-a3e5-11ea-93af-28bf16b4d08e.png)

**Comment by Senlarus** [comment]
This should be fixed! please check (Sorry you'll have to redo your outfits)
