### ISSUE TITLE
Drills Durability 

### ISSUE THREAD

**Issue by BIRLZ95** [New-Chance-RP/Feedback#312]
<h2>Feature you are requesting.</h2>

Drills should have a % chance to break upon using them or a durability bar for it.

<h2>What are the benefits to your feature?</h2>

Too OP to be able to keep the same drill and use it forever, plus they break IRL.

<h2>Anything to support your feature request?</h2>

N/A

**Comment by bloombydee** [comment]
Will probably make it so the drill requires a bit, the bit can break but is cheap

**Comment by Birlzey** [comment]
Sounds good to me!
