### ISSUE TITLE
Can't exchange chips back to cash.

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#314]
<h2>What bug have you found?</h2>

Got bored with gambling, went to get my cash back and it says I don't ahve enough chips, but I have the exact amount of chips I put in the menu.

<h2>What do you expect should happen?</h2>

I expect to have my chips exchanged back to cash.

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/6095886/83426072-9ed3fb00-a3fc-11ea-9d67-268908c152aa.png)

**Comment by ixhal** [comment]
Should now be fixed, thanks for the report!
