### ISSUE TITLE
Item in Clothing Shop Bug

### ISSUE THREAD

**Issue by Birlzey** [New-Chance-RP/Feedback#316]
<h2>What bug have you found?</h2>

When left clicking on a certain pair of arms in the clothing store it makes you throw a punch and you are unable to get the clothing menu off your screen.

<h2>What do you expect should happen?</h2>

Left clicking on the arms should make them show on your character and not make you throw a punch.

<h2>Anything to support your bug report?</h2>

https://www.youtube.com/watch?v=S-qXddU4kAE&feature=youtu.be

**Comment by Senlarus** [comment]
I can't reproduce this and I noticed in your F8 menu this happened right as I restarted a NUI resource I was working on which is most likely what caused it to happen.
