### ISSUE TITLE
Garage's at Job Sites

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#317]
<h2>Feature you are requesting.</h2>

We need to be able to park our cars close to job sites so that we're not having to waste money on bikes just to get our car after it despawned.

<h2>What are the benefits to your feature?</h2>

Not having our cars despawn when at a job site if the job takes too long to do.

<h2>Anything to support your feature request?</h2>

It's legitimately tilting that every time I try to do a job I come back to my car being missing.  It's not being stolen its just fucking off into the abyss and there's no garage near Taxi or Trash so I have to run or bike my happy ass over to the garage I last parked it which is across the map.

**Comment by Senlarus** [comment]
Wish granted :)
