### ISSUE TITLE
Two fishing concerns: Payment & Unrealistic bait issues.

### ISSUE THREAD

**Issue by iamrayuu** [New-Chance-RP/Feedback#319]
<h2>What bug have you found?</h2>

This is a bit of a recording of my experience, but as I mentioned in my post before this I made 3k one round and 3.1k another round. I had started a video shortly after starting my fishing run to measure time and have something to listen to. The video was about 45+ minutes but by about 36 minutes in I had already cashed out my first round and then finished up my second.

Each fish is worth 100, and I caught 61 with a glitch resulting in 6.1k in roughly 36 minutes. Plus its also worth noting that I intentionally would occasionally hit the wrong button or ignore the cue to reel in the fish, and I never lost any bait.

<h2>What do you expect should happen?</h2>

Payment or something should go way down. May it be docking the payment, taking longer to fish, or upping the payment for bait. Something's gotta give because 6.1k in 36 minutes is pretty insane compared to most other jobs. 

Plus, for the bait problem I believe any time you hit the wrong button or ignore the cue to the point you lose the fish, you should lose the bait too. Most of the time the fish will take the bait if you give them time to get loose. Plus it's good for punishing people who are trying to AFK fish and tab out constantly while fishing. 

<h2>Anything to support your bug report?</h2>

I was able to replicate losing the bait multiple times after realizing it was a thing. I don't have a clip unfortunately but it was definitely able to be repeated.

**Comment by SwizzyWT** [comment]
I haven’t had that glitch like you had but me personally I think payment is fine, I mean you have to think about it 30 fish is a lot. I believe anything under $100 per fish will turn people away as there won’t be really much money for the time spent.

**Comment by Senlarus** [comment]
Fishing isn't a career, it's a hobby. We may offer some better kind of fishing in the future that is worth more money. The price has been reduced.
