### ISSUE TITLE
Appearance change in character creation 

### ISSUE THREAD

**Issue by Geky000** [New-Chance-RP/Feedback#320]
<h2>When i was making my second character i tried to change my clothes after making my character and it switched to the default model.</h2> 

1.Make your character appearance
2. Change the clothes after the making the appearance
3. Appearance changes to the default character appearance

<h2>The character appearance should stay the same even when changing clothes</h2>

My character appearance changes back to the default one and doesn't  stay the same causing my log out every time i was

**Comment by Senlarus** [comment]
This has been corrected.
