### ISSUE TITLE
Getting into Stolen Cars

### ISSUE THREAD

**Issue by jkobro** [New-Chance-RP/Feedback#321]
<h2>What bug have you found?</h2>
The bug i have found today is Getting into a civilians car doesnt work even when i smash the window it just bugs and doesnt let me in the car and completely cancels the animation of getting inside.

<h2>What do you expect should happen?</h2>
I expect getting into the car and potentially hot wiring or finding the keys inside the car or it being aloud to drive it.    

<h2>Anything to support your bug report?</h2>
I dont have any proof very sorry.

**Comment by Birlzey** [comment]
There is a way, RP to find out ;)

**Comment by ixhal** [comment]
This is a issue with out current npc car locking script will look into a better way to handle this.

**Comment by Birlzey** [comment]
yep its just been happening to me as well

**Comment by ixhal** [comment]
Issue should now be fixed, please make a new post if you find any bugs with the new lock system I put in place thanks for the report! 👍
