### ISSUE TITLE
phrog's application

### ISSUE THREAD

**Issue by phrogzun** [New-Chance-RP/Feedback#322]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:

11000010513ce4c

**Do you have troubleshooting experience?** *(If yes please explain)* :

 Yes I do, mainly for small bugs that are causing issues, usually I can explain what is causing it and isn't. 

**How do you personally take screenshots?** : 

I use the printscreen option on windows or I would use snipping tool.

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : 

I would record/screenshot the problem and then report it on the github page, the information I would provide would be a clear video of the bug happening and the location of where it's happening and if possible what's causing it.

**Discord ID** *Please include numbers* :
zun#8559

**Comment by Senlarus** [comment]
Approved, check discord.
