### ISSUE TITLE
Yacht Heist issue

### ISSUE THREAD

**Issue by DropKickVibe** [New-Chance-RP/Feedback#323]
<h2>What bug have you found?</h2>

Couple small-ish issues. 1) NPC killed each other. 2) The money tables over spawn and sent me through the roof. Video below.

![image](https://user-images.githubusercontent.com/66173725/83442253-ca2c0980-a43f-11ea-9233-357a34b73635.png)
https://streamable.com/a44bb4

**Comment by ixhal** [comment]
Something weird happened here multiple npc spawned in the same place + 2 trollys, You and someone else probably pressed E at the same time in the starting cricle, Will stop this from happening thanks for the feedback 👍

**Comment by BillChirico** [comment]
Also, I think the NPCs should be aggressive meaning they should shoot at you before you shoot at them. Gives cops a little more time to act. Maybe some could spawn on other parts of the ship as well

**Comment by DropKickVibe** [comment]
@ixhal Yeah if I remember right. I was spamming E at the start to see if it broke it lol

**Comment by ixhal** [comment]
merging with #350 will be fixed together
