### ISSUE TITLE
[Tips's] closed alpha application 

### ISSUE THREAD

**Issue by harry223** [New-Chance-RP/Feedback#325]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:11000010c6d8e50

**Do you have troubleshooting experience?** *(If yes please explain)* : No

**How do you personally take screenshots?** : print screen and snipping tool

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : i would go to the GITHUB page and report the bug there in detail on how it happened and what problem it caused

**Discord ID** *Please include numbers* : Tips#3468

**Comment by Senlarus** [comment]
Approved, check discord.
