### ISSUE TITLE
George Keen - New Chance Application

### ISSUE THREAD

**Issue by GeorgeKeen** [New-Chance-RP/Feedback#326]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:
76561198338836311
110000116908757 (Hex)
Steam Name: GamDog

**Do you have troubleshooting experience?** *(If yes please explain)* :
No
**How do you personally take screenshots?** : 
By pressing on the Print Screen button on my keyboard
**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : 
I would go to /ooc and ask questions about how to fix, or go to the discord and ask there, providing information on what does or doesn't appear on my screen. Or I could go to GITHUB and ask questions there. Providing screenshots of the problem to show evidence of the problem/Bug.
**Discord ID** *Please include numbers* :
George_keen#5977

**Comment by Senlarus** [comment]
Approved, check discord.
