### ISSUE TITLE
LION application

### ISSUE THREAD

**Issue by GiVeDB** [New-Chance-RP/Feedback#328]
To retrieve your steam ID please do the following steps

Go to http://vacbanned.com/
Paste your steam profile link into search
Copy the Hex code on Steam3 ID (64bit)
Steam ID: 11000013680e1fb

Do you have troubleshooting experience? (If yes please explain) : no

How do you personally take screenshots? : windows + g for clips and important screenshots, shift + windows + s for small ones that i can quickly paste somewhere

If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide? : a clip of the issue + the f8 logs and put it as a bug report in feedback

Discord ID Please include numbers :
LION#6632

**Comment by Senlarus** [comment]
Approved, check discord.
