### ISSUE TITLE
Garbage Job 'Your Keys'

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#329]
<h2>What bug have you found?</h2>

Garbage is scuffed again where the red circles won't show up again but this time I decided to check my keys and I have 2 TRASH001 and TRASH006.  I can't tell if the 001's are from my main character but I would think after returning from a mission your garbage keys should be removed from your inventory.

<h2>What do you expect should happen?</h2>

Remove TRASH keys from inventory after returning from mission.

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/6095886/83472860-374a9980-a456-11ea-985b-8874372082fc.png)

**Comment by Senlarus** [comment]
![image](https://user-images.githubusercontent.com/1503963/83555260-0745d980-a4dc-11ea-981f-744449b82b06.png)

**Comment by Senlarus** [comment]
The above is after a few days of trashin

**Comment by ixhal** [comment]
Disabled keys from showing on the menu for now thanks for the feedback
