### ISSUE TITLE
ItzYaBoiMark

### ISSUE THREAD

**Issue by ItzYaBoiMark** [New-Chance-RP/Feedback#330]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:11000010afad1b6

**Do you have troubleshooting experience?** *(If yes please explain)* : Yes i run a non profit Role Play community 

**How do you personally take screenshots?** : Yes

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : I would try a restart on my game & if that didn't work i would explain everything i tried to make it easier to find the problem.

**Discord ID** *Please include numbers* : ItzYaBoiMark#4779

**Comment by DerkDuece** [comment]
Accepted welcome!!!

**Comment by Senlarus** [comment]
Approved, check discord.
