### ISSUE TITLE
Unable to see charges on MDT.

### ISSUE THREAD

**Issue by iamrayuu** [New-Chance-RP/Feedback#331]
<h2>What bug have you found?</h2>

I am specifically unable to see the charges on the MDT. I have tried to relog and left for a few hours and unfortunately still cant see the charges.

<h2>What do you expect should happen?</h2>

I should be able to see the charges.

<h2>Anything to support your bug report?</h2>

Has replicated twice and I had logged in and out and other things in order to see it. Still don't see the charges.
![image](https://user-images.githubusercontent.com/35026673/83479863-6fa2a580-a45f-11ea-8ebf-9b6b5cb0b51c.png)

**Comment by Senlarus** [comment]
Server needs a reboot

**Comment by Senlarus** [comment]
Try again

**Comment by Senlarus** [comment]
Fixed
