### ISSUE TITLE
Application

### ISSUE THREAD

**Issue by Rellzilla416** [New-Chance-RP/Feedback#332]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 11000013cbaeef1

**Do you have troubleshooting experience?** *(If yes please explain)* : No

**How do you personally take screenshots?** : GeForce Experience

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : Use GeForce Experience to record

**Discord ID** *Please include numbers* : Rell#5412

**Comment by bloombydee** [comment]
Congratulations, application accepted
