### ISSUE TITLE
Mass NPC/Vehicle's Spawning

### ISSUE THREAD

**Issue by Birlzey** [New-Chance-RP/Feedback#338]
<h2>What bug have you found?</h2>

Grove St area, NPC's and vehicles were spawning endlessly, also fell through the map.

<h2>What do you expect should happen?</h2>

Not spawn on top of each other endlessly, same with vehicles. Also not fall through map but no idea what is causing this.

<h2>Anything to support your bug report?</h2>

https://www.youtube.com/watch?v=hAkw5GEEle8&feature=youtu.be

**Comment by Senlarus** [comment]
This issue should have been fixed by our change to Onesync. Please report if it happens again.
