### ISSUE TITLE
Pistol Ammo Incompatibility

### ISSUE THREAD

**Issue by BillChirico** [New-Chance-RP/Feedback#339]
<h2>What bug have you found?</h2>

Trying to reload my Heavy Pistol with a Pistol Ammo Box, but it says it's incompatible.

<h2>What do you expect should happen?</h2>

Be able to reload my Heavy Pistol.

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/13951316/83583999-ded9d180-a513-11ea-979d-7e60bbfac3ed.png)

**Comment by ixhal** [comment]
Must have the pistol in your hand to reload.

**Comment by BillChirico** [comment]
> Must have the pistol in your hand to reload.

That would make sense haha
