### ISSUE TITLE
Twitter Profile Picture

### ISSUE THREAD

**Issue by Monster-Duck** [New-Chance-RP/Feedback#34]
<h2>Twitter Profile Pictures don't seem to work?</h2>

Create a profile picture of an image on the internet. Then whenever you tweet something the image will not appear.

<h2>My profile picture should appear upon tweeting.</h2>

I think you should be able to see the image selected in my settings, but look at the image below to see what it displays:

![image](https://user-images.githubusercontent.com/59716781/77251589-8c338d80-6c25-11ea-9dc0-5ec58a68110c.png)

**Comment by Senlarus** [comment]
This has been fixed with the new GCPhone! Go test it out :)
