### ISSUE TITLE
Speaking while processing. 

### ISSUE THREAD

**Issue by TheAmazingGryphon** [New-Chance-RP/Feedback#340]
<h2>What bug have you found?</h2>

I was processing cocaine in my Journey camper van and I attempted to communicate to another player. However, when I tried to do so I was unable to. 

<h2>What do you expect should happen?</h2>

I expected to communicate through voice chat.

<h2>Anything to support your bug report?</h2>

I am sorry, but at the time I wasn't recording.

**Comment by ixhal** [comment]
Just pushed a update to fix this, Will go live on the next server restart!
Thanks for the report
