### ISSUE TITLE
Store and Pharmacy Robbery

### ISSUE THREAD

**Issue by Monster-Duck** [New-Chance-RP/Feedback#341]
<h2>What bug have you found?</h2>

When robbing stores and pharmacies two players can rob either the convenience store clerk or lockpick the pharmacy safe at the same time. Also, when I robbed the pharmacy I got coca leaves and apparently that isn't supposed to happen? Maybe it was because I robbed it at same time as Scruxy?

<h2>What do you expect should happen?</h2>

Only one person should be able to rob a location at once. This could be easily abused to double the income of robberies and once we leave whitelist people will probably abuse it. Also unprocessed coca leaves shouldn't drop from a pharmacy safe, but some sort of processed drug should.

<h2>Anything to support your bug report?</h2>

I didn't bother recording it since any two people could recreate it and nothing too exciting happens on screen.

**Comment by BillChirico** [comment]
I see your point, but this could also make store robberies a duo activity, which is something to consider as well. Once police are setup I’m assuming they’ll be alerted of both of the robberies.

**Comment by bloombydee** [comment]
Coca leaves are intentional as they are a raw product in the manufacture of certain prescriptions, similar to how poppy can be used to make morphine or heroin

**Comment by ixhal** [comment]
Issues should now have been fixed thanks for the report 👍
