### ISSUE TITLE
my application (xppie)

### ISSUE THREAD

**Issue by Bamboozld** [New-Chance-RP/Feedback#342]
would like to join, heard great things about the server already and have been roleplaying for a while myself. here is my steam hex id:

- steam hex code: 110000104bb3169
------------------------------------------------------------------------------------------------------------

Steam ID: https://steamcommunity.com/id/xppie/

Do you have troubleshooting experience?  (yeah, I have been playing games for a long time )

How do you personally take screenshots?:  steam

If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?: 

I would report that the marker does nothing and show any side effects that are shown with the bug.

Discord: Playz#6454

**Comment by bloombydee** [comment]
Congratulations, application accepted
