### ISSUE TITLE
Certain Robbery Issue

### ISSUE THREAD

**Issue by Birlzey** [New-Chance-RP/Feedback#343]
<h2>What bug have you found?</h2>

Two people can crack the safe (drug store) at the same time and also get individual loot, by synchronizing opening the safe door and then pressing E to grab loot.

<h2>What do you expect should happen?</h2>

Only one person can crack the safe, not able to interact with it while someone is using it.

<h2>Anything to support your bug report?</h2>

Na

**Comment by Monster-Duck** [comment]
Copy of 341.

**Comment by ixhal** [comment]
#341
