### ISSUE TITLE
Pat's Closed Alpha Application

### ISSUE THREAD

**Issue by thaprofess025** [New-Chance-RP/Feedback#345]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 1100001149c475c 

**Do you have troubleshooting experience?** *(If yes please explain)* : yes, I work as an IT professional in my real job and handle trouble shooting and ticket creation on the regular

**How do you personally take screenshots?** : The hot key for print screen and Windows + Shift + 6

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : I would post a 30 second clip of what I was doing prior to getting my car out of the garage. I would include a screenshot of the map as well as a timestamp to show the problem in full. I would provide all of this to medal.tv.

**Discord ID** *Please include numbers* : ThaProfessa025#4096

**Comment by bloombydee** [comment]
Congratulations, application accepted
