### ISSUE TITLE
Entering Instance

### ISSUE THREAD

**Issue by Birlzey** [New-Chance-RP/Feedback#346]
<h2>What bug have you found?</h2>

You can enter the wash while sat inside your vehicle if you pull up next to the door and press E and it teleports you inside.

<h2>What do you expect should happen?</h2>

Not be able to just teleport inside, you should have to exit the vehicle then press E to enter.

<h2>Anything to support your bug report?</h2>

Just pull up next to the prompt and press E.

**Comment by Senlarus** [comment]
Does it take your car inside with you? lol

**Comment by Birlzey** [comment]
No not the vehicle.

**Comment by ixhal** [comment]
Pushed a update to fix this will go live on next server restart, Thanks for the report!
