### ISSUE TITLE
Garbage Job Can't Clock-in.

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#347]
<h2>What bug have you found?</h2>

The new area for Garbage has the yellow circle but when you walk up to the circle there's no prompt to clock-in/out.

<h2>What do you expect should happen?</h2>

To be able to clock-in to Garbage.

<h2>Anything to support your bug report?</h2>

Doug Dimmadome wants to clean up the city and can't. 
![image](https://user-images.githubusercontent.com/6095886/83696071-7e0cd080-a5c9-11ea-9d82-34bbae45397e.png)

**Comment by Scarfninja** [comment]
I found where the clock-in is....
![image](https://user-images.githubusercontent.com/6095886/83696170-c1ffd580-a5c9-11ea-9c10-ef0429c74359.png)

**Comment by Scarfninja** [comment]
Adding onto Garbage Job, the yellow circle at {x = -34.56, y = -97.32, z = 57.04} is floating. 
![image](https://user-images.githubusercontent.com/6095886/83696704-1fe0ed00-a5cb-11ea-98f6-77512ce9efc6.png)

**Comment by Scarfninja** [comment]
Another Floater, someone's not eating their recommended dietary needs. {x = -8.28, y = -1569.88, z = 28.96}

![image](https://user-images.githubusercontent.com/6095886/83696919-a7c6f700-a5cb-11ea-86ff-a2a9f2af9654.png)

**Comment by Senlarus** [comment]
Thanks for putting these all in one report. I'll get 'em fixed up.

**Comment by Senlarus** [comment]
Fixed the clockin

**Comment by Senlarus** [comment]
Not fixing the floating locations because I want to change them. If you want to help get me locations contact me.
