### ISSUE TITLE
Can't see biffa Logistics after clocked on as Taxi 

### ISSUE THREAD

**Issue by yungfelixgg** [New-Chance-RP/Feedback#348]
<h2>What bug have you found?</h2>

After clocked on as a taxi driver I couldn't see Biffa Logistics anymore on the map. I don't know if this bug has been reported by someone already but here it is.

<h2>What do you expect should happen?</h2>

If the devs could look into this and try to fix it then it will not mislead new players in the future.

<h2>Anything to support your bug report?</h2>

After relogging Biffa Logistics appeared again on the map.

**Comment by Senlarus** [comment]
Fixed
