### ISSUE TITLE
Closed Alpha App

### ISSUE THREAD

**Issue by NiftyLad** [New-Chance-RP/Feedback#349]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:110000134816b05

**Do you have troubleshooting experience?** *(If yes please explain)* :Yes, I am a technician IRL and I have also helped in making servers before.

**How do you personally take screenshots?** : Steam F12

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : I would make a feedback on the discord and provide video evidence as well as the F8 console open.

**Discord ID** *Please include numbers* :Nifty Lad#9936

**Comment by Senlarus** [comment]
We are in open access now, come join in!
