### ISSUE TITLE
Boat Robbery 

### ISSUE THREAD

**Issue by Birlzey** [New-Chance-RP/Feedback#350]
<h2>What bug have you found?</h2>

Able to recieve x2 loot from the drilling part of the robbery. To reproduce this follow these steps:

Have at least two people. Open the vault door, One person starts drilling first then stops before finishing and collects the cash of the table. The second person waits for them to collect the cash then starts and completes the drilling. Once the drilling is complete both people will recieve the loot.

<h2>What do you expect should happen?</h2>

Only one person should recieve the loot, whoever drilled it open.

<h2>Anything to support your bug report?</h2>

I have a long video, will screen share if needed, thanks.

**Comment by BillChirico** [comment]
I tested this yesterday as well and it wouldn’t let me drill after the first person did. Then the first person to start the drill couldn’t finish it either. Not sure if it’s intermittent or not.

**Comment by Birlzey** [comment]
It duped for us yesterday right ?

**Comment by BillChirico** [comment]
> It duped for us yesterday right ?

Yeah it did, I tried it with Nick again later and it didn’t work. Well have to test it again and see the variable which causes it.

**Comment by Birlzey** [comment]
Yeah very strange I forgot to report it so did it now but yeah needs more looking into

**Comment by ixhal** [comment]
Will be working on this soon so will need help testing thanks for the feedback

**Comment by BillChirico** [comment]
Heist ideas: 

- NPCs on aggressive
- Spawn more NPCs around the boat once you start cracking the vault

**Comment by ixhal** [comment]
Going to revamp this tomorrow should be more fun todo as a group :)

**Comment by ixhal** [comment]
System has changed, thanks for the feedback people 👍
