### ISSUE TITLE
Ozzy Application

### ISSUE THREAD

**Issue by FroggyOzzy** [New-Chance-RP/Feedback#351]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:110000112e002c9

**Do you have troubleshooting experience?** *(If yes please explain)* : No

**How do you personally take screenshots?** : F3 record and screen shot from Rockstar editor

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : I will screenshot and send it to the mod and explain the bug. 

**Discord ID** *Please include numbers* : FroggyOzzy#6284

**Comment by bloombydee** [comment]
Congratulations, application accepted
