### ISSUE TITLE
Fell Through the Earth in Casino

### ISSUE THREAD

**Issue by LonelyOven** [New-Chance-RP/Feedback#352]
What bug have you found? I fell through the earth in the casino.
I sat in the chair at the poker tables 
My mate was somehow able to sit in the same seat and then after roughly 15 seconds I fell through the earth and died.
This may be something to do with the ragdoll button and the table interaction button I feel because my mate was using the ragdoll button to fall around a lot.

What do you expect should happen? Two people shouldnt be able to get into the same seat and you shouldnt be able to use ragdoll key in casino

Anything to support your bug report? I have screenshot of me dead on the floor as i fell through the earth I can provide it if it needs to verified further

**Comment by ixhal** [comment]
I can't seem to get it to do this again, The only thing I would advise is don't try and sit on the same chair at the same time, Let me know if you can do this again and how thanks for the report!
