### ISSUE TITLE
Closed alpha application for Zonta

### ISSUE THREAD

**Issue by chromewick** [New-Chance-RP/Feedback#353]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into the search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 11000010a02a38e

**Do you have troubleshooting experience?** *(If yes please explain)* : sort of? like when something is wrong with my game or PC. ill spend some time looking up how to fix it myself. I seem to somehow find bugs in a game by chance. I'll always report it to the devs because it may become a problem later down the line. Even if the bug/ glitch benefits me. ill stop and report. I like being helpful. like I don't have experience per see. but maybe I can help in some way.

**How do you personally take screenshots?** : 
with light shot
**If you were trying to get your car out of a garage when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : I would take a small clip or screenshot it. I would ask if anyone else is having this issue. I would relog. then if that didn't work I would try validating my files. if nothing makes it work, then I would report. sometimes just a relog will help. I would put the pic or vid or explain what happened and what it's not doing/doing. I would let them know all the things I did before I went to report it. if I've had any success in getting it to work. I would let others know this is how I got it to work. a sort of temporary fix. its always nice to be able to do something, while the issue is being worked on. 

**Discord ID** *Please include numbers* : Kintsukuroi Vector (zonta)#7951

**Comment by bloombydee** [comment]
Congratulations, application accepted
