### ISSUE TITLE
 Application

### ISSUE THREAD

**Issue by Dev-MRob** [New-Chance-RP/Feedback#354]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 110000101e1ba4c

**Do you have troubleshooting experience?** *(If yes please explain)* : Software Dev IRL

**How do you personally take screenshots?** : Medal.tv

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : 
-What I was wearing, what ping i had, what items i had on me and or equipped. 

**Discord ID** *Please include numbers* : M-Rob#5031

**Comment by bloombydee** [comment]
Congratulations, application accepted
