### ISSUE TITLE
Can escape cop car while cuffed.

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#355]
<h2>What bug have you found?</h2>

We still have access to our emote menu while handcuffed as well as the police cars glovebox.  When we use an emote in the cop car we can then exit the vehicle though we're still handcuffed.

<h2>What do you expect should happen?</h2>

Handcuffed individuals should not be able to access any menus until the cuffs are removed/fall off.

<h2>Anything to support your bug report?</h2>

3 officers watched me escape the police car and I can even drive the car while handcuffed.

**Comment by ixhal** [comment]
Should now be fixed thanks for the feedback!
