### ISSUE TITLE
Journey van trapped my friend 

### ISSUE THREAD

**Issue by TheAmazingGryphon** [New-Chance-RP/Feedback#356]
<h2>What bug have you found?</h2>

When my friend was producing meth in the Journey camper van I entered the van and started driving away with him in the back as a goof. I believe doing this trapped my friend in the back of the camper van. He was unable to pull up his menu and was unable to escape resulting in him having to pull up task manager. Once he was gone I was unable to process my meth, as it said that the back was occupied. If anyone encounters this problem, just put the vehicle in the garage and it should fix itself.

<h2>What do you expect should happen?</h2>

I expected for my friend to be able to exit the van and be able to process in the van once he disconnected. 

<h2>Anything to support your bug report?</h2>

Unfortunately, no.

**Comment by BillChirico** [comment]
I have experienced the same thing. It seems that if anyone does anything with the Journey while you’re cooking it’ll break and lock you in.

**Comment by TheAmazingGryphon** [comment]
> I have experienced the same thing. It seems that if anyone does anything with the Journey while you’re cooking it’ll break and lock you in.

Yeah, man. I figured that other people encountered the same issue. Would be nice to see it fixed, but I won't deny my friends confused screaming did crack me up... A LOT.

**Comment by ixhal** [comment]
Its because in order for the decorator to set you need to have control of the vehicle, before we moved to one sync this was working fine I believe, I'll have to look into other options for this! Thanks for the feedback

**Comment by ixhal** [comment]
Should now be fixed thanks for the feedback if there is anymore issues please post them! 👍
