### ISSUE TITLE
Stuck in Location

### ISSUE THREAD

**Issue by SwizzyWT** [New-Chance-RP/Feedback#357]
What bug have you found?
-When entering a certain location I was able to enter fine but when leaving it says you cant enter while in a vehicle 

 - Describe in good detail what bug you have found as well as list the steps to reproduce if known*
- Enter building do what you are there to do and then when leave message pops up thinking you a still in vehicle 

What do you expect should happen?
- It has worked fine every other time so just to exit building 

 - What do you think should happen, what is the intended outcome that you are currently not getting?*

-Be able to exit

 - Have you got any evidence to help prove the bug, a video or picture etc?*
-Pic is attached.

https://gyazo.com/d4248dbc9149b11fd83cc00f10060cb8

**Comment by ixhal** [comment]
Should now be fixed thanks for the feedback!
