### ISSUE TITLE
Closed Alpha Application

### ISSUE THREAD

**Issue by Jacob12348771** [New-Chance-RP/Feedback#358]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 1100001129760d8

**Do you have troubleshooting experience?** *(If yes please explain)* : Unfortunately not but I'm eager to help a new server get on it's feet and after playing the open stress test, I really enjoyed the mechanics of this server and have even helped TheAmazingGryphon find issues regarding the meth cooking system, which I helped him report, giving details and accounts.

**How do you personally take screenshots?** : To take screenshots I use the steam overlay.

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : Firstly I would give a detailed account of what I done to lead to the bug occurring. Also I would explain what the bug actually was, along with the location and name of the specified garage. Moreover; I would try to recreate the steps that led up to the bug occurring to see if it was a reoccurring issue. I would then include this information in my detailed report. In this scenario I would start by explaining how I walked up to the marker and no details appeared. Then I would try a few more times to see if the bug was still occurring. Therefore in my report I could specify the severity of this bug on my end, explaining if it was a one off, or a repeated concurrent event. A clip of the bug occurring would also be included in my detailed report by using Medal.tv.

**Discord ID** *Please include numbers* : Jacob12348771#5549

**Comment by bloombydee** [comment]
Congratulations, application accepted
