### ISSUE TITLE
Closed alpha application (Melon)

### ISSUE THREAD

**Issue by OhMelancholy** [New-Chance-RP/Feedback#359]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 1100001126de8bf (Hex)

**Do you have troubleshooting experience?** *(If yes please explain)* : I co-owned a minecraft  server once and helped fix things does that count? XD

**How do you personally take screenshots?** : I use gyazo screen shot and gif capture

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : I would first check to see if its a me issue and relog and see if someone has already reported the bug if not I'd make a report saying something like "when going to the garage I couldnt take out my car seems to be a bug" and post it on discord 

**Discord ID** *Please include numbers* : Melon #3171

**Comment by bloombydee** [comment]
Congratulations, application accepted
