### ISSUE TITLE
parksaken 

### ISSUE THREAD

**Issue by parksy88** [New-Chance-RP/Feedback#360]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

110000115fe716d 

no

print screen button

Id try relog and if not leave a comment in the discord 

parks#5262

**Comment by bloombydee** [comment]
Congratulations, application accepted
