### ISSUE TITLE
Male character turned into a woman.

### ISSUE THREAD

**Issue by TheAmazingGryphon** [New-Chance-RP/Feedback#361]
<h2>What bug have you found?</h2>

I have found a glitch that has turned my male character into a female. This glitch occurred when I loaded into the server and had found that my legs, hands, hat, hair, chest and feet were missing. The only thing I had on was a red jacket and glasses. I then went to the clothes shop and started trying to fix my character. I started adding pants and shoes to my character but could not see his face so I got another 100 from the bank and started to customise my character again. For some reason hair and hat options were not appearing, then out of nowhere my view zooms out and is over head (like when you load into the city). I decided to re-log to discover my character had transitioned into a woman. If possible I would appreciate it if I got the chance to change my characters appearance somehow.   

<h2>What do you expect should happen?</h2>

I expected to load into the server and have my legs, hands, hat, hair, chest and feet. I also expected for hair and hat options to appear for me when customising my character. I expected not to be zoomed out looking down at the city from the sky. I expected when I re-logged that my character not be turned into a woman (no hate for women but I rather not be one). Thank you, for reading!

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/62949722/83979927-be41bb00-a909-11ea-87fc-bfc458db0e67.png)

**Comment by Senlarus** [comment]
Currently working on adding a new skin system. Watch the alpha channel in discord for info once it’s complete. Until then, enjoy the heels!
