### ISSUE TITLE
Clothing Store

### ISSUE THREAD

**Issue by OfficialMasuUK** [New-Chance-RP/Feedback#362]
<h2>What bug have you found?</h2>

> Gender may be messed up in database

> Barber shop can change facial features and parents

<h2>What do you expect should happen?</h2>

<h2>Anything to support your bug report?</h2>

(More of a note to remind Senlar <3)

**Comment by Senlarus** [comment]
Try now

**Comment by Birlzey** [comment]
I'v just flown in to this..
![image](https://user-images.githubusercontent.com/64453673/84091086-64192680-a9eb-11ea-93f8-0511724bdf48.png)

**Comment by Senlarus** [comment]
Fixed... lol lookin good @Birlzey
