### ISSUE TITLE
Job Uniforms Broken

### ISSUE THREAD

**Issue by OfficialMasuUK** [New-Chance-RP/Feedback#363]
<h2>What bug have you found?</h2>

Police Clothing (Civilian clothes, orange vest, bulletproof vest and uniform all not working)
Police having to be in uniform to use the armoury.

<h2>What do you expect should happen?</h2>

Uniforms to work (Understood that things are to come <3)
To be able to use the armoury regardless of clothing.

<h2>Anything to support your bug report?</h2>

**Comment by Senlarus** [comment]
Fixed armory, working on uniforms.

**Comment by Senlarus** [comment]
I think I fickxed it1!1! Tell me if I'm right!

**Comment by Senlarus** [comment]
Fixed
