### ISSUE TITLE
Closed alpha application 

### ISSUE THREAD

**Issue by ZeroJester** [New-Chance-RP/Feedback#364]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 11000011386fbfd 

**Do you have troubleshooting experience?** *(If yes please explain)* : I do not but after playing the public stress test i am really enjoying how the server is going and would love to help in its development.

**How do you personally take screenshots?** :  Steam overlay.

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : I would take a clip of the issue taking place and send it to the admis via the designated discord channel, i would also try to relog initially to determine whether it was a repeating issue.
  
**Discord ID** *Please include numbers* : Bryce#7942

**Comment by bloombydee** [comment]
Congratulations, application accepted
