### ISSUE TITLE
New Clothing & Item issue

### ISSUE THREAD

**Issue by Birlzey** [New-Chance-RP/Feedback#365]
<h2>What bug have you found?</h2>

All items except water vanished from inventory. Which I now have 5/3 of.

<h2>What do you expect should happen?</h2>

I was testing out the new clothing system and barber shop when I noticed all my inventory had gone.. I was just changing clothes and going to barber shop, also relogged once inbetween.

<h2>Anything to support your bug report?</h2>

Not really but when I opened the console I was getting a script:raid_clothes error 1885233650 378

**Comment by Senlarus** [comment]
Fixed
