### ISSUE TITLE
Trapped in vault

### ISSUE THREAD

**Issue by Birlzey** [New-Chance-RP/Feedback#366]
<h2>What bug have you found?</h2>

Was able to walk into the vault (yacht) before I had the code and was unable to leave the vault.

<h2>What do you expect should happen?</h2>

Unable to enter the vault without code. (not be trapped inside also)

<h2>Anything to support your bug report?</h2>

Had to be tp'd out

**Comment by ixhal** [comment]
Can't seem to recreate let me know if you can do it again thanks for the report 👍
