### ISSUE TITLE
Proccessing Drugs

### ISSUE THREAD

**Issue by BIRLZ95** [New-Chance-RP/Feedback#367]
<h2>Feature you are requesting.</h2>

Processing of high end drugs e.g cocaine, requires a player owned warehouse or some kind of a special property to process but before you can process it you would also have to buy all the neccessery equipment required e.g. heavy duty press, heavy duty scales, chemicals etc, Then place them inside your property. Once that is complete you can beguin processing and distribute the product the other players via rp.

I know the devs are amazing at making things interactive in this city so I'm sure you would add plenty more to this idea if you havn't already thought of it.

<h2>What are the benefits to your feature?</h2>

Adds more to the system, just a suggestion I thought was cool.
+ involves player properties more and the ability to decorate your property.
+ big investment, need a lot of money or friends haha

<h2>Anything to support your feature request?</h2>

N/A

**Comment by DerkDuece** [comment]
We love this idea and it is most likely months out. It has been talked about among the team.

**Comment by Senlarus** [comment]
It's something that will be considered in future development.
