### ISSUE TITLE
Chop Shop/Stolen Vehicle Sell

### ISSUE THREAD

**Issue by BIRLZ95** [New-Chance-RP/Feedback#368]
<h2>Feature you are requesting.</h2>

A Chop Shop were you would go, interact with a NPC and would send you a picture w/name of a vehicle he wants for his business, you would go find steal and return it to the Chop Shop for a cash reward (dirty money).

<h2>What are the benefits to your feature?</h2>

+ more to do!
+ incorporates the phones (which are great)

<h2>Anything to support your feature request?</h2>

N/A

**Comment by bloombydee** [comment]
Already got a script for this, just waiting for mechanics update after alpha launch 😉

**Comment by Senlarus** [comment]
This is on the roadmap and is in the works. Watch the updates channel in discord!
