### ISSUE TITLE
New clothing system issue

### ISSUE THREAD

**Issue by Birlzey** [New-Chance-RP/Feedback#369]
<h2>What bug have you found?</h2>

Clothing menu disappears and freezes you, unable to do anything or re-enter clothing menu only option is to F8 quit.

I was just flicking through the neck accessorys using the arrow keys and the menu just disappeared, its done it twice now for me.

<h2>What do you expect should happen?</h2>

Menu not randomly close and freeze you. Not sure whats causing this.

<h2>Anything to support your bug report?</h2>

Just a screenshot of the console at the time of it happening not sure if this helps.
![image](https://user-images.githubusercontent.com/64453673/84046046-7e2e1700-a9a1-11ea-864b-31c1c170f0cf.png)

**Comment by Senlarus** [comment]
Yup, it's because I"m activly working on the script and restarting it to push updates and test. Everytime I do this, it closes out the menu for anyone who's in it and if yuo hadn't finished it locks you into the mouse control.
