### ISSUE TITLE
[BUG] - Jail death Timer

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Feedback#37]
<h2>What bug have you found?</h2>
If you die in jail, you get the 2 minute timer. Once the 2 mintue timer ends you then move into the 10 minute timer with a $5'000 earlier respawn penalty.

<h2>What do you expect should happen?</h2>

After the 2 minutes is up you respawn no charge just back in the main jail area.

<h2>Anything to support your bug report?</h2>

Image - https://gyazo.com/27191be8b672669354ee7a72bcee685b

**Comment by ixhal** [comment]
Has been fixed let me know if anything else happens! Cheers
