### ISSUE TITLE
Weapons Removed when Clocking on/off EMS.

### ISSUE THREAD

**Issue by lAmantel** [New-Chance-RP/Feedback#370]
<h2>What bug have you found?</h2>

I previously had a tazer, and until moments ago I realized it was gone. The last thing I remembered doing was clocking into EMS during the stress test. I didn't think anything of it. So I went out bought a pistol and I decided to clock on EMS. After clocking off I realized I again didn't have my pistol anymore, but I didn't have an proof. So I went and bought a Bat.(I unfortunately didn't have anymore money to buy a gun). Before clocking onto EMS I checked to see if i still had my bat. I then Clocked onto EMS, checked to see if i still had my bat(i did) and then when I clocked off I checked the same thing( no longer had a bat)

<h2>What do you expect should happen?</h2>

I really do not think that clocking into my job should remove any of my weapons from my inventory, It really shouldn't effect my inventory at all in my honest opinion. So I think we should maybe stop it from removing stuff from our inventories specifically weapons at this time.

<h2>Anything to support your bug report?</h2>

Excuse the lag of this video, but through the unbearable lag, you can still see the problem

https://streamable.com/0mthwg

**Comment by Scarfninja** [comment]
I'd like to add on to this that I just lost all of my weapons/ammo after buying new clothes.  So there is something wrong with the clothing script.

**Comment by Senlarus** [comment]
No doubt

**Comment by Senlarus** [comment]
I have fixed the services losing weapons... not sure what abuot the clothing script is doing it since it doesn't touch the loadout data. I'll look into it

**Comment by Senlarus** [comment]
This is fully fixed now.
