### ISSUE TITLE
Losing weapons when changing uniforms

### ISSUE THREAD

**Issue by DerkDuece** [New-Chance-RP/Feedback#371]
<h2>What bug have you found?</h2>

When you chance uniforms for PD you lose all the weapons in your inventory.

<h2>What do you expect should happen?</h2>

Not lose my weapons.

<h2>Anything to support your bug report?</h2>

https://clips.twitch.tv/RelievedBombasticSashimiNotLikeThis

**Comment by Senlarus** [comment]
Fixed
