### ISSUE TITLE
Processing into Meth doesn't use bags.

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#372]
<h2>What bug have you found?</h2>

Not sure if this is intentional or not, but when making meth, you end up with bags of meth, but don't use any materials when carrying bags.  Only when processing further down.

<h2>What do you expect should happen?</h2>

Not sure if its intentional to not need bags for the first phase of meth cooking.

<h2>Anything to support your bug report?</h2>

**Comment by ixhal** [comment]
Was not intentional thanks for the report! 👍 issue has been fixed
