### ISSUE TITLE
VisionzAx Closed Alpha Application

### ISSUE THREAD

**Issue by VisionzAx** [New-Chance-RP/Feedback#374]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**:
110000136d79dfe
**Do you have troubleshooting experience?** *(If yes please explain)* :
No
**How do you personally take screenshots?** : 
I would normally have my screen capture software on so that i could watch back and screenshot what is needed. if i do not have my software open i would print screen and save the photo.
**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** : The thing i would provide are the garage i am at, if i am on duty or off duty as a job in case that effected it. I would most likely write something along the lines of I tried to get my car out of legion garage earlier while i was clocked on as "g6" when i went to press e to enter the garage and pull my car out. it did not work. in the bottom left of my screen it did not say anything about not having a car or anything of that sort. 

**Discord ID** *Please include numbers* :
VisionzAx#7954

**Comment by bloombydee** [comment]
Congratulations, application accepted
