### ISSUE TITLE
Rogers Recycling - Job Outfit not working

### ISSUE THREAD

**Issue by VisionzAx** [New-Chance-RP/Feedback#375]
<h2>What bug have you found?</h2>
When i went to clock on as rogers recycling my character's torso and legs both disappeared and i got a new face with different hair and colour and also new shoes. i then clocked of to see if i would get my old stuff back and i only got my face back the torso and legs stayed disappeared and the shoes stayed changed.

<h2>What do you expect should happen?</h2>

<h2>Anything to support your bug report?</h2>
https://streamable.com/tzupik

**Comment by Senlarus** [comment]
Thanks, I haven’t updated this job outfit to match the new skin system yet. I’ll do it today.

**Comment by VisionzAx** [comment]
Perfect, sounds good

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Senlarus** [comment]
![image](https://user-images.githubusercontent.com/1503963/84438316-57234f80-ac04-11ea-9297-ea381d8d76ef.png)
Fixed

**Comment by VisionzAx** [comment]
Thank you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
