### ISSUE TITLE
character customization fails to work 

### ISSUE THREAD

**Issue by chromewick** [New-Chance-RP/Feedback#376]
<h2>What bug have you found?</h2> character customization fails to work after some time in the menu. 

- Describe in good detail what bug you have found as well as list the steps to reproduce if known*
ok, so I don't know if anyone else is having this issue. but with the character customization. it gets to a point that nothing works. an example is ill start playing around with the faces. then ill go do the hair and makeup. then let say I don't like the face when I go back to change anything while still in the menu of making your character for the first time. nothing happens. no changes. the hair will change but nothing else. you cant put freckles on or anything.  even if you go to the hair salon. at some point, it just stops working. I don't know what's causing it.

<h2>What do you expect should happen?</h2>
to be able to make my character while still in the creation menu. 

 - What do you think should happen, what is the intended outcome that you are currently not getting?*you should be able to take as much time as you want to making your character. sometime midway through you change your mind on want you want. 

<h2>Anything to support your bug report?</h2> no

Have you got any evidence to help prove the bug, a video or picture etc?* no

**Comment by Senlarus** [comment]
Could you send me your cfx log?
In the FiveM directory there’s a logs folder and they’re dated. I’d need the log for the time when this issue occurred. Or if you’re still doing this you can take a screenshot of your F8 console.

**Comment by chromewick** [comment]
i think this is the one. theres only like 10 in there. 
[CitizenFX_log_2020-06-11T115931.log](https://github.com/New-Chance-RP/Feedback/files/4764966/CitizenFX_log_2020-06-11T115931.log)

**Comment by Senlarus** [comment]
I don't see anything in that log after you exited the loading screen. Try another? You can just zip them and upload all. I'll find the right one if you want.

**Comment by chromewick** [comment]
[CitizenFX_log_2020-06-10T095409.log](https://github.com/New-Chance-RP/Feedback/files/4765023/CitizenFX_log_2020-06-10T095409.log)
[CitizenFX_log_2020-06-10T153031.log](https://github.com/New-Chance-RP/Feedback/files/4765024/CitizenFX_log_2020-06-10T153031.log)
[CitizenFX_log_2020-06-10T154257.log](https://github.com/New-Chance-RP/Feedback/files/4765025/CitizenFX_log_2020-06-10T154257.log)
[CitizenFX_log_2020-06-10T160430.log](https://github.com/New-Chance-RP/Feedback/files/4765026/CitizenFX_log_2020-06-10T160430.log)
[CitizenFX_log_2020-06-11T104949.log](https://github.com/New-Chance-RP/Feedback/files/4765027/CitizenFX_log_2020-06-11T104949.log)
[CitizenFX_log_2020-06-11T105648.log](https://github.com/New-Chance-RP/Feedback/files/4765028/CitizenFX_log_2020-06-11T105648.log)
[CitizenFX_log_2020-06-11T115931.log](https://github.com/New-Chance-RP/Feedback/files/4765029/CitizenFX_log_2020-06-11T115931.log)
[CitizenFX_log_2020-06-11T120540.log](https://github.com/New-Chance-RP/Feedback/files/4765030/CitizenFX_log_2020-06-11T120540.log)
[CitizenFX_log_2020-06-11T132040.log](https://github.com/New-Chance-RP/Feedback/files/4765031/CitizenFX_log_2020-06-11T132040.log)
[CitizenFX_log_2020-06-11T132249.log](https://github.com/New-Chance-RP/Feedback/files/4765032/CitizenFX_log_2020-06-11T132249.log)
[CitizenFX_log_2020-06-08T165610.log](https://github.com/New-Chance-RP/Feedback/files/4765033/CitizenFX_log_2020-06-08T165610.log)
[CitizenFX_log_2020-06-08T193728.log](https://github.com/New-Chance-RP/Feedback/files/4765034/CitizenFX_log_2020-06-08T193728.log)
[CitizenFX_log_2020-06-09T105529.log](https://github.com/New-Chance-RP/Feedback/files/4765035/CitizenFX_log_2020-06-09T105529.log)
[CitizenFX_log_2020-06-09T120925.log](https://github.com/New-Chance-RP/Feedback/files/4765036/CitizenFX_log_2020-06-09T120925.log)
[CitizenFX_log_2020-06-09T134021.log](https://github.com/New-Chance-RP/Feedback/files/4765037/CitizenFX_log_2020-06-09T134021.log)

**Comment by Senlarus** [comment]
Ok found out that this happens when you leave a "face" setting on 255. If you change all of the faces away from 255 it will work. For now do that and I'll find a fix for this.

**Comment by Senlarus** [comment]
New skin system added.
