### ISSUE TITLE
Closed alpha application

### ISSUE THREAD

**Issue by adsam56** [New-Chance-RP/Feedback#377]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**1100001176c37f6**:

**Do you have troubleshooting experience?** *Yes, I used to be a developer on New Chance and I want to come pack for better RP, im yoyotrikzx1* :

**How do you personally take screenshots?*I either edit a screen clipping off of a vid, use steams F12 or use snipping tool* : 

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?*i would give in detail what I did leading up to it then I would say exactly where and when it happed and like what garage, then I would say what car it was , if it had happened before and if it happened to anyone else * : 

**yoyotrikzx1 #0834** *Please include numbers* :

**Comment by Senlarus** [comment]
We are in open access now, come join in!
