### ISSUE TITLE
Pink Cage Motel Bug.

### ISSUE THREAD

**Issue by Jacob12348771** [New-Chance-RP/Feedback#378]
<h2>What bug have you found?</h2>

At the pink cage motel, options appear to buy clothes and go to the barbers in the middle of the yard, which I presume aren't meant to be there. Moreover; the room I purchased nearest the swimming pool has a strange underwater filter on the screen when I enter. I'm guessing the interior is putting me where the pool is to my side.

<h2>What do you expect should happen?</h2>

The clothes and hair options not to be available in the yard and the interior to be normal.

<h2>Anything to support your bug report?</h2>

https://medal.tv/clips/26239270/d1337HrL9iJV

Sorry about strange clip view.

**Comment by Senlarus** [comment]
Will be gone in next reboot, thanks!
