### ISSUE TITLE
Loading in with a Default Danny Face/ Random Hair Colour

### ISSUE THREAD

**Issue by lAmantel** [New-Chance-RP/Feedback#379]
<h2>What bug have you found?</h2>

So I'm not exactly sure what's going on, but when It's happened to me about 4 times now, When I log out of the city and come back in, Sometimes I return into the city with a male default danny face, with a randomly generated colour hair, (of the hair i originally selected as you will see in the screen shot below) and a different shirt that I never selected.

<h2>What do you expect should happen?</h2>

What I would expect should happen, is when I load into the city, I be the same person I logged out of the city as, GRANTED, Re-logging like 4-5 times fixes it, but that is NOT a Fix at all. More of an inconvenience.

<h2>Anything to support your bug report?</h2>

[Image](https://imgur.com/9nSaKWX)
[FiveM Log File](https://www.dropbox.com/s/fu6gca06jh66rw8/CitizenFX_log_2020-06-12T123001.log?dl=0)

**Comment by lAmantel** [comment]
Update: My character is now  always loading in like this | In the mean time I will go to the Barber/Clothing Store and try to recreate my face and outfit again.......

**Comment by Senlarus** [comment]
Yeah it’s the old skin system fighting the new one. I’ll go in and find that bugger...

**Comment by Senlarus** [comment]
To fix it right now you can use the EMS closckroom to change into civilian clothes again and it will restore your character

**Comment by lAmantel** [comment]
I'm not whitelisted as EMS anymore since I remade Lena,

**Comment by Senlarus** [comment]
Try now plz

**Comment by lAmantel** [comment]
Bit late, I fell asleep, but so far I loaded in with my normal face.  I'll log off and on throughout the day. To see if it maintains.

**Comment by Senlarus** [comment]
I found another problem that could have been causing this and also fixed that. Looking forward to hearing back from you. When you're testing this if you could try to "push" your computer a bit to make it a bit slower that would help get a good test.

**Comment by Senlarus** [comment]
Has this happened to you since the stress test?(Minus when the server was under severe strain from the 25 players before we upgraded it)?
