### ISSUE TITLE
Von Crastenburg Cash Only

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#380]
<h2>What bug have you found?</h2>

Went to buy a room at Von Crastenburg and it said I didn't have enough money because I wasn't carrying cash on me.

<h2>What do you expect should happen?</h2>

Is this intentionally cash only or can we use our bank account?

<h2>Anything to support your bug report?</h2>

**Comment by Senlarus** [comment]
All motels accept bank cards during purchase now.
