### ISSUE TITLE
Gas meter for car and Fuel station not working correctly

### ISSUE THREAD

**Issue by SwizzyWT** [New-Chance-RP/Feedback#381]
<h2>What bug have you found?
- When trying to fuel your car it is not working 

 - Describe in good detail what bug you have found as well as list the steps to reproduce if known*
- when in the car the gas meter goes pretty crazy going from full to half full then quarter over and over causing you not being able to know where you are at on fuel, so I go to the gas station trying to fill up and it will not do so ( pic will be attached )

<h2>What do you expect should happen?

-able to fill the car up

 - What do you think should happen, what is the intended outcome that you are currently not getting?*
- not being able to fill my car and gas meter should show correct gas level

 - Have you got any evidence to help prove the bug, a video or picture etc?*

https://gyazo.com/2a9adca147daa85cd875b463a1754d1d

**Comment by SwizzyWT** [comment]
Maybe this will help with the fuel meter in the car 

https://gyazo.com/5bd2ef16d5506a03fcbfedaca4fc6fb9

**Comment by ixhal** [comment]
merging with #383
