### ISSUE TITLE
Garbage

### ISSUE THREAD

**Issue by cNRR92** [New-Chance-RP/Feedback#382]
<h2>What bug have you found?</h2>

*Clocking onto garbage has changed my hair style *

<h2>What do you expect should happen?</h2>

*i just think its a miss type in the code or a error since the server change*

<h2>Anything to support your bug report?</h2>

* https://i.imgur.com/R2PJoiM.png *

**Comment by Senlarus** [comment]
Was this in the same session as when you made your character for the first time?
