### ISSUE TITLE
Garbage Requiring Commercial License Again

### ISSUE THREAD

**Issue by BillChirico** [New-Chance-RP/Feedback#386]
<h2>What bug have you found?</h2>

I was doing trash and then the blips went away. I couldn't return my truck. When going to clock in again it said I needed a commercial license, even though I have one and just did a shift.

<h2>What do you expect should happen?</h2>

Not have to get the license again.

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/13951316/84601283-03577700-ae4d-11ea-8e5e-b288fa89fc62.png)

**Comment by Senlarus** [comment]
I restarted the resource to fix uniform issues (hopefully)

**Comment by BillChirico** [comment]
@Senlarus Let me know when to check again
