### ISSUE TITLE
PD outfit choice changing ped model

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Feedback#388]
<h2>What bug have you found?</h2>

When choosing police outfit after I have clocked in, it resets your ped model to a bald version of yourself

<h2>What do you expect should happen?</h2>

My ped model to not change.

<h2>Anything to support your bug report?</h2>

Before outfit change - https://gyazo.com/f2b269034165f959e5d955f2f2d4608e

After outfit change - https://gyazo.com/567f27ab6b85208b147d9b88149f3a7b

**Comment by iamrayuu** [comment]
Does this for females too to my knowledge. Changed hair and makeup.
