### ISSUE TITLE
PD radio permanently on.

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Feedback#389]
<h2>What bug have you found?</h2>

When clocking in, the radio isn't turned on officially but we still hear everything going through them.

<h2>What do you expect should happen?</h2>

PD radio if not turned on to give us no audio.

<h2>Anything to support your bug report?</h2>

Clock in to any whitelist based role.

**Comment by Senlarus** [comment]
Merging with #385
