### ISSUE TITLE
Casino giving false cards.

### ISSUE THREAD

**Issue by Fat-Nick** [New-Chance-RP/Feedback#390]
<h2>What bug have you found?</h2>

when playing on the casino table, i got given a 9 and a 6 at once, when i should get 1 card. The tooltip then said i had a 9, when there was actually 15 on the table. I was then given a 10 and i went bust since i had 25 on the table.

<h2>What do you expect should happen?</h2>

the value of cards on the table should match the value given on the tool tip

<h2>Anything to support your bug report?</h2>

n/a

**Comment by ixhal** [comment]
Going to close this for now since no other reports have been given and not enough information to go on, I did have a quick look and did not see anything wrong If it happens again if you could record it that would be great.
Thanks for the report!
