### ISSUE TITLE
Clothing and facial features change when being released from prison.

### ISSUE THREAD

**Issue by rubberdingy** [New-Chance-RP/Feedback#391]
<h2>What bug have you found?</h2>
When i was realesed from prison my clothing and facial feature/textures all changed.

- Describe in good detail what bug you have found as well as list the steps to reproduce if known*
Before i was sent to prison i had chosen clothes and chosen facial features, when i got put in prison it turned me into a danny with prison clothing, then when i was released my overshirt/jacket got changed and my facial features changed, i dont have a screen shot of my clothing before i went to prison but have one of being released showing changes.
![Desktop Screenshot 2020 06 14 - 23 57 13 01](https://user-images.githubusercontent.com/61283563/84606111-d336c500-ae9a-11ea-88cc-4d0729cc2518.png)

<h2>What do you expect should happen?</h2>

- What do you think should happen, what is the intended outcome that you are currently not getting?*

<h2>Anything to support your bug report?</h2>

- Have you got any evidence to help prove the bug, a video or picture etc?*

**Comment by ixhal** [comment]
Have disable clothes from changing when going in/ getting out of jail for now (will apply next restart)
