### ISSUE TITLE
Vehicle Repairs Not Working

### ISSUE THREAD

**Issue by DerkDuece** [New-Chance-RP/Feedback#392]
<h2>What bug have you found?</h2>

When I pulled into a repair station to repair my cop car it wont repair but it is taking my money.
Hood stays open but my car is still damaged.

<h2>What do you expect should happen?</h2>

Pay money car fixes.

<h2>Anything to support your bug report?</h2>

NA

**Comment by Senlarus** [comment]
It’s related to the gas issue

**Comment by Senlarus** [comment]
Merging with #383
