### ISSUE TITLE
Chatbox clutter anytime posting.

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#393]
<h2>What bug have you found?</h2>

Anytime I make a post (no one else's does this) I get a bunch of extra information I don't need.  It'll say Message:/ooc *insert whatever I put* Color:8421504.  

<h2>What do you expect should happen?</h2>

I should just be able to make a post and not have the dialogue gobbled up with miscellaneous shit.

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/6095886/84611599-5ac90780-ae8c-11ea-89db-64d528316a40.png)

**Comment by ixhal** [comment]
should be gone one next restart thanks for report
