### ISSUE TITLE
More Illegal

### ISSUE THREAD

**Issue by BatsieSandra** [New-Chance-RP/Feedback#396]
<h2>More directed illegal rp</h2>

* fight club job

<h2>add more jobs and more rp opportunities</h2>

*DELETE THIS LINE - Another way to make money illegal, Ganges could run one, Cop could patrol and break the fights up. more work for EMS / placements,easy money,cops not stoping it*

<h2> https://www.gta5-mods.com/scripts/fight-club </h2>

*DELETE THIS LINE - If you have anything extra to provide, pictures or videos etc to help sell your idea put them here.*

**Comment by Senlarus** [comment]
Thanks for the suggestion! Our goal on the server is to try to maintain a balance between criminal and legal RP opportunities. Would you think that a fight club would be considered illegal? If everyone's consenting to the fight I don't see why there would be anything illegal about it. Just wondering what your opinion is.

**Comment by BatsieSandra** [comment]
Fight clubs are not like boxing/ufc.they have no rules really and are not regulated.Its like how nascar is fine but street racing is not.Plus ppl gamble on the fights,drugs are sold.All kind of illegal stuff.The atmosphere would helpfully bring out more rp.

**Comment by Birlzey** [comment]
A Fight club is already in the works by us the community! Please look at advertisments in discord for a sneak peek ;)

**Comment by Senlarus** [comment]
We're also planning on putting in a system for people to participate in fight clubs without fear of death. This will allow these events to happen without needing EMS to pick up people who get KO'd.
