### ISSUE TITLE
Incorrect Female Shoe Heights?

### ISSUE THREAD

**Issue by lAmantel** [New-Chance-RP/Feedback#398]
<h2>What bug have you found?</h2>

There are a few shoes in the female section that are misshapen and or at the wrong height. I've noticed for a few days now, and always put it back to maybe it will be fixed when the clothing script was completed, unfortunately the problem still persist. So the issue is some of the Sneakers/Trainers are set at the height of "heels", and then some of the heels are set to the height of "sneakers/Trainers" Thus making the before floating, and the latter squished beyond belief, as you'll see in the images provided.

<h2>What do you expect should happen?</h2>

What I would like is for the issue to be fixed, but we all know it's never that easy. So if there's anything I can do to help as you look into this please let me know VIA DM over discord or a reply here(though a reply my get a late reply cause I'm pretty bad at keeping up).

<h2>Anything to support your bug report?</h2>

I'm going to mark these with their number in the shop and the issue with it, so it will be easier to look into.

[256 | Floating off ground](https://imgur.com/BQya0pB)
[261 | Squished Heel/Wedges](https://imgur.com/JadpQjp)
[262 | Floating off ground](https://imgur.com/zNX8aYj)
[263 | Floating off ground](https://imgur.com/syHjpc5)
[264 | Floating off ground](https://imgur.com/DZcoTAA)
[268 | Floating off ground](https://imgur.com/NxRDoqG)
[270 | Floating off ground](https://imgur.com/ipaFwwu)

**Comment by Senlarus** [comment]
Best I can do is remove these options from the store. Would you like me to do that or do you think people would rather just have them in and deal with the weird height differences?
