### ISSUE TITLE
Lipstick colours not matching shown swatches

### ISSUE THREAD

**Issue by miliaeee** [New-Chance-RP/Feedback#399]
<h2>What bug have you found?</h2>

Very minor, but when creating a character, the lipstick colour being selected in the icon list, does not always match the one being shown on said character - I selected white as shown in the image attached, but shows on my character as bright red. Seems to be all of the lipstick colour selection.

<h2>What do you expect should happen?</h2>

When clicking on a colour, it correlating and being shown the same on the character.

<h2>Anything to support your bug report?</h2>

![Screenshot (2685)](https://user-images.githubusercontent.com/57221207/85039074-408a7480-b17f-11ea-9481-946f2afd9085.png)

**Comment by Senlarus** [comment]
Still happening with the new skin system recently installed?
