### ISSUE TITLE
Reviving upon Game Restart

### ISSUE THREAD

**Issue by Monster-Duck** [New-Chance-RP/Feedback#40]
<h2>What bug have you found?</h2>

When I am downed, I can close the server and come back in then I am back to full health.

<h2>What do you expect should happen?</h2>

When I am downed I shouldn't be able to abuse the system and go back to full health whenever.
<h2>Anything to support your bug report?</h2>

Nope, but it is pretty easy to replicate.

**Comment by ixhal** [comment]
Issue has been fixed, Thanks for the feedback!
