### ISSUE TITLE
Controller friendly

### ISSUE THREAD

**Issue by miliaeee** [New-Chance-RP/Feedback#400]
<h2>Feature you are requesting.</h2>

Work on making the server controller friendly - please!

<h2>What are the benefits to your feature?</h2>

Will appeal to those who use controller a lot more & add that function for anyone wanting to use it.

<h2>Anything to support your feature request?</h2>

I've been to servers before which aren't controller friendly & it has personally turned me off going back or becoming a regular player in those server, it could be a great feature to have added for all of us who are useless on keyboard and mouse!

**Comment by lAmantel** [comment]
Yeah I understand, this has been an ongoing request among others aswell.

**Comment by Senlarus** [comment]
Duplicate request, merging with #266
