### ISSUE TITLE
Taxi job not paying out.

### ISSUE THREAD

**Issue by DerkDuece** [New-Chance-RP/Feedback#401]
<h2>What bug have you found?</h2>

Was running taxi job and got a warning and after I dropped them off they paid with a card and the money never went into my account. It isnt everytime but about 20% of the time I get a warning I dont get paid.

<h2>What do you expect should happen?</h2>

GIVE ME MY MONEY.

<h2>Anything to support your bug report?</h2>

NA Will try and get a clip of it

**Comment by Senlarus** [comment]
Please provide more detail when available.

**Comment by DerkDuece** [comment]
So when picking up a customer at times you get warnings and in doing so you get notified by the customer. When I drop the customer off after getting a warning sometimes they also pay with card. And when they do it doesnt  go into my bank account.

**Comment by ixhal** [comment]
Issue has now been fixed, Thanks for the report!
