### ISSUE TITLE
Garbage locations are whack.

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#403]
<h2>What bug have you found?</h2>

A lot of the new garbage locations are super tight and hard to get into.  It's like trying to parkour with a 5 ton vehicle.

<h2>What do you expect should happen?</h2>

To be able to easily maneuver my brick of a vehicle to garbage locations so I don't damage the vehicle in the process.

<h2>Anything to support your bug report?</h2>

Couldn't find garbage at this location until I went up the ramp far away from the icon. 
![image](https://user-images.githubusercontent.com/6095886/85076346-ef35b180-b18d-11ea-8c96-b4290f267a0f.png)
![image](https://user-images.githubusercontent.com/6095886/85076384-02488180-b18e-11ea-84bd-dceddcbdadf0.png)

Garbage Location is also an unmarked Garage?
![image](https://user-images.githubusercontent.com/6095886/85076409-0ffe0700-b18e-11ea-985b-a0a7bdf6942c.png)

**Comment by Senlarus** [comment]
I really need locations coordinates or a picture of the map so I know where these are at.

**Comment by Senlarus** [comment]
Bloomb is working on finding much less whack locations for me Mr. Scarfninja.
