### ISSUE TITLE
F2 Inventory Menu

### ISSUE THREAD

**Issue by SwizzyWT** [New-Chance-RP/Feedback#405]
What bug have you found?

When hitting F2 to bring up player menu nothing comes up. 

Describe in good detail what bug you have found as well as list the steps to reproduce if known*

F2 menu not appearing when pressing for me. 

What do you expect should happen?

Press F2 and play inventory should appear 

 What do you think should happen, what is the intended outcome that you are currently not getting?*

Inventory menu should come up like it usually

**Comment by ixhal** [comment]
Keybind has been changed to I by default, Can also be remapped under the keybinds -> FiveM tab 👍
