### ISSUE TITLE
My car is gone

### ISSUE THREAD

**Issue by cNRR92** [New-Chance-RP/Feedback#406]
<h2>What bug have you found?</h2>

*Colin and Lena was on a adventure in my Masa Trail and she crashed and the vehicle went into the ocean i have checked every garage and insurance and it doesnt exit anymore its gone*

<h2>What do you expect should happen?</h2>

*Is it possible to get my vehicle back ?*

<h2>Anything to support your bug report?</h2>

*nope didnt exspect to lose it *

**Comment by Senlarus** [comment]
The car should be in the last garage you stored it in. Also, once it is destroyed it will take time for it to be pulled out again from the garage.

**Comment by Senlarus** [comment]
Your vehicle is in DownTown Cab Co garage.
