### ISSUE TITLE
Incorrect Car Name/Price (Emperor)

### ISSUE THREAD

**Issue by lAmantel** [New-Chance-RP/Feedback#407]
<h2>What bug have you found?</h2>

You have the USED Emperor and the NEW Emperor mixed up in the dealership, Causing the Rusted one to be priced higher, and the new clean one to be underpriced.

<h2>What do you expect should happen?</h2>

Just a quick switcheroo should fix this.

<h2>Anything to support your bug report?</h2>

[New Priced as Used](https://imgur.com/O3qnAKy)
[Used Priced as new](https://imgur.com/KAn8Enm)

**Comment by ixhal** [comment]
Issue has been fixed Thanks for the report!
