### ISSUE TITLE
Trunk Locked when Vehicle is Unlocked

### ISSUE THREAD

**Issue by SwizzyWT** [New-Chance-RP/Feedback#409]
What bug have you found?

- When trying to place something is my trunk on the  Vehicle I own, it says locked every time even when its unlocked

 Describe in good detail what bug you have found as well as list the steps to reproduce if known*

- Get out go to back of vehicle open trunk and says locked every time

What do you expect should happen?

- When Vehicle is unlocked you should be able to access the trunk

 What do you think should happen, what is the intended outcome that you are currently not getting?*

- Not being able to access trunk

 Have you got any evidence to help prove the bug, a video or picture etc?*

- https://gyazo.com/2006acadefc44228376d7e30eea95eed

**Comment by ixhal** [comment]
Issue should have been fixed now, Thanks for the report!
