### ISSUE TITLE
Dispatch Radio bug

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Feedback#412]
<h2>What bug have you found?</h2>

Radio prompt doesn't work after you clock out and quit the city, come back in and clock back on.

However, if you clock in, quit the city whilst clocked in and then load back into the city the radio prompt will work LSHIFT `

<h2>What do you expect should happen?</h2>

For the radio to work no matter what method of clocking in is going on.

<h2>Anything to support your bug report?</h2>
N/A

**Comment by bloombydee** [comment]
To clarify, when you clock in, the shift+` doesnt work, but if you stay clocked on and quit the server and rejoin, it does work. this is currently the only way to get the radio to work.

**Comment by Senlarus** [comment]
Pushed an update just now. Let me know if that fixes it.

**Comment by Senlarus** [comment]
Fixed! Thanks for your patience!
