### ISSUE TITLE
Driftoooo's CAA

### ISSUE THREAD

**Issue by Driftooooo** [New-Chance-RP/Feedback#414]
To retrieve your steam ID please do the following steps

- Go to http://vacbanned.com/
- Paste your steam profile link into search
- Copy the Hex code on Steam3 ID (64bit) EG 1100010002ce82

------------------------------------------------------------------------------------------------------------

**Steam ID**: 11000010a8a754a

**Do you have troubleshooting experience?** *(If yes please explain)* : Yes. I was a developer on an old server known as LS Network. I assisted with troubleshooting new features and mods. We'd go through a checklist of things to test with said modification and report it back through Github.

**How do you personally take screenshots?** : I use the F12 functionality with Steam. As a secondary, I may use Prnt. Screen if Steam Screenshots are not functioning.

**If you were trying to get your car out of a garage, when you walk over the marker nothing happens. How would you report that bug? What information would you provide?** :  I'd make sure to clip the entire encounter, then I'd input the bug issue into feedback via Github.

**Discord ID** *Please include numbers* : Driftoooo#9895

**Comment by iamrayuu** [comment]
Hey there! The server's actually now in Open Alpha, so feel free to hop in whenever! No application needed. :)
