### ISSUE TITLE
Taxi Job | Payment Issue

### ISSUE THREAD

**Issue by staxstefan** [New-Chance-RP/Feedback#415]
<h2>What bug have you found?</h2>
Taxi Job | Payment Issue
Brief description: Every time you start the job pick a customer up (NPC) payment goes through only for the first customer, every other bill of the upcoming customer goes into void. Payment prompt is active each time however bank funds as well cash in pockets remain static without added funds.

Steps to reproduce: 
- Clock in at Taxi Depot
- Grab a Cab
- F5 to start service
- Drive first customer to the destination
- Check your bank/cash after the fare
- Drive second customer to the destination
- Check your bank/cash after the fare

<h2>What do you expect should happen?</h2>
After each fare is done, money should be transferred either to our bank account or given in hands.

<h2>Anything to support your bug report?</h2>

- Not at this time.

**Comment by Senlarus** [comment]
Dupe #401
