### ISSUE TITLE
Emperors in Simeons are swapped

### ISSUE THREAD

**Issue by ZeroInsomniac** [New-Chance-RP/Feedback#417]
<h2>Emperor (used) and the normal Emperor are swapped on price and name compared to what the actual car is</h2>

![Screenshot_1](https://user-images.githubusercontent.com/49663655/87008087-73bd9380-c180-11ea-83d9-72c38117aa53.png)
![Screenshot_2](https://user-images.githubusercontent.com/49663655/87008096-761fed80-c180-11ea-84e1-db9f81bc6372.png)

**Comment by lAmantel** [comment]
Yeah I reported this as well like a week ago.

**Comment by ixhal** [comment]
Fixed thanks for the report!
