### ISSUE TITLE
Automated /me commands for common actions.

### ISSUE THREAD

**Issue by Real50BMG** [New-Chance-RP/Feedback#42]
<h2>What is your feature request?</h2>

Automated common '/me' commands

<h2>What are the benefits of your idea?</h2>

Having automated '/me' commands would make situations less awkward and would prevent situations from moving 'its flow'

<h2>Anything to support your idea?</h2>

Not really

**Comment by BadBritishGamer** [comment]
Edit your post with a list of things you feel are "common actions" and this can definitely be considered.

**Comment by Senlarus** [comment]
I like this idea but we need more feedback. See if you can get others to help you make a list? I know Rayuu had some ideas.

**Comment by BadBritishGamer** [comment]
Closing for now, if you have a list of actions that should have auto-me's open a new feedback in the future <3
