### ISSUE TITLE
Civ Radio not initializing

### ISSUE THREAD

**Issue by bloombydee** [New-Chance-RP/Feedback#421]
<h2>What bug have you found?</h2>

When purchasing radio, you must relog to be able to open menu

<h2>What do you expect should happen?</h2>

*DELETE THIS LINE - What do you think should happen, what is the intended outcome that you are currently not getting?*

<h2>Anything to support your bug report?</h2>

*DELETE THIS LINE - Have you got any evidence to help prove the bug, a video or picture etc?*

**Comment by Senlarus** [comment]
I believe this issue has been fixed.
