### ISSUE TITLE
Aiming Mechanics 

### ISSUE THREAD

**Issue by Kreated** [New-Chance-RP/Feedback#422]
<h2>Feature you are requesting.</h2>

When pressing RMB with a weapon in hand your took in 1st person POV.

<h2>What are the benefits to your feature?</h2>

Makes crosshairs pointless, more realistic, less moaning murtles..

<h2>Anything to support your feature request?</h2>

Iv requested this in the past but cant remember the exact outcome or I spoke to alan directly, but yeah I personally think this is a great idea. I'd love to hear what people think.

**Comment by Senlarus** [comment]
We discussed this request and feel it is too disorienting for people who may not enjoy a quick snap into a different view. In the future we may explore making this a "opt in" type setting where players can choose if they want this to be enabled or not but that will take a bit more development to make happen.

**Comment by Senlarus** [comment]
Merging with the original request for this feature #49
