### ISSUE TITLE
Press E Through Wall To Enter Cltohing Menu

### ISSUE THREAD

**Issue by Kreated** [New-Chance-RP/Feedback#423]
<h2>What bug have you found?</h2>
Can press E to enter the clothing menu through the wall, shop 5/14.
 
<h2>What do you expect should happen?</h2>
Not be able to do this.

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/64453673/87346133-17c08980-c549-11ea-9be8-46aabee404d3.png)

**Comment by VisionzAx** [comment]
Before: https://streamable.com/u485ly
After: https://streamable.com/rd2vht

**Comment by Senlarus** [comment]
The clothing store menu is an AOE and was made to be large to give people more space to use the clothing store at the same time.  I can try to make it smaller but I really don't think this hurts anything other than breaking some immersion. I'm going to trust players will use clothing stores properly and not buy cloths in the ally.
