### ISSUE TITLE
Dead waiting timer kicks you after waiting the 10 min for being AFK

### ISSUE THREAD

**Issue by SwizzyWT** [New-Chance-RP/Feedback#425]
What bug have you found?

- I am dead and waited the 9 min since no EMS were on, when the timer expired nothing popped up for me to respawn and then kicked me from the server for being AFK and now the timer restated all over again

 Describe in good detail what bug you have found as well as list the steps to reproduce if known*

- Died waited 9 min then no button for me to push to respawn then kicked me from server for being AFK

What do you expect should happen?

- When the timer is done there should be a button to respawn at a hospital

What do you think should happen, what is the intended outcome that you are currently not getting?*

- When dead and timer is finished there should be a respawn button to hit for a respawn at hospital, outcome im getting is waited on timer, went through the 9 min or 10 min then kicked me for being AFK relogged into server and now timer has started over 

 Have you got any evidence to help prove the bug, a video or picture etc?*

- Wasnt able to kick a pic of this happening

**Comment by SwizzyWT** [comment]
Waited 10 min again and got kicked for being AFK here is a pic 

https://gyazo.com/ffb23fc973082716d9c5c4d19d41a485

**Comment by Senlarus** [comment]
Temporarily increased afk timer to 15 min. Will put in a more long term fix later.

**Comment by Senlarus** [comment]
We may revisit this in the future but for now the AFK timer is paused while dead
