### ISSUE TITLE
Vehicle doesn't Store 

### ISSUE THREAD

**Issue by DropKickVibe** [New-Chance-RP/Feedback#426]
<h2>What bug have you found?</h2>

When I try to store my vehicle, I press e but the vehicle doesn't go away and then the circle disappears and I cant store it. I was at the garage in sandy both times this happened to me.  

<h2>Anything to support your bug report?</h2>

I have attached a screenshot below of some error code in the F8 menu
![image](https://user-images.githubusercontent.com/66173725/87968748-cb30fd00-cab8-11ea-9391-52a0a1a1f251.png)

**Comment by Senlarus** [comment]
What vehicle?

**Comment by ixhal** [comment]
The camper I think @Senlarus Also looked like his windows was smashed for the old picture I seen

**Comment by Senlarus** [comment]
That native is probably the exit people from vehicle one.

**Comment by DropKickVibe** [comment]
Yeah, it was a Journey. but I don't think it was very damaged as I didn't take it far, which now i think of it might be part of the issue

**Comment by staxstefan** [comment]
Yeap, happened to me as well when I tried to store my bike. Basically you press **E** glitch happens for a second and circle is gone, you can not store nor extract another vehicle from the garage, circles are completely gone. So are you saying if the vehicle is damaged we can not store it or is something else an issue? 

Image showing the error code: [error_log](https://drive.google.com/file/d/1SkXOvSZYTESILBwTGZA-uUMam3iFXxXt/view?usp=sharing)
Vehicle: Bike - [VADER]

**Comment by Senlarus** [comment]
Makes sense... that native has to do with broken windows. Bikes MIGHt have a windshield but there's really nothing setup to handle that type of error. I think I will just have to disable that part of the script for now.

**Comment by Senlarus** [comment]
I pushed a potential fix for this issue just now. Please test it when you can by trying to recreate the exact same circumstances that caused the crash last time and report back here if it worked.... or if it still crashes :) I tried, but I was unable to recreate the crash on my dev server so I need to rely on others to help me test this fix.

**Comment by Senlarus** [comment]
Hopefully people are storing the crap outa vehicles and having nothing but great success!

**Comment by Senlarus** [comment]
Ok, sounds like this might be fixed based on not hearing any feedback. I'm closing.
