### ISSUE TITLE
Twitter lock out when sending a picture 

### ISSUE THREAD

**Issue by Duerson** [New-Chance-RP/Feedback#427]
<h2>What bug have you found?</h2>

When you open your phone then go to send a picture on Twitter after clicking mouse 1 you are locked into first person view as if you are trying to take a picture. Nothing will take you out of this state that I know of other than logging back into the server. 

<h2>What do you expect should happen?</h2>

When possible look into it as it's helpful and provides great RP.

<h2>Anything to support your bug report?</h2>

I'll update this post when I can snag a screen cap, my capture key did not work but this happened twice today.

**Comment by Senlarus** [comment]
The plugin that does these screenshots is very problematic to say the least. I will have to remove that feature to resolve this sadly.

**Comment by Senlarus** [comment]
Removed screenshot option.
