### ISSUE TITLE
No respawn button after death 

### ISSUE THREAD

**Issue by ZeroJester** [New-Chance-RP/Feedback#428]
<h2>What bug have you found?</h2> After death, i waited the designated time before respawn but no respawn button appeared after.

<h2>What do you expect should happen?</h2> The command to press E should appear allowing you to respawn after a death occures.

<h2>Anything to support your bug report?</h2>

{https://media.discordapp.net/attachments/354284470205022210/735932197080530995/20200723_195128.jpg?width=976&height=462}

![Bugg report](https://user-images.githubusercontent.com/66621652/88328251-100a9d00-cd20-11ea-940d-44bd9c9f902b.jpg)

**Comment by Senlarus** [comment]
Thought this was resolved. I can look into it when I get home from work in about 4 hours.
