### ISSUE TITLE
Consistently falling through the floor randomly.

### ISSUE THREAD

**Issue by Fat-Nick** [New-Chance-RP/Feedback#429]
<h2>What bug have you found?</h2>

Recently while spending my time within the server, I keep falling through the floor only while driving. This happens randomly, on both high and low settings when it comes to distance scaling and texures. To avoid death I jump out the car into free fall under the map then pop back up to the surface.

<h2>What do you expect should happen?</h2>

To stay on the ground.

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/65404319/88336403-d5f3c800-cd2c-11ea-8767-73cd332fb9b2.png)

![image](https://user-images.githubusercontent.com/65404319/88336375-c96f6f80-cd2c-11ea-8795-02ab89ce5de8.png)

**Comment by Senlarus** [comment]
This is usually a client issue unless it is happening in the same location every time, then it's a mapping issue. Is it happening at any specific place? If not, when did this start? Have you updated drivers etc?

**Comment by Senlarus** [comment]
Closing due to no further information.
