### ISSUE TITLE
Being able to go "prone"

### ISSUE THREAD

**Issue by Real50BMG** [New-Chance-RP/Feedback#43]
<h2>What is your feature request?</h2>

A prone feature. GTA 5 doesn't have a prone animation where you could crawl around in by default. Not being able to go prone and sneak around for example is kind of weird in a server thats based on real life. 

<h2>What are the benefits of your idea?</h2>

Makes certain situations possible like sneaking around as a criminal, or even playing crippled when you somehow lost your wheelchair (that i seen a sneakpeak of :D )

<h2>Anything to support your idea?</h2>

Nope

**Comment by Senlarus** [comment]
We tried this and there are many reasons it will not work. For now, crouch is the best we can do.
