### ISSUE TITLE
HUD doesnt update when shuffling to driver seat

### ISSUE THREAD

**Issue by bloombydee** [New-Chance-RP/Feedback#430]
<h2>What bug have you found?</h2>

When shuffling from passenger to driver seat, you still have passenger hud until you exit and enter as driver

<h2>What do you expect should happen?</h2>

*DELETE THIS LINE - What do you think should happen, what is the intended outcome that you are currently not getting?*

<h2>Anything to support your bug report?</h2>

*DELETE THIS LINE - Have you got any evidence to help prove the bug, a video or picture etc?*

**Comment by DerkDuece** [comment]
No longer applicable as the HUD has been changed.
