### ISSUE TITLE
Stretcher Issue

### ISSUE THREAD

**Issue by Lohkii-s** [New-Chance-RP/Feedback#432]
<h2>What bug have you found?</h2>

I clocked on as EMS to mess around with the new portable stretcher, and my friend that was on it said that when i put him in the ambulance he got teleported to a different part of the map, making it so he could not hear me, but once i dragged him out of the ambulance it worked. 

<h2>What do you expect should happen?</h2>

I think it was supposed to put the patient in the back and that it is just a little script error.

<h2>Anything to support your bug report?</h2>

https://cdn.discordapp.com/attachments/691736116319223808/737359465623322745/Error_Script.png

**Comment by Senlarus** [comment]
Thanks for the report. I could use a little more information to help me look into this.
Was that error on your client or your friends?
Could you outline everything you did leading up to placing the stretcher into the ambulance?
Was your friend dead or were you just testing it while they were alive?

**Comment by iamrayuu** [comment]
Just saw this issue replicated on DerkDuece's stream. Patient was alive and teleported from the Harmony area to where Grupe Sechs is in the city after he put the stretcher in the ambulance. The EMT that fastened him in the stretcher and put him in was Jukoro420 if you want more information!
