### ISSUE TITLE
Death Issue

### ISSUE THREAD

**Issue by Lohkii-s** [New-Chance-RP/Feedback#433]
<h2>What bug have you found?</h2>

When you die, it shows that i am just laying there, on full health as if im not supposed to be dead.

<h2>What do you expect should happen?</h2>

Im guessing it was supposed to show the black screen and my body is supposed to ragdoll. 

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/66181584/88723679-2d28dc80-d121-11ea-9343-cb7666c48879.png)

**Comment by ixhal** [comment]
When you die you get revived and put into a animation this is so you wont have to relog for EMS to see you, That error is just a logging issue, Should we working how its supposed to Will look into the error later on
