### ISSUE TITLE
Police Evidence Storage Issue

### ISSUE THREAD

**Issue by DerkDuece** [New-Chance-RP/Feedback#434]
<h2>What bug have you found?</h2>

When attempting to withdraw something from police evidence it will not give you the item
<h2>What do you expect should happen?</h2>

Put the item I have withdrawn into my inventory.

<h2>Anything to support your bug report?</h2>

https://clips.twitch.tv/EsteemedComfortableDinosaurFailFish

**Comment by ixhal** [comment]
This should have been fixed, Going to close if its not please DM me, Thanks <3
