### ISSUE TITLE
Female prison suit has no pants

### ISSUE THREAD

**Issue by GothiccBih** [New-Chance-RP/Feedback#435]
<h2>What bug have you found?</h2>

As a female, you are just a floating torso and a pair of flip-flops.

<h2>What do you expect should happen?</h2>

Females should have at least legs since I know I will be going to prison often.

<h2>Anything to support your bug report?</h2>

![PANT](https://user-images.githubusercontent.com/66048097/89067891-c3cde700-d335-11ea-9040-54ac3d61ae12.jpg)

**Comment by ixhal** [comment]
#436 Closing this post just to keep it in one area for when we get around to fixing the jail up Thanks for the report and be sure to post any other issues with jail in the thread mentioned 👍 😄
