### ISSUE TITLE
F9 Menu and Radio active after clocking off Police Job

### ISSUE THREAD

**Issue by staxstefan** [New-Chance-RP/Feedback#437]
<h2>What bug have you found?</h2>

After clocking off the radio and F9 menu remained on the individual. Images will show that I do not have a radio on me nor that I am clocked in.

<h2>What do you expect should happen?</h2>

Radio button shouldn't work without one in inventory nor I should be able to see the F9 menu.

<h2>Anything to support your bug report?</h2>

https://drive.google.com/file/d/1vg-8yfPQLP2R7nnteCnEUzmnmk_a18W1/view?usp=sharing
https://drive.google.com/file/d/1_rq1gu1y5-uhe4CLUAmKhZcnKKFaGZ_B/view?usp=sharing

**Comment by ixhal** [comment]
F9 menu is  there for all jobs and is intended to be that way, What is the issue with the radio? If you don't have one and clock out you can still use it?

**Comment by Senlarus** [comment]
This was fixed.
