### ISSUE TITLE
Tackle feature

### ISSUE THREAD

**Issue by Real50BMG** [New-Chance-RP/Feedback#44]
<h2>What is your feature request?</h2>

A tackle feature.

<h2>What are the benefits of your idea?</h2>

The benefit to this feature is that it gives people a chance to stop another person from running away without instantly grabbing a weapon of some sorts. Being able to tackle others could be used in more situations like messing around with friends or even events that people can come up with that utilize this feature.

<h2>Anything to support your idea?</h2>

Not really.

**Comment by BadBritishGamer** [comment]
Problem with tackle based features is Desync ruins this completely.

For example your perspective shows you 3-4 feet ahead of me, but my perspective shows me  nearly on top of you so I trigger the tackle animation. This then teleports you back towards me and now comes the "staff situations".

It can be very abusive to, but if a decent script for it is found then I'm not against anything that encourages less gun fights and more passive fights.

**Comment by Senlarus** [comment]
Stun gun, tackle too buggy to implement.
