### ISSUE TITLE
Times up in jail, but you cant leave

### ISSUE THREAD

**Issue by DropKickVibe** [New-Chance-RP/Feedback#440]
<h2>What bug have you found?</h2>

I have seen some people finish their prison sentence but they don't get released. They have to be walked to the front gate at which point they teleport out to the front and are put in their own clothes and released.

Sadly it has not happened to me but everyone it has happened to have said there are no script errors in F8

**Comment by ixhal** [comment]
#436 Merging over there thanks for the report!
