### ISSUE TITLE
Stuck fueling

### ISSUE THREAD

**Issue by DropKickVibe** [New-Chance-RP/Feedback#441]
<h2>What bug have you found?</h2>

If you fuel your car from the opposite side to the pump you get stuck until the car if 100% fuel. A lot of people think they are glitched forever and relog.

**Comment by Senlarus** [comment]
I cannot reproduce this. Please show me now you do it.

**Comment by Senlarus** [comment]
Oh... I see what you're talking about. People are trying to gas up from the side where the pump isn't at...(Grr...)
![image](https://user-images.githubusercontent.com/1503963/89128510-150be100-d4c4-11ea-9039-a2e5a6f76ef2.png)

**Comment by DropKickVibe** [comment]
yeah lol

**Comment by Senlarus** [comment]
Fixed, thanks for the report!
