### ISSUE TITLE
Mamba 

### ISSUE THREAD

**Issue by SwizzyWT** [New-Chance-RP/Feedback#445]
What are you requesting?

-before the vehicle update the other day my mamba had speed, power ,  burning them tires!! And now I get in my mamba and it won’t go over 85mph for a $90k car 

**1) - Vehicle changes -** 

Handling is fine, but mph should be a lot more than 85 mph 

Why are you making this request?

This is a muscle car that should have speed

**Comment by bloombydee** [comment]
We recently swapped out the vehicle handling meta that we used on the server, the old one had a bunch of weird cars like FWD muscle cars, we have a team that is currently going thru and tweaking the new vehicles so I'll ask them to look into the mamba

**Comment by SwizzyWT** [comment]
Alright cool! I need my baby burning them tires again!!

**Comment by Senlarus** [comment]
I saw you say this was fixed, closing.
