### ISSUE TITLE
issue while been downed

### ISSUE THREAD

**Issue by BIRLZ95** [New-Chance-RP/Feedback#449]
<h2>What bug have you found?</h2>

You can do /pants etc to take your clothing off while you are bleeding out.

<h2>What do you expect should happen?</h2>

Not be able to remove your clothing while been downed.

<h2>Anything to support your bug report?</h2>

Nope.

**Comment by ixhal** [comment]
Its like that so if you get downed and a police officer/ EMS want to take off parts of your clothing you can do a command, its provides a bit more RP
I see ur concerns though and will talk to the others about it

**Comment by ixhal** [comment]
Talked to the others about it and we will leave it like this for the RP experience, Thanks for the report!
