### ISSUE TITLE
Government handle licenses (admins)

### ISSUE THREAD

**Issue by Real50BMG** [New-Chance-RP/Feedback#45]
<h2>What is your feature request?</h2>

The 'government' or some group of admins to control whether someone can get a gunlicense or not

<h2>What are the benefits of your idea?</h2>

Having people, mainly criminals, being able to buy a weapon license whenever they generate enough money and use said weapons from criminal activities makes little sense. Criminals wouldn't use a licensed firearm for any of their crimes irl either. This will also prevent from 'Default Dannys' from getting into the server and pretty much straight up get a gun and start shooting around himself. I am sure there are even more benefits to this kind of system

<h2>Anything to support your idea?</h2>

*DELETE THIS LINE Is there anything you can add which will help sell your idea, pictures, diagrams etc?*

**Comment by Senlarus** [comment]
Weapon licenses have been added at a cost that will prevent Default Dannies from getting in and getting one without having to play for a while first. A weapons license is required to purchase guns from Ammunation, but crims can get them other ways.
