### ISSUE TITLE
Fall through map at taxi depo

### ISSUE THREAD

**Issue by ZeroJester** [New-Chance-RP/Feedback#454]
<h2>What bug have you found?</h2>

Fell through the map at the Taxi depo garage.
Appon walking and driving into the garage interior located at the side of the Taxi depo you fall through the world and get placed back out front.
This does not just happen at the garage but at the entire taxi depo aswell as the taco shop.
P.S. the invantory does not display items when I is pressed.

<h2>What do you expect should happen?</h2>

As far as i know you should be able to store the taxi here at the end of the shift.

<h2>Anything to support your bug report?</h2>

I have video evidence however the format type of the video is not supported.

**Comment by Senlarus** [comment]
I have updated some of the files associated with there interiors to hopefully fix these issues. If it continues you can try lowering your graphics settings, but it's likely just an issue with streaming these assets.
