### ISSUE TITLE
Ped Density 

### ISSUE THREAD

**Issue by HimWhoRobs** [New-Chance-RP/Feedback#455]
<h2>What bug have you found?</h2>

A few things related to ped density, some times as we have seen the peds are stood in the road and this doesnt get cleared unless everyone leaves the area, and this is 100% a bug. However on the other side of the spectrum to this on the taxi job I can go litteraly 20mins easy without seeing a single ped to pick up

<h2>What do you expect should happen?</h2>

Both bugs would need fixing. I have no idea where to begin with the car jams. But I do feel ped density is braking in the other way also where peds just seem to disapear for 20mins at a time. and ontop of that when its working ped density seems low in some areas. Grove st / strawberry  / legion to name a few key places

<h2>Anything to support your bug report?</h2>

As stated above ped density seems off

**Comment by ixhal** [comment]
I tried something yesterday for this, If you could let me know what its like now that would be perfect, Cheers for the report!

**Comment by Senlarus** [comment]
Peds are dense.
