### ISSUE TITLE
Custom Clothing Locked behind Whitelist Jobs. (Tested only with EMS/ Females Only (not a male Character)

### ISSUE THREAD

**Issue by lAmantel** [New-Chance-RP/Feedback#457]
<h2>What bug have you found?</h2>

I've noticed after helping bloomb yesterday with the female EMS outfits that all of the currently custom clothing for females are locked behind the clock in jobs.

<h2>What do you expect should happen?</h2>

I'm guessing this was probably an error that occurred when inputing the services clothing.

<h2>Anything to support your bug report?</h2>

I was taking screenshots, but After realizing that it's all locked, I stopped x'D 
But
26, 27, 28, 29, 30, 31, 32 -Female Jackets Is as far as I got before just saying I'd tell you ALL the addon clothes were hidden.

**Comment by Senlarus** [comment]
Thanks, the release of this clothing was just slightly delayed due to other issues needing attention. Hopefully we can have another round of new clothes soon including more hair styles!
