### ISSUE TITLE
Burger Job Position Still "taken" after crashing

### ISSUE THREAD

**Issue by lAmantel** [New-Chance-RP/Feedback#458]
<h2>What bug have you found?</h2>

I crashed whilst I was clocked in as a Mascot. I relogged and the position was locked as taken.

<h2>What do you expect should happen?</h2>

I would expect the position to be available again after I crash. It works when you clock off but if you crash it gets locked.

<h2>Anything to support your bug report?</h2>

https://i.imgur.com/56JUEki.png

**Comment by bloombydee** [comment]
Also during our shift, I as cashier was only being paid 100 every 10 minutes and when the cook clocked off, I had to clock out/clock in to use all the stations

**Comment by Senlarus** [comment]
Oh crap, no wonder people don't wanna work it! I will have to fix that.

**Comment by Senlarus** [comment]
Burgershot just all got raises! 🤑

**Comment by Senlarus** [comment]
This has been fixed, thanks!
