### ISSUE TITLE
Bifta is broke

### ISSUE THREAD

**Issue by DropKickVibe** [New-Chance-RP/Feedback#459]
<h2>What bug have you found?</h2>

So, ive noticed that if a car door is open or missing then you cant get in the car using that doorway. As a result of that the Bifta, which comes with no doors, cant be accessed. 

<h2>Anything to support your bug report?</h2>

No errors in F8 
The Bifta:
![image](https://user-images.githubusercontent.com/66173725/91051156-9ebc5380-e617-11ea-9bce-9dfee45b220e.png)

**Comment by ixhal** [comment]
This issue has been fixed now! Thanks for the report
