### ISSUE TITLE
Police F5 Machines Not Working

### ISSUE THREAD

**Issue by DropKickVibe** [New-Chance-RP/Feedback#460]
<h2>What bug have you found?</h2>

Whenever you respawn or are revived while clocked into I believe any Job, but for sure police, when you get back up for F5 is broke (it doesn't appear when you press F5). The only way to fix it is by relogging. 

<h2>Anything to support your bug report?</h2>

Big RIP's but I can find the scripted errors anymore. I try again soon

**Comment by ixhal** [comment]
This issue should be fixed on the next server reboot! Sorry this went under the radar for so long.
