### ISSUE TITLE
Mechanics - Matte paint not sticking after restart

### ISSUE THREAD

**Issue by HimWhoRobs** [New-Chance-RP/Feedback#462]
<h2>What bug have you found?</h2>
Ive been to the mechs twice now and requested a matte finish which after some difficulty i the shop sticks. But upon restart it reverts back to a normal paint and very shinny

<h2>What do you expect should happen?</h2>

The car should keep its paintjob

<h2>Anything to support your bug report?</h2>

Ye my car in game xD

**Comment by HimWhoRobs** [comment]
Infact it wouldnt even be to do with the restart as I flew in just before and had the work done last night about 24hrs ago and maybe 4/5 hrs ago

**Comment by Senlarus** [comment]
This should be fixed now, please confirm.
