### ISSUE TITLE
Stocks on characters

### ISSUE THREAD

**Issue by BIRLZ95** [New-Chance-RP/Feedback#463]
<h2>What bug have you found?</h2>

If I buy stocks on 1 charcter I also have them on all my another characters.

<h2>What do you expect should happen?</h2>

Stocks be seperate for each character.

<h2>Anything to support your bug report?</h2>

Nope.

**Comment by DerkDuece** [comment]
I am unable to replicate this situation, any chance you could make a video of it?

**Comment by Senlarus** [comment]
I looked on the data side and this doesn't seem possible. The data for stocks is stored on a line with your specific characters data. Name, phone number, sex, age stocks all on the same line for that character.

**Comment by BIRLZ95** [comment]
Sorry I must have the same invested and just forgot, brainfart aha
