### ISSUE TITLE
Falling Through Map MRPD

### ISSUE THREAD

**Issue by BIRLZ95** [New-Chance-RP/Feedback#466]
<h2>What bug have you found?</h2>

I fall through the map when assigning police vehicles while clocked on LSPD. I also cannot view the garage outside it says "this model does not exist in game" so I cannot get my vehicles out.

<h2>What do you expect should happen?</h2>

Not fall through map when assigning vehicles and be able to take them out once assigned.

<h2>Anything to support your bug report?</h2>

https://youtu.be/J4GVIGoi6fs

**Comment by Senlarus** [comment]
I can't reproduce this. Is it still happening? From the video it looked like the IPL wasn't loading for you.

**Comment by BIRLZ95** [comment]
yeah still happening

**Comment by Senlarus** [comment]
MRPD has been removed. This shouldn't happen now.
