### ISSUE TITLE
Moving furniture drops you into the void

### ISSUE THREAD

**Issue by Fat-Nick** [New-Chance-RP/Feedback#467]
<h2>What bug have you found?</h2>

If i place a bit of furniture, then try to move it afterwards, i suddenly fall into the void.

<h2>What do you expect should happen?</h2>

I should be able to move furniture in any way i see fit.

<h2>Anything to support your bug report?</h2>

https://www.youtube.com/watch?v=JYXogiXFZQY

**Comment by Senlarus** [comment]
Is this a furnished shell?

**Comment by Fat-Nick** [comment]
no, its unfurnished. House medium quaint

**Comment by Senlarus** [comment]
This should be fixed now.
