### ISSUE TITLE
PD Announcements 

### ISSUE THREAD

**Issue by SirLyx** [New-Chance-RP/Feedback#468]
<h2>Feature you are requesting.</h2>

To change the current layout of PD arrest announcements 

<h2>What are the benefits to your feature?</h2>

The current system shows a message in the main chat that looks like this 
![image](https://user-images.githubusercontent.com/69530692/91663559-ecd6c880-eae9-11ea-8be5-0d87542278ba.png)

My idea is to change the following:

Change "Judge" to "LSPD"
Change "In Jail for" to "Got sentenced to prison for the following charges"
Chane "Minutes" to "Months" 

<h2>Anything to support your feature request?</h2>

Nope <3

**Comment by bloombydee** [comment]
We were actually thinking of putting jail and ICU messages into a news app, either automatically or thru the weazel news job. Do you think that would be good or would you still want them in the top left?

**Comment by Senlarus** [comment]
Remove them, metagaming.

**Comment by SirLyx** [comment]
While I wouldn't call these announcements metagaming, as some arrests of some caliber are public records. I would agree that they would be abused unrealistically, for example going to prison to pick up someone you are after and kill him, just because you know when he is getting released at what prison.

I like the idea of a news app on the phone where EMS and PD can post their announcements, thus only worthy announcements, not going to ICU for a broken arm (Seen it a lot on other servers), it would be less in the way and it would be a bit more realistic.

**Comment by Senlarus** [comment]
Arrests of some caliber still take a while to get to the eyes of the public and yes, the reason for me not wanting them is due to the abuse. They are a matter of public record and should be able to be searched up. I have something on the phone that we might be able to eventually use for something but it's not ready yet. I just don't feel like PD/EMS need access to public announcements to the entire server. People shouldn't know when robberies are going down in real time, or of jailings, or ICUs.

**Comment by staxstefan** [comment]
I would remove it. Such arrests are not public that soon unless you speak with officer/judge that made the arrest/sentence. They should appear somewhere in the app with a different layout and should be delayed so people wouldn't meta game or get trigger happy. Speaking this for both ICU & JAIL. From a different standpoint IRL we have no clue who gets arrested unless we speak with someone at the station/hospital, we should get a call from pd/medical if it's a relative but that's about it

**Comment by c-reckless** [comment]
> Remove them, metagaming.

This. If were taking this into IRL circumstances then when would you ever be able to find out someone has been arrested or sent to hospital as a member of the public? Unless there is some sort of news report or a court hearing then I feel that all of it should be kept internal with LSPD/EMS/Government. 

The only reason like seeing the information is to either laugh at the person or hunt them down after...

" Steve Jobs has been jailed for 10,000 days "

Twitter gets flooded with "F" "big RIP" "free Steve" - do we really need to see that?

**Comment by Mubbb** [comment]
Definitely remove. There's no real reason for anyone outside of the LSPD/EMS etc. to know this information.

**Comment by N3rdymomma** [comment]
So i do agree that it shouldnt be posted in the ooc area. I do like the idea of the arrest records being posted in the news app when weazel news deems appropriate. The ICU shouldn't be posted because that would violate HIPAA laws. The only thing medicaly related should be obituaries.

**Comment by Senlarus** [comment]
We will eventually have a public records system with our Department of Justice update.

**Comment by Senlarus** [comment]
Removed for now, will review this again in the future. Thanks for all of the feedback!
