### ISSUE TITLE
Drug Sales Issue

### ISSUE THREAD

**Issue by BIRLZ95** [New-Chance-RP/Feedback#469]
<h2>What bug have you found?</h2>

Multiple people can sell drugs to the same person if they press H at the same time. 

<h2>What do you expect should happen?</h2>

Once someone has sold drugs to them there should be a cooldown or whatever.

<h2>Anything to support your bug report?</h2>

Nope.

**Comment by ixhal** [comment]
Issue should be fixed after next server reboot, Cheers for the report 👍
