### ISSUE TITLE
Car keys being a physical item

### ISSUE THREAD

**Issue by Real50BMG** [New-Chance-RP/Feedback#47]
<h2>What is your feature request?</h2>

Carkeys being an actual item. On other servers, if you leave your car unlocked, someone can just drive away with it. Realisticly you wouldn't leave your carkeys in your car.

<h2>What are the benefits of your idea?</h2>

Makes stealing player cars harder, so they will always have lockpick the electronics of the car instead of magicly turning it on. Also it's more of a realistic approach and makes you able to borrow your car to a specific person, and not just give them your unlocked car.

<h2>Anything to support your idea?</h2>

*DELETE THIS LINE Is there anything you can add which will help sell your idea, pictures, diagrams etc?*

**Comment by Senlarus** [comment]
Physical items aren't always as fun as you'd think. We have added systems to lend keys to people and will continue to enhance the key system as necessary. At this time, keys will not become a physical item.
