### ISSUE TITLE
Possibility to put your friend in the car and in the hospital.

### ISSUE THREAD

**Issue by tirida** [New-Chance-RP/Feedback#470]
<h2>Feature you are requesting.</h2>

I think it would be nice to have a feature where you could put your friend in the hospital beds / in the ICU and also the possibility to put a downed person in your trunk or in your car somehow. I feel like it would fit pretty well since the server already has the /carry feature implemented. 

<h2>What are the benefits to your feature?</h2>

The biggest benefit is that you can help your friend out without any EMS / PD being clocked on. It's happened to me and my friends a couple of times now where someone of us has died and then we have to wait for EMS to come. If we had the possibility to help our friends to the hospitals we wouldn't have to wait as long. :)

<h2>Anything to support your feature request?</h2>

No.

**Comment by Senlarus** [comment]
Already in the works 👍

**Comment by Senlarus** [comment]
A few days ago we added the ability for you to check your friends into Pillbox at either the upper or lower desk. Just carry them there while they're downed and they will be able to get ICU care. The feature to be able to place people in vehicles is being worked on by @ixhal

**Comment by Senlarus** [comment]
@ixhal Done or do you wanna keep this open for now?

**Comment by Sukaklepto** [comment]
Can we get more drugs in the city like lean and so fourth 
![CE6ECC64-B53B-4B8A-B6E9-245981A93FFB](https://user-images.githubusercontent.com/72714398/95693300-9082c080-0be0-11eb-8e8a-e81e8e52c301.jpeg)
![1B16E3E1-8930-424C-88EA-9F8AF9B540E5](https://user-images.githubusercontent.com/72714398/95693303-92e51a80-0be0-11eb-8e2a-934a73f566ec.jpeg)
![5E4F0660-A323-4BE0-B600-36159A1A8F74](https://user-images.githubusercontent.com/72714398/95693304-937db100-0be0-11eb-960f-a672405c12d3.jpeg)
