### ISSUE TITLE
Have the radio on a holster or have an earpiece.

### ISSUE THREAD

**Issue by SirLyx** [New-Chance-RP/Feedback#471]
<h2>Feature you are requesting.</h2>

For the radio to be able to be attached to a holster or an earpiece so you don't have to take it out every time to talk.

<h2>What are the benefits to your feature?</h2>

The benefits are being able to talk without having the radio menu up with is interfering with a lot of other stuff.

**Comment by Senlarus** [comment]
Currently hands free mode is only for services, we will discuss if we want this for civs.

**Comment by Senlarus** [comment]
WE will just let people use it hands free
