### ISSUE TITLE
Women's Hairstyles

### ISSUE THREAD

**Issue by SuperCShe** [New-Chance-RP/Feedback#472]
About 90% of women's hairstyles make us bald (LOL) because they don't load. I was just wondering if you're going to have the style with the braid on one side of the shoulder in the future when they're fixed as that is my preference. :) 

Also, when I select black as the primary and teal as the secondary, the entire hairstyle goes teal and there's no black. IDK if that is just the hairstyle I chose that forces that or if there's an issue with selection.

**Comment by Senlarus** [comment]
Yes, women's hair is coming! I think we have the side braid, watch for an EUP update Soon(TM)

**Comment by Senlarus** [comment]
8 New hair styles were added. You will still see all of the bald slots because they are placeholders for when we add new hair to the list. This is how it is supposed to work... and I guess gives us an incentive to have A LOT more hair added so we can fill all of those empty spots!
