### ISSUE TITLE
Vehicle In the Streets Bug (Mechanic Stored My Vehicle)

### ISSUE THREAD

**Issue by lAmantel** [New-Chance-RP/Feedback#473]
<h2>What bug have you found?</h2>

Okay, So I took my Brawler to the mechanics because the Gloss finish that I purchased had turned matte. So I took it to the mechanic to return the gloss. Because this is an issue that happens often the mechanic stored the car for me. Now when I go to retrieve my vehicle from the mechanics garage, It claims that my car is on the streets. So I can't retrieve my vehicle at the moment. I can also hear my vehicle running, but invisible in the exact spot that the mechanic put it away it. I have collision with it, and I can stand on top of it, But what I can not do Is retrieve my vehicle from the garage.

<h2>What do you expect should happen?</h2>

I think this would work as intended if the error or the culprit of the situation can be solved.

<h2>Anything to support your bug report?</h2>

I have a GIFs of me being able to walk and jump over the vehicle that is not seen,
https://gyazo.com/5d8bceb125a8bc0ab3623f174a329df4
I also have a GIF of me being able to lock and unlock the invisible vehicle that the mechanic stored for me.
https://gyazo.com/221d87ed94cfa0ce8b18a9eaef82f214

**Comment by Senlarus** [comment]
Do you have when the vehicle was stored or what happened leading up to it being stored?

**Comment by lAmantel** [comment]
I don't unfortunately, but I believe this issue was resolved a few restarts ago no?

**Comment by Senlarus** [comment]
This issue has been resolved.
