### ISSUE TITLE
Cannot change voice volume once downed

### ISSUE THREAD

**Issue by GamerDaniel18** [New-Chance-RP/Feedback#474]
<h2>What bug have you found?</h2>

When you are downed and faced with the 10 minute respawn timer you cannot change the volume of your voice. It simply stays at the volume it was at when you were originally downed. For example, I have been downed while shouting and I could not cycle to normal or whisper, this made it awkward to talk to ems as others at a distance could hear me talking over them. A similar problem could occur when someone gets in a crash whilst whispering to their passenger and then find themselves unable to call ems over to them when they arrive.

<h2>What do you expect should happen?</h2>

I expect voice cycling to be always available.
 
<h2>Anything to support your bug report?</h2>

I do not have any pictures as it would be hard to convey the problem.

**Comment by ixhal** [comment]
Issue should be fixed on the next restart, Thanks for the report!
