### ISSUE TITLE
Invisible Issue

### ISSUE THREAD

**Issue by BIRLZ95** [New-Chance-RP/Feedback#479]
<h2>What bug have you found?</h2>

I was in the passenger seat of my friends car he put his car in Aloquin garage in sandy while I was still sat init and It turned me invisible, I was still able to interact with everything but no one could see me nor could I see myself.

<h2>What do you expect should happen?</h2>

Pop you out the vehicle like it does the other person, not be invisble on eject.

<h2>Anything to support your bug report?</h2>

Nope.

**Comment by Senlarus** [comment]
Updated garage script to force all players to exit.

**Comment by Senlarus** [comment]
Has this been fixed with the force all players to exit on vehicle store?

**Comment by BIRLZ95** [comment]
Think so! Not been happended since. 👍

**Comment by ixhal** [comment]
Closing issue as no other reports of this happening since the patch
