### ISSUE TITLE
Dirty Money/Black Money

### ISSUE THREAD

**Issue by BIRLZ95** [New-Chance-RP/Feedback#480]
<h2>What bug have you found?</h2>

When moving Dirty Money from pockets to storage the text changes to Black Money and vise-versa.

<h2>What do you expect should happen?</h2>

It should stay as Dirty Money I believe? It still acts the same black/dirty just should be called the same and not change when dragging it from your pockets to storage.

<h2>Anything to support your bug report?</h2>

Yeah but contains sensative footage. Msg me for link.

**Comment by Senlarus** [comment]
This isn't a bug, it is just how the game views the money. The actual currency is called black money, but the item is called dirty money. This will eventually change in a future update, but for now it's nothing to worry about.
