### ISSUE TITLE
Shooting out of vehicle.

### ISSUE THREAD

**Issue by ArnieBIB** [New-Chance-RP/Feedback#482]
<h2>What bug have you found?</h2>

Being unable to shoot out/from any vehicle, same goes with using middle finger inside vehicles

<h2>What do you expect should happen?</h2>

The ability to shoot out/from vehicles, also the ability to use middle finger.

<h2>Anything to support your bug report?</h2>

In game

**Comment by iamrayuu** [comment]
The inability to shoot from a vehicle isn't a bug. However, I would vouch that it should be a thing to be able to flip off people still, so thank you for bringing that to our attention!

**Comment by Senlarus** [comment]
Yes, we have removed drivebys. It was a difficult decision but it was ultimately what was decided to be best for the type of RP we want to have on New Chance RP. I will however look into making it so we can flip people off.

**Comment by iamrayuu** [comment]
Hi! Flipping off has been added, Shooting hasn't been added back but since that part has been explained and we also made it so you can still flip off, we will be closing this. Thank you for your feedback!
