### ISSUE TITLE
Knife Damage

### ISSUE THREAD

**Issue by Lohkii-s** [New-Chance-RP/Feedback#483]
<h2>What bug have you found?</h2>

Knifes take around 5 to 7 stabs to actually kill a local.

<h2>What do you expect should happen?</h2>

I believe that knifes should do a lot more damage and its a 10 inch blade.

<h2>Anything to support your bug report?</h2>

Sadly not

**Comment by Senlarus** [comment]
Knife had to be nerfed a bit due to how it damages players. This is not a bug, it is by design. We will review it, but it's not likely to change.
