### ISSUE TITLE
Diamond Casino Improvements

### ISSUE THREAD

**Issue by GamerDaniel18** [New-Chance-RP/Feedback#484]
<h2>Feature you are requesting.</h2>

A. The Diamond Casino is supposed to be this grand, glamourous place, where people dress up to go take in the exciting atmosphere and roll some dice. Unfortunately, when you walk in there you are faced with a massive cavernous ghost town.
 I think it would be a great idea to fill the casino with NPCs, this would give the place some atmosphere and would make it feel more like a high stakes casino and not some virtual hub. 
Even if it's just adding a few stationary NPCs at the bar, behind the cashier's table, behind the clothing store counter, and at the reception desk, these additions would make it seem like a real place and not just a glorified hallway leading to the blackjack table.

B. Seeing as there is already a clothes store placed in the casino, I think it would be a great idea to allow players to buy clothes there, this is a small addition but it just makes sense.

C. It makes tons of sense to block the use of weapons inside the casino. It makes no sense for this multimillion-dollar casino to allow guns and knives into their establishment, I think it would make more sense to block the use of weapons inside the casino, just like when you get into a vehicle. A message could pop up when you enter the building, saying something like "Security has confiscated your weapons until you leave." This would also work well with having security guard NPCs placed at the doors.

<h2>What are the benefits to your feature?</h2>

The casino seems like it could be a massively popular place for players to meet and hang out, at the moment I think it is operating at 50% of its potential. If these changes were made it would improve casino RP as well as increase immersion and realism.

<h2>Anything to support your feature request?</h2>

![image](https://user-images.githubusercontent.com/50466883/91991734-2cd8be00-ed2b-11ea-902d-31d7b4d54b30.png)
You could hear a pin drop in here!

**Comment by Senlarus** [comment]
You hit on some topics that we have already discussed. Thanks for your feedback! We do have plans for the casino to add more games and more life. We will take these suggestions into consideration!

**Comment by Senlarus** [comment]
So after further review and consideration I don't think we will really ever be able to make this place as hoppin as it should be. Thanks to FiveM and entity limits we have to be careful with how many things we manually add to the city. Everything costs resources and can contribute to other issues down the road. Especially as we get more players rolling around in cars and such. I think we will always need to limit ourselves to the NPCs needed to run the games and maybe we can add a chip seller and bartender, but I think that would be the most we could do.
