### ISSUE TITLE
Unable to use Twitter

### ISSUE THREAD

**Issue by lAmantel** [New-Chance-RP/Feedback#485]
<h2>What bug have you found?</h2>

Okay, so I wanted to move my Grandma Memaw persona onto my main account because as a mod, I wanted to be able to help no matter what character I was on. With the original memaw connected to a separate steam I had no powers. I decided to delete the original memaw that was on my second account and recreate her on my main/original account and now I'm no longer able to use the twitter. No matter what I do my messages don't show. 
I'm wondering if because the name Grandma Memaw was previously used, and now I deleted her and remade her, It's having an issue with the name having been used previously?

I've tried some fixes. I've cleared my cache. - Failed to fix the issue
I've used /telfix to see if that would fix my issue - Failed to fix the issue

<h2>What do you expect should happen?</h2>

 Well I just would expect to be able to proceed to write on twitter.

<h2>Anything to support your bug report?</h2>

Please excuse the part of discord showing, I was trying to get a quick proof whilst troubleshooting with Rayuu
https://gyazo.com/8d50d130371f6be656917189225390a3

**Comment by Senlarus** [comment]
Probably because another user has the same twitter name that doesn't match your steamID.

**Comment by lAmantel** [comment]
How do I go about fixing this then because I can't change the Twitter name, ( wont let me)

**Comment by Senlarus** [comment]
Next login this should be fixed.
