### ISSUE TITLE
Getting the wrong drugs when collecting.

### ISSUE THREAD

**Issue by tirida** [New-Chance-RP/Feedback#488]
<h2>What bug have you found?</h2>

Me and my friends went to get some drugs and when I opened the package I got the wrong drug. I kept picking up a different drug then what I should've gotten and then when the person that called the drop came and collected the drugs, he got the right drug. 
(I think that the person that called it in has to be the first one to open the package, and then the other people can pick it up ).

<h2>What do you expect should happen?</h2>

For me to get the correct drug when I'm collecting it.

<h2>Anything to support your bug report?</h2>

I have got a video that shows this however I don't want to post it in here so people don't metagame it. If you would like the video then DM me @ tirida#9534

**Comment by ixhal** [comment]
This is a known issue right now and is being worked on, Sorry about that and thanks for the report 👍

**Comment by bloombydee** [comment]
This has been fixed, if it happens again please open a ticket
