### ISSUE TITLE
Forced first person when using weapons

### ISSUE THREAD

**Issue by Real50BMG** [New-Chance-RP/Feedback#49]
<h2>What is your feature request?</h2>

Disabling being able to use weapons (guns) from third person. Even in cars. (Not sure if this is even possible, just an idea)

<h2>What are the benefits of your idea?</h2>

Makes the accusation of crosshair use invalid since the person has to use the sights of the actual gun. This makes handling guns harder and will slow down the combat. 

<h2>Anything to support your idea?</h2>

*DELETE THIS LINE Is there anything you can add which will help sell your idea, pictures, diagrams etc?*

**Comment by Senlarus** [comment]
Decided against this.
