### ISSUE TITLE
Stolen Vehicles going poof at certain locations

### ISSUE THREAD

**Issue by Mubbb** [New-Chance-RP/Feedback#493]
<h2>What bug have you found?</h2>

Stolen vehicles disappearing near drug pickup locations once you get out to retrieve the drugs.

<h2>What do you expect should happen?</h2>

Not have my freshly stolen vehicle go poof.

<h2>Anything to support your bug report?</h2>

I have clips available if anyone wants to DM me @ Mubb#3272 - Avoiding Metagaming etc.

**Comment by Senlarus** [comment]
FiveM OneSync cleans up non-player owned vehicles during a normal maintenance routine it uses. This is a common issue on other servers too. I know it's not ideal but we have no control over how this clean up process runs. We can consider adding stolen vehicles into our persistent vehicle system but this will have an impact on the server's performance as it will require the tracking of A LOT more vehicles. Some people steal a vehicle every time the one they just stole runs out of gas. This could mean over the course of a 12 hour server session, that we have to track and store information on 100's of vehicles that no one is going to use again. It will also mean a lot more cluttered streets as people often don't give a crap where they leave the stolen vehicle.

With everything considered we didn't see that much value in tasking the server this much for stolen cars, especially considering the cost of a cheap vehicle is something that people can easily earn in an hour on the server.

**Comment by Mubbb** [comment]
Oh that's fair enough then, I didnt realise it was an issue overall and not just here. Apologies
