### ISSUE TITLE
Typo in paycheck notification "received"

### ISSUE THREAD

**Issue by ATOM2855** [New-Chance-RP/Feedback#494]
<h2>What bug have you found?</h2>

![image](https://user-images.githubusercontent.com/65731181/92783460-b2004a80-f39d-11ea-8f28-aab71b5b0540.png)

<h2>What do you expect should happen?</h2>

Correct spelling "received" <3

**Comment by ixhal** [comment]
Will be fixed on the next server reboot, Thanks for the report
