### ISSUE TITLE
Can't store dirty money in hotel

### ISSUE THREAD

**Issue by TaxEhh** [New-Chance-RP/Feedback#495]
<h2>What bug have you found?</h2>

Unable to store dirty money after the weight/inventory limit was implemented for hotels.

<h2>What do you expect should happen?</h2>

Let me store my monies!

<h2>Anything to support your bug report?</h2>

Can show you a video if needed but simply dragging the money into my hotel inventory is not taking it off of my person.

**Comment by Senlarus** [comment]
Motels are fixed, store your nasty drug laced, blood stained, dirty money all you want now!
