### ISSUE TITLE
Vespucci PD and burger interior optimisation

### ISSUE THREAD

**Issue by adsam56** [New-Chance-RP/Feedback#497]
<h2>What bug have you found?</h2>

Not really a long explanation. Ive just found that the interiors round Vespucci PD and burger a shot are not very optimised and leave me lagging and stuttering until the interiors load in.

<h2>What do you expect should happen?</h2>

To run smoothly like the rest of the time.

<h2>Anything to support your bug report?</h2>

No, too laggy to press the record button lmao 

To add, my pc specs are a i5 8400 overclocked to 4.6 ghz, 16 gb RAM at 2400hz and a 1060 at 6gb Vram

**Comment by Senlarus** [comment]
This isn't something we have the current skillsets to do on our development team. VPD is a very large interior and is going to have an impact on your frames. It's mostly VPD as Burgershot doesn't have a lot of objects to load.

**Comment by Senlarus** [comment]
We have optimized a lot of the MLO's around the map, VPD was one of them.
