### ISSUE TITLE
Burger Shot change

### ISSUE THREAD

**Issue by ATOM2855** [New-Chance-RP/Feedback#498]
<h2>Feature you are requesting.</h2>

1. At the moment, when you are a cashier at Burger Shot, you need to pour a drink before you can serve the burger meal 'tray'. When you pour the drink - one drink goes into your inventory. When you serve the burger, the drink disappears from your inventory but does not go to the player who picks up the burger tray. So if they actually want a drink you have to repour the drink! Enable you to give the drink without it disappearing when you give the burger tray.

2. Also, we had a queue today of 6 people. All of the burgers were cooked. It would be great if the chef could also help to serve drinks and burger trays! 

Hope this makes sense!<3

**Comment by Senlarus** [comment]
Fixed! Thanks for the report. Also, based on negative Yelp reviews Burgershot carries ECola now!
