### ISSUE TITLE
Ability to test drive vehicles before buying

### ISSUE THREAD

**Issue by Real50BMG** [New-Chance-RP/Feedback#50]
<h2>What is your feature request?</h2>

Test driving vehicles from the vehicledealers.

<h2>What are the benefits of your idea?</h2>

This is just a convenient thing to have so players don’t have to waste money just to try a vehicle that they might want. Maybe even having a car dealership being controlled by a player would be something cool to have. Whoever would be balancing cars would be a good person to maybe run a cardealership

<h2>Anything to support your idea?</h2>

*DELETE THIS LINE Is there anything you can add which will help sell your idea, pictures, diagrams etc?*

**Comment by ixhal** [comment]
Will be looked into in the future, The only reason we don't want that right now is because it would get abused heavily when we find a better system this will be a feature
