### ISSUE TITLE
Motel/Hotel Storage

### ISSUE THREAD

**Issue by SuperCShe** [New-Chance-RP/Feedback#500]
<h2>What bug have you found?</h2>

With the new storage limits on the hotels/motels, things now disappear completely as you're placing items from your pockets to the storage. It says it accepts the items but they literally disappear to the void and don't exist anywhere. I lost items doing this not realizing they weren't being placed into storage.

<h2>What do you expect should happen?</h2>

If you're putting something into storage and it exceeds the limit, it should simply tell you the storage is full and cannot accept your item(s) rather than eat the item(s).

<h2>Anything to support your bug report?</h2>

https://clips.twitch.tv/SpinelessAmericanShallotShazBotstix

**Comment by TaxEhh** [comment]
Can vouch, hotels are buggy.  Can't store any dirty money still d:^)

**Comment by Senlarus** [comment]
Motels are fixed, store your nasty drug laced, blood stained, dirty money all you want now!
