### ISSUE TITLE
Drug System Improvements

### ISSUE THREAD

**Issue by Mubbb** [New-Chance-RP/Feedback#501]
<h2>Feature you are requesting.</h2>

_I just want to start by saying these are mainly 'quality of life' improvements & hopefully tagged properly_

- **Bigger varying of prices depending on the drug (possibly even difficulty creating the 'harder' drugs, making the price increase a tad more logical**)
- **Sale speed slightly increased, or rejection chance lowered.**
- **Contracts being single use, thus creating more of a demand for both drugs and contracts(this also goes back to the price changes) + increasing player to player sales + adding more roleplay opportunities**
- **snorting cocaine rather than 'smoking crack' (unless changes are made so that crafted + bagged cocaine actually becomes crack cocaine in your inventory)**
- **The prompt to sell drugs to locals seems delayed between sales. I'm not sure if this is a bug or a timer/feature)**
- **this is probably a more controversial one but drug 'sizes' being smaller for better storage.** 

<h2>What are the benefits to your feature?</h2>

+roleplay
+slight variation in the whole drug system
+stuff

<h2>Anything to support your feature request?</h2>

drugs xx

**Comment by HimWhoRobs** [comment]
I feel currently the drug system is not worth the risk / reward + the time investment. I feel like Meth should give you armour for longer as it seemed to be pretty short when doing a heist for example. Currently meth and coke are very very similar and this should change. Give people a reason to choose whichever weather it be sell price or the use it gives

**Comment by Zopfco** [comment]
> * **Contracts being single use, thus creating more of a demand for both drugs and contracts(this also goes back to the price > 
> changes) + increasing player to player sales + adding more roleplay opportunities**

It might be fun if some of these came through prison contacts

**Comment by Senlarus** [comment]
We have long terms plans for drugs and will be making changes over time to enhance and layer the system.
