### ISSUE TITLE
Shorter Respawn Time

### ISSUE THREAD

**Issue by realshonn** [New-Chance-RP/Feedback#503]
I think that the current respawn time of 10 minutes is just too much. I understand why its in place but I honestly think that 5 minutes is a better alternative to 10 minutes due to the fact that its still enough time for them to wait and it doesn't last as long as maybe a jail sentence.

**Comment by staxstefan** [comment]
@realshonn Please assign an "Enhancement" label to this issue. Just so we can properly categorize issues. 

Also, ehm 10 minutes may be long, what possibly could be better is Paramedics having an option to set what is the individual being ICUed for? Quick menu, if it's gunshot, stabbing it should be 10 minutes, if it's let's say regular fall or minor accident then it would be 5 minutes. If you can develop a chart when should be what that would be awesome and then categorize it as "Feature Request"

**Comment by Senlarus** [comment]
Enhancements to the medical/death system will be coming but not for a while. Until then no major changes will be made. Look for more updates on this as we knock out items on our current roadmap!
