### ISSUE TITLE
trash job pick up zone next to pd 

### ISSUE THREAD

**Issue by rulefocus2742** [New-Chance-RP/Feedback#504]
<h2>the red marker hasn't shown up for the trash job  ?</h2>
clocked on as trash and come to my first pick up and the red marker to get the bags has not shown up and i cant complete my job as this is the first one
![Screenshot (151)](https://user-images.githubusercontent.com/68706453/93366593-4b6aa900-f843-11ea-85b0-15c28c7a4cf8.png)

<h2>What do you expect should happen?</h2>

*DELETE THIS LINE - What do you think should happen, what is the intended outcome that you are currently not getting?*

<h2>Anything to support your bug report?</h2>

*DELETE THIS LINE - Have you got any evidence to help prove the bug, a video or picture etc?*

**Comment by Senlarus** [comment]
Fixed
