### ISSUE TITLE
Fishing Negatively Affects Daily Life?

### ISSUE THREAD

**Issue by SuperCShe** [New-Chance-RP/Feedback#505]
<h2>What bug have you found?</h2>

Anytime you go out fishing, you become permanently incapable of wearing seat belts, accessing your weapons/gas cans/anything else on your Tab wheel, unable to point, and unable to punch until you fly out again.

<h2>What do you expect should happen?</h2>

Fishing should not negatively impact any other function.

The thought process is that what causes it is when you accidentally pull out a gun/gas can/etc. while you're fishing because of the keybinds you have set to use during the catch process. What I mean is, if you're slightly late to press your 6 button, you pull out your pistol and cannot put it away until you allow the fishing rod to disappear again. Once you've done this, we believe that affects the coding for all of those other features mention as they disable.

<h2>Anything to support your bug report?</h2>

You can see it on any of my fishing stream.

**Comment by Senlarus** [comment]
Resolved
