### ISSUE TITLE
Working Wheelchairs

### ISSUE THREAD

**Issue by realshonn** [New-Chance-RP/Feedback#506]
<h2>Working wheelchairs that you can push yourself or be pushed by a friend around the city for immersive RP.</h2>

The actual script itself is in this link [Wheelchair](https://forum.cfx.re/t/release-qalle-wheelchair-wheelchair-for-ems-standalone/196625)
It is a working wheelchair that works just like the esx-chairs script. You spawn it in with /wheelchair and there should be an option that says "Press E to sit" from there you are able to wheel yourself around or have someone come from behind and take control of the wheelchair.

<h2>Immersive RP, funny scenarios, and double the outcomes of certain scenarios.</h2>

The positive effects are that for people who are into carrying out RP for more than 10 minutes it will add a new fun prop for RP. Some other things are it can add for some funny RP or some serious character development. The only negatives I see are it possibly loading up the server scripts even more and possibly adding a bug or 2.

<h2>Anything to support your feature request?</h2>

![image](https://user-images.githubusercontent.com/47696673/93536539-3bbc9480-f917-11ea-88b3-b1a0692faa46.png)

**Comment by Senlarus** [comment]
That wheelchair is not a working script sadly. We have tried it, twice.

**Comment by Senlarus** [comment]
oh, but we have a mobility scooter that will be added soon to accommodate this line of RP. I hope you enjoy it when it comes out soon!
