### ISSUE TITLE
LSPD F2 Menu Coop Issue 

### ISSUE THREAD

**Issue by BIRLZ95** [New-Chance-RP/Feedback#507]
<h2>What bug have you found?</h2>

Unable to put someone in your vehicle when carrying them using the F2 coop menu, It says no seats available. 
Only tried this with the Tahoe LSPD vehicle. The person I was carrying was downed also.

<h2>What do you expect should happen?</h2>

Able to place them in the vehicle and /carry them out etc.

<h2>Anything to support your bug report?</h2>

Nope.

**Comment by Senlarus** [comment]
I think this has been fixed, yes?

**Comment by BIRLZ95** [comment]
Yep!
