### ISSUE TITLE
Weazel News Door is Broke

### ISSUE THREAD

**Issue by GamerDaniel18** [New-Chance-RP/Feedback#508]
<h2>What bug have you found?</h2>

The left-hand side door of the Weazel News building has no collision mesh, allowing for people to walk into the office even when all doors are locked.

<h2>What should happen?</h2>

It should be a solid beam, preventing people from getting in.

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/50466883/93570944-aa3b3a00-f98b-11ea-9438-fd74918f473f.png)

**Comment by Senlarus** [comment]
I can't fix that, but I can see if we can put an immovable object outside to prevent it.

**Comment by Senlarus** [comment]
This was been fixed by cnrr!
