### ISSUE TITLE
Menus / Inventories Getting Stuck.

### ISSUE THREAD

**Issue by SirLyx** [New-Chance-RP/Feedback#510]
<h2>What bug have you found?</h2>

The inventory getting stuck when trying to search people with the new F5 people menu.

<h2>What do you expect should happen?</h2>

For the F5 menu to disappear before the inventory opens so it doesn't get stuck.

<h2>Anything to support your bug report?</h2>

I will try to get a video of it when I'm clocked on.

**Comment by staxstefan** [comment]
I believe this video shows the issue. 
Tell me if you can not view it. 

Link: https://discord.com/channels/@me/731933512013185044/756535215740026883

**Comment by ixhal** [comment]
This issue has been fixed.
