### ISSUE TITLE
No DMG scuba gear

### ISSUE THREAD

**Issue by BIRLZ95** [New-Chance-RP/Feedback#511]
<h2>What bug have you found?</h2>

While wearing the scuba gear you take no damage if shot in the back on the tanks or head.

<h2>What do you expect should happen?</h2>

Take DMG when being shot while wearing scuba gear, even expolde?

<h2>Anything to support your bug report?</h2>

Can provide a clip if need be. bit short on time atm

**Comment by ixhal** [comment]
This should be fixed on the next reboot but it wont explode
