### ISSUE TITLE
Screen Glitch When Respawn

### ISSUE THREAD

**Issue by realshonn** [New-Chance-RP/Feedback#512]
<h2>When you respawn your screen stays black and white and kind of blurry and does not go away until you relog.</h2>

*Basically you just have to go down and wait to respawn and once you do you will have a black and white screen effect kind of similar to when you die.*

<h2>For your screen to go back to normal</h2>

*I think that you should not have this effect on your screen but that your screen should go back to normal instead of the black and white "wasted" filter.*

<h2>Anything to support your bug report?</h2>

*No*

**Comment by ixhal** [comment]
This will be fixed on the next server reboot, Thanks for the report
