### ISSUE TITLE
MotoMarket Issue

### ISSUE THREAD

**Issue by BIRLZ95** [New-Chance-RP/Feedback#515]
<h2>What bug have you found?</h2>

Purchased a car from the moto market I did not recieve the keys and was unable to get into it, I had to lock pick it.. then once I stored it, it was nowhere to be seen in my garages etc, see clips 

<h2>What do you expect should happen?</h2>

Recieve the keys for cars purchased at the motomarket and not be scammed :( lol

<h2>Anything to support your bug report?</h2>

https://youtu.be/T_nIlGsb1U0

https://youtu.be/I7bPv28-w8E

**Comment by Senlarus** [comment]
This has been updated to provide correct info to players.
