### ISSUE TITLE
Some French left in phone

### ISSUE THREAD

**Issue by jimmydesilva** [New-Chance-RP/Feedback#516]
<h2>What bug have you found?</h2>

There is some French left in gcphone.

<h2>What do you expect should happen?</h2>

Text should be in English.

<h2>Anything to support your bug report?</h2>

From experience I know that you probably shouldn't look for it in gcphone's locales, but rather the client.lua. Under any received messages or calls you'll see the remaining French text. Search for those in that file and you should be able to find and translate it.

If you need help with the translations, poke me on Discord (same name).

**Comment by ixhal** [comment]
Avez-vous changé la langue du téléphone en anglais dans les paramètres?

**Comment by jimmydesilva** [comment]
Oui, j'ai.
Yes, I have.

**Comment by jimmydesilva** [comment]
If I recall correctly, the original file had French text under the English locale in this config.json file. If this is the case on your end as well, see the image for correct translations.

File location: gcphone\html\static\config\config.json

![image](https://user-images.githubusercontent.com/16627486/93843702-06a79d80-fc9b-11ea-9676-c3761905cac5.png)

**Comment by jimmydesilva** [comment]
I tried reproducing the issue, but I can't, so I might've done an oopsie.

Closing this issue.
