### ISSUE TITLE
Store Robbery Cooldown

### ISSUE THREAD

**Issue by SirLyx** [New-Chance-RP/Feedback#517]
<h2>Feature you are requesting.</h2>

I, and a lot of people would really appreciate at least a 10 minutes cooldown on store robberies.

<h2>What are the benefits to your feature?</h2>

Almost everyday I clock in PD. We get a 10-90 after a 10-90 without no stop. The same people going around and robbing stores all around the mop. It's unrealistic and abusive.

<h2>Anything to support your feature request?</h2>

PD would agree.

**Comment by Senlarus** [comment]
Stores are a low level crime... it's like a smash and grab and doesn't make people that much money. I have heard a lot of PD do not like getting these alerts this often so perhaps we can change it from a 10-90 and lower its sense of urgency by doing so. Maybe we can even add in a chance so PD isn't even notified.

**Comment by Senlarus** [comment]
Oh, I should add that each store has it own cooldown so 1 location cannot be chain robbed. But yes, they can travel around the map and hit them all currently. Could also change it so the player themselves gets a cooldown too.

**Comment by Zopfco** [comment]
In addition to these suggestions maybe some of the factors could be randomized, such as the amount of time required?  Diminishing returns would also make sense given the likelihood of local stores being alerted to someone robbing them in sequence. The possibility of a pissed off a local store owner popping out of their office with a shotgun is also something to consider.

**Comment by Senlarus** [comment]
Amounts awarded are random, but not based on any logic other than chance.

**Comment by Senlarus** [comment]
Cooldowns and priority of these calls has been addressed.
