### ISSUE TITLE
Num5 hardcoded to hand-on-gun emote

### ISSUE THREAD

**Issue by Zopfco** [New-Chance-RP/Feedback#519]
<h2>What bug have you found?</h2>

Numpad 5 is set to a hand-on-gun arm pose.  If you bind a new emote it does both, but mostly hand-on-gun.

<h2>What do you expect should happen?</h2>

Key defaults unbound like the rest of numpad, or can be edited if default. 

<h2>Anything to support your bug report?</h2>

Should be easy to reproduce.  Guessing this was meant for PD?

*edit* Don't see a way to unbind emotes, can only overwrite

**Comment by Zopfco** [comment]
Saw this update:

> [NCRP-Live:master] 1 new commit
> c37c20c Holster animation changed to toggleable keybind... - ixhal

Will close this thread as soon as I can verify it's fixed for me

**Comment by ixhal** [comment]
Is this a keybind you setup with the /emotebind system we have? If so you will have to remove it, The update I did was for the caps lock holster, Hopefully it was that one and it had different keys to toggle it, Thanks for the report I will leave it open till you confirm that it works 💛

**Comment by Zopfco** [comment]
> Is this a keybind you setup with the /emotebind system we have? 

No, the holster emote was hardbound to a numpad key.  Now I don't think it was related to the emotebinds at all, actually.

>If so you will have to remove it

I don't think there's a way to remove emotebinds, only overwrite them.  Overwriting with no emote entered doesn't remove it.

Problem solved, closing tkt.  Thanks.
