### ISSUE TITLE
Criminal records / point system

### ISSUE THREAD

**Issue by Real50BMG** [New-Chance-RP/Feedback#52]
<h2>What is your feature request?</h2>

Pointsystem/criminal record system.

<h2>What are the benefits of your idea?</h2>

Having a criminal get out of jail with a clean slate every time is kind of weird. Having a criminal record could be a cool thing to have so cops can see what kind of criminal they are dealing with. Whether they are dealing with a big fish, or a small guppy :P. Constantly getting caught for big crimes could result in a bigger fine for the next time the criminal would get caught. (a good moneysink?)

<h2>Anything to support your idea?</h2>

*DELETE THIS LINE Is there anything you can add which will help sell your idea, pictures, diagrams etc?*

**Comment by BadBritishGamer** [comment]
I am trying to learn a CAD program based system allowing officers to do paperwork in game without tabbing out, this will then allow for us to track criminals a lot easier.

To begin with I don't think we will implement anything crazy as tabbing onto google forms constantly becomes a pain in the ass.

**Comment by Senlarus** [comment]
MDT/CAD implemented
