### ISSUE TITLE
LSPD Vehicle Change

### ISSUE THREAD

**Issue by BIRLZ95** [New-Chance-RP/Feedback#522]
<h2>What are you requesting?</h2>

**3) - Vehicle changes -** Improve wheel traction [Crown Victoria] 

<h2>Why are you making this request?</h2>

Crown Vic just wheel spins far too much, kinda annoying when your patrolling around and everytime you have to stop for a traffic light etc you do a 5 second burnout before moving.

<h2>Anything to support the above?</h2>

Just my personal experience.

**Comment by Senlarus** [comment]
Please run these changes through the department leads. (Not arguing with you, but we want to follow a process here.)
