### ISSUE TITLE
Adder vs Nero????

### ISSUE THREAD

**Issue by MorganJames01** [New-Chance-RP/Feedback#525]
<h2>What are you requesting?- The Adder now costs 620k which i agree is alot better but the Nero is only 340k i think this should be changed to be more balanced to the price of the adder because the Adder is the Veyron and the Nero is the Chiron and the Chiron should not be half the price of a Veyron</h2>

<h2>Why are you making this request?- Because i feel it is a bit strange that a Veyron is almost double the price of a Chiron</h2>

<h2>Anything to support the above?Just another thing to add, i dont expect the cars to be priced like they are in real life but i just think that the Nero is a more premium version so it deserves a higher price. It used to be 250k for the adder and 340k for the Nero and i think that was 'better' but 620k suits the adder more and i think the nero should be buffed a bit in price</h2>

*DELETE THIS LINE - If you have any pictures or videos to help with the above*
https://cdn.discordapp.com/attachments/702225764380049451/759805179301855232/unknown.png
https://cdn.discordapp.com/attachments/702225764380049451/759805343584092160/unknown.png

**Comment by Senlarus** [comment]
Done
