### ISSUE TITLE
Empty cabs at taxi depot

### ISSUE THREAD

**Issue by Aussmeister** [New-Chance-RP/Feedback#526]
<h2>What bug have you found?</h2>

Too many empty cabs from staff finishing their roster then either not knowing how to store the cab or cbf. When a new cab is booked out its stuffed from trying to navigate it out of parking lot. Would also improve fps from less collisions.

<h2>What do you expect should happen?</h2>

Swap the de-spawn points, put the taxi despawn point (red) where the players car despawn point is now, and put the green car spawn point in front of the garage door on the pavement. When staff arrive for work they store car at garage door, on return drives taxi into front yard books it in.

<h2>Anything to support your bug report?</h2>

I will provide pics.

**Comment by jimmydesilva** [comment]
Another option would be to add a line of text to the notification that tells you what parking bay your cab is in, telling you you can bring it back around the corner. I also liked your idea (which we discussed outside of this issue) to reward a small amount of money for returning the car, so players have an incentive to do so.

**Comment by Aussmeister** [comment]
![cabs](https://user-images.githubusercontent.com/72024839/94502083-b0140380-0246-11eb-8575-f7804b1e394a.JPG)

**Comment by Aussmeister** [comment]
thats's after a few hours.

**Comment by Senlarus** [comment]
We got some new talent looking into it for us :)

**Comment by Senlarus** [comment]
Right @jimmydesilva ?

**Comment by jimmydesilva** [comment]
Hoping to live up to the expectations!

**Comment by Senlarus** [comment]
Fixed
