### ISSUE TITLE
Little Seol Ammunation MLO Issues

### ISSUE THREAD

**Issue by GamerDaniel18** [New-Chance-RP/Feedback#527]
<h2>What bug have you found?</h2>

The gun store has a different MLO that is a bit messy, the doors are jank and it looks like it sells jewelry but the menu sells guns.

<h2>What do you expect should happen?</h2>

I think maybe remove it IDK, I just wanted to let you know its a bit whack.

<h2>Anything to support your bug report?</h2>

*DELETE THIS LINE - Have you got any evidence to help prove the bug, a video or picture etc?*
![image](https://user-images.githubusercontent.com/50466883/94810853-7e3ca180-03ec-11eb-8ec2-87874d77fd0f.png)
![image](https://user-images.githubusercontent.com/50466883/94810926-9d3b3380-03ec-11eb-8223-8e7e2d699d21.png)
![image](https://user-images.githubusercontent.com/50466883/94810994-af1cd680-03ec-11eb-9b02-60b94554ca7c.png)
![image](https://user-images.githubusercontent.com/50466883/94811207-f6a36280-03ec-11eb-92fb-4cf3cd8da82e.png)

**Comment by Senlarus** [comment]
Bug... or feature? Hrm....

**Comment by Senlarus** [comment]
lol I didn't know about this, I'll have a look.

**Comment by Senlarus** [comment]
Should be fixed now
