### ISSUE TITLE
Trophy Truck 

### ISSUE THREAD

**Issue by greed702** [New-Chance-RP/Feedback#529]
**3) - Vehicle changes -** *What changes you want think should be made.*

<h2>Why are you making this request?</h2>

 The Trophy Truck is very slow for what it is. Unable to modify other than cosmetics. Could be more beneficial for RP for it to be a little more realistic 

<h2>Anything to support the above?</h2>

**Comment by MorganJames01** [comment]
What do you mean by ‘other than cosmetics’ what can’t you get? Any bodywork modification options that are not there can not be added because it is a GTA vehicle and if the GTA vehicle has no bodywork on GTA then it won’t have it here

**Comment by greed702** [comment]
I was informed my LS Customs they are unable to modify the vehicle other than cosmetics (paint and badges ect) cannot do work on engine to enhance performance.

**Comment by Mubbb** [comment]
You can definitely upgrade the trophy truck performance.

**Comment by Zopfco** [comment]
> I was informed my LS Customs they are unable to modify the vehicle other than cosmetics (paint and badges ect) cannot do work on engine to enhance performance.

My guess would be that the particular mechanic you spoke to was not able to do the work due to job rank.

**Comment by greed702** [comment]
Ah, figured it was pretty odd. But thanks for the info.

**Comment by driftoooo** [comment]
Handling of the Trophy Truck has been added to my list. It'll be pushed once I've finished with my current assignment. In regards to body modifications, the base GTA model does not feature any body modifications as far as I'm aware, and in regards to the Performance upgrades, upgrades for performance will be available depending on the mechanic's ranks.

Thanks again!
