### ISSUE TITLE
Cleaning Item Label Problem

### ISSUE THREAD

**Issue by GamerDaniel18** [New-Chance-RP/Feedback#530]
<h2>What bug have you found?</h2>

The cleaning item has the wrong name in stores/inventories. It is labeled 'binoculars' at the moment

<h2>What do you expect should happen?</h2>

I think the text should be changed to 'cleaning supplies'.

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/50466883/94924570-ae9c4280-04b5-11eb-99cd-a30f1b89e2f6.png)
![image](https://user-images.githubusercontent.com/50466883/94924598-bbb93180-04b5-11eb-9fff-3e2cb2a2da28.png)

**Comment by ixhal** [comment]
This issue should now have been fixed, Thanks <3
