### ISSUE TITLE
Raiden (tesla)

### ISSUE THREAD

**Issue by s1Sabz** [New-Chance-RP/Feedback#532]
**3) - Vehicle changes- I think the Raiden is a bit slow (capped at 110mph) considering it costs $72,000 and could be buffed or given tuning options
I think it would help the server because maybe more people will buy the car as right now it isn't too viable
I completely understand that this isn't a top priority for the server and there are more important issues that might exist, it's just a bit frustrating is all.

**Comment by MorganJames01** [comment]
Hey, the Raiden. I understand where you are coming from and we have re-handled the Raided already and made it different. The handling pushes are available and will be pushed into the server some time soon. Thank you for the feedback

**Comment by s1Sabz** [comment]
so you most likely aren't going to buff the top speed

**Comment by driftoooo** [comment]
> so you most likely aren't going to buff the top speed

The upcoming handling changes to the Raiden include but are not limited to the following: Acceleration, Braking, Flat-Land-Vehicular maximum velocity, Suspension set up, and traction.

**Comment by driftoooo** [comment]
Closing the issue, Raiden has received a buff already.
