### ISSUE TITLE
Healing Improvements

### ISSUE THREAD

**Issue by Tekoro** [New-Chance-RP/Feedback#533]
**<h2>Feature you are requesting.</h2>**

Modify the way that healing works through bandages.

**<h2>What are the benefits to your feature?</h2>**

As it stands bandages instantly heal you about 1/3 of your HP pool, while in a RP scenario this does not concern anyone.
I was thinking however that whenever there will inevitably be shootouts between gangs, police etc., it would be extremely easy to just heal yourself with a quick press of your inventory button and a bandage heal.

**<h2>Anything to support your feature request?</h2>**

Viable examples:

**1**- Make the usage of a bandage have an animation and casting time || INSTANT HEALING, ANIMATION AND TIME
**2**- Make the healing received from a bandage a **heal over time** || HEAL OVER TIME, INSTANT USAGE

**Comment by Senlarus** [comment]
Done
