### ISSUE TITLE
Increase Criminal Payout

### ISSUE THREAD

**Issue by BillChirico** [New-Chance-RP/Feedback#534]
<h2>Feature you are requesting.</h2>

At this moment in time by far the best way to make money is to have a whitelisted job. I would really like to see an increase in criminal activity payouts. (Don't want to go into detail to spoil anything, but feel free to DM me to discuss further)

<h2>What are the benefits to your feature?</h2>

Positives: More crime for more cop interaction and to balance out whitelisted jobs payout versus criminal activity

<h2>Anything to support your feature request?</h2>

For example, store robberies are almost not worth doing because of the small payout.

**Comment by BillChirico** [comment]
To help even more with cop interaction while selling drugs, the more cops online the higher payout

**Comment by Senlarus** [comment]
This was denied in discussions with the admin team.
