### ISSUE TITLE
Leaving the server not clocking you out from a job

### ISSUE THREAD

**Issue by Tekoro** [New-Chance-RP/Feedback#535]
<h2>What bug have you found?</h2>

Currently when a player leaves the server while being still **clocked in** a job, be it whitelisted or public, they are going to not be clocked out automatically as it probably should, this is not much of a problem for WL jobs or Taxi etc., but for Burger Shot it actually takes up the limited slot, for example.

<h2>What do you expect should happen?</h2>

Player leaving the server is automatically clocked out and when they re-join they will be in their casual clothing + not in any job.

<h2>Anything to support your bug report?</h2>

N/A, easily reproducible, just clock in a job, leave and rejoin

**Comment by Senlarus** [comment]
This is by design. Clock out before logging out if you don't want to be clocked in upon login.
