### ISSUE TITLE
Shelby Mustang Changes

### ISSUE THREAD

**Issue by stxrmd** [New-Chance-RP/Feedback#537]
<h2>What are you requesting?</h2>
I am requesting that the new Shelby Mustang be reviewed for its overall performance. The speed of the car caps out at 105 mph, with a supercharged V8 engine I believe this car should go a lot faster than 105mph. My buddy's Youga Classic (a van from the 1970s) can go faster than my high horsepower muscle car that almost cost 200k. There are new imports that just got put in and go double the speed of the Mustang, and they should have similar, if not worse, performance to the Mustang. A car of this stature could go well over 200 mph. I believe the car should be buffed in the speed aspect. I think the best way to balance this car is to increase the speed.

<h2>Why are you making this request?</h2>
I am making this request to maybe fix a car that is broken at the moment, at least to me. It has problems with speed, and I believe the car is not balanced.

<h2>Anything to support the above?</h2>
I went around the city asking how fast people's cars are and testing them. I found that most car, even "old" cars from Vapid Motorsports, were able to hit a greater top speed than my fully upgraded Shelby Mustang. A Youga Classic can go faster than the Mustang, and I believe that this is a major problem. Multiple imported cars can reach more than double my Mustang's speed.

**Comment by Senlarus** [comment]
It was adjusted and will eventually be made more unique.
