### ISSUE TITLE
Carrying someone duplicates vehicle from garage

### ISSUE THREAD

**Issue by TaxEhh** [New-Chance-RP/Feedback#538]
<h2>What bug have you found?</h2>

If you are carrying someone and try to access a garage to pull out a vehicle it will duplicate the vehicle.

<h2>What do you expect should happen?</h2>

Should only pull out one vehicle that you actually own.

<h2>Anything to support your bug report?</h2>

None at this time.

**Comment by Senlarus** [comment]
This is not longer happening.
