### ISSUE TITLE
Being able to sell vehicles to other players

### ISSUE THREAD

**Issue by Real50BMG** [New-Chance-RP/Feedback#54]
<h2>What is your feature request?</h2>

Players being able to sell their vehicles to another player.

<h2>What are the benefits of your idea?</h2>

This keeps vehicles in the server, rather than dissapearing. This would tie in nicely with the more exclusive vehicles being a limited item for example

<h2>Anything to support your idea?</h2>

*DELETE THIS LINE Is there anything you can add which will help sell your idea, pictures, diagrams etc?*

**Comment by Senlarus** [comment]
Added, check out Motor Market for arranging car sales to other players.
