### ISSUE TITLE
Mitsubishi Evo Handling Changes

### ISSUE THREAD

**Issue by Mubbb** [New-Chance-RP/Feedback#541]
<h2>What are you requesting?</h2>

Evo import handling changes

<h2>Why are you making this request?</h2>

Because its awful in its current state (no offense to anyone making these handling lines)

Needs less counter steer and a lot more initial traction. Probably making it feel less heavy as well but that could probably be personal taste.
 
<h2>Anything to support the above?</h2>

drive it

**Comment by driftoooo** [comment]
> ## What are you requesting?
> Evo import handling changes
> 
> ## Why are you making this request?
> Because its awful in its current state (no offense to anyone making these handling lines)
> 
> Needs less counter steer and a lot more initial traction. Probably making it feel less heavy as well but that could probably be personal taste.
> 
> ## Anything to support the above?
> drive it

Hi there, 
        At the moment, all of the new imports have been given handling of GTA equivalent cars. I’ll look into the vehicle when I have time, but for the time being the vehicle will remain using the GTA equivalent handling.meta as our main goal is to have all base GTA vehicle handling complete before we move onto custom vehicles. Sometime in the near-future, the vehicle will receive its own unique handling.meta with the cars actual characteristics in mind rather than the GTA equivalent. Hopefully this answers your question and we’re sorry for any inconvenience this may cause :)

**Comment by Mubbb** [comment]
Ahhh thats understandable, I had it in mind that you guys made custom handling for all the imports before moving onto the rest of the GTA cars. 
Thanks for the fast reply & again, i hope it didnt come across dickish
