### ISSUE TITLE
Tempesta top speed

### ISSUE THREAD

**Issue by JSharkey123** [New-Chance-RP/Feedback#542]
I have just purchased the tempesta. The car is fully tuned and the overall top speed is 155mph. This car is a super car and it is worth 110K stock. My old sports car was around half the price and the top speed was significantly better. I hope that you take this advice and increase the top speed of the tempesta. Thank you.

**Comment by driftoooo** [comment]
Hi there, 
     I understand your frustration regarding the vehicle in question, it'll be looked into in due course. Not all vehicles have been looked into as it's a WIP. Hopefully this answers your question :)

**Comment by driftoooo** [comment]
Recent handling updates have fixed this vehicle. Any further issues feel free to make another feedback. Thanks again!
