### ISSUE TITLE
Medium-low range vehicles

### ISSUE THREAD

**Issue by Xerothis** [New-Chance-RP/Feedback#544]
<h2>What are you requesting?</h2>

In this thread, I am suggesting the following vehicles to be imported in the city, and I do strongly believe that they would make a great add-on as to improve RP amongst people who would like to RP they characters as "regular Joe's (and of course, Joesettes), or just people who are looking for a cheaper alternative when buying a vehicle, since the only imported vehicles at the moment, although amazing, are quite pricey, and with the latest boost of new people joining the server, I feel those people (including myself) would appreciate those kind of vehicles, especially the cheap ones for a nice starter vehicle. Also, I am including a couple of "fun" vehicles in this thread, as they would bring joy to some people. From what I've seen, these mods are high quality and have been downloaded many times, so that shows their overall quality. I hope you will take in consideration at least some vehicles that I've listed, would hope to see some in the future :-)

**1) - Vehicle addition -** *https://www.gta5-mods.com/vehicles/1998-daewoo-fso-tico-sx-add-on-tuning, 
https://www.gta5-mods.com/vehicles/2006-volkswagen-golf-gti-v, 
https://www.gta5-mods.com/vehicles/niva-urban-2016, 
https://www.gta5-mods.com/vehicles/fiat-toro-2017, 
https://www.gta5-mods.com/vehicles/volkswagen-beetle-1963, 
https://www.gta5-mods.com/vehicles/alfa-romeo-stelvio-quadrifoglio-2018-add-on, 
https://www.gta5-mods.com/vehicles/kia-sportage-2017, 
https://www.gta5-mods.com/vehicles/2016-nissan-qashqai-add-on-hq, 
https://www.gta5-mods.com/vehicles/toyota-camry-2016, 
https://www.gta5-mods.com/vehicles/2017-chevrolet-silverado-ltz-1500-add-on-replace, 
https://www.gta5-mods.com/vehicles/fiat-600-seat-600-zastava-750-add-on-suicide-doors-tuning-parts, 
https://www.gta5-mods.com/vehicles/2015-chevrolet-malebu, 
https://www.gta5-mods.com/vehicles/1998-ford-crown-victoria-civilian-sedan
https://www.gta5-mods.com/vehicles/opel-astra-j-add-on
https://www.gta5-mods.com/vehicles/mercedes-benz-s600-w140
https://www.gta5-mods.com/vehicles/1956-bmw-isetta-300
https://www.gta5-mods.com/vehicles/bmw-750i-e38-add-on-replace
https://www.gta5-mods.com/vehicles/1999-audi-4-avant
https://www.gta5-mods.com/vehicles/1983-dodge-diplomat-replace
https://www.gta5-mods.com/vehicles/1980-ford-bronco
https://www.gta5-mods.com/vehicles/suzuki-swift-add-on-remplace*
**2) - Vehicle removal -** *-*
**3) - Vehicle changes -** *-.*

<h2>Why are you making this request?</h2>

*I think I've said everything in the first paragraph my general thoughts, so I think there is nothing to add. I know that the list is long, but I feel these would be great add ons to the server (at least some of them) to enjoy a more mid range section of vehicles and a couple budget ones :-)*

<h2>Anything to support the above?</h2>

*-*

**Comment by M4R6S** [comment]
Damn, all those vehicles looks lit, would love to see them in New Chance RP
''Love Mercedes benz'' 👍

**Comment by lAmantel** [comment]
I actually like some of these options, I think it would be nice to have vehicles that aren't just suited to the "Street Racers" and more to the casual drivers.

**Comment by SuperCShe** [comment]
@Xerothis I know you’re hard pressed to get that Crown Vic. 

I like those other choices, too!

**Comment by Xerothis** [comment]
@SuperCShe oh you know it XD

**Comment by driftoooo** [comment]
Hi! Thank you for the suggestion. That is **ALOT** of vehicles! I've gone through and looked at every model you've suggested, some of the models are too low quality to be implemented, we're focusing on getting high-quality imports (Which we reduce in texture size of course). I'm unable to state to you whether or not this thread of vehicles has influenced any choices in vehicles or not. However, I can assure you that there will be cars that will meet the criteria posted above, there will also be vehicles to suit almost every price range alongside a multitude of RP-Lines that a character may take! I'm going to be closing this issue for now, however, feel free to message me directly (Driftoooo#9895) with any further questions Xerothis!

Thanks again :)
