### ISSUE TITLE
New message notification has name in wrong place

### ISSUE THREAD

**Issue by jimmydesilva** [New-Chance-RP/Feedback#546]
<h2>What bug have you found?</h2>

If you receive a new message on your phone the notification in the left-bottom of the screen will say something along the line of "Jimmy DeSilvaYou have received a new message from", instead of "You have received a new message from Jimmy DeSilva".

<h2>What do you expect should happen?</h2>

See ^.

<h2>Anything to support your bug report?</h2>

My word is my bond.

**Comment by jimmydesilva** [comment]
Exhibit A:

![image](https://user-images.githubusercontent.com/16627486/95654244-1b8b8a00-0aff-11eb-9748-3aadee6da1b6.png)

**Comment by ixhal** [comment]
This should be fixed on the next server reboot, I will leave this open till it is confirmed though, Could not test alone

**Comment by ixhal** [comment]
Issue has been fixed, Thanks again for the report <3
