### ISSUE TITLE
Repairs sometimes not charging money

### ISSUE THREAD

**Issue by jimmydesilva** [New-Chance-RP/Feedback#547]
<h2>What bug have you found?</h2>

If you don't have enough money in your bank account the vehicle will be repaired at a repair station, the notification in the left-bottom of your screen shows a negative amount and no money is taken from your bank account.

<h2>What do you expect should happen?</h2>

You should be told you don't have enough money in your bank account.

<h2>Anything to support your bug report?</h2>

Load up on cryptocoins to empty your bank account and try a repair. Don't forget to sell them again asap!

**Comment by ixhal** [comment]
This issue should be fixed now, Thanks for the report <3
