### ISSUE TITLE
Radio turns off every X minutes in car

### ISSUE THREAD

**Issue by jimmydesilva** [New-Chance-RP/Feedback#549]
<h2>What bug have you found?</h2>

While driving with the in-game radio on there's a script that seems to interfere with the radio, and turn it back off. At that moment the GPS also re-centers and zooms in or out. Not sure what that has to do with it, but hopefully mentioning it helps somehow. I know it happens a lot when driving a taxi. Not sure about personal vehicles, or if it has to do with the taxi job.

<h2>What do you expect should happen?</h2>

Radio shouldn't automatically turn off every few minutes.

<h2>Anything to support your bug report?</h2>

Other people have confirmed to me they have this as well.

**Comment by ixhal** [comment]
I can't say this has happened to me the only time my radio turns off is from going to fuel my vehicle with my radio open at the same time, I will keep a eye out and see if I notice anything that could cause this, Thanks for the report <3

**Comment by Senlarus** [comment]
Not happening to me either. Maybe a fluke?
