### ISSUE TITLE
Online Servers in Discord Status

### ISSUE THREAD

**Issue by BillChirico** [New-Chance-RP/Feedback#551]
<h2>Feature you are requesting.</h2>

As for how many players we have in the city as shown by the status bot it would be nice to play what services and how many are online.

<h2>What are the benefits to your feature?</h2>

Easier for people to see the services online and may entice them to clock in

**Comment by Zopfco** [comment]
"TAB" key should bring this up for you?

**Comment by BillChirico** [comment]
I'm talking about in the Discord status channel. Maybe have a section at the top with services.

![image](https://user-images.githubusercontent.com/13951316/95686217-7fc75000-0bca-11eb-9fe3-5d364ecb80bc.png)

**Comment by Senlarus** [comment]
No
