### ISSUE TITLE
WHITELIST

### ISSUE THREAD

**Issue by cNRR92** [New-Chance-RP/Feedback#552]
<h2>Feature you are requesting.</h2>

Ok first off i know people hate the thought of the server going whitelisted but at this current time it is perfect to make this move, we are currently under attack from hackers everyday and i am worried its going to get to the point of people getting disheartened and not wanting to be a part anymore, i know the is things in the works to stop this but we need to think about right now and if we moved to whitelist not any tom dick and harry could join for a kick. also we can accept the people we want in the city and with that it will higher the RP in the city.

<h2>What are the benefits to your feature?</h2>

 1- Hackers will be reduced by 90% + 
 2- the level of rp will be higher since we will choose the people we want in the city
 3- the people in the city will care more and have more respect since they made the effort to apply 
 4- the apps can be reviewed by Helpers and then moved over in the trello or what ever website needed for a final review by mods for acceptance so its not high demanding on staff

**Comment by Zopfco** [comment]
> ## Feature you are requesting.
> Ok first off i know people hate the thought of the server going whitelisted

Not me,  look forward to it.  Not sure the population is there yet consistently? The s-tier crim RP are exposing things that need fixed. They help out too despite themselves and will weed themselves out in the process.  Record if you can & report ID's.  Think we'll need to do that even with the WL as pop grows, admins can't be everywhere.

**Comment by Senlarus** [comment]
Done
