### ISSUE TITLE
New Motel

### ISSUE THREAD

**Issue by wavyplays** [New-Chance-RP/Feedback#554]
<h2>New Motel right next to Mosley's auto and Grove Street.</h2>

*Describe in good detail the feature you wish to have implemented, the more detail the better.*
 I wish to have this apartment/motel complex turned into a motel for players to live in. Apartments/trailers out in Sandy or other locations are 60k+ and I feel like we need more affordable housing.
<h2>What are the benefits to your feature?</h2>
At the moment all motels in the city are full, maybe one or two rooms are open but besides that there is no other rooms. This would benefit a lot of people because this complex has a large amount of rooms, there are also many more complexes like this around the Grove Street area.
* Describe the positive / negative impacts your feature could have*
The positives would be more player housing, and to be honest I really don't know if there is a negative to this.

*If you have anything extra to provide, pictures or videos etc to help sell your idea put them here.*

![image](https://user-images.githubusercontent.com/71983583/95698643-05b5bc00-0c08-11eb-991b-19fbb4910d5f.png)
![image](https://user-images.githubusercontent.com/71983583/95698680-182ff580-0c08-11eb-8c14-f2fa0574876f.png)
![image](https://user-images.githubusercontent.com/71983583/95698700-22ea8a80-0c08-11eb-8602-9afa0314af39.png)
![image](https://user-images.githubusercontent.com/71983583/95698714-2d0c8900-0c08-11eb-8bb3-9bec19d20854.png)
![image](https://user-images.githubusercontent.com/71983583/95698734-38f84b00-0c08-11eb-886c-5abc4d647e08.png)
![image](https://user-images.githubusercontent.com/71983583/95698785-55948300-0c08-11eb-8665-63ab7a4318ad.png)

**Comment by Mubbb** [comment]
And on that note, players definitely need to have a limit of 1 maybe 2 motels so that any newer players actually have a place to live rather than people owning 7 because they need places to stash their coke :^)

**Comment by Zopfco** [comment]
Could the Pink Cage be reopened? Lots of rooms there but it seems to have been disabled or broken, there's no Buy/Knock option when you try the doors.

**Comment by Zopfco** [comment]
The derelict hotel next door to DTCC would be a good location if replaced with a working hotel.  It looks to be roughly the same building & footprint as Pink Cage.

DTCC draws a lot of day one players & I think would fill up quickly.

**Comment by Senlarus** [comment]
@iamrayuu is bringing us new motels with the Thiefsgiving day update!
