### ISSUE TITLE
PILLBOX ELEVATOR ISSUE

### ISSUE THREAD

**Issue by lAmantel** [New-Chance-RP/Feedback#555]
<h2>What bug have you found?</h2>

So I was bringing back three patients from Mount Chilliad via ANGEL. After we've landed I was able to carry one patient down to the infirmary. As I tried access the elevator to bring down the next patient the elevator prompt showed up, allowed me to select helipad, but then it never took me upstairs. Afterwards I wasn't able to use the elevator at all.

<h2>What do you expect should happen?</h2>

I'm hoping and I know this will get fixed easily with you guys really working hard, so I don't doubt this can be fixed.

<h2>Anything to support your bug report?</h2>

Attached below is an image which captures my F8 Menu with the error in which the elevator stopped working
![unknown](https://user-images.githubusercontent.com/62526207/95724679-a6c26800-0c44-11eb-9263-8a865871f9ea.png)

**Comment by Senlarus** [comment]
This should be fixed.
