### ISSUE TITLE
torro (lamborghini urus) bug

### ISSUE THREAD

**Issue by s1Sabz** [New-Chance-RP/Feedback#556]
there is a bug when you brake and come to a stop in the torro the car will breakdown and can't go anywhere unless you get a repair kit

I'm hoping that you guys can fix the bug

**Comment by s1Sabz** [comment]
i have an update on the toros, the first problem is it breaks down incredibly easy and the second problem is when you stop it can't go fast as in it takes off incredibly slowly and the reason (i believe) is that it randomly goes into gear 9 so it cant accelerate

**Comment by Mubbb** [comment]
The 9th gear issue is known by the vehicle fellows. I'm sure it'll be fixed in coming time. If you've had your transmission upgraded, I believe that's what it is that causes it, so for now you might wanna take that off if its causing the issue a lot

**Comment by MorganJames01** [comment]
Yes, 
If you have problems with any of the cars going into 9th gear, 9 times out of 10 you need to just remove your transmission upgrade, durability will be looked into

**Comment by driftoooo** [comment]
Complete. Will be pushed once I've completed my current project. Thanks again for the report, and sorry for the wait, I missed it from my to-do list. 

Thanks again :)
