### ISSUE TITLE
Vanilla GTA Ped Characters

### ISSUE THREAD

**Issue by Real50BMG** [New-Chance-RP/Feedback#56]
<h2>Feature you are requesting.</h2>

Having the NPC models that roam around be playable. 

<h2>What are the benefits to your feature?</h2>

There are a ton of them and some are very unique and aren't really possible to make yourself due to clothing choices, for example the hobo NPC characters have dirty and scruffy clothing which isn't obtainable through the clothing store. Also when you make a new character with the normal character customization, you can't make your character taller or smaller, nor can you make it fatter or skinnier. These are just a few of the limitation that there are.
Having these 'peds' available aswell as the normal customizable characters would allow for more variety of characters. 

<h2>Anything to support your feature request?</h2>

*DELETE THIS LINE - If you have anything extra to provide, pictures or videos etc to help sell your idea put them here.*

**Comment by ixhal** [comment]
Will be something to look into later down the line, But not right now
Cheers for the great idea
