### ISSUE TITLE
Ability to change character

### ISSUE THREAD

**Issue by shadowviper0** [New-Chance-RP/Feedback#561]
<h2>Feature you are requesting.</h2> Way to change character without leaving city

* - Describe in good detail the feature you wish to have implemented, the more detail the better.* With having this implemented, people can just go to a location to change character, instead of having to closing the game, and reopen to change characters. It would just be more simple and easier.

<h2>What are the benefits to your feature?</h2>Not having to log out, making it easier to change characters, and giving way for doa characters to change quickly.

* - Describe the positive / negative impacts your feature could have* N/A it would just enhance user friendliness

<h2>Anything to support your feature request?</h2> N/A

**Comment by Senlarus** [comment]
F8 Quit, log back in and select your new character. If there is a queue you have 3 minutes of grace time where you will keep your spot. That is plenty of time to relaunch FiveM and start loading the server resources. We have no plans with our current multicharacter system to add support for a character switching ability.
