### ISSUE TITLE
Stromburg price

### ISSUE THREAD

**Issue by MorganJames01** [New-Chance-RP/Feedback#563]
<h2>What are you requesting The price gets changed as it is only 100k and it is worth way way more than that?</h2>

**3) - Vehicle changes -** *Price change.*

<h2>Why are you making this request? Because the car can do all sorts of things, (its a submarine) and it only costs 100k and thats the price that anyone and there cat could afford</h2>

I believe this will enhance peoples experiences because there wont be random people who are in the server for the first time going round all in scuba cars which would probably cost more than its current sale place just to make

**Comment by Senlarus** [comment]
Shouldn't have been added, was removed.
