### ISSUE TITLE
Extended criminal activity

### ISSUE THREAD

**Issue by ChuckBurn** [New-Chance-RP/Feedback#565]
<h2>Multiple Features for criminals.</h2>

*Criminals selling drugs and robbing stores is fun, however can get old. Criminals are always looking for the big score. That being said,

IDEA 1: I believe implementing something like "once you have 50k dirty money you can take it to a specific location you get 30k clean cash and a random counterfeit card key for a dock container or bank." The container could hold body armor or ARs for PD. (This wound obviously need atleast a 2hour cool down between cleans.) However I feel this would inspire a group of 4 people to pool money together or inspire other solo players to save up dirty money and perhaps sell the counterfeit card key to other people in groups. 

IDEA 2: Implement an AI that you can selling 10 slabs of coke or 100bags for 15k clean cash. (Not dirty cash to avoid this being a method to gain dirty cash for IDEA 1) However the AI asks you to deliver a random stolen sports car from point A to B. (Only the person to accept deal will be given keys and the car cannot be lockpicked, this will prevent a friend from sitting on location A) Now you must get the car out of location A before the police show up. (You will not receive any money until you talk to second AI at location B. If the car reaches location B payout will be 20k total. If you fail to deliver the car. You will only receive 10k clean cash.) Police will receive a ping of the vehicle type, plate and position A as soon as you accept the deal. (This should also have atleast a 2-3 hours cool down)

IDEA 3: Similar to IDEA 2. However 40 slabs of coke or 400bags. AI will ask you to deliver a box truck containing all of the coke from his location to specific locations. Cops will be pinged of suspicious cargo location immediately. Including model and plate of vehicle. Once at delivery point you must unload 10 boxes to receive payment (payment would be 140k clean cash if all boxes are unloaded, however if you fail to unload every box you will receive nothing.)

<h2>Criminals crime build to higher payout or downfall. Police will have more variety of crime</h2>

Criminals can work slowly toward a big crime. Get body armor and guns before transportation of box truck incase of a shoot out. This would require multiple day planning before a big pay out. Police would have to utilize air1 and work more together to Identify and stop the box truck. Some negatives: multiple crimes at the same times could be difficult for PD to respond to. Possible solution: someone starts a box truck mission. All other missions are put on a 15 minutes cool down timer.

<h2>More info to support these features</h2>

I have several ideas for locations for start and finish aswell as containers to break into. Also have more possible restrictions and rules for these missions. However it is very difficult to put on paper. Please contact me on discord if you have questions. [ TooEasyBro #0652]

Thank you for your time.
   Chuck Burn

**Comment by wavyplays** [comment]
this is fucking big brain

**Comment by MorganJames01** [comment]
1. Damn bro those ideas are amazing and so much effort put into them
2. I like the first idea but think 50k would be a very low amount of money for such things, maybe make it like 200k dirty (ok maybe not this high)or else everyone and their cat will have a counterfeit card thing and therefor could use it as a method to get better weaponary which then will be sold by everyone completely exposing the police to a bad situation of new player with enhanced weaponary

**Comment by ChuckBurn** [comment]
Thank you for you feedback. I do believe I have a solution to your very valid point. Let me try and explain in a little more detail. When you get the a card it can only be used once. You have a chance to receive 1 of 8 cards. 1 for each individual bank. 1 for income PD equipment and 1 for PD seized items. The PD equipment card would give you random items. Large chance for smaller items ammo for AR or handcuffs medium chance for body armor and low chance to receive ARs. The PD seized items card would give you a chance of getting preprocessed drugs, key card, maybe even some dirty money or possibly a little of each. Let's not forget the time you spent getting the dirty money just to get the card. ( Also could make people have to wait 30minute from the time they drop the money off to be cleaned to receive the card and clean money.) Let's not forget the pressure to escape just double because  you just spent atleast 2hours preparing. I can only imagine PD would take robbery of their containers extra personal and respond with more force then a normal robbery. (The number of M4's would need to be limited to 1 per robbery max.) As far as new players finding out to soon. I think people that know about the cleaning spot with cards would be more likely to offer to trade 10k clean cash for dirty cash before giving away that location. This would both help an new player receive more then they would a normal wash. This would open more positive RP among criminals. People trading illegal items among each other.

Again thank you for your time. I look forward to more constructive criticism.

Chuck Burn

**Comment by Senlarus** [comment]
We have incorporated some of these ideas in different ways in the upcoming Thiefsgiving day patch!
