### ISSUE TITLE
Import a Chrysler 300 

### ISSUE THREAD

**Issue by jay2huncho** [New-Chance-RP/Feedback#567]
Import a Chrysler 300!

Importing a Chrysler 300 would be very unique. It is often compared to a Dodge Charger, but I think it would be very unique if you imported the 300, because I have not seen them in a lot of cities. 

![14541686483789_0a1ace-gta5-2016-01-29-22-20-26-11](https://user-images.githubusercontent.com/69692710/96805293-e7557a80-13d6-11eb-863c-fb812dfe3e5f.jpg)

**Comment by timmy-timm** [comment]
You can open anyones inventory and take there stuff no matter if they are across the map they can still open it and take stuff

**Comment by Senlarus** [comment]
@timmy-timm wha?

**Comment by driftoooo** [comment]
We have **ALOT** of import vehicles coming. Thank you for the request, I'll have a look round this particular model of vehicle, however, I cannot make any promises.

Thanks again!
