### ISSUE TITLE
the furniture UI  

### ISSUE THREAD

**Issue by rulefocus2742** [New-Chance-RP/Feedback#568]
<h2>Feature you are requesting.</h2>

well as trying to do my project house up i seen there no part to add in better walls or celling as that what im trying to put in iv looked in everything and on thing i could find was the metal wall braces witch is not that good for a house project 

well with have the fact of being able to place walls and kinda type means i can get my project RP going and start buy place that run down and need massive work done 

well i like whats in the furniture UI with everything its got just needs wall placements added 

well i think added the wall placement feature would help most people out that have run down place or holes in the walls  

![Screenshot (199)](https://user-images.githubusercontent.com/68706453/97005831-e50a3200-1536-11eb-9c9e-ab3b1525e3cf.png)
![Screenshot (200)](https://user-images.githubusercontent.com/68706453/97005836-e6d3f580-1536-11eb-8a8f-0f3f22561d0a.png)

**Comment by Senlarus** [comment]
It's furniture, not carpentry. Use pictures and other items if you wish, but this is not meant for this. You can contact D8 to list your house for sale and purchase another property but before you get money for your house you or the D8 agent will have to find a buyer.
