### ISSUE TITLE
Remove Weapon Drop

### ISSUE THREAD

**Issue by Senlarus** [New-Chance-RP/Feedback#57]
<h2>What bug have you found?</h2>

Remove Weapon Drop is not optimized

<h2>What do you expect should happen?</h2>

It should not create resource warnings for users

<h2>Anything to support your bug report?</h2>

It ticks up above 1.0 delay and creates a resource warning. Will look into optimization

**Comment by ixhal** [comment]
Put a more optimised system in place for this.
