### ISSUE TITLE
Taco Shop Remodel

### ISSUE THREAD

**Issue by Zopfco** [New-Chance-RP/Feedback#570]
<h2>Feature you are requesting.</h2>

Easy access to drive-thru window

<h2>What are the benefits to your feature?</h2>

The remodel is looking good but a working drive-thru window would be awesome.

<h2>Anything to support your feature request?</h2>

If the stove moved against the wall where the beers are stacked a worker could use that window np

More working seating would be cool too

**Comment by Senlarus** [comment]
We don't have a mapper to do this type of stuff.
