### ISSUE TITLE
T20

### ISSUE THREAD

**Issue by s1Sabz** [New-Chance-RP/Feedback#573]
I have heard a rework of the t20 might be in the works but I'm not too sure. As of right now the car cost me $240,000 and I also got it full tuned. With all of this considered I feel like the maximum speed should be a bit faster than 150mph. I am hoping that you guys can either buff it or let me know if It's happening <3

**Comment by driftoooo** [comment]
This particular vehicle has been complete already. We're just awaiting for the handling to be pushed to the live server. Hang tight! :)

**Comment by Senlarus** [comment]
Pushed
