### ISSUE TITLE
Zion Classic implemented into local dealershp

### ISSUE THREAD

**Issue by JususCrust** [New-Chance-RP/Feedback#574]
What are you requesting?
Zion Classic

**1) - Vehicle addition -https://www.gtabase.com/images/gta-5/vehicles/sports-classic/main/zion-classic.jpg

Why are you making this request?
Its a beautiful classic that I would love to have in my garage

 What improvements / benefits do you think this will have and why?
No benefits really, just to make me drive around in style

![zion-classic](https://user-images.githubusercontent.com/73196098/97216401-ae921880-17bd-11eb-81da-fd1ccd6e4325.jpg)

**Comment by Senlarus** [comment]
https://gta.fandom.com/wiki/Category:Vehicles_in_GTA_Online:_The_Diamond_Casino_%26_Resort
FiveM needs to add these cars to official support before we can put them into the server. Once they do this we will add them.
