### ISSUE TITLE
subaru

### ISSUE THREAD

**Issue by s1Sabz** [New-Chance-RP/Feedback#577]
Its basically impossible to drive as whenever you turn it flips, I can understand the constant drifting but its fully impossible to go anywhere without flipping on your back like a turtle, I understand its probably being looked at but if you just saying if you didn't know. It does need fixing asap

**Comment by s1Sabz** [comment]
just realised my english at the end was proper scuffed

**Comment by driftoooo** [comment]
The flipping issue has been fixed by using a temporary method, all F&F cars will receive correct handling once I'm finished with my current assignment.

Thanks!
