### ISSUE TITLE
selling of drugs in paleto/sandy

### ISSUE THREAD

**Issue by s1Sabz** [New-Chance-RP/Feedback#580]
I understand it might be annoying for the feds to go to sandy and paleto etc. But it makes sense to atleast be able to sell in sandy as its full of crackheads. To make it fair you could make it so you can only sell drugs like weed or maybe even meth because most people just sell coke anyway. I just feel it would make sense to be able to sell there and there is also a problem with people not allowing you to sell on their block in grove (which is understandable).

**Comment by Zopfco** [comment]
People already wait until cops are clocked off to sell, I don't see any good reason to give them a (relatively) safe zone to use for when cops are online.  

I see the appeal of having tweakers buy drugs in Sandy but unfortunately people will just use it to powergame.

Maybe if processing was riskier

**Comment by Senlarus** [comment]
I don't think this is something we will add, but we will keep this in mind as we continue to develop the illegal activities in the server.
