### ISSUE TITLE
fines

### ISSUE THREAD

**Issue by rulefocus2742** [New-Chance-RP/Feedback#582]
<h2>What bug have you found?</h2>
when a fine has been sent to a suspect its going to the bills but once the bill is paid its comes out of the pocket witch mean that can just keep going up and people will just stay in minuses on the pockets

<h2>What do you expect should happen?</h2>
really the fines need to be taken out of the bank like everything else having it sent to the pockets makes it worse for non payment having minus 100k in ur pocket that not realistic but it being moved to the bank would be the better opinion as thats what people have in life bank accounts   
<h2>Anything to support your bug report?</h2>

![2020-11-01_3](https://user-images.githubusercontent.com/68706453/97805332-58095c00-1c4d-11eb-95cb-61dd876e6e77.png)

**Comment by Senlarus** [comment]
This has been fixed
