### ISSUE TITLE
Gauntlet Classic 

### ISSUE THREAD

**Issue by wavyplays** [New-Chance-RP/Feedback#583]
<h2>What are you requesting?</h2>

Gauntlet Classic

<h2>Why are you making this request?</h2>
It is a really cool muscle car that I could see being used by a lot of people in the city.
It would benefit us because there's a lot of people that like muscle cars and the gauntlet classic is based off of the first gen dodge challenger
<h2>Anything to support the above?</h2>

[](![image](https://user-images.githubusercontent.com/71983583/97806483-6ccffa80-1c21-11eb-827c-c7544c7a4b12.png)

![image](https://user-images.githubusercontent.com/71983583/97806498-79ece980-1c21-11eb-8c97-268df6a09353.png))

**Comment by Senlarus** [comment]
https://gta.fandom.com/wiki/Category:Vehicles_in_GTA_Online:_The_Diamond_Casino_%26_Resort
FiveM needs to add the Diamond Casino cars to official support. Once they do we will add them.
