### ISSUE TITLE
Audi RS3

### ISSUE THREAD

**Issue by TheHairyPenguin** [New-Chance-RP/Feedback#585]
<h2>What are you requesting?</h2>

I'm requesting the addition of the Audi RS3
https://www.gta5-mods.com/vehicles/audi-rs3-sportback-2018-add-on-tuning

<h2>Why are you making this request?</h2>

The city has a few custom cars so far that cater towards different people but nothing sport/ business class and I think this suits that category perfectly.

<h2>Anything to support the above?</h2>

This car looks really good and well optimised in city. There are multiple bodywork options and modifications for this car to be added at LS Customs.
![unknown](https://user-images.githubusercontent.com/63511081/97833184-b0cc0980-1ccc-11eb-9405-d7c69bc099ba.png)

**Comment by Scrim0** [comment]
sexy

**Comment by Senlarus** [comment]
Soon(TM)
