### ISSUE TITLE
New Drug Selling Locations

### ISSUE THREAD

**Issue by jay2huncho** [New-Chance-RP/Feedback#587]
I think it would be cool if you could sell drugs to any local you see... But the location you sell will affect the price that you sell it for. For example, the more risker places should pay more than other less riskier places. I think this will help let people that are not in gangs, to not get taxed and robbed constantly. It will also give the cops a reason to patrol areas that are not as popular... It only makes sense to be able to sell to any local, because in real life I can offer to slang my pack to anyone, right?

**Comment by Zopfco** [comment]
I would like to see it more dynamic somehow but with the assumption that realistically, PD doesn't go "offline" or get "wiped".  Incentive pricing & high roller buyers have been ruled out.  IDK what's feasible: Supply/demand price changes, more particular buyers, maybe work the local gangs into it somehow? If there were more areas I think they should be temporarily shut down sometimes by PD presence. It'd be cool if they were a little more unique one way or another.

**Comment by Senlarus** [comment]
We hear ya, this is a difficult one to address because it ties directly into the server economy and we need to ha for with care. Closing as a no for now, but things will be added overtime to make it more interesting.
