### ISSUE TITLE
Itila GTD buff

### ISSUE THREAD

**Issue by AlFiE5738** [New-Chance-RP/Feedback#591]
The itila GTD needs a buff it slides way too much and for the price I don't think it goes quick enough it goes 150 mph and then 165-170mph when fully tuned when way cheaper cars go way quicker by like 30-40 mph

**Comment by driftoooo** [comment]
Hi there! Are you referring to the Italia GTO (Ferarri look-a-like) or the Italia GTB (McLaren look-a-like)?

**Comment by MorganJames01** [comment]
He meant the GTO

**Comment by driftoooo** [comment]
If it is the Italia GTO, then I'll take a look at it again. In my opinion, all that needs doing really is a slight buff in top speed and a little stiffer suspension. When I get time I'll go ahead and do that. Thanks for the report.

**Comment by driftoooo** [comment]
Added to the to-do list, finishing up with my current task then it'll be swiftly edited.
