### ISSUE TITLE
Chop Shop

### ISSUE THREAD

**Issue by Naisuwu** [New-Chance-RP/Feedback#592]
<h2>Feature you are requesting.</h2>A chop shop

I believe a chop shop of some sort would be interesting to bring into the server since it's a feature me and many other people have enjoyed. Ofcourse you guys can tweak it out as much as you'd like to make it balanced etc etc. Simply said, you steal a certain requested car or bike  and get it chopped at the shop for either a bit of dirty money and or even materials if you guys feel like extending it like that. Perhaps materials you could craft something with. But that's just an idea.

<h2>What are the benefits to your feature?</h2> A fun feature that isn't game changing but adds a lot to the city in a way, it's fun to go around and look for the requested car as if it's a mission of some sorts. It's risky, cause at the end of the day the cops would get notified whenever someone tries to steal a car so its a bit of an adventure too.

 - Describe the positive / negative impacts your feature could have* A fun experience, it would make people get creative about stealing the car they need. They'd have to come up with a plan of some sort to get to that chop shop safely without getting caught and they could make a bit of money (and maybe materials) A downside would be probably a lot of cars getting stolen in the city which would mean more work for the police department.

<h2>Anything to support your feature request?</h2> Just any kind of chop shop would be a great addition to the server, you guys can tweak it as much as you'd like. After all it's just an idea.

*DELETE THIS LINE - If you have anything extra to provide, pictures or videos etc to help sell your idea put them here.*

**Comment by ixhal** [comment]
This is currently in the works and we have some good ideas for it.
So keep a eye out as it should not be too far off!
We do intended to drop some others things with this so it could take a little bit of time!
Thanks for the request

**Comment by Senlarus** [comment]
Coming with Thiefsgiving day update!
