### ISSUE TITLE
Tyrus Supercar Buff

### ISSUE THREAD

**Issue by JususCrust** [New-Chance-RP/Feedback#593]
What are you requesting? 
I am requesting a buff for the Tyrus in the local dealership, it's a great looking race car but it goes as fast as a prius (115mph) I know you guys are busy with the addition of new imports so i'm making this in hope that you don't forget about the fake cars like these 👍 

**3) - Vehicle changes -** *What changes you want think should be made.*

Why are you making this request?
the Tyrus i'm sure is in need of a buff as it is very slow, i'm sure you haven't spotted this yet as I am the first in the city to own one so i'm making this so you are aware

Anything to support the above?
A video clip so show its weakness :D
https://medal.tv/clips/35986096/d1337u3z8KgI

**Comment by driftoooo** [comment]
Hi. We're aware of the issues with the Tyrus, in the next push of vehicle handling I'll ensure that it has been done, it's already been put on my list after a previous complaint. :)

**Comment by JususCrust** [comment]
> Hi. We're aware of the issues with the Tyrus, in the next push of vehicle handling I'll ensure that it has been done, it's already been put on my list after a previous complaint. :)
Okay thank you :)
