### ISSUE TITLE
LA Roads mod to be a default part of the server

### ISSUE THREAD

**Issue by BIRLZ95** [New-Chance-RP/Feedback#599]
<h2>Feature you are requesting.</h2>

LA Roads mod to be built in. Just like on No Pixel 3.0.

<h2>What are the benefits to your feature?</h2>

- Gives the map a new fresh look!
- Small to none performance loss!

<h2>Anything to support your feature request?</h2>

![image](https://user-images.githubusercontent.com/64453673/98530581-05482980-2277-11eb-96d2-34e960c162f6.png)

**Comment by BIRLZ95** [comment]
Maybe way down the line, this could be a great idea once optimizations are in full effect etc

**Comment by Senlarus** [comment]
My research indicates that this and other road addons have a large impact on performance.

**Comment by BIRLZ95** [comment]
Yeah I'm not sure then, saw it in another place and looked dope

**Comment by Senlarus** [comment]
Going to keep my eyes peeled for a non-impactful option here but closing as a no for now.
