### ISSUE TITLE
PED Model for Supporters Silver plus ?

### ISSUE THREAD

**Issue by BIRLZ95** [New-Chance-RP/Feedback#601]
<h2>Feature you are requesting.</h2>

Allowing access to a single PED for supporters silver and upwards? (maybe gold +) I would limit this to just one per person and maybe put a max limit the people who may support the server are aware of.

<h2>What are the benefits to your feature?</h2>

People who love the server and what its trying to achieve can donate and gain access to a PED model of there choice and use this to create a character around it etc for a deeper experience I believe. No one is forcing you to donate, you can still create a character and story plus the PED's are limited clothing wise so there is pros and cons.

<h2>Anything to support your feature request?</h2>

N/A

**Comment by Zopfco** [comment]
This seems like a reasonable thing to paywall so there aren't a bunch of identical twins roaming around.  I'd probably take advantage of it.

**Comment by Senlarus** [comment]
This feature needs to be controlled for a few reasons. We voted on this with the admin team and we agree with this suggestion. We will proceed.
