### ISSUE TITLE
Binoculars/Camera for zooooming in

### ISSUE THREAD

**Issue by GamerDaniel18** [New-Chance-RP/Feedback#604]
<h2>Feature you are requesting.</h2>

Make the binoculars purchasable once again.
OR add a super high zoom camera using the camera model already in-game

<h2>What are the benefits to your feature?</h2>

The phone camera allows for a certain level of magnification but for PD, you can barely see people on the yacht, at 65's, ect. Having a way of seeing people properly would be great. The same goes for Weazel News and nosy civilians alike.

<h2>Anything to support your feature request?</h2>

Binoculars already partially exist in-game due to a coding mishap but they are so rare I don't have a picture.

**Comment by Senlarus** [comment]
Ok, coming with Thiefsgiving day
