### ISSUE TITLE
Windsor Drop Weight

### ISSUE THREAD

**Issue by Mubbb** [New-Chance-RP/Feedback#612]
<h2>What are you requesting?</h2>
Figured I'd report the Windsor Drop since I haven't seen any of the owners do it lol. 

**3) - Vehicle changes -** *What changes you want think should be made.*

It weighs a TONNE. It probably shouldn't

<h2>Why are you making this request?</h2>

Its broken.

<h2>Anything to support the above?</h2>

Drive it into a lorry and you will definitely win.

**Comment by driftoooo** [comment]
Known issue, on the to-do list. Thank you for the report. I set the mass of the vehicle too high.
Thanks again :)
