### ISSUE TITLE
tow truck needs a fix

### ISSUE THREAD

**Issue by Alizz07** [New-Chance-RP/Feedback#613]
<h2>What bug have you found?</h2>

tow trucks do not want to work and need to be fixed for good RP

<h2>What do you expect should happen?</h2>

the tow truck gets fixed 

<h2>Anything to support your bug report?</h2>

https://clips.twitch.tv/GiftedDaintyTardigradeCmonBruh

**Comment by Zopfco** [comment]
Tow trucks are never going to work reliably in multiplayer.  Network desync/lag & towing physics are a bad combination, as you saw.  Flatbed trailers are far more reliable.

**Comment by Senlarus** [comment]
Will be adding flatbeds that should work with a new public job eventually.
