### ISSUE TITLE
Extra Prompt on Certain Actions

### ISSUE THREAD

**Issue by BIRLZ95** [New-Chance-RP/Feedback#616]
<h2>Feature you are requesting.</h2>

Have an extra prompt when purchasing a vehicle from player owned dealerships, just like when your at the import location, it gives you two prompts.

<h2>What are the benefits to your feature?</h2>

Stops people from purcchasing vehicles by mistake, all it takes is one G flex.

<h2>Anything to support your feature request?</h2>

Yes my bank account, I went from 500K - 120K :@

**Comment by Senlarus** [comment]
Like your cut, G.(I’ll fix this once I can breath again)

**Comment by Senlarus** [comment]
It's fixed.
