### ISSUE TITLE
Low on fuel behavior

### ISSUE THREAD

**Issue by Senlarus** [New-Chance-RP/Feedback#62]
<h2>Better handling of running low on fuel</h2>
I think vehicles should not sputter and stall and reverse when low on fuel.

<h2>What are the benefits to your feature?</h2>

Less aggravation when out of fuel

<h2>Anything to support your feature request?</h2>

I hate when the car sputters and goes in reverse at low fuel. 
(check fuel set fuel timer or warning)

**Comment by Real50BMG** [comment]
What about even adding a notification when low on fuel? Could be an audible thing, or just a little icon. Perhaps even both?

**Comment by Senlarus** [comment]
New low fuel behavior added!
- Fuel Meter blinks at 35% (Orange area of fuel icon only)
- Fuel Meter flashes and blinks at 15% (Pulsing effect around fuel icon, more attention grabbing)
- Car starts to sputter at 8% resulting in speeds being limited to around 20-40 with spontaneous breaking to keep the car moving slower.
