### ISSUE TITLE
status bot stuff

### ISSUE THREAD

**Issue by Alizz07** [New-Chance-RP/Feedback#622]
<h2>Feature you are requesting.</h2>

able to see if meds / officers / mechs ECT are clocked in

<h2>What are the benefits to your feature?</h2>

Helps people to see if there are services in city

<h2>Anything to support your feature request?</h2>

just think it would be something great to add

**Comment by Senlarus** [comment]
It’s been requested already and it’s kinda just metagaming. I don’t see any real benefit.
