### ISSUE TITLE
Fuel Script

### ISSUE THREAD

**Issue by shadowviper0** [New-Chance-RP/Feedback#626]
<h2>What bug have you found?</h2> Fuel script seems to be draining fuel alot faster and way to quickly.

It seems when you fuel up a car, after like 5 min of driving here and there, the fuel trains really fast now, and i just fueled up in mirror park, and by time I got to D8 office up the road a bit, I'm already at 92 fuel. It' seems that the fuel is training alot quicker than usual.

<h2>What do you expect should happen?</h2> Slow up the script so we don't have to fuel up so quickly just after fueling up not even 5 min ago.

**Comment by wavyplays** [comment]
100%. I've noticed this especially when I'm out patrolling on MOTO. It drains fuel super quickly. Used to be able to go from VPD to Paleto and not use half tank. Now I pretty much use the whole tank.

**Comment by Senlarus** [comment]
Fuel consumption was lowered again.
