### ISSUE TITLE
Repair kits can be used in vehicles

### ISSUE THREAD

**Issue by OfficialMasuUK** [New-Chance-RP/Feedback#63]
<h2>What bug have you found?</h2>

Repair kits can be used whilst inside vehicles. - To reproduce, get a repair kit, sit inside vehicle, enter inventory and use the repair kit. It'll put you in the animation and then repair the vehicle.

<h2>What do you expect should happen?</h2>

Shouldn't be able to use repair kits inside of vehicles.

<h2>Anything to support your bug report?</h2>

N/A

**Comment by ixhal** [comment]
Should be fixed Let me know if anything is broken
