### ISSUE TITLE
Unable to unrack weapons from trunks etc

### ISSUE THREAD

**Issue by BIRLZ95** [New-Chance-RP/Feedback#630]
<h2>What bug have you found?</h2>

When I go to get a weapon from my trunk using the TAB menu it don't work anymore.

<h2>What do you expect should happen?</h2>

Be able to unrack weapons and /rack them again.

<h2>Anything to support your bug report?</h2>

No

**Comment by Senlarus** [comment]
This should be fixed, can you confirm @BIRLZ95 ?

**Comment by Mubbb** [comment]
Can confirm. Worked fine yesterday @Senlarus

**Comment by Senlarus** [comment]
Woo!
