### ISSUE TITLE
Audi RS3 

### ISSUE THREAD

**Issue by Whisely3512** [New-Chance-RP/Feedback#633]
What bug have you found?
The back doors on Audi RS3 are not working, the car is a 4 door and you can actually open all door with your M muscle but the doors are not usable 

What do you expect should happen?
I expect if the vehicle is a 4 door all 4 door should be usable 

To recreate this bug/issue spawn a Audi RS3 make someone else sit as passenger and then 3 one just can't enter the car no matter what, that happens 10/10 times, also the trunk has only 25 storage space I think judging by the size of a trunk it should be at least 35

**Comment by driftoooo** [comment]
Known issue. Already in the works. Thanks for report
