### ISSUE TITLE
Local Being able to withstand 8 shots out of a pump shotgun.

### ISSUE THREAD

**Issue by wavyplays** [New-Chance-RP/Feedback#634]
<h2>What bug have you found?</h2>

Local taking an insane amount of shotgun shells before dieing

<h2>What do you expect should happen?</h2>

Local should not be able to take such damage.

<h2>Anything to support your bug report?</h2>

https://streamable.com/s7fji2

**Comment by Senlarus** [comment]
He took it to the vest. Aim better. (Also, this is just a glitch/FiveM issue as I don't have anything that controls/modifies the peds)
