### ISSUE TITLE
Ammunation is mistakenly replaced with pawn shop MLO

### ISSUE THREAD

**Issue by GamerDaniel18** [New-Chance-RP/Feedback#635]
<h2>What bug have you found?</h2>

The Morningwood Ammunation has a pawn shop MLO even though it is next door to a pre-existing pawn shop. 

<h2>What do you expect should happen?</h2>

The interior should be reverted back to the original ammunation. Making it a pawn shop is not necessary as it is literally next door to one.

<h2>Anything to support your bug report?</h2>

Here you can see the ammunation next to the pawn shop:

![image](https://user-images.githubusercontent.com/50466883/100607881-7e312300-3303-11eb-9a49-4e91a5f5429a.png)
![image](https://user-images.githubusercontent.com/50466883/100607931-92752000-3303-11eb-8ad4-011b61259d42.png)

When you enter the ammunation it looks like a pawn shop:

![image](https://user-images.githubusercontent.com/50466883/100607977-a587f000-3303-11eb-918e-b3dcfde3ab84.png)

But it still sells guns:

![image](https://user-images.githubusercontent.com/50466883/100607967-9dc84b80-3303-11eb-8b2e-191cb8b7a586.png)

**Comment by iamrayuu** [comment]
Should be fixed, if not feel free to make a new feedback. :)
