### ISSUE TITLE
Make Police Department Make True statements on Reports

### ISSUE THREAD

**Issue by sbrgamer** [New-Chance-RP/Feedback#637]
<h2>Make the pd stop lying on there police reports.</h2>

<h> Allows people to not get fined as much and get more jail time</h2>

<h2>Yes, I got arrested for attempted murder on one officer and i only shot one but apparently its x2 officer and 2k fine and my friend punched someone and got attempted murder with a weapon, and Some guy nearly killed 5 officers and got 2 months in jail and i got 20 months because its bias and it would be nice if this was addressed</h2>

**Comment by Senlarus** [comment]
This isn't a dev request. Submit an in-character complaint to PD. I cannot program people's behavior.
