### ISSUE TITLE
Ford Crown Vic fix

### ISSUE THREAD

**Issue by Xerothis** [New-Chance-RP/Feedback#641]
<h2>Ford Crown Victoria Suspension fix</h2>

*DELETE AS APPROPRIATE*

**3) - Vehicle changes -** *Hello, so I've noticed and i don't know if it's a known "issue", but the Crown vic seems to have suspension that is too loose, in the sense that if you hit a bump, the tires kinda go into the car itself, as seen on my video below. I've noticed that this suspension also damages the car a little, and it adds up in time, so I just wanted to let you know, other than that, I love my Vic <3.*

<h2>Why are you making this request?</h2>
Just as a fix recommendation
*What improvements / benefits do you think this will have and why?*
It will keep the crown vic from gradually start breaking down on every bump you hit, thus having to repair it less
<h2>Anything to support the above?</h2>

https://medal.tv/clips/37861941/d1337k5ITsfw

**Comment by driftoooo** [comment]
Fixed.
