### ISSUE TITLE
Snow (More Technical Report)

### ISSUE THREAD

**Issue by JakeWalker1** [New-Chance-RP/Feedback#643]
What bug have you found?
Snow making people FPS drop massively making the city un-playable

Describe in good detail what bug you have found as well as list the steps to reproduce if known
Not really a step by step situation, but ever since the snow came into the city my FPS has dropped massively, I believe this is happening to other people as well.

What do you expect should happen?
Not to FPS drop with the snow, in some way massively drop the graphics the snow gives out.

What do you think should happen, what is the intended outcome that you are currently not getting?
Stable FPS but a xmas vibe with the snow

Anything to support your bug report?
N/A

Have you got any evidence to help prove the bug, a video or picture etc?
If people see this just give an opinion.

**Comment by Alizz07** [comment]
same issue here
plz remove

**Comment by JakeWalker1** [comment]
I dont want the snow removing it just needs to be lowered, i like the xmas vibes in city

**Comment by Senlarus** [comment]
Snow was removed
