### ISSUE TITLE
BMW M6

### ISSUE THREAD

**Issue by Mubbb** [New-Chance-RP/Feedback#647]
<h2>What are you requesting?</h2>

BMW M6 Prior Changes

<h2>Why are you making this request?</h2>

For a 440k car it just seem super underwhelming , Level 5 engine & 4 everything else and still only goes around 150~160ish.

-Slow acceleration
-Super heavy handling
-Spins out after any grip loss

<h2>Anything to support the above?</h2>

Negative

**Comment by driftoooo** [comment]
Looking into the vehicle shortly. Thank you for the report. I'll update you when it has been sorted.

**Comment by driftoooo** [comment]
Complete, they'll be pushed soon.
- Acceleration: Increased
- Top speed: Increased
- Spinning out: Reduced
- Wheel spin upon launch: Reduced

Thank you for the report, feel free to close the issue and re-open it if you come across any further issues. :)

**Comment by Mubbb** [comment]
Lovely! Appreciate you boss

**Comment by driftoooo** [comment]
Has been pushed to live - thank you again for report.
