### ISSUE TITLE
Deadly objects in Paleto Police Department

### ISSUE THREAD

**Issue by iamrayuu** [New-Chance-RP/Feedback#65]
<h2>What bug have you found?</h2>

Objects in Paleto police department reskin has the ability to electrocute you upon running into it, and possibly killing if your health is low or if you continuously run into it.

<h2>What do you expect should happen?</h2>

Not sure if the reskin can be edited, but it's really one object from what I can tell that's meant to be like a heater of some sort for the department that just electrocutes and sends you flying across the room.

<h2>Anything to support your bug report?</h2>

A picture of where some of them are and I know there's more if you need more to be found, but this is what they look like.
![image](https://user-images.githubusercontent.com/35026673/79508313-f0682800-7ffe-11ea-9f47-d1018cc393da.png)
![image](https://user-images.githubusercontent.com/35026673/79508368-142b6e00-7fff-11ea-917d-3551e4338497.png)
![image](https://user-images.githubusercontent.com/35026673/79508448-32916980-7fff-11ea-9e22-123893f2731a.png)

**Comment by Senlarus** [comment]
We will have to modify the MLO to fix those and we don't have a mapper. People will have to stay away, call it an easter egg ;)
