### ISSUE TITLE
Nero is broken

### ISSUE THREAD

**Issue by KermitTheSlav** [New-Chance-RP/Feedback#653]
<h2>What are you requesting?</h2>
The Nero be updated to have a higher top speed and acceleration to accurately reflect its actual capabilities, and be worth the high cost of the car.

**3) - Vehicle changes - The Truffade Nero even with full tune and all aftermarket kits tops out at 160mph on flat ground
<h2>Why are you making this request?</h2>

What improvements / benefits do you think this will have and why?* The adder is almost 100k less and does around 280mph max speed, the Nero is supposed to be the newer version of the car and it costs 340k gets outperformed by cars under 100k when it comes to top speed, just gives a reason to own it as from what i know im the only one that owns it in city so it may not be a widely known issue.

<h2>Anything to support the above?</h2>

**Comment by driftoooo** [comment]
Known. Will be sorted when I'm back. Not all GTA vehicles have had their handling complete yet, it's a WIP at the moment so things being sorted as we go along.

**Comment by driftoooo** [comment]
Awaiting to regain access to the base GTA handling file, then I'll get this ironed out - as I explained in #606, I completely forgot about this as at the time this was the last thing on my mind. I'll get it sorted.

**Comment by driftoooo** [comment]
Done, waiting to be pushed 👀

**Comment by driftoooo** [comment]
Pushed - Available next restart https://discord.com/channels/680278765179502645/688123847047774210/801845150287396896
