### ISSUE TITLE
AUDI RS3 2018 Steering Wheel 

### ISSUE THREAD

**Issue by Whisely3512** [New-Chance-RP/Feedback#655]
What bug have you found?
I have found a bug that was been around for a couple of weeks, when you sit in 2018 Audi RS3 your hands go through the steering wheel 

This bug is very easy to reproduce, spawn 2018 Audi RS3 and just sit as a driver in it, and your hands will just he scuffed

What do you expect should happen?
I expect my hands would stick to the steering wheel just like all the other cars

There is a picture to show you guys exactly what I mean
https://cdn.discordapp.com/attachments/756857865951772694/786274176162857080/unknown.png

**Comment by driftoooo** [comment]
Known issue, you’ve already reported
It directly to me. It’ll be fixed soon. Thanks again for the report.
