### ISSUE TITLE
LS Customs official uniforms/outfits 

### ISSUE THREAD

**Issue by Whisely3512** [New-Chance-RP/Feedback#656]
Feature you are requesting.
I would like to request a special uniform for all LS Customs employees, every rank has the different one but they are all looking like a mechanic outfit

What are the benefits to your feature?
There is a couple of benefits of this feature, 1. Looks more professional and suitable for the job that you are doing, 2.Not anyone can have this outfit/uniform so noone can pretend they are mechanic anymore or they work for LS Customs and just steal your car, 3. In future if we are going to have multiple official mechanic shop around the city for example "Benny's" they would have different ones .

I personally don't see any negative sides of this feature

Sadly I don't have anything to support this feature

**Comment by Senlarus** [comment]
I believe these were added in the most recent EUP push. Enjoy!
