### ISSUE TITLE
Jaguar F-Pace Acceleration and Top Speed

### ISSUE THREAD

**Issue by TheHairyPenguin** [New-Chance-RP/Feedback#658]
<h2>What are you requesting?</h2>

An increase in Acceleration and Top Speed for the Jaguar F-Pace

<h2>Why are you making this request?</h2>

The Jaguar F-Pace sells for around the 300k in dealerships around the city and currently only hits around 120mph top speed and takes a long time to get there. Other SUV's such as the trackhawk and even cheaper SUV's like the the Dodge Durango hit almost 200mph+ for the same or even half the price point.

<h2>Anything to support the above?</h2>

I can provide a clip of me driving the car along the highway if needed.

**Comment by driftoooo** [comment]
The issue has been resolved. Will be pushed soon. Thank you for the report. The Dodge Durango will be looked into aswell.

**Comment by driftoooo** [comment]
Pushed to live - thanks again for report :)
