### ISSUE TITLE
1989 Nissan R32 GTR Top Speed, Acceleration and Breaking.

### ISSUE THREAD

**Issue by ABroHaam** [New-Chance-RP/Feedback#659]
<h2>What are you requesting?</h2>

The top Speed and Acceleration of this vehicle is very slow compared to the real-life equivalent. 

**3) - Vehicle changes -** *Top Speed and Breaks.*

<h2>Why are you making this request?</h2>

159 MPH was the stock top speed of this vehicle. The breaking as well is very underwhelming for the vehicle being a 2 door sports car the breaks were much better than they are portrayed within the city.

*DELETE THIS LINE - What improvements / benefits do you think this will have and why?*

This will make the car feel much more realistic, in its current state costing as much as it does nobody wants to buy it so its a nonsellable car at this point.

<h2>Anything to support the above?</h2>

Did a google search and was able to find all the info needed : https://www.encycarpedia.com/us/nissan/89-skyline-gtr-r32

**Comment by driftoooo** [comment]
Changes have been complete, they'll just need pushing soon. Thank you for the report.

**Comment by driftoooo** [comment]
Pushed to live - thanks again for report
