### ISSUE TITLE
Drug System (As it stands)

### ISSUE THREAD

**Issue by OfficialMasuUK** [New-Chance-RP/Feedback#66]
<h2>What bug have you found?</h2>

Didn't have a car waiting so tried to steal a car with package in hand, could steal car but still not put package inside of vehicle. Ended up driving across town and being left with box attached to hand and prompt still up on screen with no way to remove box.

Got a "Press E to delete object" prompt on box.

<h2>What do you expect should happen?</h2>

<h2>Anything to support your bug report?</h2>
![Screenshot_2](https://user-images.githubusercontent.com/10865605/79615609-2094f100-80fb-11ea-982e-990b4765a942.png)
![Screenshot_3](https://user-images.githubusercontent.com/10865605/79615616-225eb480-80fb-11ea-9af8-f211b7e5d1e6.png)
![Screenshot_4](https://user-images.githubusercontent.com/10865605/79615618-22f74b00-80fb-11ea-963f-422af9d6dafa.png)

**Comment by ixhal** [comment]
That prompt will be gone soon its because you're job was set as police, Will fix this tomorrow and look into better options for how you receive the drugs thanks for the report

**Comment by ixhal** [comment]
changed RP to find out
