### ISSUE TITLE
city NEEDS Turismo R & Zentorno local spawns to help avoid people having to chop there own constantly 

### ISSUE THREAD

**Issue by GmunPlayZ** [New-Chance-RP/Feedback#660]
just simply add local turismo R and Zentorno spanwns if there is any way to do so. every other vehicle can be found

**Comment by ABroHaam** [comment]
They do have local spawn points it's just very rare I have over 17 Days of playtime in this city and never seen 1 spawn anywhere. I have looked at every known spawn in regular GTA and also looked everywhere else never seen one. I know people that have hunted for over 10 hours straight looking in every nook and cranny and never found one so they went and bought the car cause they could not complete their list. With Insurance claims being a thing people just went out and bought the car and claimed insurance on it was just much easier and with it being a function within the server was not lead to being thought as wrong.

**Comment by Senlarus** [comment]
Will handle in #661
