### ISSUE TITLE
Pawn Shop Bug

### ISSUE THREAD

**Issue by Honton** [New-Chance-RP/Feedback#665]
<h2>What bug have you found?</h2>

Pawn shop will become bugged and unusable to everyone if you open your inventory while the pawnshop menu is opened.

<h2>What do you expect should happen?</h2>

For the pawnshop to work after looking at your own inventory when selling
<h2>Anything to support your bug report?</h2>

No video, but I'm pretty sure this is a bug.

**Comment by Mubbb** [comment]
Can confirm bug. Had to take a flight to fix it. It seems to also effect all pawn shops regardless of which you do it at

**Comment by Honton** [comment]
Can confirm it seems after the bug, it appears that you are still "talking" to the pawnshop owner.

**Comment by Senlarus** [comment]
Thank god!! I had no idea what was causing this. Much love for the report, I can fix this now!

**Comment by Honton** [comment]
Hashtag Honton to the rescue

**Comment by Senlarus** [comment]
I started to fix this but it’s not done yet

**Comment by iamrayuu** [comment]
Annnnd fixed!
