### ISSUE TITLE
CHOP SHOP

### ISSUE THREAD

**Issue by Grim-Reaper12** [New-Chance-RP/Feedback#666]
If its not in the works have chop have a cancelation in which we can cancel the list to be able to request a new one. Also Susy in Sandy still not working with chopping cars.

**Comment by iamrayuu** [comment]
Ability to cancel has been added! Has the issue with Susy been fixed?

**Comment by Grim-Reaper12** [comment]
Susy still hasnt been fixed. There is no circle in front of the guy you're supposed to chop it at

**Comment by Senlarus** [comment]
Susy won't be added for the time being. Once we reach more consistently high populations I plan on moving out from the city, but for now I want to keep people in the same area to help roleplay. This will be done along side other things so I am closing this request as pending implimentation.
