### ISSUE TITLE
Pistol Whip worked somehow.

### ISSUE THREAD

**Issue by OfficialMasuUK** [New-Chance-RP/Feedback#67]
<h2>What bug have you found?</h2>

Pistol whip still worked. 4 hit kill. Cannot reproduce for certain. Also, when checking death cause it comes up saying "Patient has bullet wounds".

<h2>What do you expect should happen?</h2>

No pistol whip? If pistol whip, cause of death should come up with "Patient died from blunt force trauma" or similar.

<h2>Anything to support your bug report?</h2>
![Screenshot_1](https://user-images.githubusercontent.com/10865605/79615859-8d0ff000-80fb-11ea-856d-4e9def39c7d1.png)

**Comment by ixhal** [comment]
Can't recreate this will close for now, if you manage to do it again let me know
