### ISSUE TITLE
Track hawk

### ISSUE THREAD

**Issue by ChuckBurn** [New-Chance-RP/Feedback#674]
<h2>Not heavy enough/can't tune</h2>
 Vehicle changes - Car rolls onto roof very easy. Can not tune vehicle or add kits.

**Comment by driftoooo** [comment]
Unable to replicate the rolling issue. However, I've fixed the issue regarding vehicle tuning and its. You can now do all performance mods to the vehicle alongside using performance kits on it. I've also done some other modifications to it :eyes: (https://imgur.com/a/TH2mauQ)

**Comment by ChuckBurn** [comment]
I have been unable to roll the vehicle aswell. However it is because of the snow. Try with no snow. you will see.

**Comment by ChuckBurn** [comment]
Just checked the imgur. That's bad ass LOL

**Comment by driftoooo** [comment]
The DEV server is also currently filled with snow. When I'm able to get someone to pop on and temporarily remove it I'll look into it. For now, enjoy the ability to tint the windows again, the new customization, and all the performance parts. Enjoy! :) Feel free to close the issue aswell, I've got the rolling issue logged on my sheet

**Comment by driftoooo** [comment]
They'll be available to you in a couple of days, depends when they're pushed.

**Comment by ChuckBurn** [comment]
Sweet! Thank You!

**Comment by ChuckBurn** [comment]
Tint <3

**Comment by driftoooo** [comment]
Has been pushed to live - thank you again for report.
