### ISSUE TITLE
Tempesta

### ISSUE THREAD

**Issue by ChuckBurn** [New-Chance-RP/Feedback#676]
<h2>Kits added to tempesta do nothing</h2> 
Vehicle changes - Fix so the kits work.

<h2>No change</h2>
I have a full tuned no kit tempesta. A friend has a full tuned everything but suspension kit tempesta. We raced zero to max speed on highway. Side by side the entire 
time.

**Comment by driftoooo** [comment]
Cannot really replicate the issue. Closing at this time, the way the kits work is by locking the top upgrade option, when RStar made this vehicle, they must've not added a higher multiplier for the vehicle. I performed this test on a long straight away, and there was a minor difference, but it isn't significant.
