### ISSUE TITLE
Fuel Mileage

### ISSUE THREAD

**Issue by ABroHaam** [New-Chance-RP/Feedback#677]
<h2>What are you requesting?</h2>

Fuel Economy!

This server strives to make the most realistic driving experience in comparison to what vehicles do performance-wise in real life. The one major discrepancy is the fuel. 
Many people complain about the performance of vehicles being less than they desire due. 
For example, they want a Silvia or R34 to go 250 MPH and turn on a dime (yes an exaggeration but you get the point).
But the fuel economy in this city is horrendous I find myself at gas stations staring at a screen gaining no actual RP just fueling my vehicle 20+ times a day.
My request with this is that the fuel economy matches IRL or at least something close or better than what we have.
Being able to drive even 100 miles or 50 miles on a tank would be better than 9. Some vehicles in the city yes have better fuel economy but overall it's about the same difference if you run IRL numbers against the data.

The test I did to come to this conclusion:

6.8 Miles From The gas station Caddy Corner to Moto Mart To the corner gas station at the east end of Paleto.

26% of gas used to make the trip. 

Real-Life Statistics:

Range, city/highway (miles) 240.50 / 407.00

EPA Fuel Economy, combined/city/highway (mpg) 16 / 13 / 22

Fuel Capacity / Gas Tank Size 18.5

In City Statistics: 

The constant I used for this math was from the IRL stats of the vehicle.

Range: 9.190263288623944 Miles

Fuel Capacity : 18.5 <- IRL number.

Fuel Economy: 2.013 MPG

The difference is huge and isn't as realistic as the vehicles handling and driving compared to IRL.

Would love to hear people's thoughts on this so please submit your feedback! I am open and always willing to listen and even take on other ideas!

**Comment by KermitTheSlav** [comment]
Agreed, I get that MPG might not be able to be the same as IRL but current consumption is insane, some cars are almost gas station to gas station how bad they are (Drift Tampa)

**Comment by AriesVeno** [comment]
The gas Drains super quick, compared to what it's supposed to be. Theres times where the tank is full, the car gets parked and comes out almost empty, as if it has been driven. Also have to fill up i feel like 20times or more within the day, SO i much agree with this !

**Comment by Senlarus** [comment]
The main issue here is you guys are running the vehicles at top speed, highest RPM, and the fuel script makes you use more fuel when you do that. Slow down!... Also I've lowered fuel consumption at high RPMs... GO FAST! 💯

**Comment by EvanChasse** [comment]
The test Abroham is referring too in the original post, was done at the speed limit. Agreed running at top speed should use a lot of gas. But we used 26% of the fuel tank going the speed limit from the gas station near Motor Market to paleto, which is 6.8 miles.

**Comment by AriesVeno** [comment]
The same test was done 3 different times with 3 people along for the ride, with the same result While going the speed limit, I agree going fast should suck the gas out, but the fact is none of us were driving fast, it sucked out a lot of gas when it shouldnt of
