### ISSUE TITLE
Lockpick House scuffed

### ISSUE THREAD

**Issue by ChuckBurn** [New-Chance-RP/Feedback#680]
<h2>Lockpick will scuff</h2>

Secondary stage of lock pick must be done first. after always 100% success you will enter building and then have to complete first stage (circle) to be able to move. Can not explain more without meta gaming

<h2>Normal lockpicking</h2>

Have normal lockpicking. This could be used as a power gaming tactic to never fail lockpick on a house

Can't show without meta game. PM me for details

**Comment by Senlarus** [comment]
This should be fixed after the next restart.

**Comment by iamrayuu** [comment]
Closing as this is fixed. :)
