### ISSUE TITLE
Local Cars

### ISSUE THREAD

**Issue by Zopfco** [New-Chance-RP/Feedback#685]
<h2>Buff or Remove?</h2>

It seems there are a number of local vehicles that have a problem shifting into higher gears.  To me it feels like a transmission issue. They will redline in a lower gear, topping out at ~80mph on level ground.  In rare cases they will shift into the last (?) gear and accelerate briefly before quickly downshifting & redlining again.  

<h2>On Cinderblocks in the Front Yard</h2>

I own a Desert Raid truck which is meant to be an offroad rally racing vehicle, as well as the Tulip muscle car.  Both are fully tuned and neither one will do 100mph on level ground.  By contrast the Rumpo Custom _van_ with stock components outperforms them in just about every way.  These vehicles are all roughly the same price (counting the Custom upgrade for the Rumpo.)

<h2>The Case for Removal</h2>

An import Crown Vic or Chevy Tahoe costs roughly twice as much as these local vehicles.  The expectation is then that they should be twice as good.  This price=performance model puts the local vehicles in a strange spot since even the high-end local car is considerably cheaper than the average import in most cases.

For the sake of balance (& simplicity) maybe it would be better to no longer sell most of the local vehicles? A few of the popular low-end/starter options could remain, along with some of the specialized ones (cargo, liveries etc) that are more RP-related or without a ready import equivalent.

Most of the local sedans, sports, muscle, SUVs & trucks etc could all be removed in favor of a few more mid-range imports along the same lines as the Celica or Tahoe.  This might create more walk-in business for the dealerships around town & remove these underperforming/unbalanced local cars from the market.  It would also prevent the more expensive imports from sometimes being outperformed by considerably cheaper locals.

**Comment by driftoooo** [comment]
Section A - Buff or remove:
As stated previously, not all GTA cars have had their handling done. I’ve not had time to go through and do all of the GTA cars, alongside all of the imports alongside school. So I decided to make import cars a priority and get them rolled out with fully custom handling. 

Section B - On Cinderblocks in the front yard: 
As stated above, not all handling for GTA vehicles has been complete yet, the two vehicles that you’ve stated above are on a to-do list.

Section C - The Case for removal:
For the price of vehicles, remember that an import tax is added onto these vehicles. The fact that it’s an import already adds value to the car, as it A) Takes up more server resources B) It’s an import
As far as simply scrapping most of the local cars, I personally don’t think that’s a solution. Scrapping some of the local cars simply just reduces the variety of cars in the server. Some people also like to use the traditional local cars for many reasons, and some just like to use them all the time as they don’t want an import car.
I understand your frustration and handling, but hopefully everything I’ve said above in the three sections can assist you in understanding the reasons / causes behind this.

**Comment by Zopfco** [comment]
Other people had mentioned that same failure to shift problem with their local cars so I thought it might not be vehicle-specific.  Adjusting them all individually sounds like a pain. To be clear, I only meant removing them from sale, not entirely.  Maybe to be added back to the shop later once they're fixed?  

Thanks for having a look.
