### ISSUE TITLE
Trash job with no trash bin

### ISSUE THREAD

**Issue by ChuckBurn** [New-Chance-RP/Feedback#686]
<h2>Trash bin not at location </h2>

Pull up to nothing. Honk and it gives next location to drive to and get payed nothing. We drove to multiple locations in a row with no trash bin and no pick-up, but sometimes no trash bin but can still pick up.

<h2>Have a trash bin to pick up </h2>

If a location requests a trash pick up. Should have trash bin

https://steamcommunity.com/sharedfiles/filedetails/?id=2323497004

**Comment by Senlarus** [comment]
It's close by, but sometimes it picks one a bit out of sight range.

**Comment by Senlarus** [comment]
... or that new version of the VU has no garbage there... heh

**Comment by ChuckBurn** [comment]
Here is a picture of no trash available as well as a video of no trash bin but can pick up. I know the one you mean where its off to the side. Not the same thing I am talking about. and yes VU never has trash bin.

https://steamcommunity.com/sharedfiles/filedetails/?id=2323497004

https://www.youtube.com/watch?v=tyKHFre0kjE

**Comment by Senlarus** [comment]
Yea... 40 locations and didn't account for changes to the mapping. Will fix.

**Comment by Senlarus** [comment]
I switched some locations last night and applied a fix to the no bins found message. Please report if fixed

**Comment by Senlarus** [comment]
Feedback from others indicates this has been fixed.
