### ISSUE TITLE
1989 Nissan Skyline R32 GTR Tuning

### ISSUE THREAD

**Issue by ChuckBurn** [New-Chance-RP/Feedback#689]
<h2>1989 Nissan Skyline R32 GTR Tuning</h2>

**3) - Vehicle changes -** Tuning didn't get pushed to live? Top speed 160. full tuned with kits. Braking terrible and turning very wide radius acceleration equal to elegy retro. When on dirt zero turning or brakes. Best test is at Trash Job.

<h2>300k+ Vehicle equal to 40k Elegy Retro</h2>

300k Car should go at least 200mph and have decent brakes and turning

**Comment by driftoooo** [comment]
It’s the only working model that meets server requirements. Handling has been changed and is live. Handling changes are fine when on tarmac, I recommend not using your car that has no TCS, ABS etc on the snow. Vehicles real top speed is 160mph, and fully tuned this particular one will go 175 in the server. You pay the price tag for the ability to have an import car in the city, alongside other factors. Hopefully this answers your question, I’m going to be closing this issue. Thank you for your report.
