### ISSUE TITLE
Vehicle Sell Doesn't Work

### ISSUE THREAD

**Issue by bloombydee** [New-Chance-RP/Feedback#69]
<h2>What bug have you found?</h2>

Vehicle sell behind Simeon's doesn't work

<h2>What do you expect should happen?</h2>

Delete car and give a portion of the money, move sell location to Mosley's

<h2>Anything to support your bug report?</h2>

Multiple people experienced it

**Comment by ixhal** [comment]
Removed the sell for now as we discussed thanks for the report
