### ISSUE TITLE
Salon resets hair and makeup & makeup doesn't stay after restarting game.

### ISSUE THREAD

**Issue by iamrayuu** [New-Chance-RP/Feedback#70]
<h2>What bug have you found?</h2>

When you initiate the salon to re-customize your character, all your hair and makeup disappear except for the eyebrow thickness. Also when you restart your game, the makeup on your face disappears entirely, but you still keep your hair or blush if you have it.

<h2>What do you expect should happen?</h2>

I expect usually that things stay the same and make it so I can just scroll through other options for what I want to change and that makeup stay on even after leaving your game.

**Comment by iamrayuu** [comment]
A comment to add that the makeup I had stayed on after I restarted the game before I used the salon, but didn't once I used the salon for the first time on that character.

**Comment by Senlarus** [comment]
This has been fixed.
