### ISSUE TITLE
DOJ System

### ISSUE THREAD

**Issue by Tybo89** [New-Chance-RP/Feedback#701]
<h2>Feature you are requesting.</h2>

I would like to help implement a DOJ System (Judges, Lawyers)

<h2>What are the benefits to your feature?</h2>

The positive impacts would be 

1. It would create a buffer between the cops and criminals in the city. 
2. It would create more RP and more Whitelisted (Legal) jobs in the city.
3. Help criminals as well as cops with any legal issues.
4. In the future you could also create RP for businesses and other citizens by including business proposals, personal Wills, etc

<h2>Anything to support your feature request?</h2>

I would like to team up with someone higher up in the server and start implementing the DOJ slowly.  We could start out by having only Public Defenders who would go down to PD when someone requests a lawyer.  They would be able to listen to the charges and see if they could get the charges reduced at all.  In extreme cases we could have a Bench Trial where the Public Defenders would represent the Defendants and the PD would represent the State and a "Higher Up" would server as Judge.  If more and more people are interested in joining the DOJ i wouldnt be opposed to coming up with a Bar Exam and having people apply.  We could then expand to having Person Attorneys and District Attorneys and such, but like i said just basic at first.  I do have experience in other cities with running a DOJ system but considering I'm still new to the city I would still be getting acclimated to the different city rules/laws.  If any one is interested in helping me with this (With approval from the city leaders of course)  Please feel free to shoot me a message  (Melvin Douglas) Tyob89 #9318

**Comment by greed702** [comment]
This is already in the works to be implemented

**Comment by Zopfco** [comment]
> This is already in the works to be implemented

The business proposals are already being accepted.

**Comment by Tybo89** [comment]
Lol   I was told today by the Head Leaders that after if i was serious about helping with DOJ i should post it in here...

**Comment by Zopfco** [comment]
> Lol I was told today by the Head Leaders that if i was serious about helping with DOJ i should post it in here...

Oh I'm sure they will be "hiring" for it soon & this should get you linked up with the right people.

**Comment by Tybo89** [comment]
> > Lol I was told today by the Head Leaders that if i was serious about helping with DOJ i should post it in here...
> 
> Oh I'm sure they will be "hiring" for it soon & this should get you linked up with the right people.

Thanks a lot for the help man.  Look forward to helping out

**Comment by Senlarus** [comment]
@Tybo89 Open and ticket and @ me
