### ISSUE TITLE
Re-Locate Clock-In/Out and Clothing Change Location - MRPD

### ISSUE THREAD

**Issue by griffey47** [New-Chance-RP/Feedback#711]
<h2>What bug have you found?</h2>

The blue designated areas to change clothes or clock-in/out at Mission Row PD are a bit close together. Making it difficult to clock-in or out. The default seems to select "Change Clothing" and brings up the regular clothing menu that you would see in a store.

<h2>What do you expect should happen?</h2>

Perhaps we can yeet one of those locations to a different part of the locker-room?

<h2>Anything to support your bug report?</h2>

No, but if needed I can send something. It isn't a huge priority because MRPD isn't used very often. I just happened to be in the area and needed to change out my bulletproof vest, but was unable to.

**Comment by Senlarus** [comment]
I will set this up properly when we get the new MRPD.
