### ISSUE TITLE
Mac-10

### ISSUE THREAD

**Issue by wavyplays** [New-Chance-RP/Feedback#718]
<h2>Feature you are requesting.</h2>

Mac-10 SMG for civilians

<h2>What are the benefits to your feature?</h2>

I think it'd be pretty cool for more weapons to be introduced for both civilians and law enforcement. As it stands there isn't a whole lot of variety of weapons and only the very high powered weapons such as the Carbine rifle are restricted to higher ranks in PD. As a whole i'd just like to see more weapons/ weapon variety for different types of players.

<h2>Anything to support your feature request?</h2>

https://www.gta5-mods.com/weapons/ingram-mac-10-animated

**Comment by Zopfco** [comment]
Assuming you mean available on the black market, yeah that'd be pretty cool.

**Comment by Senlarus** [comment]
For what purpose? Also, there are weapons available to civilians but they’re just not as easily obtained as before.

**Comment by Zopfco** [comment]
> For what purpose? Also, there are weapons available to civilians but they’re just not as easily obtained as before.

Just for variety, it's an iconic weapon with that cartel/Miami Vice sort of aesthetic.  I don't think there's any real *need* for new guns, but the same could be said about cars too.  It's a style thing 😄 

As for the civilian stuff, the new options are very cool but seem to exist in a sort of grey area legally due to where they come from..

**Comment by Senlarus** [comment]
Well any automatic weapon isn’t going to be legal for civilians to carry. So the only other things we could add for them would be handguns

**Comment by wavyplays** [comment]
> Well any automatic weapon isn’t going to be legal for civilians to carry. So the only other things we could add for them would be handguns

I dont only mean for civilians to carry them, they can be used by criminals aswell. Pretty much anyone that is able to obtain one can.

**Comment by Zopfco** [comment]
> Well any automatic weapon isn’t going to be legal for civilians to carry.

👍  Practically I'd expect a Mac-10 to be about the same as a Tec, just a different (imo cooler) model. 

>So the only other things we could add for them would be handguns

A semi-auto shotgun or full-sized double barrel could be cool? Agree there's a good mix of pistols now.  GTA isn't much of a shooter, the firearms aren't that granular & this is an RP server besides..

For the sake of increasing variety I think weapons mods would be better, something kind of like the automotive kits? That might deserve its own thread

**Comment by Senlarus** [comment]
I'll slowly be adding weapons over time. Also, closing this and adding it to the newest weapon thread #754
