### ISSUE TITLE
2017 Rolls Royce Wraith

### ISSUE THREAD

**Issue by SwizzyWT** [New-Chance-RP/Feedback#726]
What are you requesting?

- some re work done to the Rolls Royce Wraith: Handling and speed, middle body color as well if possible only stays black can’t change color. 

Vehicle changes -** *What changes you want think should be made.*

- So for the Wraith the car for one drives like a boat and does not handle the best along with the car being fully tuned with every kit as well is slow in my opinion with only topping at 180 with everything done. I have driven a wraith before and just because the car looks big doesn’t mean it drives big, the wraith is 625+ Hp with a 6.6L V12 so it handles very good along with great pick up speed. But other than that that car is awesome would like to change color of the middle section but not must.

**Comment by EvanChasse** [comment]
The wraith tops out at 155 in head. And 0 to 60 is 4.1 seconds. Its in a very good spot rn. And not to mention they drive like literal boats in head. Its nicknamed a yacht on wheels.

**Comment by EvanChasse** [comment]
If anything its faster then it should be not slower.

**Comment by driftoooo** [comment]
First and foremost, I’d like to thank you for opening the issue and also thank both of you for airing your opinion on the vehicle. I’ll give it a test tomorrow and then I’ll inform you of my personal opinion and where I’ll be moving from there regarding the car.

**Comment by SwizzyWT** [comment]
Evan just asking have you driven one before?

**Comment by SwizzyWT** [comment]
My main thing really is handling speed is what it is, but from driving one in RL it doesn’t turn like that how it does in city.

**Comment by driftoooo** [comment]
Complete - Awaiting pushing

**Comment by driftoooo** [comment]
Pushed
