### ISSUE TITLE
2006 Evo IX - Handling/Brakes

### ISSUE THREAD

**Issue by BIRLZ95** [New-Chance-RP/Feedback#738]
<h2>What are you requesting?</h2>

Evo breaks need tightening up and handling needs making a more responsive on and off road.

**3) - Vehicle changes -** Better handling & Braking

<h2>Why are you making this request?</h2>

Not enjoyable to drive yet, its nearly there though, the speed is fine just handling is off and don't feel right yet.

<h2>Anything to support the above?</h2>

Mine and others experience.

**Comment by driftoooo** [comment]
Thank you for the report, 
I'll look into it shortly.

**Comment by driftoooo** [comment]
In progress...

**Comment by driftoooo** [comment]
Complete. I've maid this more of a 'hybrid road/drift car'. So this thing is a fun city car, but it provides the traction you need when you need it most. To explain, I put this video together real quick - https://streamable.com/o1x90f

It's awaiting pushing.

**Comment by BIRLZ95** [comment]
You the man!

**Comment by driftoooo** [comment]
Pushed - available next restart :)
