### ISSUE TITLE
pd and med blimps on the map 

### ISSUE THREAD

**Issue by rulefocus2742** [New-Chance-RP/Feedback#741]
<h2>Feature you are requesting.</h2>
as we know that on the map we have just blips on the map on where units are but we don't no who that person i think that if we change that so it shows a name or a call tag it would make it a lot easier for us to tell who is where from this change when one unit gets taken as a hostage we all in radio at once calling out to find out who's been taken 

<h2>What are the benefits to your feature?</h2>
i think we having this where units name or call tag show would make it easier for other unit know where others are and how close but also when one is taken or killed we no who we are responding to

**Comment by Senlarus** [comment]
Good idea! I actually have a full dispatch script that I’ll be customizing and adding at a later date that will allow for better tracking an identification of units. At that time I will also be able to enable 911 to ring to the dispatchers so they can field real 911 calls from players.

the issue currently is with the built in GTA map there is no capability to add custom callsigns to the map.

**Comment by rulefocus2742** [comment]
you say there's a problem with the gta 5 map script wouldn't it just be easier to replace with a different one when the time come to it to save time trying to edit the map script that already being used
