### ISSUE TITLE
Apartments are flooded

### ISSUE THREAD

**Issue by Aeroheadz** [New-Chance-RP/Feedback#742]
<h2>What bug have you found?</h2>

Apartments across from LifeInvader are flooded or at least just the one.

<h2>What do you expect should happen?</h2>

Ive already been given my money back by the bank. just want the rooms fixed or removed all together. 

<h2>Anything to support your bug report?</h2>

https://clips.twitch.tv/PlayfulTacitLionPeanutButterJellyTime

**Comment by Aeroheadz** [comment]
The name of there apartments/hotel rooms are "Von Crasenberg Richman"

**Comment by Senlarus** [comment]
Removed at restart
