### ISSUE TITLE
Cant Walk with phone out

### ISSUE THREAD

**Issue by Grim-Reaper12** [New-Chance-RP/Feedback#744]
<h2>What bug have you found?</h2>

Cant walk or drive while having my phone out

<h2>What do you expect should happen?</h2>

Able to drive and walk with it

<h2>Anything to support your bug report?</h2>

https://streamable.com/5evkk2

**Comment by Mubbb** [comment]
This could be complete piss in the wind but I dont know if the mouse cursor popping up is normal or not but have you changed your phone controls to mouse?
