### ISSUE TITLE
Mclaren Speedtail is bi-polar

### ISSUE THREAD

**Issue by KermitTheSlav** [New-Chance-RP/Feedback#750]
<h2>What bug have you found?</h2>

For some reason when driving the speedtail its acceleration and top speed changes randomly. Sometimes when I get in it'll accelerate hard and drive like a bat out of hell (like it should) and other times it randomly slows to the speed of about an R8 if not slightly slower. Example, half the time i rockets up to 300mph no problem, the other half it struggles to hit 200 and barely goes past 220.

<h2>What do you expect should happen?</h2>

Might have 2 tune files for some reason or could be related to how damaged it is, sometimes when its beat up a bit it goes back to its normal cracked speed, im not sure whats causing it.

**Comment by driftoooo** [comment]
That’s normally due to invisible health damage,  and the location in which your driving it. If you’re going up or down Los Santos freeway, the bumps on the road help the car accelerate to a very high top speed but these bumps can also cause damage to the vehicle. In contrast, driving the car on a flat, smooth road, may make the car feel less responsive and not as powerful.

**Comment by KermitTheSlav** [comment]
I understand that but it drove differently at different times on flat ground fully repaired, previous owner mentioned this happening as well

**Comment by Hazza19** [comment]
As the previous owner i had a problem where the speed would lock at times and other times it wouldnt for example id fly in one day and the car wouldnt go over 300 like it would be stuck at 300 even at downhill but other times id fly in it would just keep rising to around 330 340 so im not sure why that is

**Comment by driftoooo** [comment]
Unable to replicate the issue, currently closing at this time.

Thank you again for the report, any further issues feel free to contact me.
