### ISSUE TITLE
Fishing issues atm.

### ISSUE THREAD

**Issue by Honton** [New-Chance-RP/Feedback#751]
<h2>What bug have you found?</h2>

1. I know it's due to some of the spawn protection issues we had in the past, but fishing poles are still invisible when in use.
2. The button prompt when fishing can be blocked by ooc chat when it pops up, resulting in not being able to press the correct button
<h2>What do you expect should happen?</h2>
1. Have the fishing pole be visible during fishing activities.
2. Don't know if it;'s possible, but essentially pull the fishing prompt "layer" in front of the OOC chat "layer" If that makes any sense.
3. <h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/66952510/104136366-71fca480-534a-11eb-87d5-380e95b6a8c3.png)

Here's a picture of the chat blocking the prompt and also the character model not having the fishing pole while fishing.

**Comment by Senlarus** [comment]
Fixed the fishing rod, there's nothing I can do about the chat box blocking that sadly. Fishing uses helptext which is a static GTA function that cannot be moved. I will be adding a way to opt out of ooc chat so you won't ever see it which should address this in the future.
