### ISSUE TITLE
Clothing issue

### ISSUE THREAD

**Issue by BIRLZ95** [New-Chance-RP/Feedback#753]
<h2>What bug have you found?</h2>

Come to my attention that if you press f7 and take your shirt off you get a salmon colored top appear instead

<h2>What do you expect should happen?</h2>

Be able to take ur top off and be shirtless like previous

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/64453673/104165183-ef7af000-53f0-11eb-8ab7-438d6e159d00.png)
![image](https://user-images.githubusercontent.com/64453673/104165205-f73a9480-53f0-11eb-84f9-ceccfd0f413e.png)

**Comment by Ic3BoxTheSuspect** [comment]
This happens with /pants and /shoes as well, although I thought this bug was already known.

**Comment by BIRLZ95** [comment]
Yeah seen it now thanks
