### ISSUE TITLE
Changing outfits makes your HP full

### ISSUE THREAD

**Issue by Choppa25** [New-Chance-RP/Feedback#756]
<h2>What bug have you found?</h2>

Whenever you use /outfituse to change your outfit, your HP will reset to full.

<h2>What do you expect should happen?</h2>

The HP should remain the same since all the healing changes, not to mention the fact that it can be abused.

<h2>Anything to support your bug report?</h2>

https://streamable.com/kkytf8

**Comment by Senlarus** [comment]
This was fixed, thanks for the report!
