### ISSUE TITLE
update to the drug side of things

### ISSUE THREAD

**Issue by rulefocus2742** [New-Chance-RP/Feedback#757]
<h2>Feature you are requesting.</h2>

<h2>What are the benefits to your feature?</h2>
well for me would help to the group im in 

<h2>Anything to support your feature request?</h2>

https://www.fivem-store.com/product/drug-system-v2/
![Screenshot (479)](https://user-images.githubusercontent.com/68706453/104330126-950f8b80-54e5-11eb-852d-422133700166.png)

**Comment by Senlarus** [comment]
We have long terms plans for drugs and will be making changes over time to enhance and layer the system.
