### ISSUE TITLE
Hellcat gets dirty way too fast

### ISSUE THREAD

**Issue by Husk123** [New-Chance-RP/Feedback#758]
<h2>What bug have you found?</h2>

After a clean the hellcat will get dirty within 2 mins of driving, this is annoying to keep cleaning.

<h2>What do you expect should happen?</h2>

I would expect it take at least 15 mins before it starts to get dirty.

<h2>Anything to support your bug report?</h2>

https://streamable.com/ktnkjo

**Comment by driftoooo** [comment]
I'll see what I can do.

**Comment by driftoooo** [comment]
Unable to replicate this issue, closing at this time.

Thank you again for the report.
