### ISSUE TITLE
Golf VW R Tuning 

### ISSUE THREAD

**Issue by Ali-Walker** [New-Chance-RP/Feedback#760]
<h2>What are you requesting?</h2>

The vehicle doesn't have any Tuning to it except turbo

<h2>Why are you making this request?</h2>

i have this car and some others may too and want the vehicle to be able to have upgrades

**Comment by driftoooo** [comment]
Known issue. Already fixed, just needs pushing.

**Comment by driftoooo** [comment]
For reference, the vehicle had mods previously, however, due to a new FiveM/GTA update the mod kits unique identifier became invalid. Once the fix is in, all tuning parts, cosmetics, and (if applicable) body mods will be available.

**Comment by driftoooo** [comment]
Issue fixed - Pushed to live already
