### ISSUE TITLE
Turrismo Classic well deserved Buff.

### ISSUE THREAD

**Issue by Napkins-real** [New-Chance-RP/Feedback#762]
<h2>What are you requesting?</h2>

**1) - Vehicle changes - Turrismo Classic top speed and acceleration buff

<h2>Why are you making this request?</h2>

I am requesting that the classic Ferrari F40 spin off, The Turrismo Classic, receive a buff with it's top speed which right now stands at 118mph. A bison pulling a trailer can pass you on the interstate (Trust me my mate did it) The Classic Ferrari F40, Which the car is based off of had a top speed of 200+mph @ 500hp stock. 

<h2>Anything to support the above?</h2>
Ferrari F40
V8
ENGINE
2936.25 cc
TOTAL DISPLACEMENT
351.5 kW
MAXIMUM POWER @ 7000 RPM
324 km/h

**Comment by driftoooo** [comment]
Not all vanilla GTA vehicles have had their handling done yet, it's a big Work In Progress at the moment. This car is already on my to-do list. I'll update here when I've completed the handling on it.

**Comment by driftoooo** [comment]
Awaiting to regain access to the base GTA handling file, then I'll get this ironed out

**Comment by driftoooo** [comment]
Done, waiting to be pushed 👀

**Comment by driftoooo** [comment]
Pushed - Available next restart https://discord.com/channels/680278765179502645/688123847047774210/801845150287396896
