### ISSUE TITLE
Silverado Nerf

### ISSUE THREAD

**Issue by DerkDuece** [New-Chance-RP/Feedback#765]
<h2>What are you requesting?</h2>

Silverado Nerf

**1) - Vehicle addition -** *(Provide Link)*
**2) - Vehicle removal -** *Name of vehicle*
**3) - Vehicle changes -** *What changes you want think should be made.*

<h2>Why are you making this request?</h2>

*DELETE THIS LINE - What improvements / benefits do you think this will have and why?*

<h2>Anything to support the above?</h2>

*DELETE THIS LINE - If you have any pictures or videos to help with the above*

**Comment by driftoooo** [comment]
In progress

**Comment by driftoooo** [comment]
Complete - Awaiting pushing

**Comment by driftoooo** [comment]
Pushed
