### ISSUE TITLE
Clothing Shop on LSPD Lockers

### ISSUE THREAD

**Issue by alruiz95** [New-Chance-RP/Feedback#766]
<h2>Feature you are requesting.</h2>

Simply to add a clothing shop at the lockers of LSPD VPD and a wardrobe.

<h2>What are the benefits to your feature?</h2>
We will be able to modify our uniforms to be more personalized, like short sleeves, and also rank insignias.

<h2>Anything to support your feature request?</h2>

Nothing more.

**Comment by Senlarus** [comment]
@DerkDuece What say you? If we give them access to clothing shop they can literally put ANYTHING on, including command uniforms or street clothes.

**Comment by alruiz95** [comment]
We already do, we go across the street, but some officers that have their personalized uniforms after a shift are stuck with those. So they have to go across the street off duty but with the uniform to change.

**Comment by alruiz95** [comment]
Also in this way, we can add decals, for ranks.

**Comment by Senlarus** [comment]
I know you do but there has already been issues with people accessing clothiers that aren’t approved for their rank. This is a command decision. We can build your own clothing menu that can be rank locked that includes decals and all options available to your rank if that’s what command wants.

**Comment by Senlarus** [comment]
@DerkDuece Could you review and discuss?

**Comment by DerkDuece** [comment]
> @DerkDuece Could you review and discuss?

I have no problem with it. We have SOP's in place so if they violate uniform code they can be punished. I wouldnt put it on top of the PD Clothing menu at MRPD tho. Have it somewhere.

**Comment by Senlarus** [comment]
Will be in at restart
