### ISSUE TITLE
Apartments can only store the same amount as your pockets

### ISSUE THREAD

**Issue by Oh-Nooo** [New-Chance-RP/Feedback#768]
<h2>To be able to stack more in your appartment.</h2>

*DELETE THIS LINE - To be able to stack more of one item in your apartment storage for example. You can only store 5 pistol magazines in the apartment and can only store 2 repair kits .*

<h2>So we don't have to throw away or leave stuff that we find doing recycling or from gloves boxes etc.</h2>

*DELETE THIS LINE - Less frustration on were to put things I.E in spare vehicles glove boxes, car boot/trunk when out of space in your apartment. *

*DELETE THIS LINE - If you have anything extra to provide, pictures or videos etc to help sell your idea put them here.*

**Comment by Zopfco** [comment]
The hotel-style apartments are meant to be temporary housing for new people.  Think you can buy a trailer or proper apartment for <$50k at the moment & they all have unlimited storage (at least for now).

**Comment by Senlarus** [comment]
This is intended. If you want more storage buy a bigger house.
