### ISSUE TITLE
Camaro ZL1 - Buff 

### ISSUE THREAD

**Issue by driftoooo** [New-Chance-RP/Feedback#770]
<h2>What are you requesting?</h2>
Notes to self:
- Doesn't seem to respond 
- Needs an overhaul 

Info: 
N/A

**Comment by ABroHaam** [comment]
I personally agree, seems to spin out too much only does about 150 with full kits. Good luck :D

**Comment by driftoooo** [comment]
Complete - awaiting to be pushed
