### ISSUE TITLE
Evo 2006 Braking & handling & the car is not a drift car 

### ISSUE THREAD

**Issue by RedBullT** [New-Chance-RP/Feedback#775]
Evo breaks need tightening up and handling needs making a more responsive on and off road.

3) - Vehicle changes - Better handling & Braking & the car is not a drift car

Why are you making this request?
Not enjoyable to drive yet, its nearly there though, the speed is fine just handling is off and don't feel right yet.

Anything to support the above?
Mine and others experience.

**Comment by 5hallow** [comment]
Yeah, this car hates coming out of first gear and is currently a rear wheel drift car in the city.. however in head, this car is an all wheel drive monster that people build to support well, well over 1,000hp+ with fat turbos and built internals.  This is one of the most common drag cars that people will build, the 4g63 platform is so solid. So seeing this car handle how it currently does basically breaks my heart. Yes, you can make a drift car out of an AWD platform but these cars in specific are known for their BRUTAL launches and how quick this car can grip and put the right amount of power down. Instead, in city it handles and performs no different compared to the Evo VII from the FNF car lineup. If anything, I prefer how the FNF Evo drives - especially considering it is 100k cheaper than the 2006 Evo VIIII.

**Comment by driftoooo** [comment]
Yes, I made a typo on the driveline bias. My bad.

**Comment by RedBullT** [comment]
Thanks man love the work u been putting in can wait to drive it when its not drifty

**Comment by driftoooo** [comment]
Complete, awaiting pushing. The car is now AWD, it grips more around turns, however, if you really try to it will slide, not everyone wants the car for racing in, I've balanced it so its fun for both uses.

**Comment by driftoooo** [comment]
P.S. Also has a MUCH better launch

**Comment by driftoooo** [comment]
Closing - It was pushed yesterday (If you don't notice any changes, feel free to re-open)

Enjoy!
