### ISSUE TITLE
Fishing is broken?

### ISSUE THREAD

**Issue by Honton** [New-Chance-RP/Feedback#789]
<h2>What bug have you found?</h2>

When fishing, correctly "catching" the fish when pressing the command doesn't net you a fish, however it does use up fishing bait.

<h2>What do you expect should happen?</h2>

Fishing should allow you to catch a fish when using correctly inputting the commands.
<h2>Anything to support your bug report?</h2>

Honestly I kinda get into the fishermen zone when fishing so I don't know how long it's been happening, but I feel like I've been using up alot of bait and hours without noticing this. lol. I've taken flights, etc and tested it, I still cannot catch fish.

![image](https://user-images.githubusercontent.com/66952510/105621426-173c6180-5dbc-11eb-94bd-e99d6684c8ef.png)
![image](https://user-images.githubusercontent.com/66952510/105621428-1d324280-5dbc-11eb-9c3d-bdb25ede3aa2.png)

**Comment by Honton** [comment]
Please let me know if it's just me or if it's a thing xD

**Comment by Honton** [comment]
Found an f8 script error when attempting to sell fish
![image](https://user-images.githubusercontent.com/66952510/105648571-0265d980-5e61-11eb-9c8e-65c4223ad3e3.png) 
hope this helps

**Comment by Senlarus** [comment]
Fixed, and groundwork laid out for future enhancements.
