### ISSUE TITLE
Main HUD shows before spawning in as a character

### ISSUE THREAD

**Issue by roleplaydev** [New-Chance-RP/Feedback#79]
<h2>What bug have you found?</h2>

Upon loading in before even selecting the character main HUD shows up.

<h2>What do you expect should happen?</h2>

Main HUD { food bar, water bar etc } to shows after we spawn in as a character

<h2>Anything to support your bug report?</h2>

Link to the photo [Photo](https://imgur.com/gallery/4JTvuBB)

**Comment by Senlarus** [comment]
Fixed in a recent commit.
