### ISSUE TITLE
PD Weapon Matching

### ISSUE THREAD

**Issue by 5hallow** [New-Chance-RP/Feedback#791]
<h2>Feature you are requesting.</h2>

PD respond to most situations involving gunfire with Class 2s, AKA fully automatic M4s. Most situations they are responding to, the crims are using pistols / Class 1s. In just about every city (and in real life, lol) PD match gunfire. I've noticed some higher up Officers are rather M4 trigger happy. I understand you guys get them for free and can just throw them on your back and pull them out whenever you would like, but it's simply not realistic pulling Class 2s, even Class 3s (yes, I have had a sniper pulled and used on me when nothing but Class 1s were shown) when nothing but pistols are being brandished.

<h2>What are the benefits to your feature?</h2>

Would make the RP between crims and PD 10x better, and would give both sides more of an even gunfight. PD already gets to start with full body armor as is, whereas we have to expose ourselves by smoking meth for 10 seconds just to get a little armor. Showing up with M4s to a pistol situation basically throws the ball in their park.

<h2>Anything to support your feature request?</h2>

Every other city. Even in real life, Class 2s are only pulled out for very specific situations such as involving the SWAT.

**Comment by ZeroInsomniac** [comment]
As per standard SOP's virtually anywhere, firepower is matched, and pushed up a level to ensure officer and public safety. This isnt a development issue.

**Comment by ChuckBurn** [comment]
Say less. I'll keep the win mental next cop I see. I'll do whatever it takes to ensure I get away. Yikes

**Comment by ZeroInsomniac** [comment]
Value your life. Rules apply across the board to everyone.

**Comment by ChuckBurn** [comment]
I would rather die then go to jail. If the officer is bleeding in his driver seat, I'll be free as a bird.

**Comment by Senlarus** [comment]
Not a feature request or bug.
