### ISSUE TITLE
Server Rules

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Feedback#8]
<h2>What is your feature request?</h2>

Server rules to be discussed and worked out, added to the discord.

<h2>What are the benefits of your idea?</h2>

Stops people from being butts.

<h2>Anything to support your idea?</h2>

**Comment by Senlarus** [comment]
@DerkDuece Can we put these out for review soon?

**Comment by Senlarus** [comment]
These are done, check #welcome channel in discord.
