### ISSUE TITLE
NVG When making a new character

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#80]
<h2>What bug have you found?</h2>

When making a new character, the 23rd hairstyle is a set of Night-vision Goggles and not a hairstyle to choose from.

<h2>What do you expect should happen?</h2>

To have one of the hairstyles and not an item.

<h2>Anything to support your bug report?</h2>

Corroborated with another user when discovered.

**Comment by Senlarus** [comment]
New skin system fixed this.
