### ISSUE TITLE
Making while Selling Drugs

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#81]
<h2>What bug have you found?</h2>

While selling Meth/Weed to Ped's, you can go into your inventory and start making a new set of drugs with the progress bars overlapping.

<h2>What do you expect should happen?</h2>

Inventory menu should not be accessible while selling to Ped's to prevent doubling tasks.

<h2>Anything to support your bug report?</h2>

Have done it in discord stream several times for Bloomb

**Comment by ixhal** [comment]
Fixed cheers for the heads up
