### ISSUE TITLE
Busy homes buying more bulk drugs.

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#82]
<h2>Feature you are requesting.</h2>

Having the ability to sell higher amounts of drugs to homes that seem to be having a party (i.e. playing music). 

<h2>What are the benefits to your feature?</h2>

Being able to get through your drug inventory more quickly so that you're not stuck in a part of town for a long time. Such as Ped's buying 0-4 bags of drugs, while houses could go from 0 or 5-10 depending on if they call the cops or buy from you.  

<h2>Anything to support your feature request?</h2>

![image](https://user-images.githubusercontent.com/6095886/81108412-a7611080-8ee6-11ea-895c-0c06918ce90e.png) vector3(324.16, -1991.08, 24.16)

![image](https://user-images.githubusercontent.com/6095886/81108629-fa3ac800-8ee6-11ea-96db-ce1ec67033dc.png) vector3(280.48, -1897.16, 26.88)

![image](https://user-images.githubusercontent.com/6095886/81108821-2f471a80-8ee7-11ea-9656-0bf09126c490.png) vector3(332.8, -2018.88, 22.36)

![image](https://user-images.githubusercontent.com/6095886/81108959-5e5d8c00-8ee7-11ea-9e6c-a91a65045f18.png) vector3(293.12, -2086.92, 17.68)

![image](https://user-images.githubusercontent.com/6095886/81109019-76351000-8ee7-11ea-852c-b3003ff544aa.png) vector3(53.64, -1874.36, 22.4)

![image](https://user-images.githubusercontent.com/6095886/81109081-8d73fd80-8ee7-11ea-845f-cc5b1d7541cd.png) vector3(86.2, -1958.76, 21.12)

![image](https://user-images.githubusercontent.com/6095886/81109152-aaa8cc00-8ee7-11ea-985f-ef1fc2770636.png) vector3(126.08, -1929.8, 21.4)

**Comment by Senlarus** [comment]
We can eventually find a way to make the system more dynamic. This isn't something we will plan for the time being as a lot can change during our alpha development. Thanks for the feedback!

**Comment by Senlarus** [comment]
This will be considered in future drug system changes.
