### ISSUE TITLE
Selling drugs to convenience store clerks.

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#83]
<h2>What bug have you found?</h2>

You're able to sell drugs to the Ped's standing behind the store counters, when you do, they start walking around and trying to leave the store.

<h2>What do you expect should happen?</h2>

Not sure if its possible to keep them from being accessible with drug transactions.

<h2>Anything to support your bug report?</h2>

Easily replicated.

**Comment by ixhal** [comment]
Fixed thanks the the info
