### ISSUE TITLE
bulk selling drugs (location)

### ISSUE THREAD

**Issue by BIRLZ95** [New-Chance-RP/Feedback#84]
<h2>Feature you are requesting.</h2>

ALT Sell location for drugs

<h2>What are the benefits to your feature?</h2>

Been able to sell coke for example in bulk for a slightly better profit at a secret location. The location would be a hidden and would just mix things up abit and add an extra layer to the system I believe. 

<h2>Anything to support your feature request?</h2>

Nope just an idea I had.

**Comment by BillChirico** [comment]
Could potentially ruin the gang system where you can control corners and such. I would think that being able to sell to any NPC (some limited spots) will allow gangs to control their areas.

**Comment by Senlarus** [comment]
This will be considered in future drug system development.
