### ISSUE TITLE
Reduce radius of drug selling range

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#85]
<h2>Feature you are requesting.</h2>

Currently the radius of being able to sell drugs is around 970-990ft from the center of the marker.  That's somewhere between 2-3 blocks in distance.  I think we should reduce the size of the radius should be drastically reduced so that people can't be too far from the initial selling point.

<h2>What are the benefits to your feature?</h2>

May make it easier for PD to locate a person selling drugs to make a more interesting interaction between dealers and PD.

<h2>Anything to support your feature request?</h2>

N/A

**Comment by ixhal** [comment]
Changed the radius now still needs more tweaking but is smaller than it used to be
