### ISSUE TITLE
Drug Selling to Furniture buying

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#86]
<h2>Feature you are requesting.</h2>

For how much money you can make in an hour having to find the right vehicle for making meth, or finding where weed spawns, having it processed, and then bagging it yourself.  The cost of furniture is a little uneven as what I spent maybe 2 hours of working on with admin guidance I could only buy 3-4 furniture items before running out of money.  I believe either Furniture prices need to be brought way down since its an added feature not necessary to the game, or drugs should rake in more money to offset those costs on top of being able to buy homes and cars.

<h2>What are the benefits to your feature?</h2>

Giving drug running more bang for their buck.  If they get caught trying to sell, that's going to severely hamper the want to be a villain when the payout isn't worth the risks.  I made maybe 18k in the 1-2 hours I was doing the drug selling.  Then the furniture ate all of that effort and time in a few seconds.

<h2>Anything to support your feature request?</h2>

N/A

**Comment by Senlarus** [comment]
Furniture was removed.

**Comment by BillChirico** [comment]
I do agree that drugs are a bit too low especially weed
