### ISSUE TITLE
Grey screen

### ISSUE THREAD

**Issue by Birlzey** [New-Chance-RP/Feedback#87]
<h2>What bug have you found?</h2>

When creating a character and inputing your name if you hold left click to highlight and delete it makes all your screen go grey, see attached clip please.

<h2>What do you expect should happen?</h2>

Should be able to highlight and delete text.

<h2>Anything to support your bug report?</h2>

https://www.youtube.com/watch?v=Yh8d3ISz_pE

**Comment by Senlarus** [comment]
Fixed issue in recent commit
