### ISSUE TITLE
Automated-capitalisation issue during character registration

### ISSUE THREAD

**Issue by spyr0sec** [New-Chance-RP/Feedback#88]
<h2>What bug have you found?</h2>

It's not really a bug, it's more of an oversight.

The automated capitalision of the first and last names is great, as there's nothing worse than a bloke called peTER SMith piping up on Twitter, however this makes it impossible for people with names such as McGuinness to have those names.

<h2>What do you expect should happen?</h2>

Keep the auto-caps on the first letter and then just trust people to not bugger up their names. Maybe give staff perms to just manually tweak peoples names in case someone makes a mistake or decides that SmITH is a good surname.

<h2>Anything to support your bug report?</h2>

N/A

**Comment by Senlarus** [comment]
![image](https://user-images.githubusercontent.com/1503963/81262498-f48ad280-900b-11ea-81f8-5038dee332ad.png)
