### ISSUE TITLE
Few things noticed while playing, possible adjust/QoL

### ISSUE THREAD

**Issue by ModzyUK** [New-Chance-RP/Feedback#89]
<h2>Feature you are requesting.</h2>
No request as such, more things I have noticed while playing for Devs to take a look at:

- Seat-belt sound absolutely destroying your ears.

- HUD not sitting correctly/overlapping GPS, maybe move to right side?

- More, User friendly keyboard, a lot of people including myself use F2 for their toggle deafen on discord.

- My hair seemed to have gone after a relog? Not sure if a me issue, maybe something to look at.

- Vehicle Prices (I know that's not high on the agenda, also the Oppressor is in there, flying bike)

- Voice software, not spoke to any devs yet about this but is it staying as is or moving to mumble, TokoVoip etc?

- Custom Vehicles (Again probably not high on Agenda, had people ask me)

Apart from all of this, I know it's a lot to list, and I am in no-way a Dev, but just some things I have noticed that you may all think needs a look at too :) 

<h2>What are the benefits to your feature?</h2>
QoL

<h2>Anything to support your feature request?</h2>
N/A

*DELETE THIS LINE - If you have anything extra to provide, pictures or videos etc to help sell your idea put them here.*

**Comment by Senlarus** [comment]
Seat-belt sound has been lowered.
HUD Re positioned the best it can be.
Keybinding revamped
Hair issue resolved
Vehicle Prices are being actively reviewed.
Staying as is, we won't be using Toko. Once we move to OneSync we will implement 3d sound with Mumble built in.
Custom Vehicles will be added at a later day.
