### ISSUE TITLE
Scuffed Motels

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#91]
<h2>What bug have you found?</h2>

When I got into the server, I still had a key to room 12 but the marker for owning the room was red.  I could still buy a room so I bought 10 with Stephensen.  Went into his room and couldn't see any furniture, shot the wall a few times for giggles and then handed them the key to my 10 to see if they would duplicate.  I went up to 12 and could enter the room because it still said I had a key to 12.  When I went into 12 I saw my mini fridge but also bullet holes from 10.  Now anytime I enter a room Stephensen can't see me and while together in the room I can shoot them but they take no damage.  

There's no key inventory aside from F9, when I hand over keys, I had 2 #12's but can only hand over 1 and the other is stuck in my inventory.

I just bought room 4 and teleported into #12 again

<h2>What do you expect should happen?</h2>

I believe I am glitched to forever hold room #12's key and need it removed from my script or however that is.  Individual rooms should not share cosmetic damage to walls.  

<h2>Anything to support your bug report?</h2>

Stephensen was working with me to scuff the motels and it took maybe 1 minute.

**Comment by Scarfninja** [comment]
When buying and selling rooms, the server is not removing the key from inventory so I've bought and sold 4 motels but still have keys to them.  I can't enter the old rooms but the keys still exist.

Cosmetic damage to one room is spread across all rooms for each individual.  So if one person shoots up their room, and comes to my clean room, they'll see the damage and I wont.  But if I shoot my room up and go to theirs they can't see the damage I'd done to mine.  If we both are in a room and shoot it up and go to another room we'll both see the same damage in a different room.

**Comment by bloombydee** [comment]
Closing as we are replacing this resource
