### ISSUE TITLE
Drug crafting inaccurate amounts

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#92]
<h2>What bug have you found?</h2>

Meth (1G) says you can hold 100, but you can't craft beyond 50 before having to drop what you're holding to make more.  You can hold 100 but if you hit 50 you can't craft beyond that.

<h2>What do you expect should happen?</h2>

Fix the maximum capacity to 50 (1G) or fix the crafting capacity to 100.

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/6095886/81354600-0ca93300-909a-11ea-8fb6-a95ccbead3f0.png)

![image](https://user-images.githubusercontent.com/6095886/81354612-129f1400-909a-11ea-8bb7-95c06c72505f.png)

**Comment by ixhal** [comment]
Should be fixed in the next commit

**Comment by ixhal** [comment]
Fixed let me know if anything is broken cheers
