### ISSUE TITLE
Garbage Job Clothing MALE (Adding female now)

### ISSUE THREAD

**Issue by Birlzey** [New-Chance-RP/Feedback#93]
<h2>Feature you are requesting.</h2>

Clothing for the Garbage job, I have screenshotted each individual item and numbered them, obv if you don't think something goes feel free to change.

<h2>What are the benefits to your feature?</h2>

Better immersion / RP.

<h2>Anything to support your feature request?</h2>

Hat -3 ![image](https://user-images.githubusercontent.com/64453673/81404087-a4eff800-912c-11ea-9f8c-8174a710a74e.png)

Gloves - 65 ![image](https://user-images.githubusercontent.com/64453673/81405139-fef1bd00-912e-11ea-8edd-5c9be24544d4.png)

Undertshirt - 60 ![image](https://user-images.githubusercontent.com/64453673/81405216-2052a900-912f-11ea-9cd3-205c71887655.png)

Overshirt - 58 ![image](https://user-images.githubusercontent.com/64453673/81405276-3d877780-912f-11ea-8ee0-9dcca580c369.png)

Pants - 37 ![image](https://user-images.githubusercontent.com/64453673/81405313-4d06c080-912f-11ea-82e0-6654447afc2e.png)

Shoes - 28 ![image](https://user-images.githubusercontent.com/64453673/81404452-6870cc00-912d-11ea-9653-9df9173ede2b.png)

**Comment by Senlarus** [comment]
This has been added, thanks!
