### ISSUE TITLE
Garbage Job Clothing FEMALE

### ISSUE THREAD

**Issue by Birlzey** [New-Chance-RP/Feedback#94]
<h2>Feature you are requesting.</h2>

Clothing for the Garbage job, I have screenshotted each individual item and numbered them, obv if you don't think something goes feel free to change.

<h2>What are the benefits to your feature?</h2>

Better immersion / RP.

<h2>Anything to support your feature request?</h2>

Hat - 59 - Colour 3 ![image](https://user-images.githubusercontent.com/64453673/81406893-55142f80-9132-11ea-8334-199def934862.png)

Gloves - 75 ![image](https://user-images.githubusercontent.com/64453673/81407002-87be2800-9132-11ea-9feb-320879a06637.png)

Undershirt - 37 - Colour 2 ![image](https://user-images.githubusercontent.com/64453673/81407095-b89e5d00-9132-11ea-90c2-a64f5c8deb0b.png)

Overshirt - 51 ![image](https://user-images.githubusercontent.com/64453673/81407159-d5d32b80-9132-11ea-801b-8ba8a9afb24e.png)

Pants - 36 ![image](https://user-images.githubusercontent.com/64453673/81407212-eb485580-9132-11ea-9abe-b3ff036d5e4d.png)

Shoes - 27 ![image](https://user-images.githubusercontent.com/64453673/81407273-ff8c5280-9132-11ea-9188-5942c6cda2a1.png)

Full outfit 
![image](https://user-images.githubusercontent.com/64453673/81407346-25b1f280-9133-11ea-8e7c-1769599aeff7.png)

**Comment by Senlarus** [comment]
Thanks! This has been added.
