### ISSUE TITLE
PD checking ID has wrong info

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Feedback#95]
<h2>What bug have you found?</h2>

When checking the info listed below it gives semi-incorrect information.

Name : Pulling steam name instead of character name.
Sex : Pulling incorrect gender
DOB : NIL
Height: NIL

<h2>What do you expect should happen?</h2>

Name : Pull character name
Sex : Pull the correct gender
DOB : Pull the characters DOB
Height : Pull the characters height.

<h2>Anything to support your bug report?</h2>

Screenshot of the issue - https://gyazo.com/541843cfdbb09e907e29df7cc95148c8

**Comment by ixhal** [comment]
Fixed with new menu, get in there and test it out currently known issue searching player is instant + does not show weapons (working on it)
