### ISSUE TITLE
No Phone shows french

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Feedback#96]
<h2>What bug have you found?</h2>

If you have no phone and press the keybind it prompts you telling you that you don't have a phone but in French.

<h2>What do you expect should happen?</h2>

Either to have no message, or display the message in English

<h2>Anything to support your bug report?</h2>

Screenshot attached - https://gyazo.com/0d5a43bc29dcec223db7e3641e6e46aa

**Comment by ixhal** [comment]
closing due to duplicated post see #90

**Comment by BadBritishGamer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/lvGHQ07F/1-test)
