### ISSUE TITLE
Objects clipping through walls at MRPD

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Feedback#97]
<h2>What bug have you found?</h2>
At MRPD on the corner there is a bench and a lightpost clipping weirdly.

<h2>What do you expect should happen?</h2>
Remove the extra bench and adjust the street light.

<h2>Anything to support your bug report?</h2>

Screenshot of lampost - https://gyazo.com/208cf061045316f21f303215b7f9d38d

**Comment by Senlarus** [comment]
This has been corrected, along with other improvements to MRPD gate.
