### ISSUE TITLE
Police MDT/CAD System

### ISSUE THREAD

**Issue by itomicz** [New-Chance-RP/Feedback#98]
<h2>Police MDT/CAD System</h2>
Firstly, when i go onto the police CAD/MDT System i see that there is no "SUBMIT" button or anything to complete a report. Of course this is need if the police want to fill out a report. Also another thing i have found when looking through the CAD/MDT system is that when you go onto "Create Report" it automatically is going onto a suspect that you was searching from the "Search Persons" Tab and there is no actual "Create Report Button". Not only that but i feel that if we are clicking onto "Create report" then there should be a box there called "Civilians name" where we can type it in and it will go onto there profile once we are done writing it. (just like the box for "Details". This is also the same for "Warrants." As i cannot submit a warrant and put it through.

Another thing what would be good when making reports would be  the ability to have a box for "EVIDENCE". personally i think this would be good just like a heading for "INCIDENT" or "DETAILS" as then we can put the link in the evidence box which can go with the report but if there is no evidence entered then the evidence box will NOT show. (one thing that could be cool is if the font could be changed for all the headers, in my opinion that font we have right now doesn't look that nice and would be better. for example change it to the font that we use for "DETAILS" within new report) < that's not a huge thing but just thought i would throw it in there while i'm at it.

<h2>What are the benefits to your feature?</h2>
The benefits of my feature would be that the police would be able to properly use the CAD/MDT they they should be able to. 

<h2>Anything to support your feature request?</h2>
Picture Of "Search Persons" without a "SUBMIT" button;
https://gyazo.com/ac05ed5202e90a6747acc3493284189c

Picture Of "New Warrants" without a "SUBMIT" button;
https://gyazo.com/9a820ec3ff798db0dcc333b804fdf166

A box for "EVIDENCE" just like "DETAILS" and "INCIDENT"
https://gyazo.com/1306b92369f4433c86153acae0585338

**Comment by BadBritishGamer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Potato](https://trello.com/c/pRUNWcrt/2-potato)

**Comment by Senlarus** [comment]
This is in
