### ISSUE TITLE
Realistic handling mod being mean

### ISSUE THREAD

**Issue by Real50BMG** [New-Chance-RP/Feedback#99]
<h2>What bug have you found?</h2>

Realistic handling mod overwriting my custom submitted .meta files

<h2>What do you expect should happen?</h2>

My metafiles to be able to be tested on the devserver. Should probably just disable the mod.

<h2>Anything to support your bug report?</h2>

*DELETE THIS LINE - Have you got any evidence to help prove the bug, a video or picture etc?*

**Comment by Senlarus** [comment]
It was a problem with the handling.meta file, missed a closing tag. It's fixed now.
